/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 --keepmeshes --resolution 1024 --keepnames --types --output ./DemotrainModel.tsx --transform ./scene.gltf 
Files: ./scene.gltf [180.89KB] > C:\Users\HP\Downloads\wag-12\scene-transformed.glb [168.37KB] (7%)
Author: lakshyasharma11052002 (https://sketchfab.com/lakshyasharma11052002)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/wag-12-3330081494cd436db99345ea7094caac
Title: WAG-12
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Object_4: THREE.Mesh
    Object_6: THREE.Mesh
    Object_162: THREE.Mesh
    Object_174: THREE.Mesh
    Object_8: THREE.Mesh
    Object_10: THREE.Mesh
    Object_160: THREE.Mesh
    Object_172: THREE.Mesh
    Object_12: THREE.Mesh
    Object_14: THREE.Mesh
    Object_158: THREE.Mesh
    Object_170: THREE.Mesh
    Object_16: THREE.Mesh
    Object_18: THREE.Mesh
    Object_156: THREE.Mesh
    Object_168: THREE.Mesh
    Object_20: THREE.Mesh
    Object_100: THREE.Mesh
    Object_22: THREE.Mesh
    Object_98: THREE.Mesh
    Object_24: THREE.Mesh
    Object_150: THREE.Mesh
    Object_26: THREE.Mesh
    Object_148: THREE.Mesh
    Object_28: THREE.Mesh
    Object_145: THREE.Mesh
    Object_29: THREE.Mesh
    Object_146: THREE.Mesh
    Object_31: THREE.Mesh
    Object_142: THREE.Mesh
    Object_32: THREE.Mesh
    Object_143: THREE.Mesh
    Object_34: THREE.Mesh
    Object_140: THREE.Mesh
    Object_36: THREE.Mesh
    Object_138: THREE.Mesh
    Object_38: THREE.Mesh
    Object_136: THREE.Mesh
    Object_40: THREE.Mesh
    Object_134: THREE.Mesh
    Object_42: THREE.Mesh
    Object_132: THREE.Mesh
    Object_44: THREE.Mesh
    Object_130: THREE.Mesh
    Object_46: THREE.Mesh
    Object_128: THREE.Mesh
    Object_48: THREE.Mesh
    Object_126: THREE.Mesh
    Object_50: THREE.Mesh
    Object_124: THREE.Mesh
    Object_52: THREE.Mesh
    Object_54: THREE.Mesh
    Object_154: THREE.Mesh
    Object_166: THREE.Mesh
    Object_56: THREE.Mesh
    Object_96: THREE.Mesh
    Object_58: THREE.Mesh
    Object_122: THREE.Mesh
    Object_60: THREE.Mesh
    Object_120: THREE.Mesh
    Object_62: THREE.Mesh
    Object_118: THREE.Mesh
    Object_64: THREE.Mesh
    Object_116: THREE.Mesh
    Object_66: THREE.Mesh
    Object_114: THREE.Mesh
    Object_68: THREE.Mesh
    Object_112: THREE.Mesh
    Object_70: THREE.Mesh
    Object_110: THREE.Mesh
    Object_72: THREE.Mesh
    Object_108: THREE.Mesh
    Object_74: THREE.Mesh
    Object_106: THREE.Mesh
    Object_76: THREE.Mesh
    Object_104: THREE.Mesh
    Object_78: THREE.Mesh
    Object_102: THREE.Mesh
    Object_80: THREE.Mesh
    Object_82: THREE.Mesh
    Object_152: THREE.Mesh
    Object_84: THREE.Mesh
    Object_85: THREE.Mesh
    Object_86: THREE.Mesh
    Object_92: THREE.Mesh
    Object_87: THREE.Mesh
    Object_88: THREE.Mesh
    Object_90: THREE.Mesh
    Object_91: THREE.Mesh
    Object_93: THREE.Mesh
    Object_94: THREE.Mesh
    Object_164: THREE.Mesh
  }
  materials: {
    PaletteMaterial001: THREE.MeshStandardMaterial
    PaletteMaterial002: THREE.MeshStandardMaterial
    PaletteMaterial003: THREE.MeshStandardMaterial
    PaletteMaterial004: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('./Demotrain-wag12/scene-transformed.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh name="Object_4" geometry={nodes.Object_4.geometry} material={materials.PaletteMaterial001} position={[0.064, 0.156, -3.193]} rotation={[-Math.PI, 0, -Math.PI]} scale={0.234} />
      <mesh name="Object_6" geometry={nodes.Object_6.geometry} material={materials.PaletteMaterial001} position={[0.061, 0.156, -11.941]} rotation={[-Math.PI, 0, -Math.PI]} scale={0.234} />
      <mesh name="Object_162" geometry={nodes.Object_162.geometry} material={materials.PaletteMaterial001} position={[0, 0.156, 11.991]} scale={0.234} />
      <mesh name="Object_174" geometry={nodes.Object_174.geometry} material={materials.PaletteMaterial001} position={[0, 0.156, 3.244]} scale={0.234} />
      <mesh name="Object_8" geometry={nodes.Object_8.geometry} material={materials.PaletteMaterial001} position={[0.064, 0.156, -3.193]} rotation={[-Math.PI, 0, -Math.PI]} scale={0.234} />
      <mesh name="Object_10" geometry={nodes.Object_10.geometry} material={materials.PaletteMaterial001} position={[0.061, 0.156, -11.941]} rotation={[-Math.PI, 0, -Math.PI]} scale={0.234} />
      <mesh name="Object_160" geometry={nodes.Object_160.geometry} material={materials.PaletteMaterial001} position={[0, 0.156, 11.991]} scale={0.234} />
      <mesh name="Object_172" geometry={nodes.Object_172.geometry} material={materials.PaletteMaterial001} position={[0, 0.156, 3.244]} scale={0.234} />
      <mesh name="Object_12" geometry={nodes.Object_12.geometry} material={materials.PaletteMaterial001} position={[0.064, 0.156, -3.193]} rotation={[-Math.PI, 0, -Math.PI]} scale={0.234} />
      <mesh name="Object_14" geometry={nodes.Object_14.geometry} material={materials.PaletteMaterial001} position={[0.061, 0.156, -11.941]} rotation={[-Math.PI, 0, -Math.PI]} scale={0.234} />
      <mesh name="Object_158" geometry={nodes.Object_158.geometry} material={materials.PaletteMaterial001} position={[0, 0.156, 11.991]} scale={0.234} />
      <mesh name="Object_170" geometry={nodes.Object_170.geometry} material={materials.PaletteMaterial001} position={[0, 0.156, 3.244]} scale={0.234} />
      <mesh name="Object_16" geometry={nodes.Object_16.geometry} material={materials.PaletteMaterial001} position={[0.064, 0.156, -3.193]} rotation={[-Math.PI, 0, -Math.PI]} scale={0.234} />
      <mesh name="Object_18" geometry={nodes.Object_18.geometry} material={materials.PaletteMaterial001} position={[0.061, 0.156, -11.941]} rotation={[-Math.PI, 0, -Math.PI]} scale={0.234} />
      <mesh name="Object_156" geometry={nodes.Object_156.geometry} material={materials.PaletteMaterial001} position={[0, 0.156, 11.991]} scale={0.234} />
      <mesh name="Object_168" geometry={nodes.Object_168.geometry} material={materials.PaletteMaterial001} position={[0, 0.156, 3.244]} scale={0.234} />
      <mesh name="Object_20" geometry={nodes.Object_20.geometry} material={materials.PaletteMaterial002} position={[0.019, -0.311, -3.363]} rotation={[-Math.PI, 0, -Math.PI]} />
      <mesh name="Object_100" geometry={nodes.Object_100.geometry} material={materials.PaletteMaterial002} position={[0.045, -0.311, 3.414]} />
      <mesh name="Object_22" geometry={nodes.Object_22.geometry} material={materials.PaletteMaterial002} position={[0.019, -0.311, -3.363]} rotation={[-Math.PI, 0, -Math.PI]} />
      <mesh name="Object_98" geometry={nodes.Object_98.geometry} material={materials.PaletteMaterial002} position={[0.045, -0.311, 3.414]} />
      <mesh name="Object_24" geometry={nodes.Object_24.geometry} material={materials.PaletteMaterial002} position={[0.019, -0.311, -3.363]} rotation={[Math.PI, 0, Math.PI / 2]} scale={0.348} />
      <mesh name="Object_150" geometry={nodes.Object_150.geometry} material={materials.PaletteMaterial002} position={[0.045, -0.311, 3.414]} rotation={[0, 0, -Math.PI / 2]} scale={0.348} />
      <mesh name="Object_26" geometry={nodes.Object_26.geometry} material={materials.PaletteMaterial002} position={[0.019, -0.311, -3.363]} rotation={[-Math.PI, 0, -Math.PI]} />
      <mesh name="Object_148" geometry={nodes.Object_148.geometry} material={materials.PaletteMaterial002} position={[0.045, -0.311, 3.414]} />
      <mesh name="Object_28" geometry={nodes.Object_28.geometry} material={materials.PaletteMaterial002} position={[0.019, -0.311, -3.363]} rotation={[Math.PI / 2, 0, 3.141]} />
      <mesh name="Object_145" geometry={nodes.Object_145.geometry} material={materials.PaletteMaterial002} position={[0.045, -0.311, 3.414]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh name="Object_29" geometry={nodes.Object_29.geometry} material={materials.PaletteMaterial002} position={[0.019, -0.311, -3.363]} rotation={[Math.PI / 2, 0, 3.141]} />
      <mesh name="Object_146" geometry={nodes.Object_146.geometry} material={materials.PaletteMaterial002} position={[0.045, -0.311, 3.414]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh name="Object_31" geometry={nodes.Object_31.geometry} material={materials.PaletteMaterial002} position={[0.019, -0.311, -3.363]} rotation={[Math.PI / 2, 0, 3.141]} />
      <mesh name="Object_142" geometry={nodes.Object_142.geometry} material={materials.PaletteMaterial002} position={[0.045, -0.311, 3.414]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh name="Object_32" geometry={nodes.Object_32.geometry} material={materials.PaletteMaterial002} position={[0.019, -0.311, -3.363]} rotation={[Math.PI / 2, 0, 3.141]} />
      <mesh name="Object_143" geometry={nodes.Object_143.geometry} material={materials.PaletteMaterial002} position={[0.045, -0.311, 3.414]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh name="Object_34" geometry={nodes.Object_34.geometry} material={materials.PaletteMaterial002} position={[0.019, -0.311, -3.363]} rotation={[Math.PI / 2, 0, 3.141]} />
      <mesh name="Object_140" geometry={nodes.Object_140.geometry} material={materials.PaletteMaterial002} position={[0.045, -0.311, 3.414]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh name="Object_36" geometry={nodes.Object_36.geometry} material={materials.PaletteMaterial001} position={[0.019, -0.311, -3.363]} rotation={[-Math.PI, 0, -Math.PI]} scale={0.042} />
      <mesh name="Object_138" geometry={nodes.Object_138.geometry} material={materials.PaletteMaterial001} position={[0.045, -0.311, 3.414]} scale={0.042} />
      <mesh name="Object_38" geometry={nodes.Object_38.geometry} material={materials.PaletteMaterial001} position={[0.019, -0.311, -3.363]} rotation={[-Math.PI, 0, -Math.PI]} scale={0.042} />
      <mesh name="Object_136" geometry={nodes.Object_136.geometry} material={materials.PaletteMaterial001} position={[0.045, -0.311, 3.414]} scale={0.042} />
      <mesh name="Object_40" geometry={nodes.Object_40.geometry} material={materials.PaletteMaterial001} position={[0.019, -0.311, -3.363]} rotation={[-Math.PI, 0, -Math.PI]} scale={0.215} />
      <mesh name="Object_134" geometry={nodes.Object_134.geometry} material={materials.PaletteMaterial001} position={[0.045, -0.311, 3.414]} scale={0.215} />
      <mesh name="Object_42" geometry={nodes.Object_42.geometry} material={materials.PaletteMaterial001} position={[0.019, -0.311, -3.363]} rotation={[-Math.PI, 0, -Math.PI]} scale={0.042} />
      <mesh name="Object_132" geometry={nodes.Object_132.geometry} material={materials.PaletteMaterial001} position={[0.045, -0.311, 3.414]} scale={0.042} />
      <mesh name="Object_44" geometry={nodes.Object_44.geometry} material={materials.PaletteMaterial001} position={[0.019, -0.311, -3.363]} rotation={[-Math.PI, 0, -Math.PI]} scale={0.215} />
      <mesh name="Object_130" geometry={nodes.Object_130.geometry} material={materials.PaletteMaterial001} position={[0.045, -0.311, 3.414]} scale={0.215} />
      <mesh name="Object_46" geometry={nodes.Object_46.geometry} material={materials.PaletteMaterial001} position={[0.019, -0.311, -3.363]} rotation={[-1.916, 0, -3.141]} scale={0.015} />
      <mesh name="Object_128" geometry={nodes.Object_128.geometry} material={materials.PaletteMaterial001} position={[0.045, -0.311, 3.414]} rotation={[-1.225, 0, 0]} scale={0.015} />
      <mesh name="Object_48" geometry={nodes.Object_48.geometry} material={materials.PaletteMaterial002} position={[0.019, -0.311, -3.363]} rotation={[-1.249, 0, -3.141]} scale={0.034} />
      <mesh name="Object_126" geometry={nodes.Object_126.geometry} material={materials.PaletteMaterial002} position={[0.045, -0.311, 3.414]} rotation={[-1.892, 0, 0]} scale={0.034} />
      <mesh name="Object_50" geometry={nodes.Object_50.geometry} material={materials.PaletteMaterial002} position={[0.019, -0.311, -3.363]} rotation={[-1.916, 0, -3.141]} scale={0.036} />
      <mesh name="Object_124" geometry={nodes.Object_124.geometry} material={materials.PaletteMaterial002} position={[0.045, -0.311, 3.414]} rotation={[-1.225, 0, 0]} scale={0.036} />
      <mesh name="Object_52" geometry={nodes.Object_52.geometry} material={materials.PaletteMaterial001} position={[0.064, 0.156, -3.193]} rotation={[Math.PI, 0, Math.PI / 2]} scale={0.234} />
      <mesh name="Object_54" geometry={nodes.Object_54.geometry} material={materials.PaletteMaterial001} position={[0.061, 0.156, -11.941]} rotation={[Math.PI, 0, Math.PI / 2]} scale={0.234} />
      <mesh name="Object_154" geometry={nodes.Object_154.geometry} material={materials.PaletteMaterial001} position={[0, 0.156, 11.991]} rotation={[0, 0, -Math.PI / 2]} scale={0.234} />
      <mesh name="Object_166" geometry={nodes.Object_166.geometry} material={materials.PaletteMaterial001} position={[0, 0.156, 3.244]} rotation={[0, 0, -Math.PI / 2]} scale={0.234} />
      <mesh name="Object_56" geometry={nodes.Object_56.geometry} material={materials.PaletteMaterial002} position={[0.019, -0.311, -3.363]} rotation={[Math.PI / 2, 0, 3.141]} />
      <mesh name="Object_96" geometry={nodes.Object_96.geometry} material={materials.PaletteMaterial002} position={[0.045, -0.311, 3.414]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh name="Object_58" geometry={nodes.Object_58.geometry} material={materials.PaletteMaterial002} position={[0.019, -0.311, -3.363]} rotation={[-Math.PI, 0, -Math.PI]} />
      <mesh name="Object_122" geometry={nodes.Object_122.geometry} material={materials.PaletteMaterial002} position={[0.045, -0.311, 3.414]} />
      <mesh name="Object_60" geometry={nodes.Object_60.geometry} material={materials.PaletteMaterial002} position={[0.019, -0.311, -3.363]} rotation={[-Math.PI, 0, -Math.PI]} />
      <mesh name="Object_120" geometry={nodes.Object_120.geometry} material={materials.PaletteMaterial002} position={[0.045, -0.311, 3.414]} />
      <mesh name="Object_62" geometry={nodes.Object_62.geometry} material={materials.PaletteMaterial002} position={[0.019, -0.311, -3.363]} rotation={[-Math.PI, 0, -Math.PI]} />
      <mesh name="Object_118" geometry={nodes.Object_118.geometry} material={materials.PaletteMaterial002} position={[0.045, -0.311, 3.414]} />
      <mesh name="Object_64" geometry={nodes.Object_64.geometry} material={materials.PaletteMaterial002} position={[0.019, -0.311, -3.363]} rotation={[-Math.PI, 0, -Math.PI]} />
      <mesh name="Object_116" geometry={nodes.Object_116.geometry} material={materials.PaletteMaterial002} position={[0.045, -0.311, 3.414]} />
      <mesh name="Object_66" geometry={nodes.Object_66.geometry} material={materials.PaletteMaterial002} position={[0.019, -0.311, -3.363]} rotation={[-Math.PI, 0, -Math.PI]} />
      <mesh name="Object_114" geometry={nodes.Object_114.geometry} material={materials.PaletteMaterial002} position={[0.045, -0.311, 3.414]} />
      <mesh name="Object_68" geometry={nodes.Object_68.geometry} material={materials.PaletteMaterial002} position={[0.019, -0.311, -3.363]} rotation={[-Math.PI, 0, -Math.PI]} />
      <mesh name="Object_112" geometry={nodes.Object_112.geometry} material={materials.PaletteMaterial002} position={[0.045, -0.311, 3.414]} />
      <mesh name="Object_70" geometry={nodes.Object_70.geometry} material={materials.PaletteMaterial002} position={[0.019, -0.311, -3.363]} rotation={[-Math.PI, 0, -Math.PI]} />
      <mesh name="Object_110" geometry={nodes.Object_110.geometry} material={materials.PaletteMaterial002} position={[0.045, -0.311, 3.414]} />
      <mesh name="Object_72" geometry={nodes.Object_72.geometry} material={materials.PaletteMaterial002} position={[0.019, -0.311, -3.363]} rotation={[-Math.PI, 0, -Math.PI]} />
      <mesh name="Object_108" geometry={nodes.Object_108.geometry} material={materials.PaletteMaterial002} position={[0.045, -0.311, 3.414]} />
      <mesh name="Object_74" geometry={nodes.Object_74.geometry} material={materials.PaletteMaterial002} position={[0.019, -0.311, -3.363]} scale={[0.408, 0.046, 0.032]} />
      <mesh name="Object_106" geometry={nodes.Object_106.geometry} material={materials.PaletteMaterial002} position={[0.045, -0.311, 3.414]} rotation={[-Math.PI, 0, -Math.PI]} scale={[0.408, 0.046, 0.032]} />
      <mesh name="Object_76" geometry={nodes.Object_76.geometry} material={materials.PaletteMaterial002} position={[0.019, -0.311, -3.363]} scale={[0.175, 0.056, 0.061]} />
      <mesh name="Object_104" geometry={nodes.Object_104.geometry} material={materials.PaletteMaterial002} position={[0.045, -0.311, 3.414]} rotation={[-Math.PI, 0, -Math.PI]} scale={[0.175, 0.056, 0.061]} />
      <mesh name="Object_78" geometry={nodes.Object_78.geometry} material={materials.PaletteMaterial002} position={[0.019, -0.311, -3.363]} rotation={[-Math.PI, 0, -Math.PI]} scale={[0.661, 1, 1]} />
      <mesh name="Object_102" geometry={nodes.Object_102.geometry} material={materials.PaletteMaterial002} position={[0.045, -0.311, 3.414]} scale={[0.661, 1, 1]} />
      <mesh name="Object_80" geometry={nodes.Object_80.geometry} material={materials.PaletteMaterial003} position={[0.064, 0.156, -3.193]} rotation={[-Math.PI, 0, -Math.PI]} scale={0.234} />
      <mesh name="Object_82" geometry={nodes.Object_82.geometry} material={materials.PaletteMaterial003} position={[0.061, 0.156, -11.941]} rotation={[-Math.PI, 0, -Math.PI]} scale={0.234} />
      <mesh name="Object_152" geometry={nodes.Object_152.geometry} material={materials.PaletteMaterial003} position={[0, 0.156, 11.991]} scale={0.234} />
      <mesh name="Object_84" geometry={nodes.Object_84.geometry} material={materials.PaletteMaterial002} position={[0.019, -0.311, -3.363]} rotation={[-Math.PI, 0, -Math.PI]} />
      <mesh name="Object_85" geometry={nodes.Object_85.geometry} material={materials.PaletteMaterial002} position={[0.019, -0.311, -3.363]} rotation={[-Math.PI, 0, -Math.PI]} />
      <mesh name="Object_86" geometry={nodes.Object_86.geometry} material={materials.PaletteMaterial002} position={[0.019, -0.311, -3.363]} rotation={[-Math.PI, 0, -Math.PI]} />
      <mesh name="Object_92" geometry={nodes.Object_92.geometry} material={materials.PaletteMaterial002} position={[0.045, -0.311, 3.414]} />
      <mesh name="Object_87" geometry={nodes.Object_87.geometry} material={materials.PaletteMaterial002} position={[0.019, -0.311, -3.363]} rotation={[-Math.PI, 0, -Math.PI]} />
      <mesh name="Object_88" geometry={nodes.Object_88.geometry} material={materials.PaletteMaterial002} position={[0.019, -0.311, -3.363]} rotation={[-Math.PI, 0, -Math.PI]} />
      <mesh name="Object_90" geometry={nodes.Object_90.geometry} material={materials.PaletteMaterial002} position={[0.045, -0.311, 3.414]} />
      <mesh name="Object_91" geometry={nodes.Object_91.geometry} material={materials.PaletteMaterial002} position={[0.045, -0.311, 3.414]} />
      <mesh name="Object_93" geometry={nodes.Object_93.geometry} material={materials.PaletteMaterial002} position={[0.045, -0.311, 3.414]} />
      <mesh name="Object_94" geometry={nodes.Object_94.geometry} material={materials.PaletteMaterial002} position={[0.045, -0.311, 3.414]} />
      <mesh name="Object_164" geometry={nodes.Object_164.geometry} material={materials.PaletteMaterial004} position={[0, 0.156, 3.244]} scale={0.234} />
    </group>
  )
}

useGLTF.preload('./Demotrain-wag12/scene-transformed.glb')
