/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 --keepmeshes --resolution 1024 --keepnames --types --output ./FobBridgeModel.tsx --transform ./FobBridge.gltf 
Files: ./FobBridge.gltf [18.89KB] > /home/cronabit/Downloads/Prem/FobBridge/FobBridge-transformed.glb [55KB] (-191%)
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Piller_Left_M: THREE.Mesh
    Piller_Right_M: THREE.Mesh
    Railings_M: THREE.Mesh
    Roof_M: THREE.Mesh
    Stairs_M: THREE.Mesh
    Support_M: THREE.Mesh
    pillers_R: THREE.Mesh
    Railings_R: THREE.Mesh
    Stair_roof_R: THREE.Mesh
    Stairs_R: THREE.Mesh
    Support_R: THREE.Mesh
    pillers_L: THREE.Mesh
    Railings_L: THREE.Mesh
    Stair_roof_L: THREE.Mesh
    Stairs_L: THREE.Mesh
    Support_L: THREE.Mesh
  }
  materials: {
    Railings_And_PIllers_MAT: THREE.MeshStandardMaterial
    ROOF_MAT: THREE.MeshStandardMaterial
    Stairs_MAT: THREE.MeshStandardMaterial
    Support_MAT: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('./Demotrain-wag12/FobBridge-transformed.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh name="Piller_Left_M" geometry={nodes.Piller_Left_M.geometry} material={materials.Railings_And_PIllers_MAT} rotation={[Math.PI / 2, 0, 0]} scale={2.484} />
      <mesh name="Piller_Right_M" geometry={nodes.Piller_Right_M.geometry} material={materials.Railings_And_PIllers_MAT} rotation={[Math.PI / 2, 0, 0]} scale={2.484} />
      <mesh name="Railings_M" geometry={nodes.Railings_M.geometry} material={materials.Railings_And_PIllers_MAT} rotation={[Math.PI / 2, 0, 0]} scale={2.484} />
      <mesh name="Roof_M" geometry={nodes.Roof_M.geometry} material={materials.ROOF_MAT} rotation={[Math.PI / 2, 0, 0]} scale={2.484} />
      <mesh name="Stairs_M" geometry={nodes.Stairs_M.geometry} material={materials.Stairs_MAT} rotation={[Math.PI / 2, 0, 0]} scale={2.484} />
      <mesh name="Support_M" geometry={nodes.Support_M.geometry} material={materials.Support_MAT} rotation={[Math.PI / 2, 0, 0]} scale={2.484} />
      <mesh name="pillers_R" geometry={nodes.pillers_R.geometry} material={materials.Railings_And_PIllers_MAT} rotation={[Math.PI / 2, 0, 0]} scale={2.484} />
      <mesh name="Railings_R" geometry={nodes.Railings_R.geometry} material={materials.Railings_And_PIllers_MAT} rotation={[Math.PI / 2, 0, 0]} scale={2.484} />
      <mesh name="Stair_roof_R" geometry={nodes.Stair_roof_R.geometry} material={materials.ROOF_MAT} rotation={[Math.PI / 2, 0, 0]} scale={2.484} />
      <mesh name="Stairs_R" geometry={nodes.Stairs_R.geometry} material={materials.Stairs_MAT} rotation={[Math.PI / 2, 0, 0]} scale={2.484} />
      <mesh name="Support_R" geometry={nodes.Support_R.geometry} material={materials.Support_MAT} rotation={[Math.PI / 2, 0, 0]} scale={2.484} />
      <mesh name="pillers_L" geometry={nodes.pillers_L.geometry} material={materials.Railings_And_PIllers_MAT} rotation={[Math.PI / 2, 0, 0]} scale={2.484} />
      <mesh name="Railings_L" geometry={nodes.Railings_L.geometry} material={materials.Railings_And_PIllers_MAT} rotation={[Math.PI / 2, 0, 0]} scale={2.484} />
      <mesh name="Stair_roof_L" geometry={nodes.Stair_roof_L.geometry} material={materials.ROOF_MAT} rotation={[Math.PI / 2, 0, 0]} scale={2.484} />
      <mesh name="Stairs_L" geometry={nodes.Stairs_L.geometry} material={materials.Stairs_MAT} rotation={[Math.PI / 2, 0, 0]} scale={2.484} />
      <mesh name="Support_L" geometry={nodes.Support_L.geometry} material={materials.Support_MAT} rotation={[Math.PI / 2, 0, 0]} scale={2.484} />
    </group>
  )
}

useGLTF.preload('./Demotrain-wag12/FobBridge-transformed.glb')
