/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 --keepmeshes --resolution 1024 --keepnames --types --output ./GoodstrainModel.tsx --transform ./scene.gltf 
Files: ./scene.gltf [25.95KB] > C:\Users\HP\Downloads\train_freight_compartment\scene-transformed.glb [360.24KB] (-1288%)
Author: Prabhu Ram (https://sketchfab.com/virtualmakes)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/train-freight-compartment-2cd8d1032b53426a92abb64a71743aa6
Title: Train Freight Compartment
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Object_3: THREE.Mesh
    Object_4: THREE.Mesh
    Object_5: THREE.Mesh
    Object_6: THREE.Mesh
    Object_7: THREE.Mesh
    Object_8: THREE.Mesh
    Object_9: THREE.Mesh
    Object_10: THREE.Mesh
    Object_11: THREE.Mesh
    Object_12: THREE.Mesh
    Object_13: THREE.Mesh
    Object_14: THREE.Mesh
    Object_15: THREE.Mesh
    Object_16: THREE.Mesh
    Object_17: THREE.Mesh
    Object_18: THREE.Mesh
    Object_19: THREE.Mesh
    Object_20: THREE.Mesh
    Object_21: THREE.Mesh
  }
  materials: {
    GoodsCompatmentlambert1SG: THREE.MeshStandardMaterial
    GoodsCompatmentlambert5SG: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('./Demotrain-wag12/goodstrain-transformed.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh name="Object_3" geometry={nodes.Object_3.geometry} material={materials.GoodsCompatmentlambert1SG} position={[5.319, 1.469, 11.918]} rotation={[-Math.PI / 2, 0, 0]} scale={0.464} />
      <mesh name="Object_4" geometry={nodes.Object_4.geometry} material={materials.GoodsCompatmentlambert1SG} position={[5.319, 1.469, 11.918]} rotation={[-Math.PI / 2, 0, 0]} scale={0.464} />
      <mesh name="Object_5" geometry={nodes.Object_5.geometry} material={materials.GoodsCompatmentlambert1SG} position={[5.319, 1.469, 11.918]} rotation={[-Math.PI / 2, 0, 0]} scale={0.464} />
      <mesh name="Object_6" geometry={nodes.Object_6.geometry} material={materials.GoodsCompatmentlambert1SG} position={[5.319, 1.469, 11.918]} rotation={[-Math.PI / 2, 0, 0]} scale={0.464} />
      <mesh name="Object_7" geometry={nodes.Object_7.geometry} material={materials.GoodsCompatmentlambert1SG} position={[5.319, 1.469, 11.918]} rotation={[-Math.PI / 2, 0, 0]} scale={0.464} />
      <mesh name="Object_8" geometry={nodes.Object_8.geometry} material={materials.GoodsCompatmentlambert1SG} position={[5.319, 1.469, 11.918]} rotation={[-Math.PI / 2, 0, 0]} scale={0.464} />
      <mesh name="Object_9" geometry={nodes.Object_9.geometry} material={materials.GoodsCompatmentlambert1SG} position={[5.319, 1.469, 11.918]} rotation={[-Math.PI / 2, 0, 0]} scale={0.464} />
      <mesh name="Object_10" geometry={nodes.Object_10.geometry} material={materials.GoodsCompatmentlambert1SG} position={[5.319, 1.469, 11.918]} rotation={[-Math.PI / 2, 0, 0]} scale={0.464} />
      <mesh name="Object_11" geometry={nodes.Object_11.geometry} material={materials.GoodsCompatmentlambert1SG} position={[5.319, 1.469, 11.918]} rotation={[-Math.PI / 2, 0, 0]} scale={0.464} />
      <mesh name="Object_12" geometry={nodes.Object_12.geometry} material={materials.GoodsCompatmentlambert1SG} position={[5.319, 1.469, 11.918]} rotation={[-Math.PI / 2, 0, 0]} scale={0.464} />
      <mesh name="Object_13" geometry={nodes.Object_13.geometry} material={materials.GoodsCompatmentlambert1SG} position={[5.319, 1.469, 11.918]} rotation={[-Math.PI / 2, 0, 0]} scale={0.464} />
      <mesh name="Object_14" geometry={nodes.Object_14.geometry} material={materials.GoodsCompatmentlambert1SG} position={[5.319, 1.469, 11.918]} rotation={[-Math.PI / 2, 0, 0]} scale={0.464} />
      <mesh name="Object_15" geometry={nodes.Object_15.geometry} material={materials.GoodsCompatmentlambert1SG} position={[5.319, 1.469, 11.918]} rotation={[-Math.PI / 2, 0, 0]} scale={0.464} />
      <mesh name="Object_16" geometry={nodes.Object_16.geometry} material={materials.GoodsCompatmentlambert1SG} position={[5.319, 1.469, 11.918]} rotation={[-Math.PI / 2, 0, 0]} scale={0.464} />
      <mesh name="Object_17" geometry={nodes.Object_17.geometry} material={materials.GoodsCompatmentlambert1SG} position={[5.319, 1.469, 11.918]} rotation={[-Math.PI / 2, 0, 0]} scale={0.464} />
      <mesh name="Object_18" geometry={nodes.Object_18.geometry} material={materials.GoodsCompatmentlambert1SG} position={[5.319, 1.469, 11.918]} rotation={[-Math.PI / 2, 0, 0]} scale={0.464} />
      <mesh name="Object_19" geometry={nodes.Object_19.geometry} material={materials.GoodsCompatmentlambert1SG} position={[5.319, 1.469, 11.918]} rotation={[-Math.PI / 2, 0, 0]} scale={0.464} />
      <mesh name="Object_20" geometry={nodes.Object_20.geometry} material={materials.GoodsCompatmentlambert5SG} position={[5.319, 1.469, 11.918]} rotation={[-Math.PI / 2, 0, 0]} scale={0.464} />
      <mesh name="Object_21" geometry={nodes.Object_21.geometry} material={materials.GoodsCompatmentlambert5SG} position={[5.319, 1.469, 11.918]} rotation={[-Math.PI / 2, 0, 0]} scale={0.464} />
    </group>
  )
}

useGLTF.preload('./Demotrain-wag12/goodstrain-transformed.glb')
