/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 --keepmeshes --resolution 1024 --keepnames --types --output ./GrassDryModel.tsx --transform ./GrassDry.gltf 
Files: ./GrassDry.gltf [6.39KB] > /home/cronabit/Downloads/Prem/chinese_fountain_grass/GrassDry-transformed.glb [108.87KB] (-1604%)
Author: Somersby (https://sketchfab.com/Somersby)
License: CC-BY-NC-4.0 (http://creativecommons.org/licenses/by-nc/4.0/)
Source: https://sketchfab.com/3d-models/chinese-fountain-grass-1b43d98193b746cca341bb9dbb13b45e
Title: Chinese Fountain Grass
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    ['red-baron-grass-ornamental-Va7qqJC-600001_red-baron-grass-ornamental-Va7qqJC-600_0']: THREE.Mesh
    ['red-baron-grass-ornamental-Va7qqJC-600_red-baron-grass-ornamental-Va7qqJC-600_0']: THREE.Mesh
  }
  materials: {
    ['red-baron-grass-ornamental-Va7qqJC-600']: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('./Demotrain-wag12/GrassDrySingle-transformed.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh name="red-baron-grass-ornamental-Va7qqJC-600001_red-baron-grass-ornamental-Va7qqJC-600_0" geometry={nodes['red-baron-grass-ornamental-Va7qqJC-600001_red-baron-grass-ornamental-Va7qqJC-600_0'].geometry} material={materials['red-baron-grass-ornamental-Va7qqJC-600']} position={[1.973, 0, 0.926]} rotation={[-Math.PI / 2, 0, 0]} scale={1.074} />
      <mesh name="red-baron-grass-ornamental-Va7qqJC-600_red-baron-grass-ornamental-Va7qqJC-600_0" geometry={nodes['red-baron-grass-ornamental-Va7qqJC-600_red-baron-grass-ornamental-Va7qqJC-600_0'].geometry} material={materials['red-baron-grass-ornamental-Va7qqJC-600']} position={[1.973, 0, 0.926]} rotation={[-Math.PI / 2, 0, 0]} scale={1.074} />
    </group>
  )
}

useGLTF.preload('./Demotrain-wag12/GrassDrySingle-transformed.glb')
