/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 --keepmeshes --resolution 1024 --keepnames --types --output ./GrassDrySingleModel.tsx --transform ./GrassDrySingle.gltf 
Files: ./GrassDrySingle.gltf [3.95KB] > /home/cronabit/Downloads/Prem/dry_realistic_grass_lods_1 (1)/GrassDrySingle-transformed.glb [43.24KB] (-995%)
Author: Digital screen official (https://sketchfab.com/ck212575)
License: SKETCHFAB Standard (https://sketchfab.com/licenses)
Source: https://sketchfab.com/3d-models/dry-realistic-grass-lods-1-a7ace7ca73ce46d2a2614cebe20fa610
Title: Dry realistic grass lods 1
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Object_2: THREE.Mesh
  }
  materials: {
    Material: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('./Demotrain-wag12/GrassDrySingle-transformed.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh name="Object_2" geometry={nodes.Object_2.geometry} material={materials.Material} rotation={[-Math.PI / 2, 0, 0]} />
    </group>
  )
}

useGLTF.preload('./Demotrain-wag12/GrassDrySingle-transformed.glb')
