// /*
// Auto-generated by: ChatGPT based on file inspection
// Original file: temple by krishna.glb
// */

// import * as THREE from 'three'
// import React, { useMemo } from 'react'
// import { useGLTF, useTexture } from '@react-three/drei'
// import { GLTF } from 'three-stdlib'

// type GLTFResult = GLTF & {
//   nodes: {
//     Object_2: THREE.Mesh
//     Object_4: THREE.Mesh
//     Object_6: THREE.Mesh
//     Object_8: THREE.Mesh
//     Object_10: THREE.Mesh
//     Object_12: THREE.Mesh
//     Object_14: THREE.Mesh
//     Object_16: THREE.Mesh
//     Object_18: THREE.Mesh
//     Object_20: THREE.Mesh
//     Object_22: THREE.Mesh
//     Object_24: THREE.Mesh
//     Object_26: THREE.Mesh
//     Object_28: THREE.Mesh
//     Object_30: THREE.Mesh
//     Object_32: THREE.Mesh
//     Object_34: THREE.Mesh
//     Object_36: THREE.Mesh
//     Object_38: THREE.Mesh
//     Object_40: THREE.Mesh
//     Object_42: THREE.Mesh
//     Object_44: THREE.Mesh
//     Object_46: THREE.Mesh
//     Object_48: THREE.Mesh
//     Object_50: THREE.Mesh
//     Object_52: THREE.Mesh
//     Object_54: THREE.Mesh
//     Object_56: THREE.Mesh
//     Object_58: THREE.Mesh
//     Object_60: THREE.Mesh
//     Object_62: THREE.Mesh
//     Object_64: THREE.Mesh
//     Object_66: THREE.Mesh
//     Object_68: THREE.Mesh
//     Object_70: THREE.Mesh
//     Object_72: THREE.Mesh
//     Object_74: THREE.Mesh
//     Object_76: THREE.Mesh
//   }
// materials: {}
// }

// export function Model(props: JSX.IntrinsicElements['group']) {
//     const { nodes } = useGLTF('./building/temple.glb') as GLTFResult
  
//     const [
//       colorMap,
//       colorVarMap,
//       colorVar2Map,
//       normalMap,
//       roughnessMap,
//       glossMap,
//       reflectionMap,
//     ] = useTexture([
//       '../src-models/temple/Tiles05_COL_VAR1_1K.jpg',
//       '../src-models/temple/Tiles05_COL_VAR1_1K_1.jpeg',
//       '../src-models/temple/Tiles05_COL_VAR2_1K.jpg',
//       '../src-models/temple/Tiles05_NRM_1K_0.jpeg',
//       '../src-models/temple/Tiles05_REFL_1K.jpg',
//       '../src-models/temple/Tiles05_GLOSS_1K.jpg',
//       '../src-models/temple/Tiles05_REFL_1K.jpg', // Reusing REFL for both roughness and reflection
//     ])
  
//     const templeMaterial = useMemo(() => {
//       const material = new THREE.MeshStandardMaterial({
//         map: colorMap,
//         normalMap: normalMap,
//         roughnessMap: roughnessMap,
//         metalness: 0.4,
//         roughness: 1.0,
//       })
  
//       // For glossiness and reflection support (simulated using roughness and envMap if needed)
//     //   glossMap.encoding = THREE.LinearEncoding
//     //   glossMap.wrapS = glossMap.wrapT = THREE.RepeatWrapping
//     //   material.roughnessMap = glossMap
  
//     //   reflectionMap.encoding = THREE.sRGBEncoding
//     //   reflectionMap.mapping = THREE.EquirectangularReflectionMapping
//     //   material.envMap = reflectionMap
//     //   material.envMapIntensity = 1
  
//       return material
//     }, [colorMap, normalMap, roughnessMap, glossMap, reflectionMap])
  
//     return (
//       <group {...props} dispose={null} rotation={[Math.PI / 2, 0, 0]} position={[0, -2, 0]}>
//         {Object.entries(nodes).map(([name, mesh]) => (
//           <mesh
//             key={name}
//             name={name}
//             geometry={mesh.geometry}
//             material={templeMaterial}
//             position={[0, 0, 0]}
//           />
//         ))}
//       </group>
//     )
//   }
  
//   useGLTF.preload('./building/temple.glb')