/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 --keepmeshes --resolution 1024 --keepnames --types --output ./Apartment.tsx --transform ./apartment.gltf 
Files: ./apartment.gltf [2.02KB] > /home/cronabit/Desktop/Building/aparment/apartment-transformed.glb [30.46KB] (-1408%)
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Object003: THREE.Mesh
  }
  materials: {
    skp_front_default: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('./building/apartment-transformed.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh name="Object003" geometry={nodes.Object003.geometry} material={materials.skp_front_default} position={[-18.55, 98, 18.898]} scale={0.01} />
    </group>
  )
}

useGLTF.preload('./building/apartment-transformed.glb')
