/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 --keepmeshes --resolution 1024 --keepnames --types --output ./Apartment2.tsx --transform ./apartment2.gltf 
Files: ./apartment2.gltf [8.88KB] > /home/cronabit/Desktop/Building/aparment/apartment2-transformed.glb [520.74KB] (-5764%)
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type ActionName = 'VRaySun001|Take 001|BaseLayer'

interface GLTFAction extends THREE.AnimationClip {
  name: ActionName
}

type GLTFResult = GLTF & {
  nodes: {
    Box132: THREE.Mesh
    Mesh386: THREE.Mesh
    Mesh386_1: THREE.Mesh
    Mesh386_2: THREE.Mesh
  }
  materials: {
    ['02 - Default']: THREE.MeshStandardMaterial
    ['Material #26']: THREE.MeshStandardMaterial
    ['Material #25']: THREE.MeshStandardMaterial
    ['Material #27']: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const group = React.useRef<THREE.Group>()
  const { nodes, materials, animations } = useGLTF('./building/apartment2-transformed.glb') as GLTFResult
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="VRaySun001" position={[28.048, 17.536, 12.18]} rotation={[1.075, 0.508, -0.732]} scale={0.01} />
        <mesh name="Box132" geometry={nodes.Box132.geometry} material={materials['02 - Default']} position={[-4.575, 1.209, -5.885]} rotation={[-Math.PI / 2, 0, Math.PI]} scale={[-0.008, -0.007, -0.01]} />
        <group name="Object001" scale={0.025}>
          <mesh name="Mesh386" geometry={nodes.Mesh386.geometry} material={materials['Material #26']} />
          <mesh name="Mesh386_1" geometry={nodes.Mesh386_1.geometry} material={materials['Material #25']} />
          <mesh name="Mesh386_2" geometry={nodes.Mesh386_2.geometry} material={materials['Material #27']} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('./building/apartment2-transformed.glb')
