/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 --keepmeshes --resolution 1024 --keepnames --types --output ./Apartment1.tsx --transform ./apartment1.gltf 
Files: ./apartment1.gltf [459.05KB] > /home/cronabit/Desktop/Building/aparment/apartment1-transformed.glb [105.04KB] (77%)
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type ActionName = 'VRaySun001|Take 001|BaseLayer'

interface GLTFAction extends THREE.AnimationClip {
  name: ActionName
}

type GLTFResult = GLTF & {
  nodes: {
    Plane001: THREE.Mesh
    Plane012: THREE.Mesh
    Plane013: THREE.Mesh
    Plane014: THREE.Mesh
    Plane015: THREE.Mesh
    Plane019: THREE.Mesh
    Plane020: THREE.Mesh
    Plane024: THREE.Mesh
    Plane018: THREE.Mesh
    Plane016: THREE.Mesh
    Plane017: THREE.Mesh
    Plane039: THREE.Mesh
    Plane040: THREE.Mesh
    Plane041: THREE.Mesh
    Plane042: THREE.Mesh
    Plane046: THREE.Mesh
    Plane047: THREE.Mesh
    Plane048: THREE.Mesh
    Plane045: THREE.Mesh
    Plane043: THREE.Mesh
    Plane044: THREE.Mesh
    Plane049: THREE.Mesh
    Plane050: THREE.Mesh
    Plane051: THREE.Mesh
    Plane088: THREE.Mesh
    Plane089: THREE.Mesh
    Plane090: THREE.Mesh
    Plane091: THREE.Mesh
    Plane092: THREE.Mesh
    Plane093: THREE.Mesh
    Plane094: THREE.Mesh
    Plane095: THREE.Mesh
    Plane096: THREE.Mesh
    Plane097: THREE.Mesh
    Plane103: THREE.Mesh
    Plane104: THREE.Mesh
    Plane105: THREE.Mesh
    Plane106: THREE.Mesh
    Plane107: THREE.Mesh
    Plane108: THREE.Mesh
    Plane109: THREE.Mesh
    Plane110: THREE.Mesh
    Plane111: THREE.Mesh
    Plane112: THREE.Mesh
    Plane118: THREE.Mesh
    Plane122: THREE.Mesh
    Plane123: THREE.Mesh
    Plane124: THREE.Mesh
    Plane121: THREE.Mesh
    Plane119: THREE.Mesh
    Plane120: THREE.Mesh
    Plane135: THREE.Mesh
    Plane136: THREE.Mesh
    Plane137: THREE.Mesh
    Plane166: THREE.Mesh
    Plane170: THREE.Mesh
    Plane171: THREE.Mesh
    Plane172: THREE.Mesh
    Plane169: THREE.Mesh
    Plane167: THREE.Mesh
    Plane168: THREE.Mesh
    Plane173: THREE.Mesh
    Plane174: THREE.Mesh
    Plane175: THREE.Mesh
    Box001: THREE.Mesh
    Box021: THREE.Mesh
    Box022: THREE.Mesh
    Box023: THREE.Mesh
    Box002: THREE.Mesh
    Box003: THREE.Mesh
    Box077: THREE.Mesh
    Box078: THREE.Mesh
    Box131: THREE.Mesh
    Box132: THREE.Mesh
    Box179: THREE.Mesh
    Box180: THREE.Mesh
    Box208: THREE.Mesh
    Box209: THREE.Mesh
    Box024: THREE.Mesh
    Box028: THREE.Mesh
    Box029: THREE.Mesh
    Box030: THREE.Mesh
    Box041: THREE.Mesh
    Box042: THREE.Mesh
    Box013: THREE.Mesh
    Box014: THREE.Mesh
    Box051: THREE.Mesh
    Box052: THREE.Mesh
    Box054: THREE.Mesh
    Box055: THREE.Mesh
    Box027: THREE.Mesh
    Box025: THREE.Mesh
    Box026: THREE.Mesh
    Box064: THREE.Mesh
    Box065: THREE.Mesh
    Box066: THREE.Mesh
    Box067: THREE.Mesh
    Box071: THREE.Mesh
    Box072: THREE.Mesh
    Box073: THREE.Mesh
    Box070: THREE.Mesh
    Box068: THREE.Mesh
    Box069: THREE.Mesh
    Box074: THREE.Mesh
    Box075: THREE.Mesh
    Box076: THREE.Mesh
    Box088: THREE.Mesh
    Box089: THREE.Mesh
    Box085: THREE.Mesh
    Box086: THREE.Mesh
    Box098: THREE.Mesh
    Box099: THREE.Mesh
    Box101: THREE.Mesh
    Box102: THREE.Mesh
    Box111: THREE.Mesh
    Box112: THREE.Mesh
    Box113: THREE.Mesh
    Box114: THREE.Mesh
    Box115: THREE.Mesh
    Box116: THREE.Mesh
    Box117: THREE.Mesh
    Box118: THREE.Mesh
    Box119: THREE.Mesh
    Box120: THREE.Mesh
    Box121: THREE.Mesh
    Box122: THREE.Mesh
    Box123: THREE.Mesh
    Box124: THREE.Mesh
    Box125: THREE.Mesh
    Box126: THREE.Mesh
    Box127: THREE.Mesh
    Box128: THREE.Mesh
    Box129: THREE.Mesh
    Box130: THREE.Mesh
    Box142: THREE.Mesh
    Box146: THREE.Mesh
    Box147: THREE.Mesh
    Box148: THREE.Mesh
    Box149: THREE.Mesh
    Box150: THREE.Mesh
    Box139: THREE.Mesh
    Box140: THREE.Mesh
    Box159: THREE.Mesh
    Box160: THREE.Mesh
    Box162: THREE.Mesh
    Box163: THREE.Mesh
    Box145: THREE.Mesh
    Box143: THREE.Mesh
    Box144: THREE.Mesh
    Box172: THREE.Mesh
    Box173: THREE.Mesh
    Box174: THREE.Mesh
    Box185: THREE.Mesh
    Box186: THREE.Mesh
    Box182: THREE.Mesh
    Box183: THREE.Mesh
    Box195: THREE.Mesh
    Box196: THREE.Mesh
    Box198: THREE.Mesh
    Box199: THREE.Mesh
    Box214: THREE.Mesh
    Box215: THREE.Mesh
    Box211: THREE.Mesh
    Box212: THREE.Mesh
    Box224: THREE.Mesh
    Box225: THREE.Mesh
    Box227: THREE.Mesh
    Box228: THREE.Mesh
    Box237: THREE.Mesh
    Box241: THREE.Mesh
    Box242: THREE.Mesh
    Box243: THREE.Mesh
    Box240: THREE.Mesh
    Box238: THREE.Mesh
    Box239: THREE.Mesh
    Box244: THREE.Mesh
    Box245: THREE.Mesh
    Box246: THREE.Mesh
    Plane009: THREE.Mesh
    Plane010: THREE.Mesh
    Box017: THREE.Mesh
    Box018: THREE.Mesh
    Cylinder001: THREE.Mesh
    Cylinder002: THREE.Mesh
    Box010: THREE.Mesh
    Box009: THREE.Mesh
    Box007: THREE.Mesh
    Box008: THREE.Mesh
    Box011: THREE.Mesh
    Box012: THREE.Mesh
    Box081: THREE.Mesh
    Box082: THREE.Mesh
    Box083: THREE.Mesh
    Box084: THREE.Mesh
    Box137: THREE.Mesh
    Box138: THREE.Mesh
    Box175: THREE.Mesh
    Box176: THREE.Mesh
    Box177: THREE.Mesh
    Box178: THREE.Mesh
    Box045: THREE.Mesh
    Box046: THREE.Mesh
    Box047: THREE.Mesh
    Box048: THREE.Mesh
    Box049: THREE.Mesh
    Box050: THREE.Mesh
    Box058: THREE.Mesh
    Box059: THREE.Mesh
    Box060: THREE.Mesh
    Box061: THREE.Mesh
    Box062: THREE.Mesh
    Box063: THREE.Mesh
    Box092: THREE.Mesh
    Box093: THREE.Mesh
    Box094: THREE.Mesh
    Box095: THREE.Mesh
    Box096: THREE.Mesh
    Box097: THREE.Mesh
    Box105: THREE.Mesh
    Box106: THREE.Mesh
    Box107: THREE.Mesh
    Box108: THREE.Mesh
    Box109: THREE.Mesh
    Box110: THREE.Mesh
    Box153: THREE.Mesh
    Box154: THREE.Mesh
    Box155: THREE.Mesh
    Box156: THREE.Mesh
    Box157: THREE.Mesh
    Box158: THREE.Mesh
    Box166: THREE.Mesh
    Box167: THREE.Mesh
    Box168: THREE.Mesh
    Box169: THREE.Mesh
    Box170: THREE.Mesh
    Box171: THREE.Mesh
    Box189: THREE.Mesh
    Box190: THREE.Mesh
    Box191: THREE.Mesh
    Box192: THREE.Mesh
    Box193: THREE.Mesh
    Box194: THREE.Mesh
    Box202: THREE.Mesh
    Box203: THREE.Mesh
    Box204: THREE.Mesh
    Box205: THREE.Mesh
    Box206: THREE.Mesh
    Box207: THREE.Mesh
    Box218: THREE.Mesh
    Box219: THREE.Mesh
    Box220: THREE.Mesh
    Box221: THREE.Mesh
    Box222: THREE.Mesh
    Box223: THREE.Mesh
    Box231: THREE.Mesh
    Box232: THREE.Mesh
    Box233: THREE.Mesh
    Box234: THREE.Mesh
    Box235: THREE.Mesh
    Box236: THREE.Mesh
    Plane005: THREE.Mesh
    Plane006: THREE.Mesh
    Plane072: THREE.Mesh
    Plane115: THREE.Mesh
    Plane138: THREE.Mesh
    Plane139: THREE.Mesh
    Plane031: THREE.Mesh
    Plane032: THREE.Mesh
    Plane037: THREE.Mesh
    Plane038: THREE.Mesh
    Plane077: THREE.Mesh
    Plane078: THREE.Mesh
    Plane083: THREE.Mesh
    Plane084: THREE.Mesh
    Plane127: THREE.Mesh
    Plane128: THREE.Mesh
    Plane133: THREE.Mesh
    Plane134: THREE.Mesh
    Plane145: THREE.Mesh
    Plane146: THREE.Mesh
    Plane151: THREE.Mesh
    Plane152: THREE.Mesh
    Plane158: THREE.Mesh
    Plane159: THREE.Mesh
    Plane164: THREE.Mesh
    Plane165: THREE.Mesh
    Plane004: THREE.Mesh
    Plane071: THREE.Mesh
    Plane030: THREE.Mesh
    Plane036: THREE.Mesh
    Plane076: THREE.Mesh
    Plane082: THREE.Mesh
    Plane126: THREE.Mesh
    Plane132: THREE.Mesh
    Plane144: THREE.Mesh
    Plane150: THREE.Mesh
    Plane157: THREE.Mesh
    Plane163: THREE.Mesh
    Box004: THREE.Mesh
    Box079: THREE.Mesh
    Box133: THREE.Mesh
    Box043: THREE.Mesh
    Box056: THREE.Mesh
    Box090: THREE.Mesh
    Box103: THREE.Mesh
    Box151: THREE.Mesh
    Box164: THREE.Mesh
    Box187: THREE.Mesh
    Box200: THREE.Mesh
    Box216: THREE.Mesh
    Box229: THREE.Mesh
    Plane003: THREE.Mesh
    Plane070: THREE.Mesh
    Plane113: THREE.Mesh
    Plane140: THREE.Mesh
    Plane153: THREE.Mesh
    Plane029: THREE.Mesh
    Plane007: THREE.Mesh
    Plane033: THREE.Mesh
    Plane035: THREE.Mesh
    Plane075: THREE.Mesh
    Plane073: THREE.Mesh
    Plane079: THREE.Mesh
    Plane081: THREE.Mesh
    Plane125: THREE.Mesh
    Plane116: THREE.Mesh
    Plane129: THREE.Mesh
    Plane131: THREE.Mesh
    Plane143: THREE.Mesh
    Plane141: THREE.Mesh
    Plane147: THREE.Mesh
    Plane149: THREE.Mesh
    Plane156: THREE.Mesh
    Plane154: THREE.Mesh
    Plane160: THREE.Mesh
    Plane162: THREE.Mesh
    Box005: THREE.Mesh
    Box080: THREE.Mesh
    Box134: THREE.Mesh
    Box181: THREE.Mesh
    Box210: THREE.Mesh
    Box044: THREE.Mesh
    Box016: THREE.Mesh
    Box053: THREE.Mesh
    Box057: THREE.Mesh
    Box091: THREE.Mesh
    Box087: THREE.Mesh
    Box100: THREE.Mesh
    Box104: THREE.Mesh
    Box152: THREE.Mesh
    Box141: THREE.Mesh
    Box161: THREE.Mesh
    Box165: THREE.Mesh
    Box188: THREE.Mesh
    Box184: THREE.Mesh
    Box197: THREE.Mesh
    Box201: THREE.Mesh
    Box217: THREE.Mesh
    Box213: THREE.Mesh
    Box226: THREE.Mesh
    Box230: THREE.Mesh
    Plane068: THREE.Mesh
    Plane069: THREE.Mesh
    Plane085: THREE.Mesh
    Plane086: THREE.Mesh
    Plane087: THREE.Mesh
    Plane098: THREE.Mesh
    Plane099: THREE.Mesh
    Plane100: THREE.Mesh
    Plane101: THREE.Mesh
    Plane102: THREE.Mesh
    Plane177: THREE.Mesh
    Plane178: THREE.Mesh
    Plane179: THREE.Mesh
    Plane180: THREE.Mesh
    Plane181: THREE.Mesh
    Plane182: THREE.Mesh
    Plane183: THREE.Mesh
    Plane184: THREE.Mesh
    Plane185: THREE.Mesh
    Plane186: THREE.Mesh
    Plane176: THREE.Mesh
    Box247: THREE.Mesh
    Box248: THREE.Mesh
    Box249: THREE.Mesh
  }
  materials: {
    ['02 - Default']: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const group = React.useRef<THREE.Group>()
  const { nodes, materials, animations } = useGLTF('./building/apartment1-transformed.glb') as GLTFResult
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="VRaySun001" position={[28.048, 17.536, 12.18]} rotation={[1.075, 0.508, -0.732]} scale={0.01} />
        <mesh name="Plane001" geometry={nodes.Plane001.geometry} material={materials['02 - Default']} position={[0.174, 1.846, -0.079]} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
        <mesh name="Plane012" geometry={nodes.Plane012.geometry} material={materials['02 - Default']} position={[0.174, 3.046, -0.079]} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
        <mesh name="Plane013" geometry={nodes.Plane013.geometry} material={materials['02 - Default']} position={[0.174, 4.246, -0.079]} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
        <mesh name="Plane014" geometry={nodes.Plane014.geometry} material={materials['02 - Default']} position={[0.174, 5.446, -0.079]} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
        <mesh name="Plane015" geometry={nodes.Plane015.geometry} material={materials['02 - Default']} position={[-1.326, 2.446, -0.079]} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
        <mesh name="Plane019" geometry={nodes.Plane019.geometry} material={materials['02 - Default']} position={[-1.326, 1.246, -0.079]} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
        <mesh name="Plane020" geometry={nodes.Plane020.geometry} material={materials['02 - Default']} position={[-2.826, 2.446, -0.079]} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
        <mesh name="Plane024" geometry={nodes.Plane024.geometry} material={materials['02 - Default']} position={[-2.826, 1.246, -0.079]} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
        <mesh name="Plane018" geometry={nodes.Plane018.geometry} material={materials['02 - Default']} position={[-1.326, 6.046, -0.079]} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
        <mesh name="Plane016" geometry={nodes.Plane016.geometry} material={materials['02 - Default']} position={[-1.326, 3.646, -0.079]} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
        <mesh name="Plane017" geometry={nodes.Plane017.geometry} material={materials['02 - Default']} position={[-1.326, 4.846, -0.079]} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
        <mesh name="Plane039" geometry={nodes.Plane039.geometry} material={materials['02 - Default']} position={[-2.826, 3.644, -0.097]} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
        <mesh name="Plane040" geometry={nodes.Plane040.geometry} material={materials['02 - Default']} position={[-2.826, 4.844, -0.097]} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
        <mesh name="Plane041" geometry={nodes.Plane041.geometry} material={materials['02 - Default']} position={[-2.826, 6.044, -0.097]} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
        <mesh name="Plane042" geometry={nodes.Plane042.geometry} material={materials['02 - Default']} position={[3.173, 2.449, -0.06]} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
        <mesh name="Plane046" geometry={nodes.Plane046.geometry} material={materials['02 - Default']} position={[3.173, 1.249, -0.06]} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
        <mesh name="Plane047" geometry={nodes.Plane047.geometry} material={materials['02 - Default']} position={[1.673, 2.449, -0.06]} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
        <mesh name="Plane048" geometry={nodes.Plane048.geometry} material={materials['02 - Default']} position={[1.673, 1.249, -0.06]} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
        <mesh name="Plane045" geometry={nodes.Plane045.geometry} material={materials['02 - Default']} position={[3.173, 6.049, -0.06]} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
        <mesh name="Plane043" geometry={nodes.Plane043.geometry} material={materials['02 - Default']} position={[3.173, 3.649, -0.06]} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
        <mesh name="Plane044" geometry={nodes.Plane044.geometry} material={materials['02 - Default']} position={[3.173, 4.849, -0.06]} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
        <mesh name="Plane049" geometry={nodes.Plane049.geometry} material={materials['02 - Default']} position={[1.674, 3.646, -0.079]} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
        <mesh name="Plane050" geometry={nodes.Plane050.geometry} material={materials['02 - Default']} position={[1.674, 4.846, -0.079]} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
        <mesh name="Plane051" geometry={nodes.Plane051.geometry} material={materials['02 - Default']} position={[1.674, 6.046, -0.079]} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
        <mesh name="Plane088" geometry={nodes.Plane088.geometry} material={materials['02 - Default']} position={[-5.076, 2.446, -2.329]} rotation={[Math.PI / 2, 0, Math.PI / 2]} scale={0.01} />
        <mesh name="Plane089" geometry={nodes.Plane089.geometry} material={materials['02 - Default']} position={[-5.076, 1.246, -2.329]} rotation={[Math.PI / 2, 0, Math.PI / 2]} scale={0.01} />
        <mesh name="Plane090" geometry={nodes.Plane090.geometry} material={materials['02 - Default']} position={[-5.057, 3.644, -2.328]} rotation={[Math.PI / 2, 0, Math.PI / 2]} scale={0.01} />
        <mesh name="Plane091" geometry={nodes.Plane091.geometry} material={materials['02 - Default']} position={[-5.057, 4.844, -2.328]} rotation={[Math.PI / 2, 0, Math.PI / 2]} scale={0.01} />
        <mesh name="Plane092" geometry={nodes.Plane092.geometry} material={materials['02 - Default']} position={[-5.057, 6.044, -2.328]} rotation={[Math.PI / 2, 0, Math.PI / 2]} scale={0.01} />
        <mesh name="Plane093" geometry={nodes.Plane093.geometry} material={materials['02 - Default']} position={[-5.076, 2.446, -3.829]} rotation={[Math.PI / 2, 0, Math.PI / 2]} scale={0.01} />
        <mesh name="Plane094" geometry={nodes.Plane094.geometry} material={materials['02 - Default']} position={[-5.076, 1.246, -3.829]} rotation={[Math.PI / 2, 0, Math.PI / 2]} scale={0.01} />
        <mesh name="Plane095" geometry={nodes.Plane095.geometry} material={materials['02 - Default']} position={[-5.057, 3.644, -3.828]} rotation={[Math.PI / 2, 0, Math.PI / 2]} scale={0.01} />
        <mesh name="Plane096" geometry={nodes.Plane096.geometry} material={materials['02 - Default']} position={[-5.057, 4.844, -3.828]} rotation={[Math.PI / 2, 0, Math.PI / 2]} scale={0.01} />
        <mesh name="Plane097" geometry={nodes.Plane097.geometry} material={materials['02 - Default']} position={[-5.057, 6.044, -3.828]} rotation={[Math.PI / 2, 0, Math.PI / 2]} scale={0.01} />
        <mesh name="Plane103" geometry={nodes.Plane103.geometry} material={materials['02 - Default']} position={[5.423, 2.449, -2.31]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={[-0.01, 0.01, 0.01]} />
        <mesh name="Plane104" geometry={nodes.Plane104.geometry} material={materials['02 - Default']} position={[5.423, 1.249, -2.31]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={[-0.01, 0.01, 0.01]} />
        <mesh name="Plane105" geometry={nodes.Plane105.geometry} material={materials['02 - Default']} position={[5.405, 3.646, -2.309]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={[-0.01, 0.01, 0.01]} />
        <mesh name="Plane106" geometry={nodes.Plane106.geometry} material={materials['02 - Default']} position={[5.405, 4.846, -2.309]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={[-0.01, 0.01, 0.01]} />
        <mesh name="Plane107" geometry={nodes.Plane107.geometry} material={materials['02 - Default']} position={[5.405, 6.046, -2.309]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={[-0.01, 0.01, 0.01]} />
        <mesh name="Plane108" geometry={nodes.Plane108.geometry} material={materials['02 - Default']} position={[5.423, 2.449, -3.81]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={[-0.01, 0.01, 0.01]} />
        <mesh name="Plane109" geometry={nodes.Plane109.geometry} material={materials['02 - Default']} position={[5.423, 1.249, -3.81]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={[-0.01, 0.01, 0.01]} />
        <mesh name="Plane110" geometry={nodes.Plane110.geometry} material={materials['02 - Default']} position={[5.405, 3.646, -3.809]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={[-0.01, 0.01, 0.01]} />
        <mesh name="Plane111" geometry={nodes.Plane111.geometry} material={materials['02 - Default']} position={[5.405, 4.846, -3.809]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={[-0.01, 0.01, 0.01]} />
        <mesh name="Plane112" geometry={nodes.Plane112.geometry} material={materials['02 - Default']} position={[5.405, 6.046, -3.809]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={[-0.01, 0.01, 0.01]} />
        <mesh name="Plane118" geometry={nodes.Plane118.geometry} material={materials['02 - Default']} position={[-1.357, 2.418, -6.079]} rotation={[Math.PI / 2, 0, Math.PI]} scale={[-0.01, 0.01, 0.01]} />
        <mesh name="Plane122" geometry={nodes.Plane122.geometry} material={materials['02 - Default']} position={[-1.357, 1.218, -6.079]} rotation={[Math.PI / 2, 0, Math.PI]} scale={[-0.01, 0.01, 0.01]} />
        <mesh name="Plane123" geometry={nodes.Plane123.geometry} material={materials['02 - Default']} position={[-2.857, 2.418, -6.079]} rotation={[Math.PI / 2, 0, Math.PI]} scale={[-0.01, 0.01, 0.01]} />
        <mesh name="Plane124" geometry={nodes.Plane124.geometry} material={materials['02 - Default']} position={[-2.857, 1.218, -6.079]} rotation={[Math.PI / 2, 0, Math.PI]} scale={[-0.01, 0.01, 0.01]} />
        <mesh name="Plane121" geometry={nodes.Plane121.geometry} material={materials['02 - Default']} position={[-1.357, 6.018, -6.079]} rotation={[Math.PI / 2, 0, Math.PI]} scale={[-0.01, 0.01, 0.01]} />
        <mesh name="Plane119" geometry={nodes.Plane119.geometry} material={materials['02 - Default']} position={[-1.357, 3.618, -6.079]} rotation={[Math.PI / 2, 0, Math.PI]} scale={[-0.01, 0.01, 0.01]} />
        <mesh name="Plane120" geometry={nodes.Plane120.geometry} material={materials['02 - Default']} position={[-1.357, 4.818, -6.079]} rotation={[Math.PI / 2, 0, Math.PI]} scale={[-0.01, 0.01, 0.01]} />
        <mesh name="Plane135" geometry={nodes.Plane135.geometry} material={materials['02 - Default']} position={[-2.856, 3.615, -6.06]} rotation={[Math.PI / 2, 0, Math.PI]} scale={[-0.01, 0.01, 0.01]} />
        <mesh name="Plane136" geometry={nodes.Plane136.geometry} material={materials['02 - Default']} position={[-2.856, 4.815, -6.06]} rotation={[Math.PI / 2, 0, Math.PI]} scale={[-0.01, 0.01, 0.01]} />
        <mesh name="Plane137" geometry={nodes.Plane137.geometry} material={materials['02 - Default']} position={[-2.856, 6.015, -6.06]} rotation={[Math.PI / 2, 0, Math.PI]} scale={[-0.01, 0.01, 0.01]} />
        <mesh name="Plane166" geometry={nodes.Plane166.geometry} material={materials['02 - Default']} position={[3.143, 2.417, -6.079]} rotation={[Math.PI / 2, 0, Math.PI]} scale={[-0.01, 0.01, 0.01]} />
        <mesh name="Plane170" geometry={nodes.Plane170.geometry} material={materials['02 - Default']} position={[3.143, 1.217, -6.079]} rotation={[Math.PI / 2, 0, Math.PI]} scale={[-0.01, 0.01, 0.01]} />
        <mesh name="Plane171" geometry={nodes.Plane171.geometry} material={materials['02 - Default']} position={[1.643, 2.417, -6.079]} rotation={[Math.PI / 2, 0, Math.PI]} scale={[-0.01, 0.01, 0.01]} />
        <mesh name="Plane172" geometry={nodes.Plane172.geometry} material={materials['02 - Default']} position={[1.643, 1.217, -6.079]} rotation={[Math.PI / 2, 0, Math.PI]} scale={[-0.01, 0.01, 0.01]} />
        <mesh name="Plane169" geometry={nodes.Plane169.geometry} material={materials['02 - Default']} position={[3.143, 6.017, -6.079]} rotation={[Math.PI / 2, 0, Math.PI]} scale={[-0.01, 0.01, 0.01]} />
        <mesh name="Plane167" geometry={nodes.Plane167.geometry} material={materials['02 - Default']} position={[3.143, 3.617, -6.079]} rotation={[Math.PI / 2, 0, Math.PI]} scale={[-0.01, 0.01, 0.01]} />
        <mesh name="Plane168" geometry={nodes.Plane168.geometry} material={materials['02 - Default']} position={[3.143, 4.817, -6.079]} rotation={[Math.PI / 2, 0, Math.PI]} scale={[-0.01, 0.01, 0.01]} />
        <mesh name="Plane173" geometry={nodes.Plane173.geometry} material={materials['02 - Default']} position={[1.644, 3.614, -6.06]} rotation={[Math.PI / 2, 0, Math.PI]} scale={[-0.01, 0.01, 0.01]} />
        <mesh name="Plane174" geometry={nodes.Plane174.geometry} material={materials['02 - Default']} position={[1.644, 4.814, -6.06]} rotation={[Math.PI / 2, 0, Math.PI]} scale={[-0.01, 0.01, 0.01]} />
        <mesh name="Plane175" geometry={nodes.Plane175.geometry} material={materials['02 - Default']} position={[1.644, 6.014, -6.06]} rotation={[Math.PI / 2, 0, Math.PI]} scale={[-0.01, 0.01, 0.01]} />
        <mesh name="Box001" geometry={nodes.Box001.geometry} material={materials['02 - Default']} position={[0.265, 1.838, -0.273]} rotation={[Math.PI / 2, 0, 0]} scale={[0.008, 0.007, 0.01]} />
        <mesh name="Box021" geometry={nodes.Box021.geometry} material={materials['02 - Default']} position={[0.265, 3.038, -0.273]} rotation={[Math.PI / 2, 0, 0]} scale={[0.008, 0.007, 0.01]} />
        <mesh name="Box022" geometry={nodes.Box022.geometry} material={materials['02 - Default']} position={[0.265, 4.238, -0.273]} rotation={[Math.PI / 2, 0, 0]} scale={[0.008, 0.007, 0.01]} />
        <mesh name="Box023" geometry={nodes.Box023.geometry} material={materials['02 - Default']} position={[0.265, 5.438, -0.273]} rotation={[Math.PI / 2, 0, 0]} scale={[0.008, 0.007, 0.01]} />
        <mesh name="Box002" geometry={nodes.Box002.geometry} material={materials['02 - Default']} position={[-4.167, 1.238, -0.273]} rotation={[Math.PI / 2, 0, 0]} scale={[0.008, 0.007, 0.01]} />
        <mesh name="Box003" geometry={nodes.Box003.geometry} material={materials['02 - Default']} position={[-4.545, 1.238, -0.273]} rotation={[Math.PI / 2, 0, 0]} scale={[0.008, 0.007, 0.01]} />
        <mesh name="Box077" geometry={nodes.Box077.geometry} material={materials['02 - Default']} position={[4.832, 1.241, -0.254]} rotation={[Math.PI / 2, 0, 0]} scale={[0.008, 0.007, 0.01]} />
        <mesh name="Box078" geometry={nodes.Box078.geometry} material={materials['02 - Default']} position={[4.455, 1.241, -0.254]} rotation={[Math.PI / 2, 0, 0]} scale={[0.008, 0.007, 0.01]} />
        <mesh name="Box131" geometry={nodes.Box131.geometry} material={materials['02 - Default']} position={[-4.197, 1.209, -5.885]} rotation={[-Math.PI / 2, 0, Math.PI]} scale={[-0.008, -0.007, -0.01]} />
        <mesh name="Box132" geometry={nodes.Box132.geometry} material={materials['02 - Default']} position={[-4.575, 1.209, -5.885]} rotation={[-Math.PI / 2, 0, Math.PI]} scale={[-0.008, -0.007, -0.01]} />
        <mesh name="Box179" geometry={nodes.Box179.geometry} material={materials['02 - Default']} position={[0.302, 1.209, -5.885]} rotation={[-Math.PI / 2, 0, Math.PI]} scale={[-0.008, -0.007, -0.01]} />
        <mesh name="Box180" geometry={nodes.Box180.geometry} material={materials['02 - Default']} position={[-0.075, 1.209, -5.885]} rotation={[-Math.PI / 2, 0, Math.PI]} scale={[-0.008, -0.007, -0.01]} />
        <mesh name="Box208" geometry={nodes.Box208.geometry} material={materials['02 - Default']} position={[4.802, 1.212, -5.866]} rotation={[-Math.PI / 2, 0, Math.PI]} scale={[-0.008, -0.007, -0.01]} />
        <mesh name="Box209" geometry={nodes.Box209.geometry} material={materials['02 - Default']} position={[4.425, 1.212, -5.866]} rotation={[-Math.PI / 2, 0, Math.PI]} scale={[-0.008, -0.007, -0.01]} />
        <mesh name="Box024" geometry={nodes.Box024.geometry} material={materials['02 - Default']} position={[-1.235, 2.438, -0.273]} rotation={[Math.PI / 2, 0, 0]} scale={[0.008, 0.007, 0.01]} />
        <mesh name="Box028" geometry={nodes.Box028.geometry} material={materials['02 - Default']} position={[-1.235, 1.238, -0.273]} rotation={[Math.PI / 2, 0, 0]} scale={[0.008, 0.007, 0.01]} />
        <mesh name="Box029" geometry={nodes.Box029.geometry} material={materials['02 - Default']} position={[-2.735, 2.438, -0.273]} rotation={[Math.PI / 2, 0, 0]} scale={[0.008, 0.007, 0.01]} />
        <mesh name="Box030" geometry={nodes.Box030.geometry} material={materials['02 - Default']} position={[-2.735, 1.238, -0.273]} rotation={[Math.PI / 2, 0, 0]} scale={[0.008, 0.007, 0.01]} />
        <mesh name="Box041" geometry={nodes.Box041.geometry} material={materials['02 - Default']} position={[-4.167, 2.438, -0.273]} rotation={[Math.PI / 2, 0, 0]} scale={[0.008, 0.007, 0.01]} />
        <mesh name="Box042" geometry={nodes.Box042.geometry} material={materials['02 - Default']} position={[-4.545, 2.438, -0.273]} rotation={[Math.PI / 2, 0, 0]} scale={[0.008, 0.007, 0.01]} />
        <mesh name="Box013" geometry={nodes.Box013.geometry} material={materials['02 - Default']} position={[-4.167, 3.636, -0.273]} rotation={[Math.PI / 2, 0, 0]} scale={[0.008, 0.007, 0.01]} />
        <mesh name="Box014" geometry={nodes.Box014.geometry} material={materials['02 - Default']} position={[-4.544, 3.636, -0.273]} rotation={[Math.PI / 2, 0, 0]} scale={[0.008, 0.007, 0.01]} />
        <mesh name="Box051" geometry={nodes.Box051.geometry} material={materials['02 - Default']} position={[-4.167, 4.836, -0.273]} rotation={[Math.PI / 2, 0, 0]} scale={[0.008, 0.007, 0.01]} />
        <mesh name="Box052" geometry={nodes.Box052.geometry} material={materials['02 - Default']} position={[-4.544, 4.836, -0.273]} rotation={[Math.PI / 2, 0, 0]} scale={[0.008, 0.007, 0.01]} />
        <mesh name="Box054" geometry={nodes.Box054.geometry} material={materials['02 - Default']} position={[-4.167, 6.036, -0.273]} rotation={[Math.PI / 2, 0, 0]} scale={[0.008, 0.007, 0.01]} />
        <mesh name="Box055" geometry={nodes.Box055.geometry} material={materials['02 - Default']} position={[-4.545, 6.036, -0.273]} rotation={[Math.PI / 2, 0, 0]} scale={[0.008, 0.007, 0.01]} />
        <mesh name="Box027" geometry={nodes.Box027.geometry} material={materials['02 - Default']} position={[-1.235, 6.038, -0.273]} rotation={[Math.PI / 2, 0, 0]} scale={[0.008, 0.007, 0.01]} />
        <mesh name="Box025" geometry={nodes.Box025.geometry} material={materials['02 - Default']} position={[-1.235, 3.638, -0.273]} rotation={[Math.PI / 2, 0, 0]} scale={[0.008, 0.007, 0.01]} />
        <mesh name="Box026" geometry={nodes.Box026.geometry} material={materials['02 - Default']} position={[-1.235, 4.838, -0.273]} rotation={[Math.PI / 2, 0, 0]} scale={[0.008, 0.007, 0.01]} />
        <mesh name="Box064" geometry={nodes.Box064.geometry} material={materials['02 - Default']} position={[-2.735, 3.636, -0.291]} rotation={[Math.PI / 2, 0, 0]} scale={[0.008, 0.007, 0.01]} />
        <mesh name="Box065" geometry={nodes.Box065.geometry} material={materials['02 - Default']} position={[-2.735, 4.836, -0.291]} rotation={[Math.PI / 2, 0, 0]} scale={[0.008, 0.007, 0.01]} />
        <mesh name="Box066" geometry={nodes.Box066.geometry} material={materials['02 - Default']} position={[-2.735, 6.036, -0.291]} rotation={[Math.PI / 2, 0, 0]} scale={[0.008, 0.007, 0.01]} />
        <mesh name="Box067" geometry={nodes.Box067.geometry} material={materials['02 - Default']} position={[3.264, 2.441, -0.254]} rotation={[Math.PI / 2, 0, 0]} scale={[0.008, 0.007, 0.01]} />
        <mesh name="Box071" geometry={nodes.Box071.geometry} material={materials['02 - Default']} position={[3.264, 1.241, -0.254]} rotation={[Math.PI / 2, 0, 0]} scale={[0.008, 0.007, 0.01]} />
        <mesh name="Box072" geometry={nodes.Box072.geometry} material={materials['02 - Default']} position={[1.764, 2.441, -0.254]} rotation={[Math.PI / 2, 0, 0]} scale={[0.008, 0.007, 0.01]} />
        <mesh name="Box073" geometry={nodes.Box073.geometry} material={materials['02 - Default']} position={[1.764, 1.241, -0.254]} rotation={[Math.PI / 2, 0, 0]} scale={[0.008, 0.007, 0.01]} />
        <mesh name="Box070" geometry={nodes.Box070.geometry} material={materials['02 - Default']} position={[3.264, 6.041, -0.254]} rotation={[Math.PI / 2, 0, 0]} scale={[0.008, 0.007, 0.01]} />
        <mesh name="Box068" geometry={nodes.Box068.geometry} material={materials['02 - Default']} position={[3.264, 3.641, -0.254]} rotation={[Math.PI / 2, 0, 0]} scale={[0.008, 0.007, 0.01]} />
        <mesh name="Box069" geometry={nodes.Box069.geometry} material={materials['02 - Default']} position={[3.264, 4.841, -0.254]} rotation={[Math.PI / 2, 0, 0]} scale={[0.008, 0.007, 0.01]} />
        <mesh name="Box074" geometry={nodes.Box074.geometry} material={materials['02 - Default']} position={[1.765, 3.638, -0.273]} rotation={[Math.PI / 2, 0, 0]} scale={[0.008, 0.007, 0.01]} />
        <mesh name="Box075" geometry={nodes.Box075.geometry} material={materials['02 - Default']} position={[1.765, 4.838, -0.273]} rotation={[Math.PI / 2, 0, 0]} scale={[0.008, 0.007, 0.01]} />
        <mesh name="Box076" geometry={nodes.Box076.geometry} material={materials['02 - Default']} position={[1.765, 6.038, -0.273]} rotation={[Math.PI / 2, 0, 0]} scale={[0.008, 0.007, 0.01]} />
        <mesh name="Box088" geometry={nodes.Box088.geometry} material={materials['02 - Default']} position={[4.832, 2.441, -0.254]} rotation={[Math.PI / 2, 0, 0]} scale={[0.008, 0.007, 0.01]} />
        <mesh name="Box089" geometry={nodes.Box089.geometry} material={materials['02 - Default']} position={[4.455, 2.441, -0.254]} rotation={[Math.PI / 2, 0, 0]} scale={[0.008, 0.007, 0.01]} />
        <mesh name="Box085" geometry={nodes.Box085.geometry} material={materials['02 - Default']} position={[4.832, 3.64, -0.254]} rotation={[Math.PI / 2, 0, 0]} scale={[0.008, 0.007, 0.01]} />
        <mesh name="Box086" geometry={nodes.Box086.geometry} material={materials['02 - Default']} position={[4.455, 3.64, -0.254]} rotation={[Math.PI / 2, 0, 0]} scale={[0.008, 0.007, 0.01]} />
        <mesh name="Box098" geometry={nodes.Box098.geometry} material={materials['02 - Default']} position={[4.832, 4.84, -0.254]} rotation={[Math.PI / 2, 0, 0]} scale={[0.008, 0.007, 0.01]} />
        <mesh name="Box099" geometry={nodes.Box099.geometry} material={materials['02 - Default']} position={[4.455, 4.84, -0.254]} rotation={[Math.PI / 2, 0, 0]} scale={[0.008, 0.007, 0.01]} />
        <mesh name="Box101" geometry={nodes.Box101.geometry} material={materials['02 - Default']} position={[4.832, 6.039, -0.254]} rotation={[Math.PI / 2, 0, 0]} scale={[0.008, 0.007, 0.01]} />
        <mesh name="Box102" geometry={nodes.Box102.geometry} material={materials['02 - Default']} position={[4.455, 6.039, -0.254]} rotation={[Math.PI / 2, 0, 0]} scale={[0.008, 0.007, 0.01]} />
        <mesh name="Box111" geometry={nodes.Box111.geometry} material={materials['02 - Default']} position={[-4.882, 2.438, -2.238]} rotation={[Math.PI / 2, 0, Math.PI / 2]} scale={[0.008, 0.007, 0.01]} />
        <mesh name="Box112" geometry={nodes.Box112.geometry} material={materials['02 - Default']} position={[-4.882, 1.238, -2.238]} rotation={[Math.PI / 2, 0, Math.PI / 2]} scale={[0.008, 0.007, 0.01]} />
        <mesh name="Box113" geometry={nodes.Box113.geometry} material={materials['02 - Default']} position={[-4.863, 3.636, -2.237]} rotation={[Math.PI / 2, 0, Math.PI / 2]} scale={[0.008, 0.007, 0.01]} />
        <mesh name="Box114" geometry={nodes.Box114.geometry} material={materials['02 - Default']} position={[-4.863, 4.836, -2.237]} rotation={[Math.PI / 2, 0, Math.PI / 2]} scale={[0.008, 0.007, 0.01]} />
        <mesh name="Box115" geometry={nodes.Box115.geometry} material={materials['02 - Default']} position={[-4.863, 6.036, -2.237]} rotation={[Math.PI / 2, 0, Math.PI / 2]} scale={[0.008, 0.007, 0.01]} />
        <mesh name="Box116" geometry={nodes.Box116.geometry} material={materials['02 - Default']} position={[-4.882, 2.438, -3.738]} rotation={[Math.PI / 2, 0, Math.PI / 2]} scale={[0.008, 0.007, 0.01]} />
        <mesh name="Box117" geometry={nodes.Box117.geometry} material={materials['02 - Default']} position={[-4.882, 1.238, -3.738]} rotation={[Math.PI / 2, 0, Math.PI / 2]} scale={[0.008, 0.007, 0.01]} />
        <mesh name="Box118" geometry={nodes.Box118.geometry} material={materials['02 - Default']} position={[-4.863, 3.636, -3.737]} rotation={[Math.PI / 2, 0, Math.PI / 2]} scale={[0.008, 0.007, 0.01]} />
        <mesh name="Box119" geometry={nodes.Box119.geometry} material={materials['02 - Default']} position={[-4.863, 4.836, -3.737]} rotation={[Math.PI / 2, 0, Math.PI / 2]} scale={[0.008, 0.007, 0.01]} />
        <mesh name="Box120" geometry={nodes.Box120.geometry} material={materials['02 - Default']} position={[-4.863, 6.036, -3.737]} rotation={[Math.PI / 2, 0, Math.PI / 2]} scale={[0.008, 0.007, 0.01]} />
        <mesh name="Box121" geometry={nodes.Box121.geometry} material={materials['02 - Default']} position={[5.23, 2.441, -2.219]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={[-0.008, 0.007, 0.01]} />
        <mesh name="Box122" geometry={nodes.Box122.geometry} material={materials['02 - Default']} position={[5.23, 1.241, -2.219]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={[-0.008, 0.007, 0.01]} />
        <mesh name="Box123" geometry={nodes.Box123.geometry} material={materials['02 - Default']} position={[5.211, 3.638, -2.219]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={[-0.008, 0.007, 0.01]} />
        <mesh name="Box124" geometry={nodes.Box124.geometry} material={materials['02 - Default']} position={[5.211, 4.838, -2.219]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={[-0.008, 0.007, 0.01]} />
        <mesh name="Box125" geometry={nodes.Box125.geometry} material={materials['02 - Default']} position={[5.211, 6.038, -2.219]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={[-0.008, 0.007, 0.01]} />
        <mesh name="Box126" geometry={nodes.Box126.geometry} material={materials['02 - Default']} position={[5.23, 2.441, -3.719]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={[-0.008, 0.007, 0.01]} />
        <mesh name="Box127" geometry={nodes.Box127.geometry} material={materials['02 - Default']} position={[5.23, 1.241, -3.719]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={[-0.008, 0.007, 0.01]} />
        <mesh name="Box128" geometry={nodes.Box128.geometry} material={materials['02 - Default']} position={[5.211, 3.638, -3.719]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={[-0.008, 0.007, 0.01]} />
        <mesh name="Box129" geometry={nodes.Box129.geometry} material={materials['02 - Default']} position={[5.211, 4.838, -3.719]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={[-0.008, 0.007, 0.01]} />
        <mesh name="Box130" geometry={nodes.Box130.geometry} material={materials['02 - Default']} position={[5.211, 6.038, -3.719]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={[-0.008, 0.007, 0.01]} />
        <mesh name="Box142" geometry={nodes.Box142.geometry} material={materials['02 - Default']} position={[-1.266, 2.41, -5.885]} rotation={[Math.PI / 2, 0, Math.PI]} scale={[-0.008, 0.007, 0.01]} />
        <mesh name="Box146" geometry={nodes.Box146.geometry} material={materials['02 - Default']} position={[-1.266, 1.21, -5.885]} rotation={[Math.PI / 2, 0, Math.PI]} scale={[-0.008, 0.007, 0.01]} />
        <mesh name="Box147" geometry={nodes.Box147.geometry} material={materials['02 - Default']} position={[-2.766, 2.41, -5.885]} rotation={[Math.PI / 2, 0, Math.PI]} scale={[-0.008, 0.007, 0.01]} />
        <mesh name="Box148" geometry={nodes.Box148.geometry} material={materials['02 - Default']} position={[-2.766, 1.21, -5.885]} rotation={[Math.PI / 2, 0, Math.PI]} scale={[-0.008, 0.007, 0.01]} />
        <mesh name="Box149" geometry={nodes.Box149.geometry} material={materials['02 - Default']} position={[-4.197, 2.409, -5.885]} rotation={[Math.PI / 2, 0, Math.PI]} scale={[-0.008, 0.007, 0.01]} />
        <mesh name="Box150" geometry={nodes.Box150.geometry} material={materials['02 - Default']} position={[-4.575, 2.409, -5.885]} rotation={[Math.PI / 2, 0, Math.PI]} scale={[-0.008, 0.007, 0.01]} />
        <mesh name="Box139" geometry={nodes.Box139.geometry} material={materials['02 - Default']} position={[-4.197, 3.608, -5.885]} rotation={[Math.PI / 2, 0, Math.PI]} scale={[-0.008, 0.007, 0.01]} />
        <mesh name="Box140" geometry={nodes.Box140.geometry} material={materials['02 - Default']} position={[-4.575, 3.608, -5.885]} rotation={[Math.PI / 2, 0, Math.PI]} scale={[-0.008, 0.007, 0.01]} />
        <mesh name="Box159" geometry={nodes.Box159.geometry} material={materials['02 - Default']} position={[-4.197, 4.808, -5.885]} rotation={[Math.PI / 2, 0, Math.PI]} scale={[-0.008, 0.007, 0.01]} />
        <mesh name="Box160" geometry={nodes.Box160.geometry} material={materials['02 - Default']} position={[-4.575, 4.808, -5.885]} rotation={[Math.PI / 2, 0, Math.PI]} scale={[-0.008, 0.007, 0.01]} />
        <mesh name="Box162" geometry={nodes.Box162.geometry} material={materials['02 - Default']} position={[-4.197, 6.007, -5.885]} rotation={[Math.PI / 2, 0, Math.PI]} scale={[-0.008, 0.007, 0.01]} />
        <mesh name="Box163" geometry={nodes.Box163.geometry} material={materials['02 - Default']} position={[-4.575, 6.007, -5.885]} rotation={[Math.PI / 2, 0, Math.PI]} scale={[-0.008, 0.007, 0.01]} />
        <mesh name="Box145" geometry={nodes.Box145.geometry} material={materials['02 - Default']} position={[-1.266, 6.01, -5.885]} rotation={[Math.PI / 2, 0, Math.PI]} scale={[-0.008, 0.007, 0.01]} />
        <mesh name="Box143" geometry={nodes.Box143.geometry} material={materials['02 - Default']} position={[-1.266, 3.61, -5.885]} rotation={[Math.PI / 2, 0, Math.PI]} scale={[-0.008, 0.007, 0.01]} />
        <mesh name="Box144" geometry={nodes.Box144.geometry} material={materials['02 - Default']} position={[-1.266, 4.81, -5.885]} rotation={[Math.PI / 2, 0, Math.PI]} scale={[-0.008, 0.007, 0.01]} />
        <mesh name="Box172" geometry={nodes.Box172.geometry} material={materials['02 - Default']} position={[-2.765, 3.607, -5.866]} rotation={[Math.PI / 2, 0, Math.PI]} scale={[-0.008, 0.007, 0.01]} />
        <mesh name="Box173" geometry={nodes.Box173.geometry} material={materials['02 - Default']} position={[-2.765, 4.807, -5.866]} rotation={[Math.PI / 2, 0, Math.PI]} scale={[-0.008, 0.007, 0.01]} />
        <mesh name="Box174" geometry={nodes.Box174.geometry} material={materials['02 - Default']} position={[-2.765, 6.007, -5.866]} rotation={[Math.PI / 2, 0, Math.PI]} scale={[-0.008, 0.007, 0.01]} />
        <mesh name="Box185" geometry={nodes.Box185.geometry} material={materials['02 - Default']} position={[0.302, 2.409, -5.885]} rotation={[Math.PI / 2, 0, Math.PI]} scale={[-0.008, 0.007, 0.01]} />
        <mesh name="Box186" geometry={nodes.Box186.geometry} material={materials['02 - Default']} position={[-0.075, 2.409, -5.885]} rotation={[Math.PI / 2, 0, Math.PI]} scale={[-0.008, 0.007, 0.01]} />
        <mesh name="Box182" geometry={nodes.Box182.geometry} material={materials['02 - Default']} position={[0.302, 3.608, -5.885]} rotation={[Math.PI / 2, 0, Math.PI]} scale={[-0.008, 0.007, 0.01]} />
        <mesh name="Box183" geometry={nodes.Box183.geometry} material={materials['02 - Default']} position={[-0.075, 3.608, -5.885]} rotation={[Math.PI / 2, 0, Math.PI]} scale={[-0.008, 0.007, 0.01]} />
        <mesh name="Box195" geometry={nodes.Box195.geometry} material={materials['02 - Default']} position={[0.302, 4.808, -5.885]} rotation={[Math.PI / 2, 0, Math.PI]} scale={[-0.008, 0.007, 0.01]} />
        <mesh name="Box196" geometry={nodes.Box196.geometry} material={materials['02 - Default']} position={[-0.075, 4.808, -5.885]} rotation={[Math.PI / 2, 0, Math.PI]} scale={[-0.008, 0.007, 0.01]} />
        <mesh name="Box198" geometry={nodes.Box198.geometry} material={materials['02 - Default']} position={[0.302, 6.007, -5.885]} rotation={[Math.PI / 2, 0, Math.PI]} scale={[-0.008, 0.007, 0.01]} />
        <mesh name="Box199" geometry={nodes.Box199.geometry} material={materials['02 - Default']} position={[-0.075, 6.007, -5.885]} rotation={[Math.PI / 2, 0, Math.PI]} scale={[-0.008, 0.007, 0.01]} />
        <mesh name="Box214" geometry={nodes.Box214.geometry} material={materials['02 - Default']} position={[4.802, 2.412, -5.866]} rotation={[Math.PI / 2, 0, Math.PI]} scale={[-0.008, 0.007, 0.01]} />
        <mesh name="Box215" geometry={nodes.Box215.geometry} material={materials['02 - Default']} position={[4.425, 2.412, -5.866]} rotation={[Math.PI / 2, 0, Math.PI]} scale={[-0.008, 0.007, 0.01]} />
        <mesh name="Box211" geometry={nodes.Box211.geometry} material={materials['02 - Default']} position={[4.802, 3.61, -5.866]} rotation={[Math.PI / 2, 0, Math.PI]} scale={[-0.008, 0.007, 0.01]} />
        <mesh name="Box212" geometry={nodes.Box212.geometry} material={materials['02 - Default']} position={[4.425, 3.61, -5.866]} rotation={[Math.PI / 2, 0, Math.PI]} scale={[-0.008, 0.007, 0.01]} />
        <mesh name="Box224" geometry={nodes.Box224.geometry} material={materials['02 - Default']} position={[4.802, 4.81, -5.866]} rotation={[Math.PI / 2, 0, Math.PI]} scale={[-0.008, 0.007, 0.01]} />
        <mesh name="Box225" geometry={nodes.Box225.geometry} material={materials['02 - Default']} position={[4.425, 4.81, -5.866]} rotation={[Math.PI / 2, 0, Math.PI]} scale={[-0.008, 0.007, 0.01]} />
        <mesh name="Box227" geometry={nodes.Box227.geometry} material={materials['02 - Default']} position={[4.802, 6.01, -5.866]} rotation={[Math.PI / 2, 0, Math.PI]} scale={[-0.008, 0.007, 0.01]} />
        <mesh name="Box228" geometry={nodes.Box228.geometry} material={materials['02 - Default']} position={[4.425, 6.01, -5.866]} rotation={[Math.PI / 2, 0, Math.PI]} scale={[-0.008, 0.007, 0.01]} />
        <mesh name="Box237" geometry={nodes.Box237.geometry} material={materials['02 - Default']} position={[3.234, 2.409, -5.885]} rotation={[Math.PI / 2, 0, Math.PI]} scale={[-0.008, 0.007, 0.01]} />
        <mesh name="Box241" geometry={nodes.Box241.geometry} material={materials['02 - Default']} position={[3.234, 1.209, -5.885]} rotation={[Math.PI / 2, 0, Math.PI]} scale={[-0.008, 0.007, 0.01]} />
        <mesh name="Box242" geometry={nodes.Box242.geometry} material={materials['02 - Default']} position={[1.734, 2.409, -5.885]} rotation={[Math.PI / 2, 0, Math.PI]} scale={[-0.008, 0.007, 0.01]} />
        <mesh name="Box243" geometry={nodes.Box243.geometry} material={materials['02 - Default']} position={[1.734, 1.209, -5.885]} rotation={[Math.PI / 2, 0, Math.PI]} scale={[-0.008, 0.007, 0.01]} />
        <mesh name="Box240" geometry={nodes.Box240.geometry} material={materials['02 - Default']} position={[3.234, 6.009, -5.885]} rotation={[Math.PI / 2, 0, Math.PI]} scale={[-0.008, 0.007, 0.01]} />
        <mesh name="Box238" geometry={nodes.Box238.geometry} material={materials['02 - Default']} position={[3.234, 3.609, -5.885]} rotation={[Math.PI / 2, 0, Math.PI]} scale={[-0.008, 0.007, 0.01]} />
        <mesh name="Box239" geometry={nodes.Box239.geometry} material={materials['02 - Default']} position={[3.234, 4.809, -5.885]} rotation={[Math.PI / 2, 0, Math.PI]} scale={[-0.008, 0.007, 0.01]} />
        <mesh name="Box244" geometry={nodes.Box244.geometry} material={materials['02 - Default']} position={[1.734, 3.606, -5.866]} rotation={[Math.PI / 2, 0, Math.PI]} scale={[-0.008, 0.007, 0.01]} />
        <mesh name="Box245" geometry={nodes.Box245.geometry} material={materials['02 - Default']} position={[1.734, 4.806, -5.866]} rotation={[Math.PI / 2, 0, Math.PI]} scale={[-0.008, 0.007, 0.01]} />
        <mesh name="Box246" geometry={nodes.Box246.geometry} material={materials['02 - Default']} position={[1.734, 6.006, -5.866]} rotation={[Math.PI / 2, 0, Math.PI]} scale={[-0.008, 0.007, 0.01]} />
        <mesh name="Plane009" geometry={nodes.Plane009.geometry} material={materials['02 - Default']} position={[0.174, 6.046, -0.079]} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
        <mesh name="Plane010" geometry={nodes.Plane010.geometry} material={materials['02 - Default']} position={[0.173, 0.65, -0.076]} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
        <mesh name="Box017" geometry={nodes.Box017.geometry} material={materials['02 - Default']} position={[0.177, 1.139, 0.178]} scale={0.01} />
        <mesh name="Box018" geometry={nodes.Box018.geometry} material={materials['02 - Default']} position={[0.177, -0.014, 0.178]} scale={0.01} />
        <mesh name="Cylinder001" geometry={nodes.Cylinder001.geometry} material={materials['02 - Default']} position={[-0.486, 1.25, 0.312]} scale={0.01} />
        <mesh name="Cylinder002" geometry={nodes.Cylinder002.geometry} material={materials['02 - Default']} position={[0.815, 1.25, 0.312]} scale={0.01} />
        <mesh name="Box010" geometry={nodes.Box010.geometry} material={materials['02 - Default']} position={[-5.06, 0.929, -0.066]} scale={[0.01, 0.012, 0.01]} />
        <mesh name="Box009" geometry={nodes.Box009.geometry} material={materials['02 - Default']} position={[-4.081, 0.939, 0.41]} scale={[0.01, 0.012, 0.01]} />
        <mesh name="Box007" geometry={nodes.Box007.geometry} material={materials['02 - Default']} position={[-5.06, 0.939, 0.41]} scale={[0.01, 0.012, 0.01]} />
        <mesh name="Box008" geometry={nodes.Box008.geometry} material={materials['02 - Default']} position={[-4.582, 0.939, 0.41]} scale={[0.01, 0.012, 0.01]} />
        <mesh name="Box011" geometry={nodes.Box011.geometry} material={materials['02 - Default']} position={[-3.591, 0.939, -0.567]} scale={[0.01, 0.012, 0.01]} />
        <mesh name="Box012" geometry={nodes.Box012.geometry} material={materials['02 - Default']} position={[-3.591, 0.941, -0.092]} scale={[0.01, 0.012, 0.01]} />
        <mesh name="Box081" geometry={nodes.Box081.geometry} material={materials['02 - Default']} position={[3.939, 0.943, 0.429]} scale={[0.01, 0.012, 0.01]} />
        <mesh name="Box082" geometry={nodes.Box082.geometry} material={materials['02 - Default']} position={[4.417, 0.943, 0.429]} scale={[0.01, 0.012, 0.01]} />
        <mesh name="Box083" geometry={nodes.Box083.geometry} material={materials['02 - Default']} position={[4.919, 0.943, 0.429]} scale={[0.01, 0.012, 0.01]} />
        <mesh name="Box084" geometry={nodes.Box084.geometry} material={materials['02 - Default']} position={[3.939, 0.933, -0.047]} scale={[0.01, 0.012, 0.01]} />
        <mesh name="Box137" geometry={nodes.Box137.geometry} material={materials['02 - Default']} position={[-3.622, 0.91, -5.59]} rotation={[0, 0, Math.PI]} scale={[-0.01, -0.012, -0.01]} />
        <mesh name="Box138" geometry={nodes.Box138.geometry} material={materials['02 - Default']} position={[-3.622, 0.913, -6.066]} rotation={[0, 0, Math.PI]} scale={[-0.01, -0.012, -0.01]} />
        <mesh name="Box175" geometry={nodes.Box175.geometry} material={materials['02 - Default']} position={[-3.591, 0.939, 0.41]} scale={[0.01, 0.012, 0.01]} />
        <mesh name="Box176" geometry={nodes.Box176.geometry} material={materials['02 - Default']} position={[-3.591, 0.939, -0.066]} scale={[0.01, 0.012, 0.01]} />
        <mesh name="Box177" geometry={nodes.Box177.geometry} material={materials['02 - Default']} position={[5.408, 0.943, 0.429]} scale={[0.01, 0.012, 0.01]} />
        <mesh name="Box178" geometry={nodes.Box178.geometry} material={materials['02 - Default']} position={[5.408, 0.943, -0.047]} scale={[0.01, 0.012, 0.01]} />
        <mesh name="Box045" geometry={nodes.Box045.geometry} material={materials['02 - Default']} position={[-5.06, 2.139, 0.41]} scale={[0.01, 0.012, 0.01]} />
        <mesh name="Box046" geometry={nodes.Box046.geometry} material={materials['02 - Default']} position={[-4.582, 2.139, 0.41]} scale={[0.01, 0.012, 0.01]} />
        <mesh name="Box047" geometry={nodes.Box047.geometry} material={materials['02 - Default']} position={[-4.081, 2.139, 0.41]} scale={[0.01, 0.012, 0.01]} />
        <mesh name="Box048" geometry={nodes.Box048.geometry} material={materials['02 - Default']} position={[-5.06, 2.129, -0.066]} scale={[0.01, 0.012, 0.01]} />
        <mesh name="Box049" geometry={nodes.Box049.geometry} material={materials['02 - Default']} position={[-3.591, 2.139, -0.066]} scale={[0.01, 0.012, 0.01]} />
        <mesh name="Box050" geometry={nodes.Box050.geometry} material={materials['02 - Default']} position={[-3.591, 2.141, 0.41]} scale={[0.01, 0.012, 0.01]} />
        <mesh name="Box058" geometry={nodes.Box058.geometry} material={materials['02 - Default']} position={[-5.06, 5.737, 0.41]} scale={[0.01, 0.012, 0.01]} />
        <mesh name="Box059" geometry={nodes.Box059.geometry} material={materials['02 - Default']} position={[-4.582, 5.737, 0.41]} scale={[0.01, 0.012, 0.01]} />
        <mesh name="Box060" geometry={nodes.Box060.geometry} material={materials['02 - Default']} position={[-4.081, 5.737, 0.41]} scale={[0.01, 0.012, 0.01]} />
        <mesh name="Box061" geometry={nodes.Box061.geometry} material={materials['02 - Default']} position={[-5.06, 5.727, -0.066]} scale={[0.01, 0.012, 0.01]} />
        <mesh name="Box062" geometry={nodes.Box062.geometry} material={materials['02 - Default']} position={[-3.591, 5.737, -0.066]} scale={[0.01, 0.012, 0.01]} />
        <mesh name="Box063" geometry={nodes.Box063.geometry} material={materials['02 - Default']} position={[-3.591, 5.739, 0.41]} scale={[0.01, 0.012, 0.01]} />
        <mesh name="Box092" geometry={nodes.Box092.geometry} material={materials['02 - Default']} position={[3.939, 2.143, 0.429]} scale={[0.01, 0.012, 0.01]} />
        <mesh name="Box093" geometry={nodes.Box093.geometry} material={materials['02 - Default']} position={[4.417, 2.143, 0.429]} scale={[0.01, 0.012, 0.01]} />
        <mesh name="Box094" geometry={nodes.Box094.geometry} material={materials['02 - Default']} position={[4.919, 2.143, 0.429]} scale={[0.01, 0.012, 0.01]} />
        <mesh name="Box095" geometry={nodes.Box095.geometry} material={materials['02 - Default']} position={[3.939, 2.133, -0.047]} scale={[0.01, 0.012, 0.01]} />
        <mesh name="Box096" geometry={nodes.Box096.geometry} material={materials['02 - Default']} position={[5.408, 2.142, -0.047]} scale={[0.01, 0.012, 0.01]} />
        <mesh name="Box097" geometry={nodes.Box097.geometry} material={materials['02 - Default']} position={[5.408, 2.145, 0.429]} scale={[0.01, 0.012, 0.01]} />
        <mesh name="Box105" geometry={nodes.Box105.geometry} material={materials['02 - Default']} position={[3.939, 5.741, 0.429]} scale={[0.01, 0.012, 0.01]} />
        <mesh name="Box106" geometry={nodes.Box106.geometry} material={materials['02 - Default']} position={[4.417, 5.741, 0.429]} scale={[0.01, 0.012, 0.01]} />
        <mesh name="Box107" geometry={nodes.Box107.geometry} material={materials['02 - Default']} position={[4.919, 5.741, 0.429]} scale={[0.01, 0.012, 0.01]} />
        <mesh name="Box108" geometry={nodes.Box108.geometry} material={materials['02 - Default']} position={[3.939, 5.731, -0.047]} scale={[0.01, 0.012, 0.01]} />
        <mesh name="Box109" geometry={nodes.Box109.geometry} material={materials['02 - Default']} position={[5.408, 5.74, -0.047]} scale={[0.01, 0.012, 0.01]} />
        <mesh name="Box110" geometry={nodes.Box110.geometry} material={materials['02 - Default']} position={[5.408, 5.743, 0.429]} scale={[0.01, 0.012, 0.01]} />
        <mesh name="Box153" geometry={nodes.Box153.geometry} material={materials['02 - Default']} position={[-5.091, 2.11, -6.567]} rotation={[-Math.PI, 0, -Math.PI]} scale={[-0.01, 0.012, 0.01]} />
        <mesh name="Box154" geometry={nodes.Box154.geometry} material={materials['02 - Default']} position={[-4.613, 2.11, -6.567]} rotation={[-Math.PI, 0, -Math.PI]} scale={[-0.01, 0.012, 0.01]} />
        <mesh name="Box155" geometry={nodes.Box155.geometry} material={materials['02 - Default']} position={[-4.111, 2.11, -6.567]} rotation={[-Math.PI, 0, -Math.PI]} scale={[-0.01, 0.012, 0.01]} />
        <mesh name="Box156" geometry={nodes.Box156.geometry} material={materials['02 - Default']} position={[-5.091, 2.1, -6.092]} rotation={[-Math.PI, 0, -Math.PI]} scale={[-0.01, 0.012, 0.01]} />
        <mesh name="Box157" geometry={nodes.Box157.geometry} material={materials['02 - Default']} position={[-3.622, 2.11, -6.092]} rotation={[-Math.PI, 0, -Math.PI]} scale={[-0.01, 0.012, 0.01]} />
        <mesh name="Box158" geometry={nodes.Box158.geometry} material={materials['02 - Default']} position={[-3.622, 2.113, -6.567]} rotation={[-Math.PI, 0, -Math.PI]} scale={[-0.01, 0.012, 0.01]} />
        <mesh name="Box166" geometry={nodes.Box166.geometry} material={materials['02 - Default']} position={[-5.091, 5.708, -6.567]} rotation={[-Math.PI, 0, -Math.PI]} scale={[-0.01, 0.012, 0.01]} />
        <mesh name="Box167" geometry={nodes.Box167.geometry} material={materials['02 - Default']} position={[-4.613, 5.708, -6.567]} rotation={[-Math.PI, 0, -Math.PI]} scale={[-0.01, 0.012, 0.01]} />
        <mesh name="Box168" geometry={nodes.Box168.geometry} material={materials['02 - Default']} position={[-4.111, 5.708, -6.567]} rotation={[-Math.PI, 0, -Math.PI]} scale={[-0.01, 0.012, 0.01]} />
        <mesh name="Box169" geometry={nodes.Box169.geometry} material={materials['02 - Default']} position={[-5.091, 5.698, -6.092]} rotation={[-Math.PI, 0, -Math.PI]} scale={[-0.01, 0.012, 0.01]} />
        <mesh name="Box170" geometry={nodes.Box170.geometry} material={materials['02 - Default']} position={[-3.622, 5.708, -6.092]} rotation={[-Math.PI, 0, -Math.PI]} scale={[-0.01, 0.012, 0.01]} />
        <mesh name="Box171" geometry={nodes.Box171.geometry} material={materials['02 - Default']} position={[-3.622, 5.71, -6.567]} rotation={[-Math.PI, 0, -Math.PI]} scale={[-0.01, 0.012, 0.01]} />
        <mesh name="Box189" geometry={nodes.Box189.geometry} material={materials['02 - Default']} position={[-0.591, 2.11, -6.567]} rotation={[-Math.PI, 0, -Math.PI]} scale={[-0.01, 0.012, 0.01]} />
        <mesh name="Box190" geometry={nodes.Box190.geometry} material={materials['02 - Default']} position={[-0.113, 2.11, -6.567]} rotation={[-Math.PI, 0, -Math.PI]} scale={[-0.01, 0.012, 0.01]} />
        <mesh name="Box191" geometry={nodes.Box191.geometry} material={materials['02 - Default']} position={[0.388, 2.11, -6.567]} rotation={[-Math.PI, 0, -Math.PI]} scale={[-0.01, 0.012, 0.01]} />
        <mesh name="Box192" geometry={nodes.Box192.geometry} material={materials['02 - Default']} position={[-0.591, 2.1, -6.092]} rotation={[-Math.PI, 0, -Math.PI]} scale={[-0.01, 0.012, 0.01]} />
        <mesh name="Box193" geometry={nodes.Box193.geometry} material={materials['02 - Default']} position={[0.878, 2.11, -6.092]} rotation={[-Math.PI, 0, -Math.PI]} scale={[-0.01, 0.012, 0.01]} />
        <mesh name="Box194" geometry={nodes.Box194.geometry} material={materials['02 - Default']} position={[0.878, 2.113, -6.567]} rotation={[-Math.PI, 0, -Math.PI]} scale={[-0.01, 0.012, 0.01]} />
        <mesh name="Box202" geometry={nodes.Box202.geometry} material={materials['02 - Default']} position={[-0.591, 5.708, -6.567]} rotation={[-Math.PI, 0, -Math.PI]} scale={[-0.01, 0.012, 0.01]} />
        <mesh name="Box203" geometry={nodes.Box203.geometry} material={materials['02 - Default']} position={[-0.113, 5.708, -6.567]} rotation={[-Math.PI, 0, -Math.PI]} scale={[-0.01, 0.012, 0.01]} />
        <mesh name="Box204" geometry={nodes.Box204.geometry} material={materials['02 - Default']} position={[0.388, 5.708, -6.567]} rotation={[-Math.PI, 0, -Math.PI]} scale={[-0.01, 0.012, 0.01]} />
        <mesh name="Box205" geometry={nodes.Box205.geometry} material={materials['02 - Default']} position={[-0.591, 5.698, -6.092]} rotation={[-Math.PI, 0, -Math.PI]} scale={[-0.01, 0.012, 0.01]} />
        <mesh name="Box206" geometry={nodes.Box206.geometry} material={materials['02 - Default']} position={[0.878, 5.708, -6.092]} rotation={[-Math.PI, 0, -Math.PI]} scale={[-0.01, 0.012, 0.01]} />
        <mesh name="Box207" geometry={nodes.Box207.geometry} material={materials['02 - Default']} position={[0.878, 5.71, -6.567]} rotation={[-Math.PI, 0, -Math.PI]} scale={[-0.01, 0.012, 0.01]} />
        <mesh name="Box218" geometry={nodes.Box218.geometry} material={materials['02 - Default']} position={[3.909, 2.113, -6.548]} rotation={[-Math.PI, 0, -Math.PI]} scale={[-0.01, 0.012, 0.01]} />
        <mesh name="Box219" geometry={nodes.Box219.geometry} material={materials['02 - Default']} position={[4.387, 2.113, -6.548]} rotation={[-Math.PI, 0, -Math.PI]} scale={[-0.01, 0.012, 0.01]} />
        <mesh name="Box220" geometry={nodes.Box220.geometry} material={materials['02 - Default']} position={[4.889, 2.113, -6.548]} rotation={[-Math.PI, 0, -Math.PI]} scale={[-0.01, 0.012, 0.01]} />
        <mesh name="Box221" geometry={nodes.Box221.geometry} material={materials['02 - Default']} position={[3.909, 2.103, -6.073]} rotation={[-Math.PI, 0, -Math.PI]} scale={[-0.01, 0.012, 0.01]} />
        <mesh name="Box222" geometry={nodes.Box222.geometry} material={materials['02 - Default']} position={[5.378, 2.113, -6.073]} rotation={[-Math.PI, 0, -Math.PI]} scale={[-0.01, 0.012, 0.01]} />
        <mesh name="Box223" geometry={nodes.Box223.geometry} material={materials['02 - Default']} position={[5.378, 2.115, -6.548]} rotation={[-Math.PI, 0, -Math.PI]} scale={[-0.01, 0.012, 0.01]} />
        <mesh name="Box231" geometry={nodes.Box231.geometry} material={materials['02 - Default']} position={[3.909, 5.711, -6.548]} rotation={[-Math.PI, 0, -Math.PI]} scale={[-0.01, 0.012, 0.01]} />
        <mesh name="Box232" geometry={nodes.Box232.geometry} material={materials['02 - Default']} position={[4.387, 5.711, -6.548]} rotation={[-Math.PI, 0, -Math.PI]} scale={[-0.01, 0.012, 0.01]} />
        <mesh name="Box233" geometry={nodes.Box233.geometry} material={materials['02 - Default']} position={[4.889, 5.711, -6.548]} rotation={[-Math.PI, 0, -Math.PI]} scale={[-0.01, 0.012, 0.01]} />
        <mesh name="Box234" geometry={nodes.Box234.geometry} material={materials['02 - Default']} position={[3.909, 5.701, -6.073]} rotation={[-Math.PI, 0, -Math.PI]} scale={[-0.01, 0.012, 0.01]} />
        <mesh name="Box235" geometry={nodes.Box235.geometry} material={materials['02 - Default']} position={[5.378, 5.711, -6.073]} rotation={[-Math.PI, 0, -Math.PI]} scale={[-0.01, 0.012, 0.01]} />
        <mesh name="Box236" geometry={nodes.Box236.geometry} material={materials['02 - Default']} position={[5.378, 5.713, -6.548]} rotation={[-Math.PI, 0, -Math.PI]} scale={[-0.01, 0.012, 0.01]} />
        <mesh name="Plane005" geometry={nodes.Plane005.geometry} material={materials['02 - Default']} position={[-5.048, 1.388, 0.159]} rotation={[Math.PI / 2, 0, Math.PI / 2]} scale={0.01} />
        <mesh name="Plane006" geometry={nodes.Plane006.geometry} material={materials['02 - Default']} position={[-3.604, 1.388, -0.342]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={0.01} />
        <mesh name="Plane072" geometry={nodes.Plane072.geometry} material={materials['02 - Default']} position={[3.951, 1.392, 0.178]} rotation={[Math.PI / 2, 0, Math.PI / 2]} scale={0.01} />
        <mesh name="Plane115" geometry={nodes.Plane115.geometry} material={materials['02 - Default']} position={[-3.635, 1.36, -5.815]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={-0.01} />
        <mesh name="Plane138" geometry={nodes.Plane138.geometry} material={materials['02 - Default']} position={[-3.603, 1.388, 0.159]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={0.01} />
        <mesh name="Plane139" geometry={nodes.Plane139.geometry} material={materials['02 - Default']} position={[5.399, 1.392, 0.178]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={0.01} />
        <mesh name="Plane031" geometry={nodes.Plane031.geometry} material={materials['02 - Default']} position={[-5.048, 2.588, 0.159]} rotation={[Math.PI / 2, 0, Math.PI / 2]} scale={0.01} />
        <mesh name="Plane032" geometry={nodes.Plane032.geometry} material={materials['02 - Default']} position={[-3.604, 2.588, 0.159]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={0.01} />
        <mesh name="Plane037" geometry={nodes.Plane037.geometry} material={materials['02 - Default']} position={[-5.048, 6.186, 0.159]} rotation={[Math.PI / 2, 0, Math.PI / 2]} scale={0.01} />
        <mesh name="Plane038" geometry={nodes.Plane038.geometry} material={materials['02 - Default']} position={[-3.604, 6.186, 0.159]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={0.01} />
        <mesh name="Plane077" geometry={nodes.Plane077.geometry} material={materials['02 - Default']} position={[3.951, 2.592, 0.178]} rotation={[Math.PI / 2, 0, Math.PI / 2]} scale={0.01} />
        <mesh name="Plane078" geometry={nodes.Plane078.geometry} material={materials['02 - Default']} position={[5.395, 2.592, 0.178]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={0.01} />
        <mesh name="Plane083" geometry={nodes.Plane083.geometry} material={materials['02 - Default']} position={[3.951, 6.19, 0.178]} rotation={[Math.PI / 2, 0, Math.PI / 2]} scale={0.01} />
        <mesh name="Plane084" geometry={nodes.Plane084.geometry} material={materials['02 - Default']} position={[5.395, 6.19, 0.178]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={0.01} />
        <mesh name="Plane127" geometry={nodes.Plane127.geometry} material={materials['02 - Default']} position={[-5.078, 2.56, -6.316]} rotation={[Math.PI / 2, 0, Math.PI / 2]} scale={[-0.01, 0.01, 0.01]} />
        <mesh name="Plane128" geometry={nodes.Plane128.geometry} material={materials['02 - Default']} position={[-3.635, 2.56, -6.316]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={[-0.01, 0.01, 0.01]} />
        <mesh name="Plane133" geometry={nodes.Plane133.geometry} material={materials['02 - Default']} position={[-5.078, 6.158, -6.316]} rotation={[Math.PI / 2, 0, Math.PI / 2]} scale={[-0.01, 0.01, 0.01]} />
        <mesh name="Plane134" geometry={nodes.Plane134.geometry} material={materials['02 - Default']} position={[-3.635, 6.158, -6.316]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={[-0.01, 0.01, 0.01]} />
        <mesh name="Plane145" geometry={nodes.Plane145.geometry} material={materials['02 - Default']} position={[-0.579, 2.56, -6.316]} rotation={[Math.PI / 2, 0, Math.PI / 2]} scale={[-0.01, 0.01, 0.01]} />
        <mesh name="Plane146" geometry={nodes.Plane146.geometry} material={materials['02 - Default']} position={[0.865, 2.56, -6.316]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={[-0.01, 0.01, 0.01]} />
        <mesh name="Plane151" geometry={nodes.Plane151.geometry} material={materials['02 - Default']} position={[-0.579, 6.158, -6.316]} rotation={[Math.PI / 2, 0, Math.PI / 2]} scale={[-0.01, 0.01, 0.01]} />
        <mesh name="Plane152" geometry={nodes.Plane152.geometry} material={materials['02 - Default']} position={[0.865, 6.158, -6.316]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={[-0.01, 0.01, 0.01]} />
        <mesh name="Plane158" geometry={nodes.Plane158.geometry} material={materials['02 - Default']} position={[3.921, 2.563, -6.298]} rotation={[Math.PI / 2, 0, Math.PI / 2]} scale={[-0.01, 0.01, 0.01]} />
        <mesh name="Plane159" geometry={nodes.Plane159.geometry} material={materials['02 - Default']} position={[5.365, 2.563, -6.298]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={[-0.01, 0.01, 0.01]} />
        <mesh name="Plane164" geometry={nodes.Plane164.geometry} material={materials['02 - Default']} position={[3.921, 6.161, -6.298]} rotation={[Math.PI / 2, 0, Math.PI / 2]} scale={[-0.01, 0.01, 0.01]} />
        <mesh name="Plane165" geometry={nodes.Plane165.geometry} material={materials['02 - Default']} position={[5.365, 6.161, -6.298]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={[-0.01, 0.01, 0.01]} />
        <mesh name="Plane004" geometry={nodes.Plane004.geometry} material={materials['02 - Default']} position={[-4.326, 1.245, 0.404]} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
        <mesh name="Plane071" geometry={nodes.Plane071.geometry} material={materials['02 - Default']} position={[4.673, 1.249, 0.423]} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
        <mesh name="Plane030" geometry={nodes.Plane030.geometry} material={materials['02 - Default']} position={[-4.326, 2.445, 0.404]} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
        <mesh name="Plane036" geometry={nodes.Plane036.geometry} material={materials['02 - Default']} position={[-4.326, 6.043, 0.404]} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
        <mesh name="Plane076" geometry={nodes.Plane076.geometry} material={materials['02 - Default']} position={[4.673, 2.449, 0.423]} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
        <mesh name="Plane082" geometry={nodes.Plane082.geometry} material={materials['02 - Default']} position={[4.673, 6.047, 0.423]} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
        <mesh name="Plane126" geometry={nodes.Plane126.geometry} material={materials['02 - Default']} position={[-4.356, 2.417, -6.561]} rotation={[Math.PI / 2, 0, Math.PI]} scale={[-0.01, 0.01, 0.01]} />
        <mesh name="Plane132" geometry={nodes.Plane132.geometry} material={materials['02 - Default']} position={[-4.356, 6.015, -6.561]} rotation={[Math.PI / 2, 0, Math.PI]} scale={[-0.01, 0.01, 0.01]} />
        <mesh name="Plane144" geometry={nodes.Plane144.geometry} material={materials['02 - Default']} position={[0.143, 2.417, -6.561]} rotation={[Math.PI / 2, 0, Math.PI]} scale={[-0.01, 0.01, 0.01]} />
        <mesh name="Plane150" geometry={nodes.Plane150.geometry} material={materials['02 - Default']} position={[0.143, 6.015, -6.561]} rotation={[Math.PI / 2, 0, Math.PI]} scale={[-0.01, 0.01, 0.01]} />
        <mesh name="Plane157" geometry={nodes.Plane157.geometry} material={materials['02 - Default']} position={[4.643, 2.42, -6.543]} rotation={[Math.PI / 2, 0, Math.PI]} scale={[-0.01, 0.01, 0.01]} />
        <mesh name="Plane163" geometry={nodes.Plane163.geometry} material={materials['02 - Default']} position={[4.643, 6.017, -6.543]} rotation={[Math.PI / 2, 0, Math.PI]} scale={[-0.01, 0.01, 0.01]} />
        <mesh name="Box004" geometry={nodes.Box004.geometry} material={materials['02 - Default']} position={[-4.331, 1.802, 0.172]} scale={0.01} />
        <mesh name="Box079" geometry={nodes.Box079.geometry} material={materials['02 - Default']} position={[4.668, 1.806, 0.191]} scale={0.01} />
        <mesh name="Box133" geometry={nodes.Box133.geometry} material={materials['02 - Default']} position={[-4.361, 1.774, -6.329]} rotation={[0, 0, Math.PI]} scale={-0.01} />
        <mesh name="Box043" geometry={nodes.Box043.geometry} material={materials['02 - Default']} position={[-4.331, 3.002, 0.172]} scale={0.01} />
        <mesh name="Box056" geometry={nodes.Box056.geometry} material={materials['02 - Default']} position={[-4.331, 6.6, 0.172]} scale={0.01} />
        <mesh name="Box090" geometry={nodes.Box090.geometry} material={materials['02 - Default']} position={[4.668, 3.006, 0.191]} scale={0.01} />
        <mesh name="Box103" geometry={nodes.Box103.geometry} material={materials['02 - Default']} position={[4.668, 6.604, 0.191]} scale={0.01} />
        <mesh name="Box151" geometry={nodes.Box151.geometry} material={materials['02 - Default']} position={[-4.361, 2.974, -6.329]} rotation={[-Math.PI, 0, -Math.PI]} scale={[-0.01, 0.01, 0.01]} />
        <mesh name="Box164" geometry={nodes.Box164.geometry} material={materials['02 - Default']} position={[-4.361, 6.572, -6.329]} rotation={[-Math.PI, 0, -Math.PI]} scale={[-0.01, 0.01, 0.01]} />
        <mesh name="Box187" geometry={nodes.Box187.geometry} material={materials['02 - Default']} position={[0.138, 2.974, -6.329]} rotation={[-Math.PI, 0, -Math.PI]} scale={[-0.01, 0.01, 0.01]} />
        <mesh name="Box200" geometry={nodes.Box200.geometry} material={materials['02 - Default']} position={[0.138, 6.572, -6.329]} rotation={[-Math.PI, 0, -Math.PI]} scale={[-0.01, 0.01, 0.01]} />
        <mesh name="Box216" geometry={nodes.Box216.geometry} material={materials['02 - Default']} position={[4.638, 2.977, -6.311]} rotation={[-Math.PI, 0, -Math.PI]} scale={[-0.01, 0.01, 0.01]} />
        <mesh name="Box229" geometry={nodes.Box229.geometry} material={materials['02 - Default']} position={[4.638, 6.574, -6.311]} rotation={[-Math.PI, 0, -Math.PI]} scale={[-0.01, 0.01, 0.01]} />
        <mesh name="Plane003" geometry={nodes.Plane003.geometry} material={materials['02 - Default']} position={[-4.326, 1.246, -0.079]} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
        <mesh name="Plane070" geometry={nodes.Plane070.geometry} material={materials['02 - Default']} position={[4.673, 1.249, -0.06]} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
        <mesh name="Plane113" geometry={nodes.Plane113.geometry} material={materials['02 - Default']} position={[-4.356, 1.217, -6.079]} rotation={[-Math.PI / 2, 0, Math.PI]} scale={-0.01} />
        <mesh name="Plane140" geometry={nodes.Plane140.geometry} material={materials['02 - Default']} position={[0.143, 1.217, -6.079]} rotation={[-Math.PI / 2, 0, Math.PI]} scale={-0.01} />
        <mesh name="Plane153" geometry={nodes.Plane153.geometry} material={materials['02 - Default']} position={[4.643, 1.22, -6.06]} rotation={[-Math.PI / 2, 0, Math.PI]} scale={-0.01} />
        <mesh name="Plane029" geometry={nodes.Plane029.geometry} material={materials['02 - Default']} position={[-4.326, 2.446, -0.079]} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
        <mesh name="Plane007" geometry={nodes.Plane007.geometry} material={materials['02 - Default']} position={[-4.326, 3.644, -0.079]} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
        <mesh name="Plane033" geometry={nodes.Plane033.geometry} material={materials['02 - Default']} position={[-4.326, 4.844, -0.079]} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
        <mesh name="Plane035" geometry={nodes.Plane035.geometry} material={materials['02 - Default']} position={[-4.326, 6.044, -0.079]} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
        <mesh name="Plane075" geometry={nodes.Plane075.geometry} material={materials['02 - Default']} position={[4.673, 2.449, -0.06]} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
        <mesh name="Plane073" geometry={nodes.Plane073.geometry} material={materials['02 - Default']} position={[4.674, 3.648, -0.06]} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
        <mesh name="Plane079" geometry={nodes.Plane079.geometry} material={materials['02 - Default']} position={[4.674, 4.848, -0.06]} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
        <mesh name="Plane081" geometry={nodes.Plane081.geometry} material={materials['02 - Default']} position={[4.673, 6.047, -0.06]} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
        <mesh name="Plane125" geometry={nodes.Plane125.geometry} material={materials['02 - Default']} position={[-4.356, 2.417, -6.079]} rotation={[Math.PI / 2, 0, Math.PI]} scale={[-0.01, 0.01, 0.01]} />
        <mesh name="Plane116" geometry={nodes.Plane116.geometry} material={materials['02 - Default']} position={[-4.356, 3.616, -6.079]} rotation={[Math.PI / 2, 0, Math.PI]} scale={[-0.01, 0.01, 0.01]} />
        <mesh name="Plane129" geometry={nodes.Plane129.geometry} material={materials['02 - Default']} position={[-4.356, 4.816, -6.079]} rotation={[Math.PI / 2, 0, Math.PI]} scale={[-0.01, 0.01, 0.01]} />
        <mesh name="Plane131" geometry={nodes.Plane131.geometry} material={materials['02 - Default']} position={[-4.356, 6.015, -6.079]} rotation={[Math.PI / 2, 0, Math.PI]} scale={[-0.01, 0.01, 0.01]} />
        <mesh name="Plane143" geometry={nodes.Plane143.geometry} material={materials['02 - Default']} position={[0.143, 2.417, -6.079]} rotation={[Math.PI / 2, 0, Math.PI]} scale={[-0.01, 0.01, 0.01]} />
        <mesh name="Plane141" geometry={nodes.Plane141.geometry} material={materials['02 - Default']} position={[0.143, 3.616, -6.079]} rotation={[Math.PI / 2, 0, Math.PI]} scale={[-0.01, 0.01, 0.01]} />
        <mesh name="Plane147" geometry={nodes.Plane147.geometry} material={materials['02 - Default']} position={[0.143, 4.816, -6.079]} rotation={[Math.PI / 2, 0, Math.PI]} scale={[-0.01, 0.01, 0.01]} />
        <mesh name="Plane149" geometry={nodes.Plane149.geometry} material={materials['02 - Default']} position={[0.143, 6.015, -6.079]} rotation={[Math.PI / 2, 0, Math.PI]} scale={[-0.01, 0.01, 0.01]} />
        <mesh name="Plane156" geometry={nodes.Plane156.geometry} material={materials['02 - Default']} position={[4.643, 2.42, -6.06]} rotation={[Math.PI / 2, 0, Math.PI]} scale={[-0.01, 0.01, 0.01]} />
        <mesh name="Plane154" geometry={nodes.Plane154.geometry} material={materials['02 - Default']} position={[4.644, 3.619, -6.06]} rotation={[Math.PI / 2, 0, Math.PI]} scale={[-0.01, 0.01, 0.01]} />
        <mesh name="Plane160" geometry={nodes.Plane160.geometry} material={materials['02 - Default']} position={[4.644, 4.819, -6.06]} rotation={[Math.PI / 2, 0, Math.PI]} scale={[-0.01, 0.01, 0.01]} />
        <mesh name="Plane162" geometry={nodes.Plane162.geometry} material={materials['02 - Default']} position={[4.643, 6.018, -6.06]} rotation={[Math.PI / 2, 0, Math.PI]} scale={[-0.01, 0.01, 0.01]} />
        <mesh name="Box005" geometry={nodes.Box005.geometry} material={materials['02 - Default']} position={[-4.331, 0.646, 0.172]} scale={0.01} />
        <mesh name="Box080" geometry={nodes.Box080.geometry} material={materials['02 - Default']} position={[4.668, 0.65, 0.191]} scale={0.01} />
        <mesh name="Box134" geometry={nodes.Box134.geometry} material={materials['02 - Default']} position={[-4.361, 0.618, -6.329]} rotation={[0, 0, Math.PI]} scale={-0.01} />
        <mesh name="Box181" geometry={nodes.Box181.geometry} material={materials['02 - Default']} position={[0.138, 0.618, -6.329]} rotation={[0, 0, Math.PI]} scale={-0.01} />
        <mesh name="Box210" geometry={nodes.Box210.geometry} material={materials['02 - Default']} position={[4.638, 0.621, -6.311]} rotation={[0, 0, Math.PI]} scale={-0.01} />
        <mesh name="Box044" geometry={nodes.Box044.geometry} material={materials['02 - Default']} position={[-4.331, 1.846, 0.172]} scale={0.01} />
        <mesh name="Box016" geometry={nodes.Box016.geometry} material={materials['02 - Default']} position={[-4.331, 3.045, 0.172]} scale={0.01} />
        <mesh name="Box053" geometry={nodes.Box053.geometry} material={materials['02 - Default']} position={[-4.331, 4.245, 0.172]} scale={0.01} />
        <mesh name="Box057" geometry={nodes.Box057.geometry} material={materials['02 - Default']} position={[-4.331, 5.444, 0.172]} scale={0.01} />
        <mesh name="Box091" geometry={nodes.Box091.geometry} material={materials['02 - Default']} position={[4.668, 1.85, 0.191]} scale={0.01} />
        <mesh name="Box087" geometry={nodes.Box087.geometry} material={materials['02 - Default']} position={[4.668, 3.049, 0.191]} scale={0.01} />
        <mesh name="Box100" geometry={nodes.Box100.geometry} material={materials['02 - Default']} position={[4.668, 4.249, 0.191]} scale={0.01} />
        <mesh name="Box104" geometry={nodes.Box104.geometry} material={materials['02 - Default']} position={[4.668, 5.448, 0.191]} scale={0.01} />
        <mesh name="Box152" geometry={nodes.Box152.geometry} material={materials['02 - Default']} position={[-4.361, 1.818, -6.329]} rotation={[-Math.PI, 0, -Math.PI]} scale={[-0.01, 0.01, 0.01]} />
        <mesh name="Box141" geometry={nodes.Box141.geometry} material={materials['02 - Default']} position={[-4.361, 3.016, -6.329]} rotation={[-Math.PI, 0, -Math.PI]} scale={[-0.01, 0.01, 0.01]} />
        <mesh name="Box161" geometry={nodes.Box161.geometry} material={materials['02 - Default']} position={[-4.361, 4.216, -6.329]} rotation={[-Math.PI, 0, -Math.PI]} scale={[-0.01, 0.01, 0.01]} />
        <mesh name="Box165" geometry={nodes.Box165.geometry} material={materials['02 - Default']} position={[-4.361, 5.416, -6.329]} rotation={[-Math.PI, 0, -Math.PI]} scale={[-0.01, 0.01, 0.01]} />
        <mesh name="Box188" geometry={nodes.Box188.geometry} material={materials['02 - Default']} position={[0.138, 1.818, -6.329]} rotation={[-Math.PI, 0, -Math.PI]} scale={[-0.01, 0.01, 0.01]} />
        <mesh name="Box184" geometry={nodes.Box184.geometry} material={materials['02 - Default']} position={[0.138, 3.016, -6.329]} rotation={[-Math.PI, 0, -Math.PI]} scale={[-0.01, 0.01, 0.01]} />
        <mesh name="Box197" geometry={nodes.Box197.geometry} material={materials['02 - Default']} position={[0.138, 4.216, -6.329]} rotation={[-Math.PI, 0, -Math.PI]} scale={[-0.01, 0.01, 0.01]} />
        <mesh name="Box201" geometry={nodes.Box201.geometry} material={materials['02 - Default']} position={[0.138, 5.416, -6.329]} rotation={[-Math.PI, 0, -Math.PI]} scale={[-0.01, 0.01, 0.01]} />
        <mesh name="Box217" geometry={nodes.Box217.geometry} material={materials['02 - Default']} position={[4.638, 1.821, -6.311]} rotation={[-Math.PI, 0, -Math.PI]} scale={[-0.01, 0.01, 0.01]} />
        <mesh name="Box213" geometry={nodes.Box213.geometry} material={materials['02 - Default']} position={[4.638, 3.019, -6.311]} rotation={[-Math.PI, 0, -Math.PI]} scale={[-0.01, 0.01, 0.01]} />
        <mesh name="Box226" geometry={nodes.Box226.geometry} material={materials['02 - Default']} position={[4.638, 4.219, -6.311]} rotation={[-Math.PI, 0, -Math.PI]} scale={[-0.01, 0.01, 0.01]} />
        <mesh name="Box230" geometry={nodes.Box230.geometry} material={materials['02 - Default']} position={[4.638, 5.419, -6.311]} rotation={[-Math.PI, 0, -Math.PI]} scale={[-0.01, 0.01, 0.01]} />
        <mesh name="Plane068" geometry={nodes.Plane068.geometry} material={materials['02 - Default']} position={[-5.076, 2.446, -0.829]} rotation={[Math.PI / 2, 0, Math.PI / 2]} scale={0.01} />
        <mesh name="Plane069" geometry={nodes.Plane069.geometry} material={materials['02 - Default']} position={[-5.076, 1.246, -0.829]} rotation={[Math.PI / 2, 0, Math.PI / 2]} scale={0.01} />
        <mesh name="Plane085" geometry={nodes.Plane085.geometry} material={materials['02 - Default']} position={[-5.076, 3.646, -0.829]} rotation={[Math.PI / 2, 0, Math.PI / 2]} scale={0.01} />
        <mesh name="Plane086" geometry={nodes.Plane086.geometry} material={materials['02 - Default']} position={[-5.076, 4.846, -0.829]} rotation={[Math.PI / 2, 0, Math.PI / 2]} scale={0.01} />
        <mesh name="Plane087" geometry={nodes.Plane087.geometry} material={materials['02 - Default']} position={[-5.076, 6.046, -0.829]} rotation={[Math.PI / 2, 0, Math.PI / 2]} scale={0.01} />
        <mesh name="Plane098" geometry={nodes.Plane098.geometry} material={materials['02 - Default']} position={[5.423, 2.449, -0.81]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={-0.01} />
        <mesh name="Plane099" geometry={nodes.Plane099.geometry} material={materials['02 - Default']} position={[5.423, 1.249, -0.81]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={-0.01} />
        <mesh name="Plane100" geometry={nodes.Plane100.geometry} material={materials['02 - Default']} position={[5.423, 3.649, -0.81]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={-0.01} />
        <mesh name="Plane101" geometry={nodes.Plane101.geometry} material={materials['02 - Default']} position={[5.423, 4.849, -0.81]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={-0.01} />
        <mesh name="Plane102" geometry={nodes.Plane102.geometry} material={materials['02 - Default']} position={[5.423, 6.049, -0.81]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={-0.01} />
        <mesh name="Plane177" geometry={nodes.Plane177.geometry} material={materials['02 - Default']} position={[5.424, 2.449, -5.31]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={-0.01} />
        <mesh name="Plane178" geometry={nodes.Plane178.geometry} material={materials['02 - Default']} position={[5.424, 1.249, -5.31]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={-0.01} />
        <mesh name="Plane179" geometry={nodes.Plane179.geometry} material={materials['02 - Default']} position={[5.424, 3.649, -5.31]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={-0.01} />
        <mesh name="Plane180" geometry={nodes.Plane180.geometry} material={materials['02 - Default']} position={[5.424, 4.849, -5.31]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={-0.01} />
        <mesh name="Plane181" geometry={nodes.Plane181.geometry} material={materials['02 - Default']} position={[5.424, 6.049, -5.31]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={-0.01} />
        <mesh name="Plane182" geometry={nodes.Plane182.geometry} material={materials['02 - Default']} position={[-5.076, 2.446, -5.329]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={-0.01} />
        <mesh name="Plane183" geometry={nodes.Plane183.geometry} material={materials['02 - Default']} position={[-5.076, 1.246, -5.329]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={-0.01} />
        <mesh name="Plane184" geometry={nodes.Plane184.geometry} material={materials['02 - Default']} position={[-5.076, 3.646, -5.329]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={-0.01} />
        <mesh name="Plane185" geometry={nodes.Plane185.geometry} material={materials['02 - Default']} position={[-5.076, 4.846, -5.329]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={-0.01} />
        <mesh name="Plane186" geometry={nodes.Plane186.geometry} material={materials['02 - Default']} position={[-5.076, 6.046, -5.329]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={-0.01} />
        <mesh name="Plane176" geometry={nodes.Plane176.geometry} material={materials['02 - Default']} position={[-2.826, 0.346, -0.079]} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
        <mesh name="Box247" geometry={nodes.Box247.geometry} material={materials['02 - Default']} position={[0.143, 6.643, -3.087]} scale={[0.01, 0.003, 0.01]} />
        <mesh name="Box248" geometry={nodes.Box248.geometry} material={materials['02 - Default']} position={[0.72, 7.276, -1.015]} rotation={[Math.PI / 2, 0, Math.PI / 2]} scale={[0.029, 0.032, 0.01]} />
        <mesh name="Box249" geometry={nodes.Box249.geometry} material={materials['02 - Default']} position={[0.72, 7.276, -5.178]} rotation={[Math.PI / 2, 0, Math.PI / 2]} scale={[0.029, 0.032, 0.01]} />
      </group>
    </group>
  )
}

useGLTF.preload('./building/apartment1-transformed.glb')
