/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 --keepmeshes --resolution 1024 --keepnames --types --output ./building_groups_model.tsx --transform ./building_groups.gltf 
Files: ./building_groups.gltf [4.78KB] > /home/cronabit/Downloads/SUNR/Building/pack_-_low_poly_-_22_building__interior/building_groups-transformed.glb [91.26KB] (-1809%)
Author: Islide (https://sketchfab.com/Islide)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/pack-low-poly-22-building-interior-86c688c132d14edc8a2f4d105578b7ad
Title: Pack - Low Poly - 22 Building [ Interior ]
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Object_2: THREE.Mesh
    Object_3: THREE.Mesh
  }
  materials: {
    SU_COLOR: THREE.MeshStandardMaterial
    SU_GLASS: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('./building/building_groups-transformed.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh name="Object_2" geometry={nodes.Object_2.geometry} material={materials.SU_COLOR} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh name="Object_3" geometry={nodes.Object_3.geometry} material={materials.SU_GLASS} rotation={[-Math.PI / 2, 0, 0]} />
    </group>
  )
}

useGLTF.preload('./building/building_groups-transformed.glb')
