/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 --keepmeshes --resolution 1024 --keepnames --types --output ./City_Building_Model.tsx --transform ./city_building.gltf 
Files: ./city_building.gltf [149.07KB] > /home/cronabit/Downloads/Prem_cronabit/game_ready_city_building/city_building-transformed.glb [66.07KB] (56%)
Author: ModelMaker (https://sketchfab.com/mireubay1)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/game-ready-city-building-2bd7122c0f774cb48565187848154436
Title: Game Ready City Building
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Object_4: THREE.Mesh
    Object_12: THREE.Mesh
    Object_84: THREE.Mesh
    Object_92: THREE.Mesh
    Object_6: THREE.Mesh
    Object_14: THREE.Mesh
    Object_40: THREE.Mesh
    Object_44: THREE.Mesh
    Object_62: THREE.Mesh
    Object_66: THREE.Mesh
    Object_86: THREE.Mesh
    Object_94: THREE.Mesh
    Object_8: THREE.Mesh
    Object_16: THREE.Mesh
    Object_42: THREE.Mesh
    Object_46: THREE.Mesh
    Object_64: THREE.Mesh
    Object_68: THREE.Mesh
    Object_88: THREE.Mesh
    Object_96: THREE.Mesh
    Object_10: THREE.Mesh
    Object_18: THREE.Mesh
    Object_90: THREE.Mesh
    Object_98: THREE.Mesh
    Object_20: THREE.Mesh
    Object_48: THREE.Mesh
    Object_60: THREE.Mesh
    Object_70: THREE.Mesh
    Object_82: THREE.Mesh
    Object_100: THREE.Mesh
    Object_22: THREE.Mesh
    Object_30: THREE.Mesh
    Object_50: THREE.Mesh
    Object_58: THREE.Mesh
    Object_72: THREE.Mesh
    Object_80: THREE.Mesh
    Object_102: THREE.Mesh
    Object_110: THREE.Mesh
    Object_24: THREE.Mesh
    Object_26: THREE.Mesh
    Object_28: THREE.Mesh
    Object_52: THREE.Mesh
    Object_54: THREE.Mesh
    Object_56: THREE.Mesh
    Object_74: THREE.Mesh
    Object_76: THREE.Mesh
    Object_78: THREE.Mesh
    Object_104: THREE.Mesh
    Object_106: THREE.Mesh
    Object_108: THREE.Mesh
    Object_32: THREE.Mesh
    Object_34: THREE.Mesh
    Object_36: THREE.Mesh
    Object_112: THREE.Mesh
    Object_114: THREE.Mesh
    Object_116: THREE.Mesh
    Object_38: THREE.Mesh
    Object_118: THREE.Mesh
    Object_120: THREE.Mesh
    Object_122: THREE.Mesh
    Object_124: THREE.Mesh
    Object_126: THREE.Mesh
    Object_128: THREE.Mesh
    Object_130: THREE.Mesh
    Object_132: THREE.Mesh
    Object_134: THREE.Mesh
    Object_136: THREE.Mesh
    Object_138: THREE.Mesh
    Object_140: THREE.Mesh
    Object_142: THREE.Mesh
    Object_144: THREE.Mesh
    Object_146: THREE.Mesh
    Object_148: THREE.Mesh
    Object_150: THREE.Mesh
    Object_152: THREE.Mesh
    Object_154: THREE.Mesh
    Object_156: THREE.Mesh
    Object_158: THREE.Mesh
    Object_160: THREE.Mesh
    Object_162: THREE.Mesh
  }
  materials: {
    atlas: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('./building/city_building-transformed.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh name="Object_4" geometry={nodes.Object_4.geometry} material={materials.atlas} position={[-1.471, -0.225, 0.004]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh name="Object_12" geometry={nodes.Object_12.geometry} material={materials.atlas} position={[-0.355, -0.225, 0.004]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh name="Object_84" geometry={nodes.Object_84.geometry} material={materials.atlas} position={[0.223, -0.225, -2.282]} rotation={[Math.PI / 2, 0, Math.PI]} />
      <mesh name="Object_92" geometry={nodes.Object_92.geometry} material={materials.atlas} position={[-0.892, -0.225, -2.282]} rotation={[Math.PI / 2, 0, Math.PI]} />
      <mesh name="Object_6" geometry={nodes.Object_6.geometry} material={materials.atlas} position={[-1.471, -0.225, 0.004]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh name="Object_14" geometry={nodes.Object_14.geometry} material={materials.atlas} position={[-0.355, -0.225, 0.004]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh name="Object_40" geometry={nodes.Object_40.geometry} material={materials.atlas} position={[-1.77, -0.225, -1.998]} rotation={[Math.PI / 2, 0, 1.571]} />
      <mesh name="Object_44" geometry={nodes.Object_44.geometry} material={materials.atlas} position={[-1.77, -0.225, -0.882]} rotation={[Math.PI / 2, 0, 1.571]} />
      <mesh name="Object_62" geometry={nodes.Object_62.geometry} material={materials.atlas} position={[0.533, -0.225, -0.297]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} />
      <mesh name="Object_66" geometry={nodes.Object_66.geometry} material={materials.atlas} position={[0.533, -0.225, -1.412]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} />
      <mesh name="Object_86" geometry={nodes.Object_86.geometry} material={materials.atlas} position={[0.223, -0.225, -2.282]} rotation={[Math.PI / 2, 0, Math.PI]} />
      <mesh name="Object_94" geometry={nodes.Object_94.geometry} material={materials.atlas} position={[-0.892, -0.225, -2.282]} rotation={[Math.PI / 2, 0, Math.PI]} />
      <mesh name="Object_8" geometry={nodes.Object_8.geometry} material={materials.atlas} position={[-0.925, -0.225, 0.004]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh name="Object_16" geometry={nodes.Object_16.geometry} material={materials.atlas} position={[0.191, -0.225, 0.004]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh name="Object_42" geometry={nodes.Object_42.geometry} material={materials.atlas} position={[-1.77, -0.225, -1.452]} rotation={[Math.PI / 2, 0, 1.571]} />
      <mesh name="Object_46" geometry={nodes.Object_46.geometry} material={materials.atlas} position={[-1.77, -0.225, -0.336]} rotation={[Math.PI / 2, 0, 1.571]} />
      <mesh name="Object_64" geometry={nodes.Object_64.geometry} material={materials.atlas} position={[0.533, -0.225, -0.843]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} />
      <mesh name="Object_68" geometry={nodes.Object_68.geometry} material={materials.atlas} position={[0.533, -0.225, -1.958]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} />
      <mesh name="Object_88" geometry={nodes.Object_88.geometry} material={materials.atlas} position={[-0.323, -0.225, -2.282]} rotation={[Math.PI / 2, 0, Math.PI]} />
      <mesh name="Object_96" geometry={nodes.Object_96.geometry} material={materials.atlas} position={[-1.438, -0.225, -2.282]} rotation={[Math.PI / 2, 0, Math.PI]} />
      <mesh name="Object_10" geometry={nodes.Object_10.geometry} material={materials.atlas} position={[-1.099, -0.2, 0.035]} rotation={[Math.PI / 2, 0, 0]} scale={0.382} />
      <mesh name="Object_18" geometry={nodes.Object_18.geometry} material={materials.atlas} position={[0.017, -0.2, 0.035]} rotation={[Math.PI / 2, 0, 0]} scale={0.382} />
      <mesh name="Object_90" geometry={nodes.Object_90.geometry} material={materials.atlas} position={[-0.149, -0.2, -2.313]} rotation={[Math.PI / 2, 0, Math.PI]} scale={0.382} />
      <mesh name="Object_98" geometry={nodes.Object_98.geometry} material={materials.atlas} position={[-1.264, -0.2, -2.313]} rotation={[Math.PI / 2, 0, Math.PI]} scale={0.382} />
      <mesh name="Object_20" geometry={nodes.Object_20.geometry} material={materials.atlas} position={[-1.432, 0.157, 0.032]} rotation={[Math.PI / 2, 0, 0]} scale={0.726} />
      <mesh name="Object_48" geometry={nodes.Object_48.geometry} material={materials.atlas} position={[-1.787, 0.157, -1.959]} rotation={[Math.PI / 2, 0, Math.PI / 2]} scale={0.726} />
      <mesh name="Object_60" geometry={nodes.Object_60.geometry} material={materials.atlas} position={[-1.787, -0.226, -1.959]} rotation={[Math.PI / 2, 0, Math.PI / 2]} scale={0.726} />
      <mesh name="Object_70" geometry={nodes.Object_70.geometry} material={materials.atlas} position={[0.561, 0.157, -0.335]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={0.726} />
      <mesh name="Object_82" geometry={nodes.Object_82.geometry} material={materials.atlas} position={[0.549, -0.226, -0.335]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={0.726} />
      <mesh name="Object_100" geometry={nodes.Object_100.geometry} material={materials.atlas} position={[0.185, 0.157, -2.31]} rotation={[Math.PI / 2, 0, Math.PI]} scale={0.726} />
      <mesh name="Object_22" geometry={nodes.Object_22.geometry} material={materials.atlas} position={[-1.758, -0.333, 0.035]} scale={0.074} />
      <mesh name="Object_30" geometry={nodes.Object_30.geometry} material={materials.atlas} position={[0.515, -0.333, 0.035]} scale={0.074} />
      <mesh name="Object_50" geometry={nodes.Object_50.geometry} material={materials.atlas} position={[-1.802, -0.333, -2.284]} rotation={[0, -Math.PI / 2, 0]} scale={0.074} />
      <mesh name="Object_58" geometry={nodes.Object_58.geometry} material={materials.atlas} position={[-1.802, -0.333, -0.012]} rotation={[0, -Math.PI / 2, 0]} scale={0.074} />
      <mesh name="Object_72" geometry={nodes.Object_72.geometry} material={materials.atlas} position={[0.564, -0.333, -0.01]} rotation={[0, Math.PI / 2, 0]} scale={0.074} />
      <mesh name="Object_80" geometry={nodes.Object_80.geometry} material={materials.atlas} position={[0.564, -0.333, -2.282]} rotation={[0, Math.PI / 2, 0]} scale={0.074} />
      <mesh name="Object_102" geometry={nodes.Object_102.geometry} material={materials.atlas} position={[0.51, -0.333, -2.313]} rotation={[-Math.PI, 0, -Math.PI]} scale={0.074} />
      <mesh name="Object_110" geometry={nodes.Object_110.geometry} material={materials.atlas} position={[-1.762, -0.333, -2.313]} rotation={[-Math.PI, 0, -Math.PI]} scale={0.074} />
      <mesh name="Object_24" geometry={nodes.Object_24.geometry} material={materials.atlas} position={[-1.193, -0.333, 0.035]} scale={0.074} />
      <mesh name="Object_26" geometry={nodes.Object_26.geometry} material={materials.atlas} position={[-0.624, -0.333, 0.035]} scale={0.074} />
      <mesh name="Object_28" geometry={nodes.Object_28.geometry} material={materials.atlas} position={[-0.079, -0.333, 0.035]} scale={0.074} />
      <mesh name="Object_52" geometry={nodes.Object_52.geometry} material={materials.atlas} position={[-1.802, -0.333, -1.719]} rotation={[0, -Math.PI / 2, 0]} scale={0.074} />
      <mesh name="Object_54" geometry={nodes.Object_54.geometry} material={materials.atlas} position={[-1.802, -0.333, -1.151]} rotation={[0, -Math.PI / 2, 0]} scale={0.074} />
      <mesh name="Object_56" geometry={nodes.Object_56.geometry} material={materials.atlas} position={[-1.802, -0.333, -0.605]} rotation={[0, -Math.PI / 2, 0]} scale={0.074} />
      <mesh name="Object_74" geometry={nodes.Object_74.geometry} material={materials.atlas} position={[0.564, -0.333, -0.575]} rotation={[0, Math.PI / 2, 0]} scale={0.074} />
      <mesh name="Object_76" geometry={nodes.Object_76.geometry} material={materials.atlas} position={[0.564, -0.333, -1.143]} rotation={[0, Math.PI / 2, 0]} scale={0.074} />
      <mesh name="Object_78" geometry={nodes.Object_78.geometry} material={materials.atlas} position={[0.564, -0.333, -1.689]} rotation={[0, Math.PI / 2, 0]} scale={0.074} />
      <mesh name="Object_104" geometry={nodes.Object_104.geometry} material={materials.atlas} position={[-0.055, -0.333, -2.313]} rotation={[-Math.PI, 0, -Math.PI]} scale={0.074} />
      <mesh name="Object_106" geometry={nodes.Object_106.geometry} material={materials.atlas} position={[-0.623, -0.333, -2.313]} rotation={[-Math.PI, 0, -Math.PI]} scale={0.074} />
      <mesh name="Object_108" geometry={nodes.Object_108.geometry} material={materials.atlas} position={[-1.169, -0.333, -2.313]} rotation={[-Math.PI, 0, -Math.PI]} scale={0.074} />
      <mesh name="Object_32" geometry={nodes.Object_32.geometry} material={materials.atlas} position={[-0.612, 0.338, -0.923]} />
      <mesh name="Object_34" geometry={nodes.Object_34.geometry} material={materials.atlas} position={[-1.478, 0.633, 0.034]} rotation={[Math.PI / 2, 0, 0]} scale={0.639} />
      <mesh name="Object_36" geometry={nodes.Object_36.geometry} material={materials.atlas} position={[-1.463, 2.223, -0.01]} rotation={[Math.PI / 2, 0, 0]} scale={1.045} />
      <mesh name="Object_112" geometry={nodes.Object_112.geometry} material={materials.atlas} position={[0.516, 2.223, -0.287]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={1.045} />
      <mesh name="Object_114" geometry={nodes.Object_114.geometry} material={materials.atlas} position={[0.239, 2.223, -2.266]} rotation={[Math.PI / 2, 0, Math.PI]} scale={1.045} />
      <mesh name="Object_116" geometry={nodes.Object_116.geometry} material={materials.atlas} position={[-1.74, 2.223, -1.989]} rotation={[Math.PI / 2, 0, 1.571]} scale={1.045} />
      <mesh name="Object_38" geometry={nodes.Object_38.geometry} material={materials.atlas} position={[-0.585, 2.012, -0.923]} />
      <mesh name="Object_118" geometry={nodes.Object_118.geometry} material={materials.atlas} position={[-0.585, 2.363, -0.923]} />
      <mesh name="Object_120" geometry={nodes.Object_120.geometry} material={materials.atlas} position={[0.5, 1.738, -0.022]} scale={0.074} />
      <mesh name="Object_122" geometry={nodes.Object_122.geometry} material={materials.atlas} position={[-0.045, 1.738, -0.022]} scale={0.074} />
      <mesh name="Object_124" geometry={nodes.Object_124.geometry} material={materials.atlas} position={[-0.614, 1.738, -0.022]} scale={0.074} />
      <mesh name="Object_126" geometry={nodes.Object_126.geometry} material={materials.atlas} position={[-1.184, 1.738, -0.022]} scale={0.074} />
      <mesh name="Object_128" geometry={nodes.Object_128.geometry} material={materials.atlas} position={[-1.709, 1.738, -0.022]} scale={0.074} />
      <mesh name="Object_130" geometry={nodes.Object_130.geometry} material={materials.atlas} position={[0.5, 1.738, -2.239]} scale={0.074} />
      <mesh name="Object_132" geometry={nodes.Object_132.geometry} material={materials.atlas} position={[-0.045, 1.738, -2.239]} scale={0.074} />
      <mesh name="Object_134" geometry={nodes.Object_134.geometry} material={materials.atlas} position={[-0.614, 1.738, -2.239]} scale={0.074} />
      <mesh name="Object_136" geometry={nodes.Object_136.geometry} material={materials.atlas} position={[-1.184, 1.738, -2.239]} scale={0.074} />
      <mesh name="Object_138" geometry={nodes.Object_138.geometry} material={materials.atlas} position={[-1.709, 1.738, -2.239]} scale={0.074} />
      <mesh name="Object_140" geometry={nodes.Object_140.geometry} material={materials.atlas} position={[0.5, 1.738, -1.701]} scale={0.074} />
      <mesh name="Object_142" geometry={nodes.Object_142.geometry} material={materials.atlas} position={[-1.709, 1.738, -1.701]} scale={0.074} />
      <mesh name="Object_144" geometry={nodes.Object_144.geometry} material={materials.atlas} position={[0.5, 1.738, -1.134]} scale={0.074} />
      <mesh name="Object_146" geometry={nodes.Object_146.geometry} material={materials.atlas} position={[-1.709, 1.738, -1.134]} scale={0.074} />
      <mesh name="Object_148" geometry={nodes.Object_148.geometry} material={materials.atlas} position={[0.5, 1.738, -0.565]} scale={0.074} />
      <mesh name="Object_150" geometry={nodes.Object_150.geometry} material={materials.atlas} position={[-1.709, 1.738, -0.565]} scale={0.074} />
      <mesh name="Object_152" geometry={nodes.Object_152.geometry} material={materials.atlas} position={[-0.909, -0.092, 0.242]} scale={0.19} />
      <mesh name="Object_154" geometry={nodes.Object_154.geometry} material={materials.atlas} position={[-0.336, -0.092, 0.242]} scale={0.19} />
      <mesh name="Object_156" geometry={nodes.Object_156.geometry} material={materials.atlas} position={[0.214, -0.092, 0.242]} scale={0.19} />
      <mesh name="Object_158" geometry={nodes.Object_158.geometry} material={materials.atlas} position={[0.481, 0.633, -0.307]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={0.639} />
      <mesh name="Object_160" geometry={nodes.Object_160.geometry} material={materials.atlas} position={[0.07, 0.633, -2.24]} rotation={[Math.PI / 2, 0, Math.PI]} scale={0.639} />
      <mesh name="Object_162" geometry={nodes.Object_162.geometry} material={materials.atlas} position={[-1.889, 0.633, -1.899]} rotation={[Math.PI / 2, 0, Math.PI / 2]} scale={0.639} />
    </group>
  )
}

useGLTF.preload('./building/city_building-transformed.glb')
