/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 --keepmeshes --resolution 1024 --keepnames --types --output ./NewApartmentModel.tsx --transform ./newapartment.gltf 
Files: ./newapartment.gltf [271.36KB] > /home/cronabit/Downloads/Prem_cronabit/apartment_exterior/newapartment-transformed.glb [214.69KB] (21%)
Author: yuuuusukeeee (https://sketchfab.com/yuuuusukeeee)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/apartment-exterior-b201517e8f594a1a9791721e6bbc932f
Title: Apartment_[exterior]
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Object_6: THREE.Mesh
    Object_8: THREE.Mesh
    Object_11: THREE.Mesh
    Object_13: THREE.Mesh
    Object_15: THREE.Mesh
    Object_17: THREE.Mesh
    Object_19: THREE.Mesh
    Object_21: THREE.Mesh
    Object_23: THREE.Mesh
    Object_26: THREE.Mesh
    Object_28: THREE.Mesh
    Object_30: THREE.Mesh
    Object_32: THREE.Mesh
    Object_34: THREE.Mesh
    Object_36: THREE.Mesh
    Object_38: THREE.Mesh
    Object_40: THREE.Mesh
    Object_42: THREE.Mesh
    Object_44: THREE.Mesh
    Object_46: THREE.Mesh
    Object_48: THREE.Mesh
    Object_50: THREE.Mesh
    Object_52: THREE.Mesh
    Object_54: THREE.Mesh
    Object_56: THREE.Mesh
    Object_58: THREE.Mesh
    Object_61: THREE.Mesh
    Object_63: THREE.Mesh
    Object_65: THREE.Mesh
    Object_67: THREE.Mesh
    Object_69: THREE.Mesh
    Object_71: THREE.Mesh
    Object_73: THREE.Mesh
    Object_75: THREE.Mesh
    Object_77: THREE.Mesh
    Object_79: THREE.Mesh
    Object_81: THREE.Mesh
    Object_83: THREE.Mesh
    Object_85: THREE.Mesh
    Object_87: THREE.Mesh
    Object_89: THREE.Mesh
    Object_91: THREE.Mesh
    Object_93: THREE.Mesh
    Object_95: THREE.Mesh
    Object_97: THREE.Mesh
    Object_99: THREE.Mesh
    Object_101: THREE.Mesh
    Object_103: THREE.Mesh
    Object_105: THREE.Mesh
    Object_107: THREE.Mesh
    Object_110: THREE.Mesh
    Object_112: THREE.Mesh
    Object_114: THREE.Mesh
    Object_116: THREE.Mesh
    Object_118: THREE.Mesh
    Object_120: THREE.Mesh
    Object_122: THREE.Mesh
    Object_124: THREE.Mesh
    Object_127: THREE.Mesh
    Object_129: THREE.Mesh
    Object_131: THREE.Mesh
    Object_133: THREE.Mesh
    Object_135: THREE.Mesh
    Object_137: THREE.Mesh
    Object_139: THREE.Mesh
    Object_141: THREE.Mesh
    Object_143: THREE.Mesh
    Object_146: THREE.Mesh
    Object_148: THREE.Mesh
    Object_150: THREE.Mesh
    Object_152: THREE.Mesh
    Object_154: THREE.Mesh
    Object_156: THREE.Mesh
    Object_158: THREE.Mesh
    Object_160: THREE.Mesh
    Object_162: THREE.Mesh
    Object_164: THREE.Mesh
    Object_166: THREE.Mesh
    Object_168: THREE.Mesh
    Object_170: THREE.Mesh
    Object_172: THREE.Mesh
    Object_174: THREE.Mesh
    Object_176: THREE.Mesh
    Object_178: THREE.Mesh
    Object_180: THREE.Mesh
    Object_182: THREE.Mesh
    Object_184: THREE.Mesh
    Object_186: THREE.Mesh
    Object_188: THREE.Mesh
    Object_190: THREE.Mesh
    Object_192: THREE.Mesh
    Object_194: THREE.Mesh
    Object_196: THREE.Mesh
    Object_198: THREE.Mesh
    Object_200: THREE.Mesh
    Object_202: THREE.Mesh
    Object_204: THREE.Mesh
    Object_206: THREE.Mesh
    Object_208: THREE.Mesh
    Object_210: THREE.Mesh
    Object_212: THREE.Mesh
    Object_214: THREE.Mesh
    Object_216: THREE.Mesh
    Object_218: THREE.Mesh
    Object_220: THREE.Mesh
    Object_222: THREE.Mesh
    Object_224: THREE.Mesh
    Object_228: THREE.Mesh
    Object_230: THREE.Mesh
    Object_232: THREE.Mesh
    Object_234: THREE.Mesh
    Object_236: THREE.Mesh
    Object_238: THREE.Mesh
    Object_240: THREE.Mesh
    Object_242: THREE.Mesh
    Object_244: THREE.Mesh
    Object_246: THREE.Mesh
    Object_248: THREE.Mesh
    Object_250: THREE.Mesh
    Object_252: THREE.Mesh
    Object_254: THREE.Mesh
    Object_256: THREE.Mesh
    Object_258: THREE.Mesh
    Object_260: THREE.Mesh
    Object_262: THREE.Mesh
    Object_264: THREE.Mesh
    Object_266: THREE.Mesh
    Object_268: THREE.Mesh
    Object_270: THREE.Mesh
    Object_272: THREE.Mesh
    Object_274: THREE.Mesh
    Object_276: THREE.Mesh
    Object_278: THREE.Mesh
    Object_280: THREE.Mesh
    Object_282: THREE.Mesh
    Object_284: THREE.Mesh
    Object_286: THREE.Mesh
    Object_288: THREE.Mesh
    Object_290: THREE.Mesh
    Object_292: THREE.Mesh
    Object_294: THREE.Mesh
    Object_296: THREE.Mesh
    Object_298: THREE.Mesh
    Object_300: THREE.Mesh
    Object_302: THREE.Mesh
    Object_304: THREE.Mesh
    Object_306: THREE.Mesh
    Object_308: THREE.Mesh
    Object_310: THREE.Mesh
    Object_312: THREE.Mesh
    Object_315: THREE.Mesh
    Object_317: THREE.Mesh
    Object_319: THREE.Mesh
    Object_321: THREE.Mesh
    Object_323: THREE.Mesh
    Object_325: THREE.Mesh
    Object_327: THREE.Mesh
    Object_329: THREE.Mesh
    Object_331: THREE.Mesh
    Object_333: THREE.Mesh
    Object_335: THREE.Mesh
    Object_337: THREE.Mesh
    Object_339: THREE.Mesh
    Object_341: THREE.Mesh
    Object_343: THREE.Mesh
    Object_345: THREE.Mesh
    Object_347: THREE.Mesh
    Object_349: THREE.Mesh
    Object_351: THREE.Mesh
    Object_353: THREE.Mesh
    Object_355: THREE.Mesh
    Object_357: THREE.Mesh
    Object_359: THREE.Mesh
    Object_361: THREE.Mesh
    Object_363: THREE.Mesh
    Object_365: THREE.Mesh
    Object_367: THREE.Mesh
    Object_369: THREE.Mesh
    Object_371: THREE.Mesh
    Object_373: THREE.Mesh
  }
  materials: {
    PaletteMaterial001: THREE.MeshStandardMaterial
    PaletteMaterial002: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('./building/newapartment-transformed.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh name="Object_6" geometry={nodes.Object_6.geometry} material={materials.PaletteMaterial001} scale={0.001} />
      <mesh name="Object_8" geometry={nodes.Object_8.geometry} material={materials.PaletteMaterial001} scale={0.001} />
      <mesh name="Object_11" geometry={nodes.Object_11.geometry} material={materials.PaletteMaterial001} scale={0.001} />
      <mesh name="Object_13" geometry={nodes.Object_13.geometry} material={materials.PaletteMaterial001} scale={0.001} />
      <mesh name="Object_15" geometry={nodes.Object_15.geometry} material={materials.PaletteMaterial001} scale={0.001} />
      <mesh name="Object_17" geometry={nodes.Object_17.geometry} material={materials.PaletteMaterial001} scale={0.001} />
      <mesh name="Object_19" geometry={nodes.Object_19.geometry} material={materials.PaletteMaterial001} scale={0.001} />
      <mesh name="Object_21" geometry={nodes.Object_21.geometry} material={materials.PaletteMaterial001} scale={0.001} />
      <mesh name="Object_23" geometry={nodes.Object_23.geometry} material={materials.PaletteMaterial001} scale={0.001} />
      <mesh name="Object_26" geometry={nodes.Object_26.geometry} material={materials.PaletteMaterial001} scale={0.001} />
      <mesh name="Object_28" geometry={nodes.Object_28.geometry} material={materials.PaletteMaterial001} scale={0.001} />
      <mesh name="Object_30" geometry={nodes.Object_30.geometry} material={materials.PaletteMaterial001} scale={0.001} />
      <mesh name="Object_32" geometry={nodes.Object_32.geometry} material={materials.PaletteMaterial001} scale={0.001} />
      <mesh name="Object_34" geometry={nodes.Object_34.geometry} material={materials.PaletteMaterial001} scale={0.001} />
      <mesh name="Object_36" geometry={nodes.Object_36.geometry} material={materials.PaletteMaterial001} scale={0.001} />
      <mesh name="Object_38" geometry={nodes.Object_38.geometry} material={materials.PaletteMaterial001} scale={0.001} />
      <mesh name="Object_40" geometry={nodes.Object_40.geometry} material={materials.PaletteMaterial001} scale={0.001} />
      <mesh name="Object_42" geometry={nodes.Object_42.geometry} material={materials.PaletteMaterial001} scale={0.001} />
      <mesh name="Object_44" geometry={nodes.Object_44.geometry} material={materials.PaletteMaterial001} scale={0.001} />
      <mesh name="Object_46" geometry={nodes.Object_46.geometry} material={materials.PaletteMaterial001} scale={0.001} />
      <mesh name="Object_48" geometry={nodes.Object_48.geometry} material={materials.PaletteMaterial001} scale={0.001} />
      <mesh name="Object_50" geometry={nodes.Object_50.geometry} material={materials.PaletteMaterial001} scale={0.001} />
      <mesh name="Object_52" geometry={nodes.Object_52.geometry} material={materials.PaletteMaterial001} scale={0.001} />
      <mesh name="Object_54" geometry={nodes.Object_54.geometry} material={materials.PaletteMaterial001} scale={0.001} />
      <mesh name="Object_56" geometry={nodes.Object_56.geometry} material={materials.PaletteMaterial001} scale={0.001} />
      <mesh name="Object_58" geometry={nodes.Object_58.geometry} material={materials.PaletteMaterial001} scale={0.001} />
      <mesh name="Object_61" geometry={nodes.Object_61.geometry} material={materials.PaletteMaterial001} scale={0.001} />
      <mesh name="Object_63" geometry={nodes.Object_63.geometry} material={materials.PaletteMaterial001} scale={0.001} />
      <mesh name="Object_65" geometry={nodes.Object_65.geometry} material={materials.PaletteMaterial001} scale={0.001} />
      <mesh name="Object_67" geometry={nodes.Object_67.geometry} material={materials.PaletteMaterial001} scale={0.001} />
      <mesh name="Object_69" geometry={nodes.Object_69.geometry} material={materials.PaletteMaterial001} scale={0.001} />
      <mesh name="Object_71" geometry={nodes.Object_71.geometry} material={materials.PaletteMaterial001} scale={0.001} />
      <mesh name="Object_73" geometry={nodes.Object_73.geometry} material={materials.PaletteMaterial001} scale={0.001} />
      <mesh name="Object_75" geometry={nodes.Object_75.geometry} material={materials.PaletteMaterial001} scale={0.001} />
      <mesh name="Object_77" geometry={nodes.Object_77.geometry} material={materials.PaletteMaterial001} scale={0.001} />
      <mesh name="Object_79" geometry={nodes.Object_79.geometry} material={materials.PaletteMaterial001} scale={0.001} />
      <mesh name="Object_81" geometry={nodes.Object_81.geometry} material={materials.PaletteMaterial001} scale={0.001} />
      <mesh name="Object_83" geometry={nodes.Object_83.geometry} material={materials.PaletteMaterial001} scale={0.001} />
      <mesh name="Object_85" geometry={nodes.Object_85.geometry} material={materials.PaletteMaterial001} scale={0.001} />
      <mesh name="Object_87" geometry={nodes.Object_87.geometry} material={materials.PaletteMaterial001} scale={0.001} />
      <mesh name="Object_89" geometry={nodes.Object_89.geometry} material={materials.PaletteMaterial001} scale={0.001} />
      <mesh name="Object_91" geometry={nodes.Object_91.geometry} material={materials.PaletteMaterial001} scale={0.001} />
      <mesh name="Object_93" geometry={nodes.Object_93.geometry} material={materials.PaletteMaterial001} scale={0.001} />
      <mesh name="Object_95" geometry={nodes.Object_95.geometry} material={materials.PaletteMaterial001} scale={0.001} />
      <mesh name="Object_97" geometry={nodes.Object_97.geometry} material={materials.PaletteMaterial001} scale={0.001} />
      <mesh name="Object_99" geometry={nodes.Object_99.geometry} material={materials.PaletteMaterial001} scale={0.001} />
      <mesh name="Object_101" geometry={nodes.Object_101.geometry} material={materials.PaletteMaterial001} scale={0.001} />
      <mesh name="Object_103" geometry={nodes.Object_103.geometry} material={materials.PaletteMaterial001} scale={0.001} />
      <mesh name="Object_105" geometry={nodes.Object_105.geometry} material={materials.PaletteMaterial001} scale={0.001} />
      <mesh name="Object_107" geometry={nodes.Object_107.geometry} material={materials.PaletteMaterial001} scale={0.001} />
      <mesh name="Object_110" geometry={nodes.Object_110.geometry} material={materials.PaletteMaterial002} scale={0.001} />
      <mesh name="Object_112" geometry={nodes.Object_112.geometry} material={materials.PaletteMaterial002} scale={0.001} />
      <mesh name="Object_114" geometry={nodes.Object_114.geometry} material={materials.PaletteMaterial002} scale={0.001} />
      <mesh name="Object_116" geometry={nodes.Object_116.geometry} material={materials.PaletteMaterial002} scale={0.001} />
      <mesh name="Object_118" geometry={nodes.Object_118.geometry} material={materials.PaletteMaterial002} scale={0.001} />
      <mesh name="Object_120" geometry={nodes.Object_120.geometry} material={materials.PaletteMaterial002} scale={0.001} />
      <mesh name="Object_122" geometry={nodes.Object_122.geometry} material={materials.PaletteMaterial002} scale={0.001} />
      <mesh name="Object_124" geometry={nodes.Object_124.geometry} material={materials.PaletteMaterial002} scale={0.001} />
      <mesh name="Object_127" geometry={nodes.Object_127.geometry} material={materials.PaletteMaterial001} scale={0.001} />
      <mesh name="Object_129" geometry={nodes.Object_129.geometry} material={materials.PaletteMaterial001} scale={0.001} />
      <mesh name="Object_131" geometry={nodes.Object_131.geometry} material={materials.PaletteMaterial001} scale={0.001} />
      <mesh name="Object_133" geometry={nodes.Object_133.geometry} material={materials.PaletteMaterial001} scale={0.001} />
      <mesh name="Object_135" geometry={nodes.Object_135.geometry} material={materials.PaletteMaterial001} scale={0.001} />
      <mesh name="Object_137" geometry={nodes.Object_137.geometry} material={materials.PaletteMaterial001} scale={0.001} />
      <mesh name="Object_139" geometry={nodes.Object_139.geometry} material={materials.PaletteMaterial001} scale={0.001} />
      <mesh name="Object_141" geometry={nodes.Object_141.geometry} material={materials.PaletteMaterial001} scale={0.001} />
      <mesh name="Object_143" geometry={nodes.Object_143.geometry} material={materials.PaletteMaterial001} scale={0.001} />
      <mesh name="Object_146" geometry={nodes.Object_146.geometry} material={materials.PaletteMaterial001} scale={0.001} />
      <mesh name="Object_148" geometry={nodes.Object_148.geometry} material={materials.PaletteMaterial001} scale={0.001} />
      <mesh name="Object_150" geometry={nodes.Object_150.geometry} material={materials.PaletteMaterial001} scale={0.001} />
      <mesh name="Object_152" geometry={nodes.Object_152.geometry} material={materials.PaletteMaterial001} scale={0.001} />
      <mesh name="Object_154" geometry={nodes.Object_154.geometry} material={materials.PaletteMaterial001} scale={0.001} />
      <mesh name="Object_156" geometry={nodes.Object_156.geometry} material={materials.PaletteMaterial001} scale={0.001} />
      <mesh name="Object_158" geometry={nodes.Object_158.geometry} material={materials.PaletteMaterial001} scale={0.001} />
      <mesh name="Object_160" geometry={nodes.Object_160.geometry} material={materials.PaletteMaterial001} scale={0.001} />
      <mesh name="Object_162" geometry={nodes.Object_162.geometry} material={materials.PaletteMaterial001} scale={0.001} />
      <mesh name="Object_164" geometry={nodes.Object_164.geometry} material={materials.PaletteMaterial001} scale={0.001} />
      <mesh name="Object_166" geometry={nodes.Object_166.geometry} material={materials.PaletteMaterial001} scale={0.001} />
      <mesh name="Object_168" geometry={nodes.Object_168.geometry} material={materials.PaletteMaterial001} scale={0.001} />
      <mesh name="Object_170" geometry={nodes.Object_170.geometry} material={materials.PaletteMaterial001} scale={0.001} />
      <mesh name="Object_172" geometry={nodes.Object_172.geometry} material={materials.PaletteMaterial001} scale={0.001} />
      <mesh name="Object_174" geometry={nodes.Object_174.geometry} material={materials.PaletteMaterial001} scale={0.001} />
      <mesh name="Object_176" geometry={nodes.Object_176.geometry} material={materials.PaletteMaterial001} scale={0.001} />
      <mesh name="Object_178" geometry={nodes.Object_178.geometry} material={materials.PaletteMaterial001} scale={0.001} />
      <mesh name="Object_180" geometry={nodes.Object_180.geometry} material={materials.PaletteMaterial001} scale={0.001} />
      <mesh name="Object_182" geometry={nodes.Object_182.geometry} material={materials.PaletteMaterial001} scale={0.001} />
      <mesh name="Object_184" geometry={nodes.Object_184.geometry} material={materials.PaletteMaterial001} scale={0.001} />
      <mesh name="Object_186" geometry={nodes.Object_186.geometry} material={materials.PaletteMaterial001} scale={0.001} />
      <mesh name="Object_188" geometry={nodes.Object_188.geometry} material={materials.PaletteMaterial001} scale={0.001} />
      <mesh name="Object_190" geometry={nodes.Object_190.geometry} material={materials.PaletteMaterial001} scale={0.001} />
      <mesh name="Object_192" geometry={nodes.Object_192.geometry} material={materials.PaletteMaterial001} scale={0.001} />
      <mesh name="Object_194" geometry={nodes.Object_194.geometry} material={materials.PaletteMaterial001} scale={0.001} />
      <mesh name="Object_196" geometry={nodes.Object_196.geometry} material={materials.PaletteMaterial001} scale={0.001} />
      <mesh name="Object_198" geometry={nodes.Object_198.geometry} material={materials.PaletteMaterial001} scale={0.001} />
      <mesh name="Object_200" geometry={nodes.Object_200.geometry} material={materials.PaletteMaterial001} scale={0.001} />
      <mesh name="Object_202" geometry={nodes.Object_202.geometry} material={materials.PaletteMaterial001} scale={0.001} />
      <mesh name="Object_204" geometry={nodes.Object_204.geometry} material={materials.PaletteMaterial001} scale={0.001} />
      <mesh name="Object_206" geometry={nodes.Object_206.geometry} material={materials.PaletteMaterial001} scale={0.001} />
      <mesh name="Object_208" geometry={nodes.Object_208.geometry} material={materials.PaletteMaterial001} scale={0.001} />
      <mesh name="Object_210" geometry={nodes.Object_210.geometry} material={materials.PaletteMaterial001} scale={0.001} />
      <mesh name="Object_212" geometry={nodes.Object_212.geometry} material={materials.PaletteMaterial001} scale={0.001} />
      <mesh name="Object_214" geometry={nodes.Object_214.geometry} material={materials.PaletteMaterial001} scale={0.001} />
      <mesh name="Object_216" geometry={nodes.Object_216.geometry} material={materials.PaletteMaterial001} scale={0.001} />
      <mesh name="Object_218" geometry={nodes.Object_218.geometry} material={materials.PaletteMaterial001} scale={0.001} />
      <mesh name="Object_220" geometry={nodes.Object_220.geometry} material={materials.PaletteMaterial001} scale={0.001} />
      <mesh name="Object_222" geometry={nodes.Object_222.geometry} material={materials.PaletteMaterial001} scale={0.001} />
      <mesh name="Object_224" geometry={nodes.Object_224.geometry} material={materials.PaletteMaterial001} scale={0.001} />
      <mesh name="Object_228" geometry={nodes.Object_228.geometry} material={materials.PaletteMaterial001} scale={0.001} />
      <mesh name="Object_230" geometry={nodes.Object_230.geometry} material={materials.PaletteMaterial001} scale={0.001} />
      <mesh name="Object_232" geometry={nodes.Object_232.geometry} material={materials.PaletteMaterial001} scale={0.001} />
      <mesh name="Object_234" geometry={nodes.Object_234.geometry} material={materials.PaletteMaterial001} scale={0.001} />
      <mesh name="Object_236" geometry={nodes.Object_236.geometry} material={materials.PaletteMaterial001} scale={0.001} />
      <mesh name="Object_238" geometry={nodes.Object_238.geometry} material={materials.PaletteMaterial001} scale={0.001} />
      <mesh name="Object_240" geometry={nodes.Object_240.geometry} material={materials.PaletteMaterial001} scale={0.001} />
      <mesh name="Object_242" geometry={nodes.Object_242.geometry} material={materials.PaletteMaterial001} scale={0.001} />
      <mesh name="Object_244" geometry={nodes.Object_244.geometry} material={materials.PaletteMaterial001} scale={0.001} />
      <mesh name="Object_246" geometry={nodes.Object_246.geometry} material={materials.PaletteMaterial001} scale={0.001} />
      <mesh name="Object_248" geometry={nodes.Object_248.geometry} material={materials.PaletteMaterial001} scale={0.001} />
      <mesh name="Object_250" geometry={nodes.Object_250.geometry} material={materials.PaletteMaterial001} scale={0.001} />
      <mesh name="Object_252" geometry={nodes.Object_252.geometry} material={materials.PaletteMaterial001} scale={0.001} />
      <mesh name="Object_254" geometry={nodes.Object_254.geometry} material={materials.PaletteMaterial001} scale={0.001} />
      <mesh name="Object_256" geometry={nodes.Object_256.geometry} material={materials.PaletteMaterial001} scale={0.001} />
      <mesh name="Object_258" geometry={nodes.Object_258.geometry} material={materials.PaletteMaterial001} scale={0.001} />
      <mesh name="Object_260" geometry={nodes.Object_260.geometry} material={materials.PaletteMaterial001} scale={0.001} />
      <mesh name="Object_262" geometry={nodes.Object_262.geometry} material={materials.PaletteMaterial001} scale={0.001} />
      <mesh name="Object_264" geometry={nodes.Object_264.geometry} material={materials.PaletteMaterial001} scale={0.001} />
      <mesh name="Object_266" geometry={nodes.Object_266.geometry} material={materials.PaletteMaterial001} scale={0.001} />
      <mesh name="Object_268" geometry={nodes.Object_268.geometry} material={materials.PaletteMaterial001} scale={0.001} />
      <mesh name="Object_270" geometry={nodes.Object_270.geometry} material={materials.PaletteMaterial001} scale={0.001} />
      <mesh name="Object_272" geometry={nodes.Object_272.geometry} material={materials.PaletteMaterial001} scale={0.001} />
      <mesh name="Object_274" geometry={nodes.Object_274.geometry} material={materials.PaletteMaterial001} scale={0.001} />
      <mesh name="Object_276" geometry={nodes.Object_276.geometry} material={materials.PaletteMaterial001} scale={0.001} />
      <mesh name="Object_278" geometry={nodes.Object_278.geometry} material={materials.PaletteMaterial001} scale={0.001} />
      <mesh name="Object_280" geometry={nodes.Object_280.geometry} material={materials.PaletteMaterial001} scale={0.001} />
      <mesh name="Object_282" geometry={nodes.Object_282.geometry} material={materials.PaletteMaterial001} scale={0.001} />
      <mesh name="Object_284" geometry={nodes.Object_284.geometry} material={materials.PaletteMaterial001} scale={0.001} />
      <mesh name="Object_286" geometry={nodes.Object_286.geometry} material={materials.PaletteMaterial001} scale={0.001} />
      <mesh name="Object_288" geometry={nodes.Object_288.geometry} material={materials.PaletteMaterial001} scale={0.001} />
      <mesh name="Object_290" geometry={nodes.Object_290.geometry} material={materials.PaletteMaterial001} scale={0.001} />
      <mesh name="Object_292" geometry={nodes.Object_292.geometry} material={materials.PaletteMaterial001} scale={0.001} />
      <mesh name="Object_294" geometry={nodes.Object_294.geometry} material={materials.PaletteMaterial001} scale={0.001} />
      <mesh name="Object_296" geometry={nodes.Object_296.geometry} material={materials.PaletteMaterial001} scale={0.001} />
      <mesh name="Object_298" geometry={nodes.Object_298.geometry} material={materials.PaletteMaterial001} scale={0.001} />
      <mesh name="Object_300" geometry={nodes.Object_300.geometry} material={materials.PaletteMaterial001} scale={0.001} />
      <mesh name="Object_302" geometry={nodes.Object_302.geometry} material={materials.PaletteMaterial001} scale={0.001} />
      <mesh name="Object_304" geometry={nodes.Object_304.geometry} material={materials.PaletteMaterial001} scale={0.001} />
      <mesh name="Object_306" geometry={nodes.Object_306.geometry} material={materials.PaletteMaterial001} scale={0.001} />
      <mesh name="Object_308" geometry={nodes.Object_308.geometry} material={materials.PaletteMaterial001} scale={0.001} />
      <mesh name="Object_310" geometry={nodes.Object_310.geometry} material={materials.PaletteMaterial001} scale={0.001} />
      <mesh name="Object_312" geometry={nodes.Object_312.geometry} material={materials.PaletteMaterial001} scale={0.001} />
      <mesh name="Object_315" geometry={nodes.Object_315.geometry} material={materials.PaletteMaterial001} scale={0.001} />
      <mesh name="Object_317" geometry={nodes.Object_317.geometry} material={materials.PaletteMaterial001} scale={0.001} />
      <mesh name="Object_319" geometry={nodes.Object_319.geometry} material={materials.PaletteMaterial001} scale={0.001} />
      <mesh name="Object_321" geometry={nodes.Object_321.geometry} material={materials.PaletteMaterial001} scale={0.001} />
      <mesh name="Object_323" geometry={nodes.Object_323.geometry} material={materials.PaletteMaterial001} scale={0.001} />
      <mesh name="Object_325" geometry={nodes.Object_325.geometry} material={materials.PaletteMaterial001} scale={0.001} />
      <mesh name="Object_327" geometry={nodes.Object_327.geometry} material={materials.PaletteMaterial001} scale={0.001} />
      <mesh name="Object_329" geometry={nodes.Object_329.geometry} material={materials.PaletteMaterial001} scale={0.001} />
      <mesh name="Object_331" geometry={nodes.Object_331.geometry} material={materials.PaletteMaterial001} scale={0.001} />
      <mesh name="Object_333" geometry={nodes.Object_333.geometry} material={materials.PaletteMaterial001} scale={0.001} />
      <mesh name="Object_335" geometry={nodes.Object_335.geometry} material={materials.PaletteMaterial001} scale={0.001} />
      <mesh name="Object_337" geometry={nodes.Object_337.geometry} material={materials.PaletteMaterial001} scale={0.001} />
      <mesh name="Object_339" geometry={nodes.Object_339.geometry} material={materials.PaletteMaterial001} scale={0.001} />
      <mesh name="Object_341" geometry={nodes.Object_341.geometry} material={materials.PaletteMaterial001} scale={0.001} />
      <mesh name="Object_343" geometry={nodes.Object_343.geometry} material={materials.PaletteMaterial001} scale={0.001} />
      <mesh name="Object_345" geometry={nodes.Object_345.geometry} material={materials.PaletteMaterial001} scale={0.001} />
      <mesh name="Object_347" geometry={nodes.Object_347.geometry} material={materials.PaletteMaterial001} scale={0.001} />
      <mesh name="Object_349" geometry={nodes.Object_349.geometry} material={materials.PaletteMaterial001} scale={0.001} />
      <mesh name="Object_351" geometry={nodes.Object_351.geometry} material={materials.PaletteMaterial001} scale={0.001} />
      <mesh name="Object_353" geometry={nodes.Object_353.geometry} material={materials.PaletteMaterial001} scale={0.001} />
      <mesh name="Object_355" geometry={nodes.Object_355.geometry} material={materials.PaletteMaterial001} scale={0.001} />
      <mesh name="Object_357" geometry={nodes.Object_357.geometry} material={materials.PaletteMaterial001} scale={0.001} />
      <mesh name="Object_359" geometry={nodes.Object_359.geometry} material={materials.PaletteMaterial001} scale={0.001} />
      <mesh name="Object_361" geometry={nodes.Object_361.geometry} material={materials.PaletteMaterial001} scale={0.001} />
      <mesh name="Object_363" geometry={nodes.Object_363.geometry} material={materials.PaletteMaterial001} scale={0.001} />
      <mesh name="Object_365" geometry={nodes.Object_365.geometry} material={materials.PaletteMaterial001} scale={0.001} />
      <mesh name="Object_367" geometry={nodes.Object_367.geometry} material={materials.PaletteMaterial001} scale={0.001} />
      <mesh name="Object_369" geometry={nodes.Object_369.geometry} material={materials.PaletteMaterial001} scale={0.001} />
      <mesh name="Object_371" geometry={nodes.Object_371.geometry} material={materials.PaletteMaterial001} scale={0.001} />
      <mesh name="Object_373" geometry={nodes.Object_373.geometry} material={materials.PaletteMaterial001} scale={0.001} />
    </group>
  )
}

useGLTF.preload('./building/newapartment-transformed.glb')
