/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 --keepmeshes --resolution 1024 --keepnames --types --output ./Old_Building_Model.tsx --transform ./old_building.gltf 
Files: ./old_building.gltf [12.25KB] > C:\Users\HP\Downloads\old_building\old_building-transformed.glb [211.34KB] (-1625%)
Author: mythical studios (https://sketchfab.com/mythicalstd3373)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/old-building-f77c9fe77e4c491ebc10a3aa89c35161
Title: Old Building
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Cube_Material001_0: THREE.Mesh
    Cube001_Material001_0: THREE.Mesh
    Cube002_Material_0: THREE.Mesh
    Cylinder_Material002_0: THREE.Mesh
    Cube003_Material001_0: THREE.Mesh
  }
  materials: {
    ['Material.001']: THREE.MeshStandardMaterial
    Material: THREE.MeshStandardMaterial
    ['Material.002']: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('./building/old_building-transformed.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh name="Cube_Material001_0" geometry={nodes.Cube_Material001_0.geometry} material={materials['Material.001']} position={[0, 0.201, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={[2.367, 0.102, 0.944]} />
      <mesh name="Cube001_Material001_0" geometry={nodes.Cube001_Material001_0.geometry} material={materials['Material.001']} position={[0, 0.201, -1.583]} rotation={[-Math.PI / 2, 0, -Math.PI]} scale={[2.367, 0.102, 0.944]} />
      <mesh name="Cube002_Material_0" geometry={nodes.Cube002_Material_0.geometry} material={materials.Material} position={[2.386, 0.17, -0.794]} rotation={[-Math.PI / 2, 0, -Math.PI]} scale={[-0.071, 0.976, 0.89]} />
      <mesh name="Cylinder_Material002_0" geometry={nodes.Cylinder_Material002_0.geometry} material={materials['Material.002']} position={[0.002, 0.705, -0.78]} rotation={[-Math.PI / 2, Math.PI / 2, 0]} scale={[0.854, 1.183, 2.438]} />
      <mesh name="Cube003_Material001_0" geometry={nodes.Cube003_Material001_0.geometry} material={materials['Material.001']} position={[-2.296, 0.228, -0.763]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]} scale={[1.016, 0.102, 0.944]} />
    </group>
  )
}

useGLTF.preload('./building/old_building-transformed.glb')
