/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 --keepmeshes --resolution 1024 --keepnames --types --output ./PanelHouseModel.tsx --transform ./panel_house.gltf 
Files: ./panel_house.gltf [14.52KB] > /home/cronabit/Downloads/Prem_cronabit/soviet_panel_house_built_in_the_1970s/panel_house-transformed.glb [292.74KB] (-1916%)
Author: Unka II (https://sketchfab.com/UnkaII)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/soviet-panel-house-built-in-the-1970s-94996e8cf4a8452d91ec1e206b5b4137
Title: Soviet panel house built in the 1970s
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Plane001_Material001_0: THREE.Mesh
    Plane001_Material002_0: THREE.Mesh
    Plane001_Material003_0: THREE.Mesh
    Plane001_FD_0: THREE.Mesh
    Plane001_Padik_0: THREE.Mesh
    Plane001_roof_0: THREE.Mesh
  }
  materials: {
    ['Material.001']: THREE.MeshStandardMaterial
    ['Material.002']: THREE.MeshStandardMaterial
    ['Material.003']: THREE.MeshStandardMaterial
    material: THREE.MeshStandardMaterial
    Padik: THREE.MeshStandardMaterial
    roof: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('./building/panel_house-transformed.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh name="Plane001_Material001_0" geometry={nodes.Plane001_Material001_0.geometry} material={materials['Material.001']} rotation={[-Math.PI / 2, 0, -Math.PI / 2]} />
      <mesh name="Plane001_Material002_0" geometry={nodes.Plane001_Material002_0.geometry} material={materials['Material.002']} rotation={[-Math.PI / 2, 0, -Math.PI / 2]} />
      <mesh name="Plane001_Material003_0" geometry={nodes.Plane001_Material003_0.geometry} material={materials['Material.003']} rotation={[-Math.PI / 2, 0, -Math.PI / 2]} />
      <mesh name="Plane001_FD_0" geometry={nodes.Plane001_FD_0.geometry} material={materials.material} rotation={[-Math.PI / 2, 0, -Math.PI / 2]} />
      <mesh name="Plane001_Padik_0" geometry={nodes.Plane001_Padik_0.geometry} material={materials.Padik} rotation={[-Math.PI / 2, 0, -Math.PI / 2]} />
      <mesh name="Plane001_roof_0" geometry={nodes.Plane001_roof_0.geometry} material={materials.roof} rotation={[-Math.PI / 2, 0, -Math.PI / 2]} />
    </group>
  )
}

useGLTF.preload('./building/panel_house-transformed.glb')
