/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 --keepmeshes --resolution 1024 --keepnames --types --output ./red_building_model.tsx --transform ./red_building.gltf 
Files: ./red_building.gltf [21.86KB] > /home/cronabit/Downloads/SUNR/Building/lowpoly_stylized_ghetto_city_pack/red_building-transformed.glb [202.78KB] (-828%)
Author: canakdemir (https://sketchfab.com/canakdemir)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/lowpoly-stylized-ghetto-city-pack-837d0d13a7224ea5a08b1fdc83bef432
Title: LOWPOLY STYLİZED GHETTO CİTY PACK
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    ['1001_Bina1_0']: THREE.Mesh
    ['2001_Bina2_0']: THREE.Mesh
    ['3001_Bina3_0']: THREE.Mesh
    ['4001_Bina4_0']: THREE.Mesh
    Bank001_Others_0: THREE.Mesh
    Garbage001_Others_0: THREE.Mesh
    Lights001_Others_0: THREE.Mesh
    Plane_Road_0: THREE.Mesh
    Cube_Road_0: THREE.Mesh
  }
  materials: {
    Bina1: THREE.MeshStandardMaterial
    Bina2: THREE.MeshStandardMaterial
    Bina3: THREE.MeshStandardMaterial
    Bina4: THREE.MeshStandardMaterial
    Others: THREE.MeshStandardMaterial
    Road: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('./building/red_building-transformed.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh name="1001_Bina1_0" geometry={nodes['1001_Bina1_0'].geometry} material={materials.Bina1} position={[0, 0.961, -2.715]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh name="2001_Bina2_0" geometry={nodes['2001_Bina2_0'].geometry} material={materials.Bina2} position={[0, 0.503, -1.393]} rotation={[-Math.PI / 2, 0, 0]} scale={0.501} />
      <mesh name="3001_Bina3_0" geometry={nodes['3001_Bina3_0'].geometry} material={materials.Bina3} position={[0, 0.474, 0.792]} rotation={[-Math.PI / 2, 0, -Math.PI]} scale={[-0.492, 0.56, 0.492]} />
      <mesh name="4001_Bina4_0" geometry={nodes['4001_Bina4_0'].geometry} material={materials.Bina4} position={[0.15, 0.465, 2.024]} rotation={[-Math.PI / 2, 0, -Math.PI]} scale={[-0.558, 0.558, 0.558]} />
      <mesh name="Bank001_Others_0" geometry={nodes.Bank001_Others_0.geometry} material={materials.Others} position={[0.587, 0.069, -3.243]} rotation={[0, Math.PI / 2, 0]} scale={0.285} />
      <mesh name="Garbage001_Others_0" geometry={nodes.Garbage001_Others_0.geometry} material={materials.Others} position={[-0.302, -0.01, -0.431]} rotation={[-Math.PI / 2, 0, -0.53]} scale={0.687} />
      <mesh name="Lights001_Others_0" geometry={nodes.Lights001_Others_0.geometry} material={materials.Others} position={[1.018, -0.018, 2.696]} rotation={[-Math.PI / 2, 0, 0]} scale={0.015} />
      <mesh name="Plane_Road_0" geometry={nodes.Plane_Road_0.geometry} material={materials.Road} position={[0, -0.055, 0]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh name="Cube_Road_0" geometry={nodes.Cube_Road_0.geometry} material={materials.Road} position={[-0.064, -0.061, -0.069]} rotation={[-Math.PI / 2, 0, 0]} />
    </group>
  )
}

useGLTF.preload('./building/red_building-transformed.glb')
