/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 --keepmeshes --resolution 1024 --keepnames --types --output ./StationBuildingsgModel.tsx --transform ./stationbuildings.gltf 
Files: ./stationbuildings.gltf [10.01KB] > /home/cronabit/Downloads/Prem_cronabit/buildings_for_background__buildings_pack/stationbuildings-transformed.glb [211.37KB] (-2012%)
Author: Fridqeir (https://sketchfab.com/Fridqeir)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/buildings-for-background-buildings-pack-3126841fdd6b4d5aa68104bf983b4b67
Title: Buildings For Background | Buildings Pack
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Object_2: THREE.Mesh
    Object_3: THREE.Mesh
    Object_4: THREE.Mesh
    Object_5: THREE.Mesh
    Object_6: THREE.Mesh
  }
  materials: {
    Building_1: THREE.MeshStandardMaterial
    Building_3: THREE.MeshStandardMaterial
    building_2: THREE.MeshStandardMaterial
    building_4: THREE.MeshStandardMaterial
    building_5: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('./building/stationbuildings-transformed.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh name="Object_2" geometry={nodes.Object_2.geometry} material={materials.Building_1} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh name="Object_3" geometry={nodes.Object_3.geometry} material={materials.Building_3} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh name="Object_4" geometry={nodes.Object_4.geometry} material={materials.building_2} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh name="Object_5" geometry={nodes.Object_5.geometry} material={materials.building_4} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh name="Object_6" geometry={nodes.Object_6.geometry} material={materials.building_5} rotation={[-Math.PI / 2, 0, 0]} />
    </group>
  )
}

useGLTF.preload('./building/stationbuildings-transformed.glb')
