/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 --keepmeshes --resolution 1024 --keepnames --types --output ./StationBuildingModel.tsx --transform ./stationbuilding.gltf 
Files: ./stationbuilding.gltf [51.81KB] > /home/cronabit/Downloads/Prem_cronabit/game_ready_city_buildings/stationbuilding-transformed.glb [76.72KB] (-48%)
Author: ModelMaker (https://sketchfab.com/mireubay1)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/game-ready-city-buildings-12ac98aa701548adbfa463157f05f6cf
Title: Game Ready City Buildings
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Object_4: THREE.Mesh
    Object_8: THREE.Mesh
    Object_6: THREE.Mesh
    Object_10: THREE.Mesh
    Object_12: THREE.Mesh
    Object_14: THREE.Mesh
    Object_16: THREE.Mesh
    Object_18: THREE.Mesh
    Object_20: THREE.Mesh
    Object_22: THREE.Mesh
    Object_24: THREE.Mesh
    Object_26: THREE.Mesh
    Object_28: THREE.Mesh
    Object_30: THREE.Mesh
    Object_32: THREE.Mesh
    Object_34: THREE.Mesh
    Object_36: THREE.Mesh
    Object_38: THREE.Mesh
    Object_40: THREE.Mesh
    Object_42: THREE.Mesh
    Object_44: THREE.Mesh
    Object_46: THREE.Mesh
    Object_48: THREE.Mesh
    Object_50: THREE.Mesh
    Object_52: THREE.Mesh
    Object_54: THREE.Mesh
    Object_56: THREE.Mesh
  }
  materials: {
    Atlas: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('./building/stationbuilding-transformed.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh name="Object_4" geometry={nodes.Object_4.geometry} material={materials.Atlas} position={[0.02, -0.203, -0.493]} scale={0.279} />
      <mesh name="Object_8" geometry={nodes.Object_8.geometry} material={materials.Atlas} position={[0.02, 0.02, -0.493]} scale={0.279} />
      <mesh name="Object_6" geometry={nodes.Object_6.geometry} material={materials.Atlas} position={[0.02, 0.02, -0.493]} scale={0.279} />
      <mesh name="Object_10" geometry={nodes.Object_10.geometry} material={materials.Atlas} position={[-0.723, 2.615, -2.358]} />
      <mesh name="Object_12" geometry={nodes.Object_12.geometry} material={materials.Atlas} position={[-0.723, 2.375, -2.358]} />
      <mesh name="Object_14" geometry={nodes.Object_14.geometry} material={materials.Atlas} position={[-0.723, 1.529, -2.358]} />
      <mesh name="Object_16" geometry={nodes.Object_16.geometry} material={materials.Atlas} position={[-0.723, 0.64, -2.358]} />
      <mesh name="Object_18" geometry={nodes.Object_18.geometry} material={materials.Atlas} position={[-0.01, 0.031, -2.161]} scale={0.028} />
      <mesh name="Object_20" geometry={nodes.Object_20.geometry} material={materials.Atlas} position={[-0.723, -0.271, -2.358]} />
      <mesh name="Object_22" geometry={nodes.Object_22.geometry} material={materials.Atlas} position={[-0.723, -0.041, -2.358]} />
      <mesh name="Object_24" geometry={nodes.Object_24.geometry} material={materials.Atlas} position={[0.05, 2.517, -1.96]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} />
      <mesh name="Object_26" geometry={nodes.Object_26.geometry} material={materials.Atlas} position={[-1.537, 2.517, -2.775]} rotation={[Math.PI / 2, 0, 1.571]} />
      <mesh name="Object_28" geometry={nodes.Object_28.geometry} material={materials.Atlas} position={[-1.531, 0.091, -2.773]} rotation={[Math.PI / 2, 0, Math.PI / 2]} />
      <mesh name="Object_30" geometry={nodes.Object_30.geometry} material={materials.Atlas} position={[-0.197, 2.517, -2.967]} rotation={[Math.PI / 2, 0, Math.PI]} />
      <mesh name="Object_32" geometry={nodes.Object_32.geometry} material={materials.Atlas} position={[-1.435, 0.009, -2.339]} rotation={[Math.PI / 2, 0, Math.PI / 2]} />
      <mesh name="Object_34" geometry={nodes.Object_34.geometry} material={materials.Atlas} position={[-0.221, -0.128, -1.708]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh name="Object_36" geometry={nodes.Object_36.geometry} material={materials.Atlas} position={[-0.597, -0.128, -1.708]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh name="Object_38" geometry={nodes.Object_38.geometry} material={materials.Atlas} position={[-0.973, -0.128, -1.708]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh name="Object_40" geometry={nodes.Object_40.geometry} material={materials.Atlas} position={[-1.349, -0.128, -1.708]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh name="Object_42" geometry={nodes.Object_42.geometry} material={materials.Atlas} position={[-1.348, -0.128, -3.007]} rotation={[Math.PI / 2, 0, Math.PI]} />
      <mesh name="Object_44" geometry={nodes.Object_44.geometry} material={materials.Atlas} position={[-0.972, -0.128, -3.007]} rotation={[Math.PI / 2, 0, Math.PI]} />
      <mesh name="Object_46" geometry={nodes.Object_46.geometry} material={materials.Atlas} position={[-0.22, -0.128, -3.007]} rotation={[Math.PI / 2, 0, Math.PI]} />
      <mesh name="Object_48" geometry={nodes.Object_48.geometry} material={materials.Atlas} position={[-1.326, 2.517, -1.734]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh name="Object_50" geometry={nodes.Object_50.geometry} material={materials.Atlas} position={[-0.121, 0.009, -2.377]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} />
      <mesh name="Object_52" geometry={nodes.Object_52.geometry} material={materials.Atlas} position={[-0.596, -0.128, -3.007]} rotation={[Math.PI / 2, 0, Math.PI]} />
      <mesh name="Object_54" geometry={nodes.Object_54.geometry} material={materials.Atlas} position={[-0.121, 0.009, -0.791]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} />
      <mesh name="Object_56" geometry={nodes.Object_56.geometry} material={materials.Atlas} position={[-0.121, 0.009, -0.791]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} />
    </group>
  )
}

useGLTF.preload('./building/stationbuilding-transformed.glb')
