/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 --keepmeshes --resolution 1024 --keepnames --types --output ./WareHouseModel1.tsx --transform ./wareHouse.gltf 
Files: ./wareHouse.gltf [11.19KB] > C:\Users\Faizal\Downloads\WareHouse\wareHouse-transformed.glb [7.6KB] (32%)
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Plane: THREE.Mesh
    Plane001: THREE.Mesh
    Plane003: THREE.Mesh
    Plane002: THREE.Mesh
    Plane004: THREE.Mesh
    Plane005: THREE.Mesh
    Plane006: THREE.Mesh
  }
  materials: {
    ['WALL ONE']: THREE.MeshBasicMaterial
    plafond: THREE.MeshBasicMaterial
    Door: THREE.MeshBasicMaterial
  }
  animations: GLTFAction[]
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('./building/wareHouse-transformed.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh name="Plane" geometry={nodes.Plane.geometry} material={materials['WALL ONE']} position={[-20.642, 4.989, 16.426]} rotation={[Math.PI / 2, -Math.PI / 2, 0]} scale={[5.027, 1, 10.948]} />
      <mesh name="Plane001" geometry={nodes.Plane001.geometry} material={materials['WALL ONE']} position={[-20.645, 4.989, -5.99]} rotation={[Math.PI / 2, -Math.PI / 2, 0]} scale={[5.027, 1, 10.948]} />
      <mesh name="Plane003" geometry={nodes.Plane003.geometry} material={materials['WALL ONE']} position={[-0.658, 9.016, -4.472]} rotation={[0, 0, -Math.PI / 2]} />
      <mesh name="Plane002" geometry={nodes.Plane002.geometry} material={materials['WALL ONE']} position={[-31.593, 9.016, -4.469]} rotation={[0, 0, -Math.PI / 2]} />
      <mesh name="Plane004" geometry={nodes.Plane004.geometry} material={materials.plafond} position={[-2.255, 10.016, -5.209]} rotation={[1.367, -1.57, 1.367]} scale={[1.053, 1, 1]} />
      <mesh name="Plane005" geometry={nodes.Plane005.geometry} material={nodes.Plane005.material} position={[-2.253, -0.038, 11.377]} rotation={[1.367, -1.57, 1.367]} />
      <mesh name="Plane006" geometry={nodes.Plane006.geometry} material={materials.Door} position={[-0.455, 6.793, 0.684]} rotation={[Math.PI / 2, 0, -1.571]} />
    </group>
  )
}

useGLTF.preload('./building/wareHouse-transformed.glb')
