/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 train-Engine.glb --transform 
Files: train-Engine.glb [4.31MB] > /home/cronabit/Documents/train-sim-back-to-rapier_EverythingComplete/train-sim-back-to-rapier/public/train-Engine-transformed.glb [863.98KB] (80%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/train-Engine-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.object_0.geometry} material={materials.PaletteMaterial001} scale={0.01} />
      <mesh geometry={nodes.object_2.geometry} material={materials.object_2} scale={0.01} />
      <mesh geometry={nodes.object_4.geometry} material={materials.object_4} scale={0.01} />
      <mesh geometry={nodes.object_8.geometry} material={materials.object_8} scale={0.01} />
      <mesh geometry={nodes.object_9.geometry} material={materials.object_9} scale={0.01} />
      <mesh geometry={nodes.object_11.geometry} material={materials.object_11} scale={0.01} />
      <mesh geometry={nodes.object_13.geometry} material={materials.object_13} scale={0.01} />
      <mesh geometry={nodes.object_14.geometry} material={materials.object_14} scale={0.01} />
      <mesh geometry={nodes.object_17.geometry} material={materials.PaletteMaterial002} scale={0.01} />
      <mesh geometry={nodes.object_20.geometry} material={materials.object_20} scale={0.01} />
      <mesh geometry={nodes.object_21.geometry} material={materials.object_21} scale={0.01} />
      <mesh geometry={nodes.object_23.geometry} material={materials.object_23} scale={0.01} />
      <mesh geometry={nodes.object_24.geometry} material={materials.object_24} scale={0.01} />
      <mesh geometry={nodes.object_25.geometry} material={materials.object_25} scale={0.01} />
      <mesh geometry={nodes.object_26.geometry} material={materials.object_26} scale={0.01} />
      <mesh geometry={nodes.object_27.geometry} material={materials.object_27} scale={0.01} />
      <mesh geometry={nodes.object_28.geometry} material={materials.object_28} scale={0.01} />
      <mesh geometry={nodes.object_32.geometry} material={materials.object_32} scale={0.01} />
      <mesh geometry={nodes.object_33.geometry} material={materials.object_33} scale={0.01} />
      <mesh geometry={nodes.object_35.geometry} material={materials.object_35} scale={0.01} />
      <mesh geometry={nodes.object_36.geometry} material={materials.object_36} scale={0.01} />
      <mesh geometry={nodes.object_37.geometry} material={materials.object_37} scale={0.01} />
      <mesh geometry={nodes.object_38.geometry} material={materials.object_38} scale={0.01} />
      <mesh geometry={nodes.object_39.geometry} material={materials.object_39} scale={0.01} />
      <mesh geometry={nodes.object_40.geometry} material={materials.object_40} scale={0.01} />
      <mesh geometry={nodes.object_42.geometry} material={materials['object_42.001']} scale={0.01} />
      <mesh geometry={nodes.object_43.geometry} material={materials.object_43} scale={0.01} />
      <mesh geometry={nodes.object_44.geometry} material={materials.object_42} scale={0.01} />
    </group>
  )
}

useGLTF.preload('/train-Engine-transformed.glb')
