/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 --keepmeshes --resolution 1024 --keepnames --types --output ./MultipleGrass.tsx --transform ./scene.gltf 
Files: ./scene.gltf [13.82KB] > /home/cronabit/Downloads/SUNR/Grass Model/grass/scene-transformed.glb [75.92KB] (-449%)
Author: sam (https://sketchfab.com/serpent)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/grass-6d418b9a945e4bee9e9ab7de954d76d1
Title: Grass
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    group_4_grass_02_0: THREE.Mesh
    group_3_grass_02_0: THREE.Mesh
    group_1_grass_02_0: THREE.Mesh
    group_2_grass_01_0: THREE.Mesh
    group_0_grass_01_0: THREE.Mesh
  }
  materials: {
    grass_02: THREE.MeshStandardMaterial
    grass_01: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('./grass/scene-transformed.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh name="group_4_grass_02_0" geometry={nodes.group_4_grass_02_0.geometry} material={materials.grass_02} position={[-45.778, 0, 63.352]} rotation={[-Math.PI / 2, 0, 0]} scale={2.54} />
      <mesh name="group_3_grass_02_0" geometry={nodes.group_3_grass_02_0.geometry} material={materials.grass_02} position={[-3.847, 0, 103.252]} rotation={[-Math.PI / 2, 0, 0]} scale={2.54} />
      <mesh name="group_1_grass_02_0" geometry={nodes.group_1_grass_02_0.geometry} material={materials.grass_02} position={[-56.655, 0, 5.796]} rotation={[-Math.PI / 2, 0, 0]} scale={2.54} />
      <mesh name="group_2_grass_01_0" geometry={nodes.group_2_grass_01_0.geometry} material={materials.grass_01} position={[-81.75, 0, 78.886]} rotation={[-Math.PI / 2, 0, 0]} scale={2.54} />
      <mesh name="group_0_grass_01_0" geometry={nodes.group_0_grass_01_0.geometry} material={materials.grass_01} position={[0, 0, 45.319]} rotation={[-Math.PI / 2, 0, 0]} scale={2.54} />
    </group>
  )
}

useGLTF.preload('./grass/scene-transformed.glb')
