/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 --keepmeshes --resolution 1024 --keepnames --types --output ./newelectricBlend2.tsx --transform ./new2-electric.glb 
Files: ./new2-electric.glb [1.66MB] > /Users/server/Documents/Rajkot/train_sim/public/electricPole/new2-electric-transformed.glb [38.04KB] (98%)
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Plane001_1: THREE.Mesh
    Plane001_2: THREE.Mesh
  
    electric_pole_1011: THREE.Mesh
    electric_pole_1019: THREE.Mesh
    electric_pole_1033: THREE.Mesh
    electric_pole_1049: THREE.Mesh
    electric_pole_1001: THREE.Mesh
    electric_pole_1010: THREE.Mesh
    electric_pole_1012: THREE.Mesh
    electric_pole_1034: THREE.Mesh
    electric_pole_1048: THREE.Mesh
    electric_pole_1009: THREE.Mesh
    electric_pole_1020: THREE.Mesh
    electric_pole_1013: THREE.Mesh
    electric_pole_1035: THREE.Mesh
    electric_pole_1047: THREE.Mesh
    electric_pole_1008: THREE.Mesh
    electric_pole_1021: THREE.Mesh
    electric_pole_1014: THREE.Mesh
    electric_pole_1036: THREE.Mesh
    electric_pole_1046: THREE.Mesh
    electric_pole_1007: THREE.Mesh
    electric_pole_1022: THREE.Mesh
    electric_pole_1015: THREE.Mesh
    electric_pole_1037: THREE.Mesh
    electric_pole_1045: THREE.Mesh
    electric_pole_1006: THREE.Mesh
    electric_pole_1023: THREE.Mesh
    electric_pole_1016: THREE.Mesh
    electric_pole_1038: THREE.Mesh
    electric_pole_1044: THREE.Mesh
    electric_pole_1005: THREE.Mesh
    electric_pole_1024: THREE.Mesh
    electric_pole_1017: THREE.Mesh
    electric_pole_1039: THREE.Mesh
    electric_pole_1042: THREE.Mesh
    electric_pole_1004: THREE.Mesh
    electric_pole_1025: THREE.Mesh
    electric_pole_1018: THREE.Mesh
    electric_pole_1040: THREE.Mesh
    electric_pole_1041: THREE.Mesh
    electric_pole_1003: THREE.Mesh
    electric_pole_1026: THREE.Mesh
    electric_pole_1043: THREE.Mesh
    electric_pole_1050: THREE.Mesh
    electric_pole_1052: THREE.Mesh
    electric_pole_1053: THREE.Mesh
    electric_pole_1002: THREE.Mesh
    electric_pole_1054: THREE.Mesh
    electric_pole_1055: THREE.Mesh
    electric_pole_1057: THREE.Mesh
    electric_pole_1058: THREE.Mesh
    electric_pole_1051: THREE.Mesh
    electric_pole_1056: THREE.Mesh
  }
  materials: {
    PaletteMaterial001: THREE.MeshStandardMaterial
    PaletteMaterial002: THREE.MeshPhysicalMaterial
    PaletteMaterial003: THREE.MeshPhysicalMaterial
    PaletteMaterial004: THREE.MeshPhysicalMaterial
  }
  animations: GLTFAction[]
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('./electricPole/new2-electric-transformed.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group name="Plane002" position={[0.12, 5.655, 11.398]} rotation={[-1.578, 0, -Math.PI / 2]} scale={[0.39, 1, 0.319]}>
        <mesh name="Plane001_1" geometry={nodes.Plane001_1.geometry} material={materials.PaletteMaterial001} />
        <mesh name="Plane001_2" geometry={nodes.Plane001_2.geometry} material={materials.PaletteMaterial001} />
      </group>
      <group name="Plane001" position={[0.12, 5.655, -28.374]} rotation={[-1.578, 0, -Math.PI / 2]} scale={[0.39, 1, 0.319]}>
        <mesh name="Plane001_1" geometry={nodes.Plane001_1.geometry} material={materials.PaletteMaterial001} />
        <mesh name="Plane001_2" geometry={nodes.Plane001_2.geometry} material={materials.PaletteMaterial001} />
      </group>
      <mesh name="electric_pole_1011" geometry={nodes.electric_pole_1011.geometry} material={materials.PaletteMaterial002} position={[0, 0, -15.701]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh name="electric_pole_1019" geometry={nodes.electric_pole_1019.geometry} material={materials.PaletteMaterial002} position={[0, 0, -16.891]} rotation={[Math.PI / 2, 0, -3.132]} />
      <mesh name="electric_pole_1033" geometry={nodes.electric_pole_1033.geometry} material={materials.PaletteMaterial002} position={[0, 0, 6.729]} rotation={[Math.PI / 2, 0, -3.132]} />
      <mesh name="electric_pole_1049" geometry={nodes.electric_pole_1049.geometry} material={materials.PaletteMaterial002} position={[0, 0, 7.919]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh name="electric_pole_1001" geometry={nodes.electric_pole_1001.geometry} material={materials.PaletteMaterial002} position={[0, 0, -16.891]} rotation={[Math.PI / 2, 0, -3.132]} />
      <mesh name="electric_pole_1010" geometry={nodes.electric_pole_1010.geometry} material={materials.PaletteMaterial002} position={[0, 0, -15.701]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh name="electric_pole_1012" geometry={nodes.electric_pole_1012.geometry} material={materials.PaletteMaterial003} position={[0, 0, -15.977]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh name="electric_pole_1034" geometry={nodes.electric_pole_1034.geometry} material={materials.PaletteMaterial003} position={[0, 0, -2.405]} rotation={[Math.PI / 2, 0, -3.132]} />
      <mesh name="electric_pole_1048" geometry={nodes.electric_pole_1048.geometry} material={materials.PaletteMaterial003} position={[0, 0, 7.919]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh name="electric_pole_1009" geometry={nodes.electric_pole_1009.geometry} material={materials.PaletteMaterial003} position={[0, 0, -15.977]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh name="electric_pole_1020" geometry={nodes.electric_pole_1020.geometry} material={materials.PaletteMaterial003} position={[0, 0, -24.933]} rotation={[Math.PI / 2, 0, -3.132]} />
      <mesh name="electric_pole_1013" geometry={nodes.electric_pole_1013.geometry} material={materials.PaletteMaterial004} position={[0, 0, -15.977]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh name="electric_pole_1035" geometry={nodes.electric_pole_1035.geometry} material={materials.PaletteMaterial004} position={[0, 0, -2.405]} rotation={[Math.PI / 2, 0, -3.132]} />
      <mesh name="electric_pole_1047" geometry={nodes.electric_pole_1047.geometry} material={materials.PaletteMaterial004} position={[0, 0, 7.919]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh name="electric_pole_1008" geometry={nodes.electric_pole_1008.geometry} material={materials.PaletteMaterial004} position={[0, 0, -15.977]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh name="electric_pole_1021" geometry={nodes.electric_pole_1021.geometry} material={materials.PaletteMaterial004} position={[0, 0, -24.933]} rotation={[Math.PI / 2, 0, -3.132]} />
      <mesh name="electric_pole_1014" geometry={nodes.electric_pole_1014.geometry} material={materials.PaletteMaterial003} position={[0, 0, -15.977]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh name="electric_pole_1036" geometry={nodes.electric_pole_1036.geometry} material={materials.PaletteMaterial003} position={[0, 0, -2.405]} rotation={[Math.PI / 2, 0, -3.132]} />
      <mesh name="electric_pole_1046" geometry={nodes.electric_pole_1046.geometry} material={materials.PaletteMaterial003} position={[0, 0, 7.919]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh name="electric_pole_1007" geometry={nodes.electric_pole_1007.geometry} material={materials.PaletteMaterial003} position={[0, 0, -15.977]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh name="electric_pole_1022" geometry={nodes.electric_pole_1022.geometry} material={materials.PaletteMaterial003} position={[0, 0, -24.933]} rotation={[Math.PI / 2, 0, -3.132]} />
      <mesh name="electric_pole_1015" geometry={nodes.electric_pole_1015.geometry} material={materials.PaletteMaterial003} position={[0, 0, -15.977]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh name="electric_pole_1037" geometry={nodes.electric_pole_1037.geometry} material={materials.PaletteMaterial003} position={[0, 0, -2.405]} rotation={[Math.PI / 2, 0, -3.132]} />
      <mesh name="electric_pole_1045" geometry={nodes.electric_pole_1045.geometry} material={materials.PaletteMaterial003} position={[0, 0, 7.919]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh name="electric_pole_1006" geometry={nodes.electric_pole_1006.geometry} material={materials.PaletteMaterial003} position={[0, 0, -15.977]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh name="electric_pole_1023" geometry={nodes.electric_pole_1023.geometry} material={materials.PaletteMaterial003} position={[0, 0, -24.933]} rotation={[Math.PI / 2, 0, -3.132]} />
      <mesh name="electric_pole_1016" geometry={nodes.electric_pole_1016.geometry} material={materials.PaletteMaterial002} position={[0, 0, -15.977]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh name="electric_pole_1038" geometry={nodes.electric_pole_1038.geometry} material={materials.PaletteMaterial002} position={[0, 0, -2.405]} rotation={[Math.PI / 2, 0, -3.132]} />
      <mesh name="electric_pole_1044" geometry={nodes.electric_pole_1044.geometry} material={materials.PaletteMaterial002} position={[0, 0, 7.919]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh name="electric_pole_1005" geometry={nodes.electric_pole_1005.geometry} material={materials.PaletteMaterial002} position={[0, 0, -15.977]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh name="electric_pole_1024" geometry={nodes.electric_pole_1024.geometry} material={materials.PaletteMaterial002} position={[0, 0, -24.933]} rotation={[Math.PI / 2, 0, -3.132]} />
      <mesh name="electric_pole_1017" geometry={nodes.electric_pole_1017.geometry} material={materials.PaletteMaterial003} position={[0, 0, -15.977]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh name="electric_pole_1039" geometry={nodes.electric_pole_1039.geometry} material={materials.PaletteMaterial003} position={[0, 0, -2.405]} rotation={[Math.PI / 2, 0, -3.132]} />
      <mesh name="electric_pole_1042" geometry={nodes.electric_pole_1042.geometry} material={materials.PaletteMaterial003} position={[0, 0, 7.919]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh name="electric_pole_1004" geometry={nodes.electric_pole_1004.geometry} material={materials.PaletteMaterial003} position={[0, 0, -15.977]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh name="electric_pole_1025" geometry={nodes.electric_pole_1025.geometry} material={materials.PaletteMaterial003} position={[0, 0, -24.933]} rotation={[Math.PI / 2, 0, -3.132]} />
      <mesh name="electric_pole_1018" geometry={nodes.electric_pole_1018.geometry} material={materials.PaletteMaterial004} position={[0, 0, -15.977]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh name="electric_pole_1040" geometry={nodes.electric_pole_1040.geometry} material={materials.PaletteMaterial004} position={[0, 0, -2.405]} rotation={[Math.PI / 2, 0, -3.132]} />
      <mesh name="electric_pole_1041" geometry={nodes.electric_pole_1041.geometry} material={materials.PaletteMaterial004} position={[0, 0, 7.919]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh name="electric_pole_1003" geometry={nodes.electric_pole_1003.geometry} material={materials.PaletteMaterial004} position={[0, 0, -15.977]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh name="electric_pole_1026" geometry={nodes.electric_pole_1026.geometry} material={materials.PaletteMaterial004} position={[0, 0, -24.933]} rotation={[Math.PI / 2, 0, -3.132]} />
      <mesh name="electric_pole_1043" geometry={nodes.electric_pole_1043.geometry} material={materials.PaletteMaterial003} position={[0, 0, 7.919]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh name="electric_pole_1050" geometry={nodes.electric_pole_1050.geometry} material={materials.PaletteMaterial004} position={[0, 6.507, 13.581]} rotation={[-0.001, 0, 0]} scale={[1, 1, 1.382]} />
      <mesh name="electric_pole_1052" geometry={nodes.electric_pole_1052.geometry} material={materials.PaletteMaterial004} position={[0, 0, 7.918]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh name="electric_pole_1053" geometry={nodes.electric_pole_1053.geometry} material={materials.PaletteMaterial004} position={[0, 5.642, -9.361]} rotation={[Math.PI / 2, 0, 0]} scale={[1, 1, 0.445]} />
      <mesh name="electric_pole_1002" geometry={nodes.electric_pole_1002.geometry} material={materials.PaletteMaterial004} position={[0, 6.507, 1.942]} rotation={[-0.001, 0, 0]} scale={[1, 1, 1.382]} />
      <mesh name="electric_pole_1054" geometry={nodes.electric_pole_1054.geometry} material={materials.PaletteMaterial004} position={[0, 6.507, -9.461]} rotation={[-0.001, 0, 0]} scale={[1, 1, 1.382]} />
      <mesh name="electric_pole_1055" geometry={nodes.electric_pole_1055.geometry} material={materials.PaletteMaterial004} position={[0, 6.507, -15.125]} rotation={[-0.001, 0, 0]} scale={[1, 1, 1.382]} />
      <mesh name="electric_pole_1057" geometry={nodes.electric_pole_1057.geometry} material={materials.PaletteMaterial004} position={[0, 0, -31.972]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh name="electric_pole_1058" geometry={nodes.electric_pole_1058.geometry} material={materials.PaletteMaterial004} position={[0, 5.642, -15.939]} rotation={[Math.PI / 2, 0, 0]} scale={[1, 1, 0.445]} />
      <mesh name="electric_pole_1051" geometry={nodes.electric_pole_1051.geometry} material={materials.PaletteMaterial003} position={[0, 0, 7.918]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh name="electric_pole_1056" geometry={nodes.electric_pole_1056.geometry} material={materials.PaletteMaterial003} position={[0, 0, -31.972]} rotation={[Math.PI / 2, 0, 0]} />
    </group>
  )
}

useGLTF.preload('./electricPole/new2-electric-transformed.glb')
