/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 --keepmeshes --resolution 1024 --keepnames --types --output ./SquareElectricPole.tsx --transform ./SquareElectricPole.gltf 
Files: ./SquareElectricPole.gltf [17.85KB] > /home/cronabit/Desktop/SquareElectricPole/SquareElectricPole-transformed.glb [30.79KB] (-72%)
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    electric_pole_1: THREE.Mesh
    electric_pole_1001: THREE.Mesh
    electric_pole_1002: THREE.Mesh
    electric_pole_1003: THREE.Mesh
    electric_pole_1004: THREE.Mesh
    electric_pole_1005: THREE.Mesh
    electric_pole_1006: THREE.Mesh
    electric_pole_1007: THREE.Mesh
    electric_pole_1008: THREE.Mesh
    electric_pole_1009: THREE.Mesh
    electric_pole_1010: THREE.Mesh
    Plane_1: THREE.Mesh
    Plane_2: THREE.Mesh
  }
  materials: {
    PaletteMaterial001: THREE.MeshPhysicalMaterial
    PaletteMaterial002: THREE.MeshPhysicalMaterial
    PaletteMaterial003: THREE.MeshPhysicalMaterial
    PaletteMaterial004: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('./electricPole/SquareElectricPole-transformed.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh name="electric_pole_1" geometry={nodes.electric_pole_1.geometry} material={materials.PaletteMaterial001} rotation={[Math.PI / 2, 0, 0]} />
      <mesh name="electric_pole_1001" geometry={nodes.electric_pole_1001.geometry} material={materials.PaletteMaterial002} rotation={[Math.PI / 2, 0, 0]} />
      <mesh name="electric_pole_1002" geometry={nodes.electric_pole_1002.geometry} material={materials.PaletteMaterial001} rotation={[Math.PI / 2, 0, 0]} />
      <mesh name="electric_pole_1003" geometry={nodes.electric_pole_1003.geometry} material={materials.PaletteMaterial002} rotation={[Math.PI / 2, 0, 0]} />
      <mesh name="electric_pole_1004" geometry={nodes.electric_pole_1004.geometry} material={materials.PaletteMaterial002} rotation={[Math.PI / 2, 0, 0]} />
      <mesh name="electric_pole_1005" geometry={nodes.electric_pole_1005.geometry} material={materials.PaletteMaterial003} rotation={[Math.PI / 2, 0, 0]} />
      <mesh name="electric_pole_1006" geometry={nodes.electric_pole_1006.geometry} material={materials.PaletteMaterial002} rotation={[Math.PI / 2, 0, 0]} />
      <mesh name="electric_pole_1007" geometry={nodes.electric_pole_1007.geometry} material={materials.PaletteMaterial002} rotation={[Math.PI / 2, 0, 0]} />
      <mesh name="electric_pole_1008" geometry={nodes.electric_pole_1008.geometry} material={materials.PaletteMaterial001} rotation={[Math.PI / 2, 0, 0]} />
      <mesh name="electric_pole_1009" geometry={nodes.electric_pole_1009.geometry} material={materials.PaletteMaterial002} rotation={[Math.PI / 2, 0, 0]} />
      <mesh name="electric_pole_1010" geometry={nodes.electric_pole_1010.geometry} material={materials.PaletteMaterial003} rotation={[Math.PI / 2, 0, 0]} />
      <group name="Plane" position={[0.118, 5.65, 3.472]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={[0.39, 1, 0.319]}>
        <mesh name="Plane_1" geometry={nodes.Plane_1.geometry} material={materials.PaletteMaterial004} />
        <mesh name="Plane_2" geometry={nodes.Plane_2.geometry} material={materials.PaletteMaterial004} />
      </group>
    </group>
  )
}

useGLTF.preload('./electricPole/SquareElectricPole-transformed.glb')
