/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 --keepmeshes --resolution 1024 --keepnames --types --output ./SquareElectricPole3.tsx --transform ./SquareElectricPole3.gltf 
Files: ./SquareElectricPole3.gltf [36KB] > /home/cronabit/Desktop/SquareElectricPole/3c/SquareElectricPole3-transformed.glb [33.51KB] (7%)
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Plane: THREE.Mesh
    Plane_1: THREE.Mesh

    electric_pole_1033: THREE.Mesh
    electric_pole_1049: THREE.Mesh
    electric_pole_1034: THREE.Mesh
    electric_pole_1048: THREE.Mesh
    electric_pole_1035: THREE.Mesh
    electric_pole_1047: THREE.Mesh
    electric_pole_1036: THREE.Mesh
    electric_pole_1046: THREE.Mesh
    electric_pole_1037: THREE.Mesh
    electric_pole_1045: THREE.Mesh
    electric_pole_1038: THREE.Mesh
    electric_pole_1044: THREE.Mesh
    electric_pole_1039: THREE.Mesh
    electric_pole_1042: THREE.Mesh
    electric_pole_1040: THREE.Mesh
    electric_pole_1041: THREE.Mesh
    electric_pole_1043: THREE.Mesh
    electric_pole_1050: THREE.Mesh
    electric_pole_1052: THREE.Mesh
    electric_pole_1053: THREE.Mesh
    electric_pole_1002: THREE.Mesh
    electric_pole_1051: THREE.Mesh
    electric_pole_1001: THREE.Mesh
  }
  materials: {
    PaletteMaterial001: THREE.MeshStandardMaterial
    PaletteMaterial002: THREE.MeshPhysicalMaterial
    PaletteMaterial003: THREE.MeshPhysicalMaterial
    PaletteMaterial004: THREE.MeshPhysicalMaterial
  }
  animations: GLTFAction[]
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('./electricPole/SquareElectricPole3-transformed.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group name="Plane001" position={[0.12, 5.655, -11.333]} rotation={[-1.578, 0, -Math.PI / 2]} scale={[0.39, 1, 0.319]}>
        <mesh name="Plane" geometry={nodes.Plane.geometry} material={materials.PaletteMaterial001} />
        <mesh name="Plane_1" geometry={nodes.Plane_1.geometry} material={materials.PaletteMaterial001} />
      </group>
      <group name="Plane002" position={[0.12, 5.655, 11.398]} rotation={[-1.578, 0, -Math.PI / 2]} scale={[0.39, 1, 0.319]}>
        <mesh name="Plane" geometry={nodes.Plane.geometry} material={materials.PaletteMaterial001} />
        <mesh name="Plane_1" geometry={nodes.Plane_1.geometry} material={materials.PaletteMaterial001} />
      </group>
      <mesh name="electric_pole_1033" geometry={nodes.electric_pole_1033.geometry} material={materials.PaletteMaterial002} position={[0, 0, 6.729]} rotation={[Math.PI / 2, 0, -3.132]} />
      <mesh name="electric_pole_1049" geometry={nodes.electric_pole_1049.geometry} material={materials.PaletteMaterial002} position={[0, 0, 7.919]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh name="electric_pole_1034" geometry={nodes.electric_pole_1034.geometry} material={materials.PaletteMaterial003} position={[0, 0, -7.854]} rotation={[Math.PI / 2, 0, -3.132]} />
      <mesh name="electric_pole_1048" geometry={nodes.electric_pole_1048.geometry} material={materials.PaletteMaterial003} position={[0, 0, 7.919]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh name="electric_pole_1035" geometry={nodes.electric_pole_1035.geometry} material={materials.PaletteMaterial004} position={[0, 0, -7.854]} rotation={[Math.PI / 2, 0, -3.132]} />
      <mesh name="electric_pole_1047" geometry={nodes.electric_pole_1047.geometry} material={materials.PaletteMaterial004} position={[0, 0, 7.919]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh name="electric_pole_1036" geometry={nodes.electric_pole_1036.geometry} material={materials.PaletteMaterial003} position={[0, 0, -7.854]} rotation={[Math.PI / 2, 0, -3.132]} />
      <mesh name="electric_pole_1046" geometry={nodes.electric_pole_1046.geometry} material={materials.PaletteMaterial003} position={[0, 0, 7.919]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh name="electric_pole_1037" geometry={nodes.electric_pole_1037.geometry} material={materials.PaletteMaterial003} position={[0, 0, -7.854]} rotation={[Math.PI / 2, 0, -3.132]} />
      <mesh name="electric_pole_1045" geometry={nodes.electric_pole_1045.geometry} material={materials.PaletteMaterial003} position={[0, 0, 7.919]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh name="electric_pole_1038" geometry={nodes.electric_pole_1038.geometry} material={materials.PaletteMaterial002} position={[0, 0, -7.854]} rotation={[Math.PI / 2, 0, -3.132]} />
      <mesh name="electric_pole_1044" geometry={nodes.electric_pole_1044.geometry} material={materials.PaletteMaterial002} position={[0, 0, 7.919]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh name="electric_pole_1039" geometry={nodes.electric_pole_1039.geometry} material={materials.PaletteMaterial003} position={[0, 0, -7.854]} rotation={[Math.PI / 2, 0, -3.132]} />
      <mesh name="electric_pole_1042" geometry={nodes.electric_pole_1042.geometry} material={materials.PaletteMaterial003} position={[0, 0, 7.919]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh name="electric_pole_1040" geometry={nodes.electric_pole_1040.geometry} material={materials.PaletteMaterial004} position={[0, 0, -7.854]} rotation={[Math.PI / 2, 0, -3.132]} />
      <mesh name="electric_pole_1041" geometry={nodes.electric_pole_1041.geometry} material={materials.PaletteMaterial004} position={[0, 0, 7.919]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh name="electric_pole_1043" geometry={nodes.electric_pole_1043.geometry} material={materials.PaletteMaterial003} position={[0, 0, 7.919]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh name="electric_pole_1050" geometry={nodes.electric_pole_1050.geometry} material={materials.PaletteMaterial004} position={[0, 6.507, 13.581]} rotation={[-0.001, 0, 0]} scale={[1, 1, 1.382]} />
      <mesh name="electric_pole_1052" geometry={nodes.electric_pole_1052.geometry} material={materials.PaletteMaterial004} position={[0, 0, 7.918]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh name="electric_pole_1053" geometry={nodes.electric_pole_1053.geometry} material={materials.PaletteMaterial004} position={[0, 0, -14.81]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh name="electric_pole_1002" geometry={nodes.electric_pole_1002.geometry} material={materials.PaletteMaterial004} position={[0, 6.507, 1.942]} rotation={[-0.001, 0, 0]} scale={[1, 1, 1.382]} />
      <mesh name="electric_pole_1051" geometry={nodes.electric_pole_1051.geometry} material={materials.PaletteMaterial003} position={[0, 0, 7.918]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh name="electric_pole_1001" geometry={nodes.electric_pole_1001.geometry} material={materials.PaletteMaterial003} position={[0, 0, -14.848]} rotation={[Math.PI / 2, 0, 0]} />
    </group>
  )
}

useGLTF.preload('./electricPole/SquareElectricPole3-transformed.glb')
