/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 --keepmeshes --resolution 1024 --keepnames --types --output ./SquareElectric2.tsx --transform ./SquareElectric2.gltf 
Files: ./SquareElectric2.gltf [35.76KB] > /home/cronabit/Desktop/SquareElectricPole/2/SquareElectric2-transformed.glb [33.38KB] (7%)
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Plane_1: THREE.Mesh
    Plane_2: THREE.Mesh
    electric_pole_1011: THREE.Mesh
    electric_pole_1013: THREE.Mesh
    electric_pole_1023: THREE.Mesh
    electric_pole_1012: THREE.Mesh
    electric_pole_1014: THREE.Mesh
    electric_pole_1032: THREE.Mesh
    electric_pole_1015: THREE.Mesh
    electric_pole_1031: THREE.Mesh
    electric_pole_1016: THREE.Mesh
    electric_pole_1030: THREE.Mesh
    electric_pole_1017: THREE.Mesh
    electric_pole_1029: THREE.Mesh
    electric_pole_1018: THREE.Mesh
    electric_pole_1028: THREE.Mesh
    electric_pole_1019: THREE.Mesh
    electric_pole_1027: THREE.Mesh
    electric_pole_1020: THREE.Mesh
    electric_pole_1026: THREE.Mesh
    electric_pole_1021: THREE.Mesh
    electric_pole_1025: THREE.Mesh
    electric_pole_1022: THREE.Mesh
    electric_pole_1024: THREE.Mesh
  }
  materials: {
    PaletteMaterial001: THREE.MeshStandardMaterial
    PaletteMaterial002: THREE.MeshPhysicalMaterial
    PaletteMaterial003: THREE.MeshPhysicalMaterial
    PaletteMaterial004: THREE.MeshPhysicalMaterial
  }
  animations: GLTFAction[]
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('./electricPole/SquareElectric2-transformed.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group name="Plane" position={[0.114, 5.673, 5.094]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={[0.39, 1, 0.319]}>
        <mesh name="Plane_1" geometry={nodes.Plane_1.geometry} material={materials.PaletteMaterial001} />
        <mesh name="Plane_2" geometry={nodes.Plane_2.geometry} material={materials.PaletteMaterial001} />
      </group>
      <group name="Plane001" position={[0.114, 5.673, -5.282]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={[0.39, 1, 0.319]}>
        <mesh name="Plane_1" geometry={nodes.Plane_1.geometry} material={materials.PaletteMaterial001} />
        <mesh name="Plane_2" geometry={nodes.Plane_2.geometry} material={materials.PaletteMaterial001} />
      </group>
      <mesh name="electric_pole_1011" geometry={nodes.electric_pole_1011.geometry} material={materials.PaletteMaterial002} position={[0, 0, 1.635]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh name="electric_pole_1013" geometry={nodes.electric_pole_1013.geometry} material={materials.PaletteMaterial002} position={[0, 6.408, 6.904]} rotation={[-0.001, 0, 0]} scale={[1, 1, 1.254]} />
      <mesh name="electric_pole_1023" geometry={nodes.electric_pole_1023.geometry} material={materials.PaletteMaterial002} position={[0, 4.637, -8.573]} rotation={[Math.PI / 2, 0, 0]} scale={[0.959, 0.959, 0.517]} />
      <mesh name="electric_pole_1012" geometry={nodes.electric_pole_1012.geometry} material={materials.PaletteMaterial003} position={[0, 0, 1.635]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh name="electric_pole_1014" geometry={nodes.electric_pole_1014.geometry} material={materials.PaletteMaterial004} position={[0, 0, 1.635]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh name="electric_pole_1032" geometry={nodes.electric_pole_1032.geometry} material={materials.PaletteMaterial004} position={[0, 0, 0.446]} rotation={[Math.PI / 2, 0, -3.132]} />
      <mesh name="electric_pole_1015" geometry={nodes.electric_pole_1015.geometry} material={materials.PaletteMaterial003} position={[0, 0, 1.635]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh name="electric_pole_1031" geometry={nodes.electric_pole_1031.geometry} material={materials.PaletteMaterial003} position={[0, 0, -1.741]} rotation={[Math.PI / 2, 0, -3.132]} />
      <mesh name="electric_pole_1016" geometry={nodes.electric_pole_1016.geometry} material={materials.PaletteMaterial002} position={[0, 0, 1.635]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh name="electric_pole_1030" geometry={nodes.electric_pole_1030.geometry} material={materials.PaletteMaterial002} position={[0, 0, -1.741]} rotation={[Math.PI / 2, 0, -3.132]} />
      <mesh name="electric_pole_1017" geometry={nodes.electric_pole_1017.geometry} material={materials.PaletteMaterial003} position={[0, 0, 1.635]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh name="electric_pole_1029" geometry={nodes.electric_pole_1029.geometry} material={materials.PaletteMaterial003} position={[0, 0, -1.741]} rotation={[Math.PI / 2, 0, -3.132]} />
      <mesh name="electric_pole_1018" geometry={nodes.electric_pole_1018.geometry} material={materials.PaletteMaterial003} position={[0, 0, 1.635]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh name="electric_pole_1028" geometry={nodes.electric_pole_1028.geometry} material={materials.PaletteMaterial003} position={[0, 0, -1.741]} rotation={[Math.PI / 2, 0, -3.132]} />
      <mesh name="electric_pole_1019" geometry={nodes.electric_pole_1019.geometry} material={materials.PaletteMaterial004} position={[0, 0, 1.635]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh name="electric_pole_1027" geometry={nodes.electric_pole_1027.geometry} material={materials.PaletteMaterial004} position={[0, 0, -1.741]} rotation={[Math.PI / 2, 0, -3.132]} />
      <mesh name="electric_pole_1020" geometry={nodes.electric_pole_1020.geometry} material={materials.PaletteMaterial003} position={[0, 0, 1.635]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh name="electric_pole_1026" geometry={nodes.electric_pole_1026.geometry} material={materials.PaletteMaterial003} position={[0, 0, -1.741]} rotation={[Math.PI / 2, 0, -3.132]} />
      <mesh name="electric_pole_1021" geometry={nodes.electric_pole_1021.geometry} material={materials.PaletteMaterial003} position={[0, 0, 1.635]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh name="electric_pole_1025" geometry={nodes.electric_pole_1025.geometry} material={materials.PaletteMaterial003} position={[0, 0, -1.741]} rotation={[Math.PI / 2, 0, -3.132]} />
      <mesh name="electric_pole_1022" geometry={nodes.electric_pole_1022.geometry} material={materials.PaletteMaterial002} position={[0, 0, 1.635]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh name="electric_pole_1024" geometry={nodes.electric_pole_1024.geometry} material={materials.PaletteMaterial002} position={[0, 0, -1.741]} rotation={[Math.PI / 2, 0, -3.132]} />
    </group>
  )
}

useGLTF.preload('./electricPole/SquareElectric2-transformed.glb')
