/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 --keepmeshes --resolution 1024 --keepnames --types --output ./StationPoleModel.tsx --transform ./stationPole1.gltf 
Files: ./stationPole1.gltf [18.64KB] > C:\Users\Faizal\Downloads\New Folder\stationPole1-transformed.glb [31.32KB] (-68%)
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Plane: THREE.Mesh
    electric_pole_1011: THREE.Mesh
    electric_pole_1013: THREE.Mesh
    electric_pole_1023: THREE.Mesh
    electric_pole_1012: THREE.Mesh
    electric_pole_1014: THREE.Mesh
    electric_pole_1032: THREE.Mesh
    electric_pole_1015: THREE.Mesh
    electric_pole_1016: THREE.Mesh
    electric_pole_1017: THREE.Mesh
    electric_pole_1018: THREE.Mesh
    electric_pole_1019: THREE.Mesh
    electric_pole_1020: THREE.Mesh
    electric_pole_1026: THREE.Mesh
    electric_pole_1021: THREE.Mesh
    electric_pole_1022: THREE.Mesh
  }
  materials: {
    PaletteMaterial001: THREE.MeshStandardMaterial
    PaletteMaterial002: THREE.MeshPhysicalMaterial
    PaletteMaterial003: THREE.MeshPhysicalMaterial
    PaletteMaterial004: THREE.MeshPhysicalMaterial
  }
  animations: GLTFAction[]
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('./electricPole/stationPole1-transformed.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh name="Plane" geometry={nodes.Plane.geometry} material={materials.PaletteMaterial001} position={[0.115, 5.673, -4.466]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={[0.39, 1, 0.319]} />
      <mesh name="electric_pole_1011" geometry={nodes.electric_pole_1011.geometry} material={materials.PaletteMaterial002} position={[0.001, 0, -7.925]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh name="electric_pole_1013" geometry={nodes.electric_pole_1013.geometry} material={materials.PaletteMaterial002} position={[-0.001, 6.505, 7.683]} rotation={[-0.001, 0, 0]} scale={[1, 1, 1.254]} />
      <mesh name="electric_pole_1023" geometry={nodes.electric_pole_1023.geometry} material={materials.PaletteMaterial002} position={[-0.031, 4.733, 2.52]} rotation={[Math.PI / 2, 0, 0]} scale={[0.959, 0.959, 0.517]} />
      <mesh name="electric_pole_1012" geometry={nodes.electric_pole_1012.geometry} material={materials.PaletteMaterial003} position={[0.001, 0, -7.925]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh name="electric_pole_1014" geometry={nodes.electric_pole_1014.geometry} material={materials.PaletteMaterial004} position={[0, 0, 2.413]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh name="electric_pole_1032" geometry={nodes.electric_pole_1032.geometry} material={materials.PaletteMaterial004} position={[0, 0, 1.223]} rotation={[Math.PI / 2, 0, -3.132]} />
      <mesh name="electric_pole_1015" geometry={nodes.electric_pole_1015.geometry} material={materials.PaletteMaterial003} position={[0, 0, 2.413]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh name="electric_pole_1016" geometry={nodes.electric_pole_1016.geometry} material={materials.PaletteMaterial002} position={[0, 0, 2.413]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh name="electric_pole_1017" geometry={nodes.electric_pole_1017.geometry} material={materials.PaletteMaterial003} position={[0, 0, 2.413]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh name="electric_pole_1018" geometry={nodes.electric_pole_1018.geometry} material={materials.PaletteMaterial003} position={[0, 0, 2.413]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh name="electric_pole_1019" geometry={nodes.electric_pole_1019.geometry} material={materials.PaletteMaterial004} position={[0, 0, 2.413]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh name="electric_pole_1020" geometry={nodes.electric_pole_1020.geometry} material={materials.PaletteMaterial003} position={[0.001, 0, -7.925]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh name="electric_pole_1026" geometry={nodes.electric_pole_1026.geometry} material={materials.PaletteMaterial003} position={[-0.031, 0.096, 9.352]} rotation={[Math.PI / 2, 0, -3.132]} />
      <mesh name="electric_pole_1021" geometry={nodes.electric_pole_1021.geometry} material={materials.PaletteMaterial003} position={[0, 0, 2.413]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh name="electric_pole_1022" geometry={nodes.electric_pole_1022.geometry} material={materials.PaletteMaterial002} position={[0, 0, 2.413]} rotation={[Math.PI / 2, 0, 0]} />
    </group>
  )
}

useGLTF.preload('./electricPole/stationPole1-transformed.glb')
