/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 --keepmeshes --resolution 1024 --keepnames --types --output ./SignalHomeFourLightLunarRight.tsx --transform ./Signal-home-four-light-lunar-right.gltf 
Files: ./Signal-home-four-light-lunar-right.gltf [35.6KB] > /home/cronabit/Desktop/S3 Opposite/Signal-home-four-light-lunar-right-transformed.glb [43.3KB] (-22%)
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    BEG_Light_4001: THREE.Mesh
    BEG_Light_9001: THREE.Mesh
    Octagon_with_7001: THREE.Mesh
    BEG_Light_1003: THREE.Mesh
    BEG_Light_2004: THREE.Mesh
    BEG_Light_3003: THREE.Mesh
    SLLT002: THREE.Mesh
    WhiteLight01: THREE.Mesh
    WhiteLight06: THREE.Mesh
    WhiteLight07: THREE.Mesh
    WhiteLight08: THREE.Mesh
    WhiteLight09: THREE.Mesh
    white_light_001: THREE.Mesh
    white_light_002: THREE.Mesh
    white_light_003: THREE.Mesh
    white_light_004: THREE.Mesh
    SS_3001: THREE.Mesh
    SS_2001: THREE.Mesh
    SS_1001: THREE.Mesh
    Lights_1001: THREE.Mesh
    hs_18001: THREE.Mesh
    BEG_Light_2001: THREE.Mesh
    BEG_Light_4002: THREE.Mesh
    Stairs001: THREE.Mesh
    Mesh326: THREE.Mesh
    Mesh326_1: THREE.Mesh
    nut_4001: THREE.Mesh
    nut_3001: THREE.Mesh
    nut_2001: THREE.Mesh
    nut_1001: THREE.Mesh
    board001: THREE.Mesh
    FS_3001: THREE.Mesh
    cube002: THREE.Mesh
    board018: THREE.Mesh
    FS_2002: THREE.Mesh
    Light_1009: THREE.Mesh
    FS_1009: THREE.Mesh
    Cube001: THREE.Mesh
  }
  materials: {
    ['Material.034']: THREE.MeshStandardMaterial
    ['Material.118']: THREE.MeshBasicMaterial
    ['Material.165']: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('./Signal-home-four-light-lunar-right-transformed.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh name="BEG_Light_4001" geometry={nodes.BEG_Light_4001.geometry} material={materials['Material.034']} position={[0.225, 6.167, -0.008]} />
      <mesh name="BEG_Light_9001" geometry={nodes.BEG_Light_9001.geometry} material={materials['Material.034']} position={[0.227, 6.405, 0.154]} />
      <mesh name="Octagon_with_7001" geometry={nodes.Octagon_with_7001.geometry} material={materials['Material.034']} position={[-0.119, 6.216, -0.009]} />
      <mesh name="BEG_Light_1003" geometry={nodes.BEG_Light_1003.geometry} material={materials['Material.034']} position={[0.227, 6.953, 0.712]} />
      <mesh name="BEG_Light_2004" geometry={nodes.BEG_Light_2004.geometry} material={materials['Material.034']} position={[0.225, 6.781, 0.541]} />
      <mesh name="BEG_Light_3003" geometry={nodes.BEG_Light_3003.geometry} material={materials['Material.034']} position={[0.228, 6.613, 0.372]} />
      <mesh name="SLLT002" geometry={nodes.SLLT002.geometry} material={materials['Material.034']} position={[0.069, 6.727, 0.501]} />
      <mesh name="WhiteLight01" geometry={nodes.WhiteLight01.geometry} material={materials['Material.118']} position={[0.17, 6.215, -0.01]} rotation={[-0.001, 0.01, 1.551]} scale={[0.235, 0.11, 0.235]} />
      <mesh name="WhiteLight06" geometry={nodes.WhiteLight06.geometry} material={materials['Material.118']} position={[0.17, 6.389, 0.152]} rotation={[-0.001, 0.01, 1.551]} scale={[0.235, 0.11, 0.235]} />
      <mesh name="WhiteLight07" geometry={nodes.WhiteLight07.geometry} material={materials['Material.118']} position={[0.17, 6.598, 0.37]} rotation={[-0.001, 0.01, 1.551]} scale={[0.235, 0.11, 0.235]} />
      <mesh name="WhiteLight08" geometry={nodes.WhiteLight08.geometry} material={materials['Material.118']} position={[0.17, 6.766, 0.539]} rotation={[-0.001, 0.01, 1.551]} scale={[0.235, 0.11, 0.235]} />
      <mesh name="WhiteLight09" geometry={nodes.WhiteLight09.geometry} material={materials['Material.118']} position={[0.17, 6.934, 0.709]} rotation={[-0.001, 0.01, 1.551]} scale={[0.235, 0.11, 0.235]} />
      <mesh name="YellowLight01" geometry={nodes.white_light_001.geometry} material={materials['Material.118']} position={[0.552, 5.772, 0.013]} rotation={[-0.001, 0.01, 1.551]} scale={[0.215, 0.1, 0.215]} />
      <mesh name="RedLight" geometry={nodes.white_light_002.geometry} material={materials['Material.118']} position={[0.552, 4.851, 0.022]} rotation={[-0.001, 0.01, 1.551]} scale={[0.215, 0.1, 0.215]} />
      <mesh name="YellowLight" geometry={nodes.white_light_003.geometry} material={materials['Material.118']} position={[0.552, 5.17, 0.022]} rotation={[-0.001, 0.01, 1.551]} scale={[0.215, 0.1, 0.215]} />
      <mesh name="GreenLight" geometry={nodes.white_light_004.geometry} material={materials['Material.118']} position={[0.552, 5.487, 0.019]} rotation={[-0.001, 0.01, 1.551]} scale={[0.215, 0.1, 0.215]} />
      <mesh name="SS_3001" geometry={nodes.SS_3001.geometry} material={materials['Material.034']} position={[0.298, 4.207, 0.03]} />
      <mesh name="SS_2001" geometry={nodes.SS_2001.geometry} material={materials['Material.034']} position={[0.461, 4.207, 0.178]} />
      <mesh name="SS_1001" geometry={nodes.SS_1001.geometry} material={materials['Material.034']} position={[0.461, 4.207, -0.104]} />
      <mesh name="Lights_1001" geometry={nodes.Lights_1001.geometry} material={materials['Material.034']} position={[0.47, 4.591, 0.068]} />
      <mesh name="hs_18001" geometry={nodes.hs_18001.geometry} material={materials['Material.034']} position={[0.55, 4.284, 0.036]} />
      <mesh name="BEG_Light_2001" geometry={nodes.BEG_Light_2001.geometry} material={materials['Material.034']} position={[0.599, 5.184, -0.717]} scale={0.915} />
      <mesh name="BEG_Light_4002" geometry={nodes.BEG_Light_4002.geometry} material={materials['Material.034']} position={[0.407, 1.216, -1.395]} />
      <mesh name="Stairs001" geometry={nodes.Stairs001.geometry} material={materials['Material.034']} position={[0, 1.05, 0.212]} />
      <group name="pole001" position={[0.007, 3.268, 0.026]} scale={[1, 1.476, 1]}>
        <mesh name="Mesh326" geometry={nodes.Mesh326.geometry} material={materials['Material.034']} />
        <mesh name="Mesh326_1" geometry={nodes.Mesh326_1.geometry} material={materials['Material.165']} />
      </group>
      <mesh name="nut_4001" geometry={nodes.nut_4001.geometry} material={materials['Material.034']} position={[0, 0.079, 0.224]} />
      <mesh name="nut_3001" geometry={nodes.nut_3001.geometry} material={materials['Material.034']} position={[0, 0.079, 0.224]} />
      <mesh name="nut_2001" geometry={nodes.nut_2001.geometry} material={materials['Material.034']} position={[0, 0.079, 0.224]} />
      <mesh name="nut_1001" geometry={nodes.nut_1001.geometry} material={materials['Material.034']} position={[0, 0.079, 0.224]} />
      <mesh name="board001" geometry={nodes.board001.geometry} material={materials['Material.034']} position={[0, 0.924, 0.22]} />
      <mesh name="FS_3001" geometry={nodes.FS_3001.geometry} material={materials['Material.034']} position={[0, 0.924, 0.22]} />
      <mesh name="cube002" geometry={nodes.cube002.geometry} material={materials['Material.034']} position={[0, 0.04, 0.224]} />
      <mesh name="board018" geometry={nodes.board018.geometry} material={materials['Material.034']} position={[0, 0.04, 0.224]} />
      <mesh name="FS_2002" geometry={nodes.FS_2002.geometry} material={materials['Material.034']} position={[0, 0.369, 0.224]} />
      <mesh name="Light_1009" geometry={nodes.Light_1009.geometry} material={materials['Material.034']} position={[0, 0.074, 0.224]} />
      <mesh name="FS_1009" geometry={nodes.FS_1009.geometry} material={materials['Material.034']} position={[0, 0.074, 0.224]} />
      <mesh name="Cube001" geometry={nodes.Cube001.geometry} material={nodes.Cube001.material} position={[0, 0.332, 0.031]} scale={[0.447, 0.34, 0.417]} />
    </group>
  )
}

useGLTF.preload('./Signal-home-four-light-lunar-right-transformed.glb')
