/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 --keepmeshes --resolution 1024 --keepnames --types --output ./SignalCounter.tsx --transform ./signal-counter.gltf 
Files: ./signal-counter.gltf [6.86KB] > /home/cronabit/Downloads/SignalDigital/signal-counter-transformed.glb [8.96KB] (-31%)
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Mesh185: THREE.Mesh
    Mesh185_1: THREE.Mesh
    Stand: THREE.Mesh
    StairdAndCube: THREE.Mesh
  }
  materials: {
    Gray: THREE.MeshPhysicalMaterial
    Black: THREE.MeshPhysicalMaterial
    ['Material.027']: THREE.MeshPhysicalMaterial
  }
  animations: GLTFAction[]
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('./signal-counter-transformed.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group name="Pole" position={[0.019, 3.401, -0.017]} scale={[1, 1.596, 1]}>
        <mesh name="Mesh185" geometry={nodes.Mesh185.geometry} material={materials.Gray} />
        <mesh name="Mesh185_1" geometry={nodes.Mesh185_1.geometry} material={materials.Black} />
      </group>
      <mesh name="Stand" geometry={nodes.Stand.geometry} material={materials['Material.027']} position={[0.017, 0.297, -0.019]} scale={[1.08, 1, 1.109]} />
      <mesh name="StairdAndCube" geometry={nodes.StairdAndCube.geometry} material={materials.Black} position={[0.27, 6.619, -0.016]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={0.25} />
    </group>
  )
}

useGLTF.preload('./signal-counter-transformed.glb')
