/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 --keepmeshes --resolution 1024 --keepnames --types --output ./SignalMainLunarRightModel.tsx --transform ./signalMainLunarRight.gltf 
Files: ./signalMainLunarRight.gltf [49.62KB] > C:\Users\Faizal\Downloads\s5\signalMainLunarRight-transformed.glb [42.05KB] (15%)
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Stairs009: THREE.Mesh
    st_1010: THREE.Mesh
    SS_3010: THREE.Mesh
    SS_2010: THREE.Mesh
    SS_1010: THREE.Mesh
    Mesh239: THREE.Mesh
    Mesh239_1: THREE.Mesh
    Octagon_with_7007: THREE.Mesh
    nut_4009: THREE.Mesh
    nut_3009: THREE.Mesh
    nut_2009: THREE.Mesh
    nut_1009: THREE.Mesh
    hs_18009: THREE.Mesh
    FS_3009: THREE.Mesh
    FS_2009: THREE.Mesh
    FS_1008: THREE.Mesh
    BEG_Light_1013: THREE.Mesh
    red_light_059: THREE.Mesh
    green_light_063: THREE.Mesh
    white_light_072: THREE.Mesh
    white_light_077: THREE.Mesh
    white_light_020: THREE.Mesh
    white_light_019: THREE.Mesh
    white_light_021: THREE.Mesh
    Cube: THREE.Mesh
    SLLT001: THREE.Mesh
    BEG_Light_4006: THREE.Mesh
    BEG_Light_9005: THREE.Mesh
    board016: THREE.Mesh
    board015: THREE.Mesh
    cube009: THREE.Mesh
    hs_17009: THREE.Mesh
    hs_16009: THREE.Mesh
    Light_1008: THREE.Mesh
    BEG_Light_1004: THREE.Mesh
    BEG_Light_2002: THREE.Mesh
    BEG_Light_3004: THREE.Mesh
  }
  materials: {
    ['Material.146']: THREE.MeshStandardMaterial
    ['Material.149']: THREE.MeshStandardMaterial
    ['Material.134']: THREE.MeshBasicMaterial
    Material: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('./signalMainLunarRight-transformed.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh name="Stairs009" geometry={nodes.Stairs009.geometry} material={materials['Material.146']} position={[-0.709, 3.646, 0.04]} />
      <mesh name="st_1010" geometry={nodes.st_1010.geometry} material={materials['Material.146']} position={[0.482, 4.125, 0.039]} />
      <mesh name="SS_3010" geometry={nodes.SS_3010.geometry} material={materials['Material.146']} position={[0.323, 4.213, 0.039]} />
      <mesh name="SS_2010" geometry={nodes.SS_2010.geometry} material={materials['Material.146']} position={[0.486, 4.213, 0.187]} />
      <mesh name="SS_1010" geometry={nodes.SS_1010.geometry} material={materials['Material.146']} position={[0.486, 4.213, -0.095]} />
      <group name="pole009" position={[0.007, 3.011, 0.023]} scale={[1, 1.407, 1]}>
        <mesh name="Mesh239" geometry={nodes.Mesh239.geometry} material={materials['Material.149']} />
        <mesh name="Mesh239_1" geometry={nodes.Mesh239_1.geometry} material={materials['Material.146']} />
      </group>
      <mesh name="Octagon_with_7007" geometry={nodes.Octagon_with_7007.geometry} material={materials['Material.146']} position={[-0.119, 5.865, 0.032]} />
      <mesh name="nut_4009" geometry={nodes.nut_4009.geometry} material={materials['Material.146']} position={[-0.103, 0.649, -0.063]} />
      <mesh name="nut_3009" geometry={nodes.nut_3009.geometry} material={materials['Material.146']} position={[-0.103, 0.649, 0.143]} />
      <mesh name="nut_2009" geometry={nodes.nut_2009.geometry} material={materials['Material.146']} position={[0.103, 0.649, 0.143]} />
      <mesh name="nut_1009" geometry={nodes.nut_1009.geometry} material={materials['Material.146']} position={[0.103, 0.649, -0.063]} />
      <mesh name="hs_18009" geometry={nodes.hs_18009.geometry} material={materials['Material.146']} position={[0.636, 3.999, 0.043]} />
      <mesh name="FS_3009" geometry={nodes.FS_3009.geometry} material={materials['Material.146']} position={[-0.009, 3.936, 0.038]} />
      <mesh name="FS_2009" geometry={nodes.FS_2009.geometry} material={materials['Material.146']} position={[0, 2.26, 0.04]} />
      <mesh name="FS_1008" geometry={nodes.FS_1008.geometry} material={materials['Material.146']} position={[0.042, 1.615, 0.04]} />
      <mesh name="BEG_Light_1013" geometry={nodes.BEG_Light_1013.geometry} material={materials['Material.146']} position={[0.514, 4.763, 0.047]} rotation={[Math.PI / 2, 0, 0]} scale={0.231} />
      <mesh name="YellowLight" geometry={nodes.red_light_059.geometry} material={materials['Material.134']} position={[0.546, 5.195, 0.028]} rotation={[-0.001, 0.01, 1.551]} scale={[0.238, 0.111, 0.238]} />
      <mesh name="RedLight" geometry={nodes.green_light_063.geometry} material={materials['Material.134']} position={[0.546, 4.866, 0.038]} rotation={[-0.001, 0.01, 1.551]} scale={[0.238, 0.111, 0.238]} />
      <mesh name="WhiteLight01" geometry={nodes.white_light_072.geometry} material={materials['Material.134']} position={[0.17, 6.038, -0.111]} rotation={[-0.001, 0.01, 1.551]} scale={[0.235, 0.11, 0.235]} />
      <mesh name="WhiteLight02" geometry={nodes.white_light_077.geometry} material={materials['Material.134']} position={[0.17, 5.864, 0.031]} rotation={[-0.001, 0.01, 1.551]} scale={[0.235, 0.11, 0.235]} />
      <mesh name="WhiteLight03" geometry={nodes.white_light_020.geometry} material={materials['Material.134']} position={[0.172, 6.433, -0.551]} rotation={[-0.001, 0.01, 1.551]} scale={[0.235, 0.11, 0.235]} />
      <mesh name="WhiteLight04" geometry={nodes.white_light_019.geometry} material={materials['Material.134']} position={[0.172, 6.6, -0.725]} rotation={[-0.001, 0.01, 1.551]} scale={[0.235, 0.11, 0.235]} />
      <mesh name="WhiteLight05" geometry={nodes.white_light_021.geometry} material={materials['Material.134']} position={[0.172, 6.264, -0.381]} rotation={[-0.001, 0.01, 1.551]} scale={[0.235, 0.11, 0.235]} />
      <mesh name="Cube" geometry={nodes.Cube.geometry} material={materials.Material} position={[0, 0.289, 0.033]} scale={[0.366, 0.3, 0.356]} />
      <mesh name="SLLT001" geometry={nodes.SLLT001.geometry} material={materials['Material.146']} position={[0.071, 6.408, -0.495]} />
      <mesh name="BEG_Light_4006" geometry={nodes.BEG_Light_4006.geometry} material={materials['Material.146']} position={[0.225, 5.882, 0.034]} />
      <mesh name="BEG_Light_9005" geometry={nodes.BEG_Light_9005.geometry} material={materials['Material.146']} position={[0.227, 6.054, -0.109]} />
      <mesh name="board016" geometry={nodes.board016.geometry} material={materials['Material.146']} position={[0.314, 4.033, 0.036]} />
      <mesh name="board015" geometry={nodes.board015.geometry} material={materials['Material.146']} position={[0.329, 2.321, 0.04]} />
      <mesh name="cube009" geometry={nodes.cube009.geometry} material={materials['Material.146']} position={[0.408, 2.63, 0.04]} />
      <mesh name="hs_17009" geometry={nodes.hs_17009.geometry} material={materials['Material.146']} position={[0.547, 2.982, 0.04]} />
      <mesh name="hs_16009" geometry={nodes.hs_16009.geometry} material={materials['Material.146']} position={[0.509, 2.364, 0.04]} />
      <mesh name="Light_1008" geometry={nodes.Light_1008.geometry} material={materials['Material.146']} position={[0.166, 1.761, 0.041]} />
      <mesh name="BEG_Light_1004" geometry={nodes.BEG_Light_1004.geometry} material={materials['Material.146']} position={[0.23, 6.618, -0.722]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh name="BEG_Light_2002" geometry={nodes.BEG_Light_2002.geometry} material={materials['Material.146']} position={[0.228, 6.448, -0.549]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh name="BEG_Light_3004" geometry={nodes.BEG_Light_3004.geometry} material={materials['Material.146']} position={[0.231, 6.279, -0.38]} rotation={[Math.PI / 2, 0, 0]} />
    </group>
  )
}

useGLTF.preload('./signalMainLunarRight-transformed.glb')
