/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 --keepmeshes --resolution 1024 --keepnames --types --output ./SignalFourLight.tsx --transform ./signalFourLight.gltf 
Files: ./signalFourLight.gltf [37.91KB] > /home/cronabit/Desktop/SignalFourLight/signalFourLight-transformed.glb [33.82KB] (11%)
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    white_light_053: THREE.Mesh
    white_light_054: THREE.Mesh
    white_light_057: THREE.Mesh
    white_light_058: THREE.Mesh
    Stairs011: THREE.Mesh
    st_1011: THREE.Mesh
    SS_3011: THREE.Mesh
    SS_2011: THREE.Mesh
    SS_1011: THREE.Mesh
    Mesh194: THREE.Mesh
    Mesh194_1: THREE.Mesh
    pipe_3003: THREE.Mesh
    pipe_2003: THREE.Mesh
    pipe_1003: THREE.Mesh
    nut_4011: THREE.Mesh
    nut_3011: THREE.Mesh
    nut_2011: THREE.Mesh
    nut_1011: THREE.Mesh
    Lights_1006: THREE.Mesh
    hs_18010: THREE.Mesh
    hs_17010: THREE.Mesh
    hs_16010: THREE.Mesh
    FS_3011: THREE.Mesh
    FS_2010: THREE.Mesh
    Cube010: THREE.Mesh
    cube010: THREE.Mesh
    board017: THREE.Mesh
    BEG_Light_2016: THREE.Mesh
    BEG_Light_4007: THREE.Mesh
  }
  materials: {
    ['Material.143']: THREE.MeshBasicMaterial
    ['Material.154']: THREE.MeshStandardMaterial
    ['Material.155']: THREE.MeshStandardMaterial
    ['Material.158']: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('./signalFourLight-transformed.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh name="YellowLight01" geometry={nodes.white_light_053.geometry} material={materials['Material.143']} position={[0.145, 5.787, -0.008]} rotation={[-0.001, 0.01, 1.551]} scale={[0.215, 0.1, 0.215]} />
      <mesh name="RedLight" geometry={nodes.white_light_054.geometry} material={materials['Material.143']} position={[0.145, 4.866, 0.001]} rotation={[-0.001, 0.01, 1.551]} scale={[0.215, 0.1, 0.215]} />
      <mesh name="YellowLight" geometry={nodes.white_light_057.geometry} material={materials['Material.143']} position={[0.145, 5.185, 0.001]} rotation={[-0.001, 0.01, 1.551]} scale={[0.215, 0.1, 0.215]} />
      <mesh name="GreenLight" geometry={nodes.white_light_058.geometry} material={materials['Material.143']} position={[0.145, 5.502, -0.001]} rotation={[-0.001, 0.01, 1.551]} scale={[0.215, 0.1, 0.215]} />
      <mesh name="Stairs011" geometry={nodes.Stairs011.geometry} material={materials['Material.154']} position={[-0.787, 3.189, 0.016]} scale={[0.926, 0.781, 0.926]} />
      <mesh name="st_1011" geometry={nodes.st_1011.geometry} material={materials['Material.154']} position={[0.05, 4.134, 0.01]} />
      <mesh name="SS_3011" geometry={nodes.SS_3011.geometry} material={materials['Material.154']} position={[-0.109, 4.222, 0.01]} />
      <mesh name="SS_2011" geometry={nodes.SS_2011.geometry} material={materials['Material.154']} position={[0.054, 4.222, 0.157]} />
      <mesh name="SS_1011" geometry={nodes.SS_1011.geometry} material={materials['Material.154']} position={[0.054, 4.222, -0.125]} />
      <group name="pole011" position={[0.007, 2.41, 0.009]}>
        <mesh name="Mesh194" geometry={nodes.Mesh194.geometry} material={materials['Material.154']} />
        <mesh name="Mesh194_1" geometry={nodes.Mesh194_1.geometry} material={materials['Material.155']} />
      </group>
      <mesh name="pipe_3003" geometry={nodes.pipe_3003.geometry} material={materials['Material.154']} position={[0.628, 2.739, 0.062]} />
      <mesh name="pipe_2003" geometry={nodes.pipe_2003.geometry} material={materials['Material.154']} position={[0.628, 2.739, -0.068]} />
      <mesh name="pipe_1003" geometry={nodes.pipe_1003.geometry} material={materials['Material.154']} position={[0.628, 2.871, -0.003]} />
      <mesh name="nut_4011" geometry={nodes.nut_4011.geometry} material={materials['Material.158']} position={[-0.107, 0.694, -0.104]} />
      <mesh name="nut_3011" geometry={nodes.nut_3011.geometry} material={materials['Material.154']} position={[-0.107, 0.694, 0.123]} />
      <mesh name="nut_2011" geometry={nodes.nut_2011.geometry} material={materials['Material.154']} position={[0.12, 0.694, 0.123]} />
      <mesh name="nut_1011" geometry={nodes.nut_1011.geometry} material={materials['Material.154']} position={[0.12, 0.694, -0.104]} />
      <mesh name="Lights_1006" geometry={nodes.Lights_1006.geometry} material={materials['Material.154']} position={[0.063, 4.606, 0.048]} />
      <mesh name="hs_18010" geometry={nodes.hs_18010.geometry} material={materials['Material.154']} position={[0.204, 4.008, 0.015]} />
      <mesh name="hs_17010" geometry={nodes.hs_17010.geometry} material={materials['Material.154']} position={[0.601, 3.038, -0.003]} />
      <mesh name="hs_16010" geometry={nodes.hs_16010.geometry} material={materials['Material.154']} position={[0.559, 2.35, -0.003]} />
      <mesh name="FS_3011" geometry={nodes.FS_3011.geometry} material={materials['Material.154']} position={[-0.01, 3.393, 0.018]} />
      <mesh name="FS_2010" geometry={nodes.FS_2010.geometry} material={materials['Material.154']} position={[0, 2.225, -0.003]} />
      <mesh name="Cube010" geometry={nodes.Cube010.geometry} material={nodes.Cube010.material} position={[0, 0.253, 0.009]} scale={[0.447, 0.34, 0.417]} />
      <mesh name="cube010" geometry={nodes.cube010.geometry} material={materials['Material.154']} position={[0.448, 2.651, -0.003]} />
      <mesh name="board017" geometry={nodes.board017.geometry} material={materials['Material.154']} position={[0.359, 2.311, -0.003]} />
      <mesh name="BEG_Light_2016" geometry={nodes.BEG_Light_2016.geometry} material={materials['Material.154']} position={[0.192, 5.199, -0.737]} scale={0.915} />
      <mesh name="BEG_Light_4007" geometry={nodes.BEG_Light_4007.geometry} material={materials['Material.154']} position={[0, 1.231, -1.416]} />
    </group>
  )
}

useGLTF.preload('./signalFourLight-transformed.glb')
