/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 --keepmeshes --resolution 1024 --keepnames --types --output ./SignalHomeFourLightLunar.tsx --transform ./Signal-home-four-light-lunar.gltf 
Files: ./Signal-home-four-light-lunar.gltf [50.18KB] > /home/cronabit/Desktop/S3/Signal-home-four-light-lunar-transformed.glb [46.03KB] (8%)
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    white_light_053: THREE.Mesh
    white_light_054: THREE.Mesh
    white_light_057: THREE.Mesh
    white_light_058: THREE.Mesh
    SS_3011: THREE.Mesh
    SS_2011: THREE.Mesh
    SS_1011: THREE.Mesh
    Lights_1006: THREE.Mesh
    hs_18010: THREE.Mesh
    BEG_Light_2016: THREE.Mesh
    white_light_075: THREE.Mesh
    white_light_076: THREE.Mesh
    white_light_078: THREE.Mesh
    white_light_079: THREE.Mesh
    white_light_080: THREE.Mesh
    SLLT008: THREE.Mesh
    Octagon_with_7010: THREE.Mesh
    Stairs011: THREE.Mesh
    Mesh326: THREE.Mesh
    Mesh326_1: THREE.Mesh
    nut_4011: THREE.Mesh
    nut_3011: THREE.Mesh
    nut_2011: THREE.Mesh
    nut_1011: THREE.Mesh
    FS_3011: THREE.Mesh
    FS_2010: THREE.Mesh
    FS_1009: THREE.Mesh
    Cube010: THREE.Mesh
    BEG_Light_4007: THREE.Mesh
    BEG_Light_1016: THREE.Mesh
    BEG_Light_2018: THREE.Mesh
    BEG_Light_3012: THREE.Mesh
    BEG_Light_4008: THREE.Mesh
    BEG_Light_9006: THREE.Mesh
    board017: THREE.Mesh
    board018: THREE.Mesh
    cube010: THREE.Mesh
    Light_1009: THREE.Mesh
  }
  materials: {
    ['Material.143']: THREE.MeshBasicMaterial
    ['Material.154']: THREE.MeshStandardMaterial
    ['Material.165']: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('./Signal-home-four-light-lunar-transformed.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh name="YellowLight01" geometry={nodes.white_light_053.geometry} material={materials['Material.143']} position={[0.552, 5.772, -0.03]} rotation={[-0.001, 0.01, 1.551]} scale={[0.215, 0.1, 0.215]} />
      <mesh name="RedLight" geometry={nodes.white_light_054.geometry} material={materials['Material.143']} position={[0.552, 4.851, -0.021]} rotation={[-0.001, 0.01, 1.551]} scale={[0.215, 0.1, 0.215]} />
      <mesh name="YellowLight" geometry={nodes.white_light_057.geometry} material={materials['Material.143']} position={[0.552, 5.17, -0.021]} rotation={[-0.001, 0.01, 1.551]} scale={[0.215, 0.1, 0.215]} />
      <mesh name="GreenLight" geometry={nodes.white_light_058.geometry} material={materials['Material.143']} position={[0.552, 5.487, -0.024]} rotation={[-0.001, 0.01, 1.551]} scale={[0.215, 0.1, 0.215]} />
      <mesh name="SS_3011" geometry={nodes.SS_3011.geometry} material={materials['Material.154']} position={[0.298, 4.207, -0.013]} />
      <mesh name="SS_2011" geometry={nodes.SS_2011.geometry} material={materials['Material.154']} position={[0.461, 4.207, 0.134]} />
      <mesh name="SS_1011" geometry={nodes.SS_1011.geometry} material={materials['Material.154']} position={[0.461, 4.207, -0.148]} />
      <mesh name="Lights_1006" geometry={nodes.Lights_1006.geometry} material={materials['Material.154']} position={[0.47, 4.591, 0.025]} />
      <mesh name="hs_18010" geometry={nodes.hs_18010.geometry} material={materials['Material.154']} position={[0.55, 4.284, -0.007]} />
      <mesh name="BEG_Light_2016" geometry={nodes.BEG_Light_2016.geometry} material={materials['Material.154']} position={[0.599, 5.184, -0.76]} scale={0.915} />
      <mesh name="WhiteLight01" geometry={nodes.white_light_075.geometry} material={materials['Material.143']} position={[0.157, 6.424, 0.088]} rotation={[-0.001, 0.01, 1.551]} scale={[0.235, 0.11, 0.235]} />
      <mesh name="WhiteLight02" geometry={nodes.white_light_076.geometry} material={materials['Material.143']} position={[0.157, 6.603, 0.225]} rotation={[-0.001, 0.01, 1.551]} scale={[0.235, 0.11, 0.235]} />
      <mesh name="WhiteLight03" geometry={nodes.white_light_078.geometry} material={materials['Material.143']} position={[0.157, 6.812, 0.488]} rotation={[-0.001, 0.01, 1.551]} scale={[0.235, 0.11, 0.235]} />
      <mesh name="WhiteLight04" geometry={nodes.white_light_079.geometry} material={materials['Material.143']} position={[0.157, 6.98, 0.658]} rotation={[-0.001, 0.01, 1.551]} scale={[0.235, 0.11, 0.235]} />
      <mesh name="WhiteLight05" geometry={nodes.white_light_080.geometry} material={materials['Material.143']} position={[0.157, 7.148, 0.827]} rotation={[-0.001, 0.01, 1.551]} scale={[0.235, 0.11, 0.235]} />
      <mesh name="SLLT008" geometry={nodes.SLLT008.geometry} material={materials['Material.154']} position={[0, 1.31, 0.289]} />
      <mesh name="Octagon_with_7010" geometry={nodes.Octagon_with_7010.geometry} material={materials['Material.154']} position={[0, 1.31, 0.289]} />
      <mesh name="Stairs011" geometry={nodes.Stairs011.geometry} material={materials['Material.154']} position={[0, 1.05, 0.169]} />
      <group name="pole011" position={[0.007, 3.268, -0.017]} scale={[1, 1.476, 1]}>
        <mesh name="Mesh326" geometry={nodes.Mesh326.geometry} material={materials['Material.154']} />
        <mesh name="Mesh326_1" geometry={nodes.Mesh326_1.geometry} material={materials['Material.165']} />
      </group>
      <mesh name="nut_4011" geometry={nodes.nut_4011.geometry} material={materials['Material.154']} position={[0, 0.079, 0.181]} />
      <mesh name="nut_3011" geometry={nodes.nut_3011.geometry} material={materials['Material.154']} position={[0, 0.079, 0.181]} />
      <mesh name="nut_2011" geometry={nodes.nut_2011.geometry} material={materials['Material.154']} position={[0, 0.079, 0.181]} />
      <mesh name="nut_1011" geometry={nodes.nut_1011.geometry} material={materials['Material.154']} position={[0, 0.079, 0.181]} />
      <mesh name="FS_3011" geometry={nodes.FS_3011.geometry} material={materials['Material.154']} position={[0, 0.924, 0.176]} />
      <mesh name="FS_2010" geometry={nodes.FS_2010.geometry} material={materials['Material.154']} position={[0, 0.369, 0.181]} />
      <mesh name="FS_1009" geometry={nodes.FS_1009.geometry} material={materials['Material.154']} position={[0, 0.074, 0.181]} />
      <mesh name="Cube010" geometry={nodes.Cube010.geometry} material={nodes.Cube010.material} position={[0, 0.332, -0.012]} scale={[0.447, 0.34, 0.417]} />
      <mesh name="BEG_Light_4007" geometry={nodes.BEG_Light_4007.geometry} material={materials['Material.154']} position={[0.407, 1.216, -1.438]} />
      <mesh name="BEG_Light_1016" geometry={nodes.BEG_Light_1016.geometry} material={materials['Material.154']} position={[0, 1.31, 0.289]} />
      <mesh name="BEG_Light_2018" geometry={nodes.BEG_Light_2018.geometry} material={materials['Material.154']} position={[0, 1.31, 0.289]} />
      <mesh name="BEG_Light_3012" geometry={nodes.BEG_Light_3012.geometry} material={materials['Material.154']} position={[0, 1.31, 0.289]} />
      <mesh name="BEG_Light_4008" geometry={nodes.BEG_Light_4008.geometry} material={materials['Material.154']} position={[0, 1.31, 0.289]} />
      <mesh name="BEG_Light_9006" geometry={nodes.BEG_Light_9006.geometry} material={materials['Material.154']} position={[0, 1.31, 0.289]} />
      <mesh name="board017" geometry={nodes.board017.geometry} material={materials['Material.154']} position={[0, 0.924, 0.176]} />
      <mesh name="board018" geometry={nodes.board018.geometry} material={materials['Material.154']} position={[0, 0.04, 0.181]} />
      <mesh name="cube010" geometry={nodes.cube010.geometry} material={materials['Material.154']} position={[0, 0.04, 0.181]} />
      <mesh name="Light_1009" geometry={nodes.Light_1009.geometry} material={materials['Material.154']} position={[0, 0.074, 0.181]} />
    </group>
  )
}

useGLTF.preload('./Signal-home-four-light-lunar-transformed.glb')
