/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 --keepmeshes --resolution 1024 --keepnames --types --output ./signalMain.tsx --transform ./signalMain.gltf 
Files: ./signalMain.gltf [35.06KB] > /home/cronabit/Desktop/singalMain/signalMain-transformed.glb [35.46KB] (-1%)
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    board010: THREE.Mesh
    cube005: THREE.Mesh
    FS_2006: THREE.Mesh
    FS_3007: THREE.Mesh
    hs_16005: THREE.Mesh
    hs_17005: THREE.Mesh
    hs_18005: THREE.Mesh
    Lights_1004: THREE.Mesh
    nut_1007: THREE.Mesh
    nut_2007: THREE.Mesh
    nut_3007: THREE.Mesh
    nut_4007: THREE.Mesh
    pipe_1002: THREE.Mesh
    pipe_2002: THREE.Mesh
    pipe_3002: THREE.Mesh
    Mesh085: THREE.Mesh
    Mesh085_1: THREE.Mesh
    SS_1008: THREE.Mesh
    SS_2008: THREE.Mesh
    SS_3008: THREE.Mesh
    st_1007: THREE.Mesh
    Stairs007: THREE.Mesh
    BEG_Light_2012: THREE.Mesh
    Cube: THREE.Mesh
    _GREEN_light_045: THREE.Mesh
    YELLOW_light_046: THREE.Mesh
    RED_light_047: THREE.Mesh
  }
  materials: {
    PaletteMaterial001: THREE.MeshStandardMaterial
    PaletteMaterial002: THREE.MeshStandardMaterial
    PaletteMaterial003: THREE.MeshStandardMaterial
    PaletteMaterial004: THREE.MeshBasicMaterial
  }
  animations: GLTFAction[]
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('./signalMain-transformed.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh name="board010" geometry={nodes.board010.geometry} material={materials.PaletteMaterial001} position={[0.359, 2.311, 0.014]} />
      <mesh name="cube005" geometry={nodes.cube005.geometry} material={materials.PaletteMaterial001} position={[0.448, 2.651, 0.015]} />
      <mesh name="FS_2006" geometry={nodes.FS_2006.geometry} material={materials.PaletteMaterial001} position={[0, 2.225, 0.015]} />
      <mesh name="FS_3007" geometry={nodes.FS_3007.geometry} material={materials.PaletteMaterial001} position={[-0.01, 3.393, 0.035]} />
      <mesh name="hs_16005" geometry={nodes.hs_16005.geometry} material={materials.PaletteMaterial001} position={[0.559, 2.35, 0.015]} />
      <mesh name="hs_17005" geometry={nodes.hs_17005.geometry} material={materials.PaletteMaterial001} position={[0.601, 3.038, 0.015]} />
      <mesh name="hs_18005" geometry={nodes.hs_18005.geometry} material={materials.PaletteMaterial001} position={[0.204, 4.008, 0.033]} />
      <mesh name="Lights_1004" geometry={nodes.Lights_1004.geometry} material={materials.PaletteMaterial001} position={[0.063, 4.606, 0.065]} />
      <mesh name="nut_1007" geometry={nodes.nut_1007.geometry} material={materials.PaletteMaterial001} position={[0.12, 0.694, -0.086]} />
      <mesh name="nut_2007" geometry={nodes.nut_2007.geometry} material={materials.PaletteMaterial001} position={[0.12, 0.694, 0.14]} />
      <mesh name="nut_3007" geometry={nodes.nut_3007.geometry} material={materials.PaletteMaterial001} position={[-0.107, 0.694, 0.14]} />
      <mesh name="nut_4007" geometry={nodes.nut_4007.geometry} material={materials.PaletteMaterial002} position={[-0.107, 0.694, -0.086]} />
      <mesh name="pipe_1002" geometry={nodes.pipe_1002.geometry} material={materials.PaletteMaterial001} position={[0.628, 2.871, 0.014]} />
      <mesh name="pipe_2002" geometry={nodes.pipe_2002.geometry} material={materials.PaletteMaterial001} position={[0.628, 2.739, -0.051]} />
      <mesh name="pipe_3002" geometry={nodes.pipe_3002.geometry} material={materials.PaletteMaterial001} position={[0.628, 2.739, 0.079]} />
      <group name="pole007" position={[0.007, 2.41, 0.027]}>
        <mesh name="Mesh085" geometry={nodes.Mesh085.geometry} material={materials.PaletteMaterial001} />
        <mesh name="Mesh085_1" geometry={nodes.Mesh085_1.geometry} material={materials.PaletteMaterial002} />
      </group>
      <mesh name="SS_1008" geometry={nodes.SS_1008.geometry} material={materials.PaletteMaterial001} position={[0.054, 4.222, -0.107]} />
      <mesh name="SS_2008" geometry={nodes.SS_2008.geometry} material={materials.PaletteMaterial001} position={[0.054, 4.222, 0.175]} />
      <mesh name="SS_3008" geometry={nodes.SS_3008.geometry} material={materials.PaletteMaterial001} position={[-0.109, 4.222, 0.027]} />
      <mesh name="st_1007" geometry={nodes.st_1007.geometry} material={materials.PaletteMaterial001} position={[0.05, 4.134, 0.027]} />
      <mesh name="Stairs007" geometry={nodes.Stairs007.geometry} material={materials.PaletteMaterial001} position={[-0.787, 3.189, 0.034]} scale={[0.926, 0.781, 0.926]} />
      <mesh name="BEG_Light_2012" geometry={nodes.BEG_Light_2012.geometry} material={materials.PaletteMaterial001} position={[0.192, 5.199, -0.72]} scale={0.915} />
      <mesh name="Cube" geometry={nodes.Cube.geometry} material={materials.PaletteMaterial003} position={[0, 0.323, 0.008]} scale={[0.417, 0.342, 0.417]} />
      <mesh name="GreenLight" geometry={nodes._GREEN_light_045.geometry} material={materials.PaletteMaterial004} position={[0.145, 5.502, 0.016]} rotation={[-0.001, 0.01, 1.551]} scale={[0.215, 0.1, 0.215]} />
      <mesh name="YellowLight" geometry={nodes.YELLOW_light_046.geometry} material={materials.PaletteMaterial004} position={[0.145, 5.185, 0.019]} rotation={[-0.001, 0.01, 1.551]} scale={[0.215, 0.1, 0.215]} />
      <mesh name="RedLight" geometry={nodes.RED_light_047.geometry} material={materials.PaletteMaterial004} position={[0.145, 4.866, 0.019]} rotation={[-0.001, 0.01, 1.551]} scale={[0.215, 0.1, 0.215]} />
    </group>
  )
}

useGLTF.preload('./signalMain-transformed.glb')
