/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 --keepmeshes --resolution 1024 --keepnames --types --output ./StaterRightLunarModel.tsx --transform ./signal-starter-right-lunar.gltf 
Files: ./signal-starter-right-lunar.gltf [49.75KB] > /home/cronabit/Downloads/signal-starter-right-lunar/signal-starter-right-lunar-transformed.glb [42.15KB] (15%)
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    FS_1001: THREE.Mesh
    FS_2001: THREE.Mesh
    FS_3003: THREE.Mesh
    hs_18002: THREE.Mesh
    nut_1003: THREE.Mesh
    nut_2003: THREE.Mesh
    nut_3003: THREE.Mesh
    nut_4003: THREE.Mesh
    Octagon_with_7001: THREE.Mesh
    Mesh202: THREE.Mesh
    Mesh202_1: THREE.Mesh
    SLLT004: THREE.Mesh
    SS_1002: THREE.Mesh
    SS_2002: THREE.Mesh
    SS_3002: THREE.Mesh
    st_1001: THREE.Mesh
    Stairs003: THREE.Mesh
    stand003: THREE.Mesh
    BEG_Light_1006: THREE.Mesh
    RedLight: THREE.Mesh
    YellowLight: THREE.Mesh
    WhiteLight01: THREE.Mesh
    WhiteLight02: THREE.Mesh
    WhiteLight03: THREE.Mesh
    WhiteLight04: THREE.Mesh
    WhiteLight05: THREE.Mesh
    Light_1001: THREE.Mesh
    board003: THREE.Mesh
    cube001: THREE.Mesh
    hs_17001: THREE.Mesh
    hs_16001: THREE.Mesh
    board002: THREE.Mesh
    BEG_Light_4001: THREE.Mesh
    BEG_Light_5001: THREE.Mesh
    BEG_Light_1002: THREE.Mesh
    BEG_Light_2005: THREE.Mesh
    BEG_Light_3002: THREE.Mesh
  }
  materials: {
    ['Material.034']: THREE.MeshStandardMaterial
    ['Material.037']: THREE.MeshStandardMaterial
    ['Material.033']: THREE.MeshStandardMaterial
    ['Material.118']: THREE.MeshBasicMaterial
  }
  animations: GLTFAction[]
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('./signal-starter-right-lunar-transformed.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh name="FS_1001" geometry={nodes.FS_1001.geometry} material={materials['Material.034']} position={[0.042, 1.615, 0.026]} />
      <mesh name="FS_2001" geometry={nodes.FS_2001.geometry} material={materials['Material.034']} position={[0, 2.26, 0.026]} />
      <mesh name="FS_3003" geometry={nodes.FS_3003.geometry} material={materials['Material.034']} position={[-0.009, 3.936, 0.023]} />
      <mesh name="hs_18002" geometry={nodes.hs_18002.geometry} material={materials['Material.034']} position={[0.636, 3.999, 0.028]} />
      <mesh name="nut_1003" geometry={nodes.nut_1003.geometry} material={materials['Material.034']} position={[0.103, 0.649, -0.077]} />
      <mesh name="nut_2003" geometry={nodes.nut_2003.geometry} material={materials['Material.034']} position={[0.103, 0.649, 0.129]} />
      <mesh name="nut_3003" geometry={nodes.nut_3003.geometry} material={materials['Material.034']} position={[-0.103, 0.649, 0.129]} />
      <mesh name="nut_4003" geometry={nodes.nut_4003.geometry} material={materials['Material.034']} position={[-0.103, 0.649, -0.077]} />
      <mesh name="Octagon_with_7001" geometry={nodes.Octagon_with_7001.geometry} material={materials['Material.034']} position={[-0.119, 5.865, 0.018]} />
      <group name="pole003" position={[0.007, 3.011, 0.008]} scale={[1, 1.407, 1]}>
        <mesh name="Mesh202" geometry={nodes.Mesh202.geometry} material={materials['Material.037']} />
        <mesh name="Mesh202_1" geometry={nodes.Mesh202_1.geometry} material={materials['Material.034']} />
      </group>
      <mesh name="SLLT004" geometry={nodes.SLLT004.geometry} material={materials['Material.034']} position={[0.069, 6.374, -0.498]} />
      <mesh name="SS_1002" geometry={nodes.SS_1002.geometry} material={materials['Material.034']} position={[0.486, 4.213, -0.11]} />
      <mesh name="SS_2002" geometry={nodes.SS_2002.geometry} material={materials['Material.034']} position={[0.486, 4.213, 0.172]} />
      <mesh name="SS_3002" geometry={nodes.SS_3002.geometry} material={materials['Material.034']} position={[0.323, 4.213, 0.025]} />
      <mesh name="st_1001" geometry={nodes.st_1001.geometry} material={materials['Material.034']} position={[0.482, 4.125, 0.025]} />
      <mesh name="Stairs003" geometry={nodes.Stairs003.geometry} material={materials['Material.034']} position={[-0.709, 3.646, 0.026]} />
      <mesh name="stand003" geometry={nodes.stand003.geometry} material={materials['Material.033']} position={[0, 0.297, 0.006]} scale={[1.08, 1, 1.109]} />
      <mesh name="BEG_Light_1006" geometry={nodes.BEG_Light_1006.geometry} material={materials['Material.034']} position={[0.514, 4.763, 0.032]} rotation={[Math.PI / 2, 0, 0]} scale={0.231} />
      <mesh name="RedLight" geometry={nodes.RedLight.geometry} material={materials['Material.118']} position={[0.546, 4.866, 0.018]} rotation={[-0.001, 0.01, 1.551]} scale={[0.238, 0.111, 0.238]} />
      <mesh name="YellowLight" geometry={nodes.YellowLight.geometry} material={materials['Material.118']} position={[0.546, 5.195, 0.013]} rotation={[-0.001, 0.01, 1.551]} scale={[0.238, 0.111, 0.238]} />
      <mesh name="WhiteLight01" geometry={nodes.WhiteLight01.geometry} material={materials['Material.118']} position={[0.17, 5.864, 0.017]} rotation={[-0.001, 0.01, 1.551]} scale={[0.235, 0.11, 0.235]} />
      <mesh name="WhiteLight02" geometry={nodes.WhiteLight02.geometry} material={materials['Material.118']} position={[0.17, 6.026, -0.158]} rotation={[-0.001, 0.01, 1.551]} scale={[0.235, 0.11, 0.235]} />
      <mesh name="WhiteLight03" geometry={nodes.WhiteLight03.geometry} material={materials['Material.118']} position={[0.17, 6.229, -0.384]} rotation={[-0.001, 0.01, 1.551]} scale={[0.235, 0.11, 0.235]} />
      <mesh name="WhiteLight04" geometry={nodes.WhiteLight04.geometry} material={materials['Material.118']} position={[0.17, 6.398, -0.554]} rotation={[-0.001, 0.01, 1.551]} scale={[0.235, 0.11, 0.235]} />
      <mesh name="WhiteLight05" geometry={nodes.WhiteLight05.geometry} material={materials['Material.118']} position={[0.17, 6.565, -0.728]} rotation={[-0.001, 0.01, 1.551]} scale={[0.235, 0.11, 0.235]} />
      <mesh name="Light_1001" geometry={nodes.Light_1001.geometry} material={materials['Material.034']} position={[0.166, 1.761, 0.026]} />
      <mesh name="board003" geometry={nodes.board003.geometry} material={materials['Material.034']} position={[0.329, 2.321, 0.026]} />
      <mesh name="cube001" geometry={nodes.cube001.geometry} material={materials['Material.034']} position={[0.408, 2.63, 0.026]} />
      <mesh name="hs_17001" geometry={nodes.hs_17001.geometry} material={materials['Material.034']} position={[0.547, 2.982, 0.026]} />
      <mesh name="hs_16001" geometry={nodes.hs_16001.geometry} material={materials['Material.034']} position={[0.509, 2.364, 0.026]} />
      <mesh name="board002" geometry={nodes.board002.geometry} material={materials['Material.034']} position={[0.314, 4.033, 0.022]} />
      <mesh name="BEG_Light_4001" geometry={nodes.BEG_Light_4001.geometry} material={materials['Material.034']} position={[0.225, 5.882, 0.019]} />
      <mesh name="BEG_Light_5001" geometry={nodes.BEG_Light_5001.geometry} material={materials['Material.034']} position={[0.228, 6.044, -0.156]} />
      <mesh name="BEG_Light_1002" geometry={nodes.BEG_Light_1002.geometry} material={materials['Material.034']} position={[0.227, 6.583, -0.725]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh name="BEG_Light_2005" geometry={nodes.BEG_Light_2005.geometry} material={materials['Material.034']} position={[0.225, 6.414, -0.552]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh name="BEG_Light_3002" geometry={nodes.BEG_Light_3002.geometry} material={materials['Material.034']} position={[0.228, 6.245, -0.383]} rotation={[Math.PI / 2, 0, 0]} />
    </group>
  )
}

useGLTF.preload('./signal-starter-right-lunar-transformed.glb')
