/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 --instanceall --resolution 1024 --types --output ./GrassPatchModel.tsx --transform ./GrassPatch.gltf 
Files: ./GrassPatch.gltf [14.81KB] > /home/cronabit/Desktop/TreesWithInstance/GrassPatch/GrassPatch-transformed.glb [246.7KB] (-1566%)
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF, Merged } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    U3DMesh_grass01_0: THREE.Mesh
    U3DMesh001_grass01001_0: THREE.Mesh
    U3DMesh002_grass01002_0: THREE.Mesh
    U3DMesh003_grass01003_0: THREE.Mesh
    U3DMesh004_wheat_0: THREE.Mesh
    U3DMesh005_wheat001_0: THREE.Mesh
    U3DMesh006_wheat002_0: THREE.Mesh
    U3DMesh007_wheat003_0: THREE.Mesh
  }
  materials: {
    grass01: THREE.MeshStandardMaterial
    ['grass01.001']: THREE.MeshStandardMaterial
    ['grass01.002']: THREE.MeshStandardMaterial
    ['grass01.003']: THREE.MeshStandardMaterial
    wheat: THREE.MeshStandardMaterial
    ['wheat.001']: THREE.MeshStandardMaterial
    ['wheat.002']: THREE.MeshStandardMaterial
    ['wheat.003']: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

type ContextType = Record<string, React.ForwardRefExoticComponent<JSX.IntrinsicElements['mesh']>>

const context = React.createContext({} as ContextType)

export function Instances({ children, ...props }: JSX.IntrinsicElements['group']) {
  const { nodes } = useGLTF('./trees/GrassPatch-transformed.glb') as GLTFResult
  const instances = React.useMemo(
    () => ({
      UDMeshgrass: nodes.U3DMesh_grass01_0,
      UDMeshgrass1: nodes.U3DMesh001_grass01001_0,
      UDMeshgrass2: nodes.U3DMesh002_grass01002_0,
      UDMeshgrass3: nodes.U3DMesh003_grass01003_0,
      UDMeshwheat: nodes.U3DMesh004_wheat_0,
      UDMeshwheat1: nodes.U3DMesh005_wheat001_0,
      UDMeshwheat2: nodes.U3DMesh006_wheat002_0,
      UDMeshwheat3: nodes.U3DMesh007_wheat003_0,
    }),
    [nodes],
  )
  return (
    <Merged meshes={instances} {...props}>
      {(instances: ContextType) => <context.Provider value={instances} children={children} />}
    </Merged>
  )
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const instances = React.useContext(context)
  return (
    <group {...props} dispose={null}>
      <instances.UDMeshgrass position={[0, 0, 35]} scale={0.01} />
      <instances.UDMeshgrass1 position={[0, 0, 25]} scale={0.01} />
      <instances.UDMeshgrass2 position={[0, 0, 15]} scale={0.01} />
      <instances.UDMeshgrass3 position={[0, 0, 5]} scale={0.01} />
      <instances.UDMeshwheat position={[0, 0, -5]} scale={0.01} />
      <instances.UDMeshwheat1 position={[0, 0, -15]} scale={0.01} />
      <instances.UDMeshwheat2 position={[0, 0, -25]} scale={0.01} />
      <instances.UDMeshwheat3 position={[0, 0, -35]} scale={0.01} />
    </group>
  )
}

useGLTF.preload('./trees/GrassPatch-transformed.glb')
