/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 --keepmeshes --resolution 1024 --keepnames --types --output ./NewTreesModel6.tsx --transform ./newtrees2.0.gltf 
Files: ./newtrees2.0.gltf [64.5KB] > /home/cronabit/Documents/Fazal/hill_top_tree/newtrees2-transformed.glb [671.86KB] (-942%)
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    ['Branch_Small_A019_14_-_Bark_0']: THREE.Mesh
    ['Branch_Small_A020_14_-_Bark_0']: THREE.Mesh
    ['Branch_Small_A040_14_-_Bark_0']: THREE.Mesh
    ['Branch_Small_A041_14_-_Bark_0']: THREE.Mesh
    ['Branch_Small_A042_14_-_Bark_0']: THREE.Mesh
    ['Branch_Small_A043_14_-_Bark_0']: THREE.Mesh
    ['Branch_Small_A044_14_-_Bark_0']: THREE.Mesh
    ['Branch_Small_A045_14_-_Bark_0']: THREE.Mesh
    ['Branch_Small_A046_14_-_Bark_0']: THREE.Mesh
    ['Branch_Small_A047_14_-_Bark_0']: THREE.Mesh
    ['Branch_Small_A048_14_-_Bark_0']: THREE.Mesh
    ['Branch_Small_A049_14_-_Bark_0']: THREE.Mesh
    ['Branch_Small_A050_14_-_Bark_0']: THREE.Mesh
    ['Branch_Small_A051_14_-_Bark_0']: THREE.Mesh
    ['Branch_Small_A052_14_-_Bark_0']: THREE.Mesh
    ['Branch_Small_A053_14_-_Bark_0']: THREE.Mesh
    ['Branch_Small_A054_14_-_Bark_0']: THREE.Mesh
    ['Branch_Small_A055_14_-_Bark_0']: THREE.Mesh
    ['Branch_Small_A056_14_-_Bark_0']: THREE.Mesh
    ['Branch_Small_A060_14_-_Bark_0']: THREE.Mesh
    ['Branch_Small_A061_14_-_Bark_0']: THREE.Mesh
    ['Branch_Small_A062_14_-_Bark_0']: THREE.Mesh
    ['Branch_Small_A063_14_-_Bark_0']: THREE.Mesh
    ['Branch_Small_A064_14_-_Bark_0']: THREE.Mesh
    ['Branch_Small_A065_14_-_Bark_0']: THREE.Mesh
    ['Branch_Small_A066_14_-_Bark_0']: THREE.Mesh
    ['Branch_Small_A067_14_-_Bark_0']: THREE.Mesh
    ['Branch_Small_A068_14_-_Bark_0']: THREE.Mesh
    ['Branch_Small_A069_14_-_Bark_0']: THREE.Mesh
    ['Branch_Small_A070_14_-_Bark_0']: THREE.Mesh
    ['Branch_Small_A071_14_-_Bark_0']: THREE.Mesh
    ['Branch_Small_A072_14_-_Bark_0']: THREE.Mesh
    ['Canopy_1_15_-_Default_0']: THREE.Mesh
    ['Spline_Branch_A001_14_-_Bark_0']: THREE.Mesh
    ['Spline_Branch_B001_14_-_Bark_0']: THREE.Mesh
    ['Spline_Branch_C001_14_-_Bark_0']: THREE.Mesh
    ['Spline_Branch_D001_14_-_Bark_0']: THREE.Mesh
    ['Spline_Branch_E001_14_-_Bark_0']: THREE.Mesh
  }
  materials: {
    ['14_-_Bark']: THREE.MeshStandardMaterial
    ['15_-_Default']: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('./trees/newtrees2-transformed.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh name="Branch_Small_A019_14_-_Bark_0" geometry={nodes['Branch_Small_A019_14_-_Bark_0'].geometry} material={materials['14_-_Bark']} position={[49.547, 414.03, 54.936]} rotation={[-Math.PI / 2, -0.698, 0]} scale={[0.593, 0.593, 0.562]} />
      <mesh name="Branch_Small_A020_14_-_Bark_0" geometry={nodes['Branch_Small_A020_14_-_Bark_0'].geometry} material={materials['14_-_Bark']} position={[77.045, 383.449, 47.174]} rotation={[-Math.PI / 2, 0.175, -3.054]} scale={[0.593, 0.593, 0.562]} />
      <mesh name="Branch_Small_A040_14_-_Bark_0" geometry={nodes['Branch_Small_A040_14_-_Bark_0'].geometry} material={materials['14_-_Bark']} position={[162.275, 285.758, -108.456]} rotation={[-2.611, -0.151, -1.483]} scale={[0.593, 0.593, 0.562]} />
      <mesh name="Branch_Small_A041_14_-_Bark_0" geometry={nodes['Branch_Small_A041_14_-_Bark_0'].geometry} material={materials['14_-_Bark']} position={[183.845, 291.355, -145.359]} rotation={[-1.834, 0.188, 0.712]} scale={[0.593, 0.593, 0.562]} />
      <mesh name="Branch_Small_A042_14_-_Bark_0" geometry={nodes['Branch_Small_A042_14_-_Bark_0'].geometry} material={materials['14_-_Bark']} position={[173.17, 289.375, -129.161]} rotation={[-2.596, 1.409, 3.004]} scale={[0.593, 0.593, 0.562]} />
      <mesh name="Branch_Small_A043_14_-_Bark_0" geometry={nodes['Branch_Small_A043_14_-_Bark_0'].geometry} material={materials['14_-_Bark']} position={[154.45, 273.438, -86.083]} rotation={[-0.996, 1.007, 0.89]} scale={[0.593, 0.593, 0.562]} />
      <mesh name="Branch_Small_A044_14_-_Bark_0" geometry={nodes['Branch_Small_A044_14_-_Bark_0'].geometry} material={materials['14_-_Bark']} position={[159.567, 281.041, -100.411]} rotation={[-1.726, 0.15, 1.093]} scale={[0.593, 0.593, 0.562]} />
      <mesh name="Branch_Small_A045_14_-_Bark_0" geometry={nodes['Branch_Small_A045_14_-_Bark_0'].geometry} material={materials['14_-_Bark']} position={[149.204, 263.435, -64.447]} rotation={[2.99, 0.129, 0.072]} scale={[0.593, 0.593, 0.562]} />
      <mesh name="Branch_Small_A046_14_-_Bark_0" geometry={nodes['Branch_Small_A046_14_-_Bark_0'].geometry} material={materials['14_-_Bark']} position={[144.443, 255.772, -58.805]} rotation={[-1.408, -0.267, 1.279]} scale={[0.593, 0.593, 0.562]} />
      <mesh name="Branch_Small_A047_14_-_Bark_0" geometry={nodes['Branch_Small_A047_14_-_Bark_0'].geometry} material={materials['14_-_Bark']} position={[136.997, 250.627, -52.892]} rotation={[2.888, 0.998, -1.351]} scale={[0.593, 0.593, 0.562]} />
      <mesh name="Branch_Small_A048_14_-_Bark_0" geometry={nodes['Branch_Small_A048_14_-_Bark_0'].geometry} material={materials['14_-_Bark']} position={[131.574, 243.19, -47.767]} rotation={[-1.274, 0.424, 1.236]} scale={[0.593, 0.593, 0.562]} />
      <mesh name="Branch_Small_A049_14_-_Bark_0" geometry={nodes['Branch_Small_A049_14_-_Bark_0'].geometry} material={materials['14_-_Bark']} position={[115.489, 225.951, -30.3]} rotation={[-2.267, -0.154, -0.18]} scale={[0.593, 0.593, 0.562]} />
      <mesh name="Branch_Small_A050_14_-_Bark_0" geometry={nodes['Branch_Small_A050_14_-_Bark_0'].geometry} material={materials['14_-_Bark']} position={[-8.364, 322.714, -71.918]} rotation={[-Math.PI / 2, 0, 0]} scale={[0.593, 0.593, 0.562]} />
      <mesh name="Branch_Small_A051_14_-_Bark_0" geometry={nodes['Branch_Small_A051_14_-_Bark_0'].geometry} material={materials['14_-_Bark']} position={[-10.498, 332.19, -77.766]} rotation={[-Math.PI / 2, -Math.PI / 6, 0]} scale={[0.593, 0.593, 0.562]} />
      <mesh name="Branch_Small_A052_14_-_Bark_0" geometry={nodes['Branch_Small_A052_14_-_Bark_0'].geometry} material={materials['14_-_Bark']} position={[-10.566, 332.584, -77.068]} rotation={[-2.581, -0.502, -1.197]} scale={[0.593, 0.593, 0.562]} />
      <mesh name="Branch_Small_A053_14_-_Bark_0" geometry={nodes['Branch_Small_A053_14_-_Bark_0'].geometry} material={materials['14_-_Bark']} position={[6.439, 272.628, -54.625]} rotation={[-2.291, -1.029, -1.682]} scale={[0.593, 0.593, 0.562]} />
      <mesh name="Branch_Small_A054_14_-_Bark_0" geometry={nodes['Branch_Small_A054_14_-_Bark_0'].geometry} material={materials['14_-_Bark']} position={[8.058, 263.227, -55.768]} rotation={[-0.913, -0.259, -1.837]} scale={[0.593, 0.593, 0.562]} />
      <mesh name="Branch_Small_A055_14_-_Bark_0" geometry={nodes['Branch_Small_A055_14_-_Bark_0'].geometry} material={materials['14_-_Bark']} position={[29.204, 221.18, -42.482]} rotation={[-2.265, 0.024, 1.52]} scale={[0.593, 0.593, 0.562]} />
      <mesh name="Branch_Small_A056_14_-_Bark_0" geometry={nodes['Branch_Small_A056_14_-_Bark_0'].geometry} material={materials['14_-_Bark']} position={[25.078, 229.015, -45.681]} rotation={[-3.025, -0.584, 1.374]} scale={[0.593, 0.593, 0.562]} />
      <mesh name="Branch_Small_A060_14_-_Bark_0" geometry={nodes['Branch_Small_A060_14_-_Bark_0'].geometry} material={materials['14_-_Bark']} position={[83.525, 302.34, 43.721]} rotation={[-0.677, 0.224, -2.704]} scale={[0.593, 0.593, 0.562]} />
      <mesh name="Branch_Small_A061_14_-_Bark_0" geometry={nodes['Branch_Small_A061_14_-_Bark_0'].geometry} material={materials['14_-_Bark']} position={[73.396, 268.233, 33.496]} rotation={[-1.546, 0.54, 3.08]} scale={[0.593, 0.593, 0.562]} />
      <mesh name="Branch_Small_A062_14_-_Bark_0" geometry={nodes['Branch_Small_A062_14_-_Bark_0'].geometry} material={materials['14_-_Bark']} position={[59.26, 233.652, 31.999]} rotation={[-0.568, 0.616, 3.071]} scale={[0.593, 0.593, 0.562]} />
      <mesh name="Branch_Small_A063_14_-_Bark_0" geometry={nodes['Branch_Small_A063_14_-_Bark_0'].geometry} material={materials['14_-_Bark']} position={[72.053, 262.184, 33.109]} rotation={[-0.979, -0.536, 2.283]} scale={[0.593, 0.593, 0.562]} />
      <mesh name="Branch_Small_A064_14_-_Bark_0" geometry={nodes['Branch_Small_A064_14_-_Bark_0'].geometry} material={materials['14_-_Bark']} position={[177.522, 312.444, 70.568]} rotation={[-1.281, 0.197, 2.153]} scale={[0.593, 0.593, 0.562]} />
      <mesh name="Branch_Small_A065_14_-_Bark_0" geometry={nodes['Branch_Small_A065_14_-_Bark_0'].geometry} material={materials['14_-_Bark']} position={[177.044, 312.811, 70.092]} rotation={[-0.545, 0.435, 0.907]} scale={[0.593, 0.593, 0.562]} />
      <mesh name="Branch_Small_A066_14_-_Bark_0" geometry={nodes['Branch_Small_A066_14_-_Bark_0'].geometry} material={materials['14_-_Bark']} position={[135.186, 258.985, 23.743]} rotation={[-1.441, 0.815, 0.283]} scale={[0.593, 0.593, 0.562]} />
      <mesh name="Branch_Small_A067_14_-_Bark_0" geometry={nodes['Branch_Small_A067_14_-_Bark_0'].geometry} material={materials['14_-_Bark']} position={[117.045, 228.224, 4.69]} rotation={[-1.685, 1.332, 0.665]} scale={[0.593, 0.593, 0.562]} />
      <mesh name="Branch_Small_A068_14_-_Bark_0" geometry={nodes['Branch_Small_A068_14_-_Bark_0'].geometry} material={materials['14_-_Bark']} position={[38.304, 203.503, -37.217]} rotation={[-0.783, -0.549, 2.538]} scale={[0.593, 0.593, 0.562]} />
      <mesh name="Branch_Small_A069_14_-_Bark_0" geometry={nodes['Branch_Small_A069_14_-_Bark_0'].geometry} material={materials['14_-_Bark']} position={[59.381, 206.427, 21.283]} rotation={[-1.836, 0.071, -0.072]} scale={[0.593, 0.593, 0.562]} />
      <mesh name="Branch_Small_A070_14_-_Bark_0" geometry={nodes['Branch_Small_A070_14_-_Bark_0'].geometry} material={materials['14_-_Bark']} position={[157.073, 343.959, 0.97]} rotation={[-2.821, -0.584, -1.312]} scale={[0.593, 0.593, 0.562]} />
      <mesh name="Branch_Small_A071_14_-_Bark_0" geometry={nodes['Branch_Small_A071_14_-_Bark_0'].geometry} material={materials['14_-_Bark']} position={[156.542, 343.311, 0.323]} rotation={[-1.894, -0.142, -0.952]} scale={[0.593, 0.593, 0.562]} />
      <mesh name="Branch_Small_A072_14_-_Bark_0" geometry={nodes['Branch_Small_A072_14_-_Bark_0'].geometry} material={materials['14_-_Bark']} position={[155.749, 318.918, 0.025]} rotation={[-1.91, 0.78, -1.83]} scale={[0.593, 0.593, 0.562]} />
      <mesh name="Canopy_1_15_-_Default_0" geometry={nodes['Canopy_1_15_-_Default_0'].geometry} material={materials['15_-_Default']} position={[169.568, 240.959, 2.591]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh name="Spline_Branch_A001_14_-_Bark_0" geometry={nodes['Spline_Branch_A001_14_-_Bark_0'].geometry} material={materials['14_-_Bark']} position={[-3, 0, 0]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh name="Spline_Branch_B001_14_-_Bark_0" geometry={nodes['Spline_Branch_B001_14_-_Bark_0'].geometry} material={materials['14_-_Bark']} position={[-2.249, 0, 0]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh name="Spline_Branch_C001_14_-_Bark_0" geometry={nodes['Spline_Branch_C001_14_-_Bark_0'].geometry} material={materials['14_-_Bark']} position={[-3, 0, 0]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh name="Spline_Branch_D001_14_-_Bark_0" geometry={nodes['Spline_Branch_D001_14_-_Bark_0'].geometry} material={materials['14_-_Bark']} position={[-3, 0, 0]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh name="Spline_Branch_E001_14_-_Bark_0" geometry={nodes['Spline_Branch_E001_14_-_Bark_0'].geometry} material={materials['14_-_Bark']} position={[-3, 0, 0]} rotation={[-Math.PI / 2, 0, 0]} />
    </group>
  )
}

useGLTF.preload('./trees/newtrees2-transformed.glb')
