/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 --keepmeshes --resolution 1024 --keepnames --types --output ./NewTreesModel5.tsx --transform ./newtrees5.gltf 
Files: ./newtrees5.gltf [6.09KB] > /home/cronabit/Documents/Fazal/train_version_2.1/newtrees5-transformed.glb [397.4KB] (-6425%)
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Circle_0: THREE.Mesh
    Circle_1: THREE.Mesh
  }
  materials: {
    ['bark.001']: THREE.MeshStandardMaterial
    Branches0025_1_S: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('./trees/newtrees5-transformed.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh name="Circle_0" geometry={nodes.Circle_0.geometry} material={materials['bark.001']} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh name="Circle_1" geometry={nodes.Circle_1.geometry} material={materials.Branches0025_1_S} rotation={[-Math.PI / 2, 0, 0]} />
    </group>
  )
}

useGLTF.preload('./trees/newtrees5-transformed.glb')
