/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 --keepmeshes --resolution 1024 --keepnames --types --output ./NewTreesModel2.tsx --transform ./newtrees2.gltf 
Files: ./newtrees.gltf [7.92KB] > /home/cronabit/Downloads/Prem_cronabit/low_poly_tree/newtrees-transformed.glb [362.48KB] (-4477%)
Author: Chenuka Wijesundara (https://sketchfab.com/ChenukaWijesundara)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/low-poly-tree-70f0e767fc2f449fa6fef9c2308b395f
Title: Low poly tree
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    LowPolyTree_Default_OBJ_0: THREE.Mesh
    LowPolyTree002_Default_OBJ001_0: THREE.Mesh
  }
  materials: {
    Default_OBJ: THREE.MeshStandardMaterial
    ['Default_OBJ.001']: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('./trees/newtrees-transformed.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh name="LowPolyTree_Default_OBJ_0" geometry={nodes.LowPolyTree_Default_OBJ_0.geometry} material={materials.Default_OBJ} scale={12.508} />
      <mesh name="LowPolyTree002_Default_OBJ001_0" geometry={nodes.LowPolyTree002_Default_OBJ001_0.geometry} material={materials['Default_OBJ.001']} scale={12.508} />
    </group>
  )
}

useGLTF.preload('./trees/newtrees-transformed.glb')
