/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 --keepmeshes --resolution 1024 --keepnames --types --output ./NewTreesModel3.tsx --transform ./newtrees3.gltf 
Files: ./newtrees3.gltf [7.05KB] > /home/cronabit/Documents/Fazal/pine_tree/newtrees3-transformed.glb [562.13KB] (-7873%)
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Object_2: THREE.Mesh
    Object_3: THREE.Mesh
    Object_4: THREE.Mesh
    Object_5: THREE.Mesh
    Object_6: THREE.Mesh
  }
  materials: {
    initialShadingGroup: THREE.MeshStandardMaterial
    lambert2SG: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('./trees/newtrees3-transformed.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh name="Object_2" geometry={nodes.Object_2.geometry} material={materials.initialShadingGroup} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh name="Object_3" geometry={nodes.Object_3.geometry} material={materials.lambert2SG} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh name="Object_4" geometry={nodes.Object_4.geometry} material={materials.lambert2SG} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh name="Object_5" geometry={nodes.Object_5.geometry} material={materials.lambert2SG} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh name="Object_6" geometry={nodes.Object_6.geometry} material={materials.lambert2SG} rotation={[-Math.PI / 2, 0, 0]} />
    </group>
  )
}

useGLTF.preload('./trees/newtrees3-transformed.glb')
