/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 --keepmeshes --resolution 1024 --keepnames --types --output ./NewTreesModel4.tsx --transform ./newtrees4.gltf 
Files: ./newtrees4.gltf [4.21KB] > /home/cronabit/Documents/Fazal/small_trees/newtrees4-transformed.glb [54.79KB] (-1201%)
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    ['red-baron-grass-ornamental-Va7qqJC-600_red-baron-grass-ornament']: THREE.Mesh
    ['red-baron-grass-ornamental-Va7qqJC-600001_red-baron-grass-orna']: THREE.Mesh
  }
  materials: {
    ['red-baron-grass-ornamental-Va7qqJC-600']: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('./trees/newtrees4-transformed.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh name="red-baron-grass-ornamental-Va7qqJC-600_red-baron-grass-ornament" geometry={nodes['red-baron-grass-ornamental-Va7qqJC-600_red-baron-grass-ornament'].geometry} material={materials['red-baron-grass-ornamental-Va7qqJC-600']} position={[1.973, 0, 0.926]} rotation={[-Math.PI / 2, 0, 0]} scale={1.074} />
      <mesh name="red-baron-grass-ornamental-Va7qqJC-600001_red-baron-grass-orna" geometry={nodes['red-baron-grass-ornamental-Va7qqJC-600001_red-baron-grass-orna'].geometry} material={materials['red-baron-grass-ornamental-Va7qqJC-600']} position={[1.973, 0, 0.926]} rotation={[-Math.PI / 2, 0, 0]} scale={1.074} />
    </group>
  )
}

useGLTF.preload('./trees/newtrees4-transformed.glb')
