/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 --instanceall --resolution 1024 --types --output ./SimpleTreeModel.tsx --transform ./SimpleTree.gltf 
Files: ./SimpleTree.gltf [6.89KB] > /home/cronabit/Desktop/TreesWithInstance/SimpleTree/SimpleTree-transformed.glb [2.98MB] (-43083%)
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF, Merged } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    leaves005_Leaf__02_0: THREE.Mesh
    tree001_Pine_Bark_0: THREE.Mesh
  }
  materials: {
    Leaf__02: THREE.MeshStandardMaterial
    Pine_Bark: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

type ContextType = Record<string, React.ForwardRefExoticComponent<JSX.IntrinsicElements['mesh']>>

const context = React.createContext({} as ContextType)

export function Instances({ children, ...props }: JSX.IntrinsicElements['group']) {
  const { nodes } = useGLTF('./trees/SimpleTree-transformed.glb') as GLTFResult
  const instances = React.useMemo(
    () => ({
      LeavesLeaf: nodes.leaves005_Leaf__02_0,
      TreePineBark: nodes.tree001_Pine_Bark_0,
    }),
    [nodes],
  )
  return (
    <Merged meshes={instances} {...props}>
      {(instances: ContextType) => <context.Provider value={instances} children={children} />}
    </Merged>
  )
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const instances = React.useContext(context)
  return (
    <group {...props} dispose={null}>
      <instances.LeavesLeaf rotation={[-Math.PI / 2, 0, 0]} />
      <instances.TreePineBark rotation={[-Math.PI / 2, 0, 0]} />
    </group>
  )
}

useGLTF.preload('./trees/SimpleTree-transformed.glb')
