/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 --resolution 1204 --types --output ./src/models/AdBillboardModel.tsx --transform ./src-models/ad-billboard/ad-billboard.gltf 
Files: ./src-models/ad-billboard/ad-billboard.gltf [7.84KB] > D:\Work\train-sim\src\models\ad-billboard-transformed.glb [68.88KB] (-779%)
Author: Anthony Yanez (https://sketchfab.com/paulyanez)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/low-poly-ad-billboard-864b8ce5d520478481198d1face5a7e5
Title: Low poly Ad Billboard
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Billboard_Billboard_Mat_1_0: THREE.Mesh
    Billboard_Billboard_Mat_2_0: THREE.Mesh
    Billboard_Billboard_Texture_0: THREE.Mesh
  }
  materials: {
    Billboard_Mat_1: THREE.MeshStandardMaterial
    Billboard_Mat_2: THREE.MeshStandardMaterial
    Billboard_Texture: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/ad-billboard-transformed.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Billboard_Billboard_Mat_1_0.geometry} material={materials.Billboard_Mat_1} position={[0, 0.019, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={0.014} />
      <mesh geometry={nodes.Billboard_Billboard_Mat_2_0.geometry} material={materials.Billboard_Mat_2} position={[0, 0.019, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={0.014} />
      <mesh geometry={nodes.Billboard_Billboard_Texture_0.geometry} material={materials.Billboard_Texture} position={[0, 0.019, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={0.014} />
    </group>
  )
}

useGLTF.preload('/ad-billboard-transformed.glb')
