/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 --resolution 1204 --keepnames --types --output ./src/models/BridgeStraightModel.tsx --transform ./src-models/bridge-straight/bridge-straight.gltf 
Files: ./src-models/bridge-straight/bridge-straight.gltf [1.93KB] > D:\Work\train-sim\src\models\bridge-straight-transformed.glb [7.16KB] (-271%)
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Bridge_Straight: THREE.Mesh
  }
  materials: {
    ['lambert1.001']: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('./bridge-straight-transformed.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh name="Bridge_Straight" geometry={nodes.Bridge_Straight.geometry} material={materials['lambert1.001']} position={[-1.111, -0.002, 0.961]} rotation={[Math.PI / 2, 0, 0]} scale={0.096} />
    </group>
  )
}

useGLTF.preload('./bridge-straight-transformed.glb')
