/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 --resolution 1204 --keepnames --types --output ./src/models/BridgeCurvedModel.tsx --transform ./src-models/bridge-curved/bridge-curved.gltf 
Files: ./src-models/bridge-curved/bridge-curved.gltf [1.84KB] > D:\Work\train-sim\src\models\bridge-curved-transformed.glb [12.89KB] (-601%)
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Vivek_Bridge: THREE.Mesh
  }
  materials: {
    lambert1: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('./bridge-curved-transformed.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh name="Vivek_Bridge" geometry={nodes.Vivek_Bridge.geometry} material={materials.lambert1} rotation={[Math.PI / 2, 0, 0]} scale={0.095} />
    </group>
  )
}

useGLTF.preload('./bridge-curved-transformed.glb')
