/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 --resolution 1204 --types --output ./src/models/BuildingsModel.tsx --transform ./src-models/buildings/buildings.gltf 
Files: ./src-models/buildings/buildings.gltf [127.21KB] > D:\Work\train-sim\src\models\buildings-transformed.glb [1.43MB] (-1020%)
Author: Elbolillo (https://sketchfab.com/Elbolilloduro)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/buildings-53fdd165f327434e9a88873253f710a5
Title: Buildings
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Building_03_ConcreteBare_0: THREE.Mesh
    Building_03_brick_modern_03_0: THREE.Mesh
    Building_03_Shops_01_0: THREE.Mesh
    Building_03_Shops_02_0: THREE.Mesh
    Building_03_Shops_0: THREE.Mesh
    Building_03_building_09_0: THREE.Mesh
    Building_03_Roof_tiles_0: THREE.Mesh
    Building_01_building_04_0: THREE.Mesh
    Building_01_Shops_03_0: THREE.Mesh
    Building_01_Shops_04_0: THREE.Mesh
    Building_01_Shops_05_0: THREE.Mesh
    Building_brick_modern_04_0: THREE.Mesh
    Building_building_06_0: THREE.Mesh
    Building_Shops_06_0: THREE.Mesh
    Building_Shops_09_0: THREE.Mesh
    Building_Shops_08_0: THREE.Mesh
    Building_02_brick_modern_02_0: THREE.Mesh
    Building_02_Shops_11_0: THREE.Mesh
    Building_02_building_08_0: THREE.Mesh
    Building_02_Shops_10_0: THREE.Mesh
    Building_02_Shops_12_0: THREE.Mesh
    Building_02_Shops_14_0: THREE.Mesh
    Building_02_Shops_13_0: THREE.Mesh
    Building_04_Shops_16_0: THREE.Mesh
    Building_04_building_01_0: THREE.Mesh
    Building_04_Shops_15_0: THREE.Mesh
    Building_04_Shops_17_0: THREE.Mesh
    Building_09_building_10_0: THREE.Mesh
    Building_09_brick_modern_0: THREE.Mesh
    Building_09_Shops_18_0: THREE.Mesh
    Building_09_Shops_07_0: THREE.Mesh
    Building_05_brick_modern_01_0: THREE.Mesh
    Building_05_building_03_0: THREE.Mesh
    Building_05_Shops_19_0: THREE.Mesh
    Building_05_Shops_21_0: THREE.Mesh
    Building_05_Shops_20_0: THREE.Mesh
    Building_05_Shops_22_0: THREE.Mesh
    Building_07_brick_modern_05_0: THREE.Mesh
    Building_07_building_0: THREE.Mesh
    Building_07_Shops_23_0: THREE.Mesh
    Building_07_Shops_24_0: THREE.Mesh
    Building_07_Shops_25_0: THREE.Mesh
    Building_08_BrickSmallPainted_0: THREE.Mesh
    Building_08_Shops_26_0: THREE.Mesh
    Building_08_Shops_27_0: THREE.Mesh
    Building_08_building_11_0: THREE.Mesh
    Building_06_BrickSmallBrown_0: THREE.Mesh
    Building_06_Shops_28_0: THREE.Mesh
    Building_06_building_07_0: THREE.Mesh
    Building_06_Shops_29_0: THREE.Mesh
    Building_06_Shops_31_0: THREE.Mesh
    Building_06_Shops_30_0: THREE.Mesh
  }
  materials: {
    ConcreteBare: THREE.MeshStandardMaterial
    brick_modern_03: THREE.MeshStandardMaterial
    Shops_01: THREE.MeshStandardMaterial
    Shops_02: THREE.MeshStandardMaterial
    Shops: THREE.MeshStandardMaterial
    building_09: THREE.MeshStandardMaterial
    Roof_tiles: THREE.MeshStandardMaterial
    building_04: THREE.MeshStandardMaterial
    Shops_03: THREE.MeshStandardMaterial
    Shops_04: THREE.MeshStandardMaterial
    Shops_05: THREE.MeshStandardMaterial
    brick_modern_04: THREE.MeshStandardMaterial
    building_06: THREE.MeshStandardMaterial
    Shops_06: THREE.MeshStandardMaterial
    Shops_09: THREE.MeshStandardMaterial
    Shops_08: THREE.MeshStandardMaterial
    brick_modern_02: THREE.MeshStandardMaterial
    Shops_11: THREE.MeshStandardMaterial
    building_08: THREE.MeshStandardMaterial
    Shops_10: THREE.MeshStandardMaterial
    Shops_12: THREE.MeshStandardMaterial
    Shops_14: THREE.MeshStandardMaterial
    Shops_13: THREE.MeshStandardMaterial
    Shops_16: THREE.MeshStandardMaterial
    building_01: THREE.MeshStandardMaterial
    Shops_15: THREE.MeshStandardMaterial
    Shops_17: THREE.MeshStandardMaterial
    building_10: THREE.MeshStandardMaterial
    brick_modern: THREE.MeshStandardMaterial
    Shops_18: THREE.MeshStandardMaterial
    Shops_07: THREE.MeshStandardMaterial
    brick_modern_01: THREE.MeshStandardMaterial
    building_03: THREE.MeshStandardMaterial
    Shops_19: THREE.MeshStandardMaterial
    Shops_21: THREE.MeshStandardMaterial
    Shops_20: THREE.MeshStandardMaterial
    Shops_22: THREE.MeshStandardMaterial
    brick_modern_05: THREE.MeshStandardMaterial
    building: THREE.MeshStandardMaterial
    Shops_23: THREE.MeshStandardMaterial
    Shops_24: THREE.MeshStandardMaterial
    Shops_25: THREE.MeshStandardMaterial
    BrickSmallPainted: THREE.MeshStandardMaterial
    Shops_26: THREE.MeshStandardMaterial
    Shops_27: THREE.MeshStandardMaterial
    building_11: THREE.MeshStandardMaterial
    BrickSmallBrown: THREE.MeshStandardMaterial
    Shops_28: THREE.MeshStandardMaterial
    building_07: THREE.MeshStandardMaterial
    Shops_29: THREE.MeshStandardMaterial
    Shops_31: THREE.MeshStandardMaterial
    Shops_30: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('./buildings-transformed.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Building_03_ConcreteBare_0.geometry} material={materials.ConcreteBare} position={[-35.9, 9.419, 15.676]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Building_03_brick_modern_03_0.geometry} material={materials.brick_modern_03} position={[-35.9, 9.419, 15.676]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Building_03_Shops_01_0.geometry} material={materials.Shops_01} position={[-35.9, 9.419, 15.676]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Building_03_Shops_02_0.geometry} material={materials.Shops_02} position={[-35.9, 9.419, 15.676]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Building_03_Shops_0.geometry} material={materials.Shops} position={[-35.9, 9.419, 15.676]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Building_03_building_09_0.geometry} material={materials.building_09} position={[-35.9, 9.419, 15.676]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Building_03_Roof_tiles_0.geometry} material={materials.Roof_tiles} position={[-35.9, 9.419, 15.676]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Building_01_building_04_0.geometry} material={materials.building_04} position={[2.456, 11.905, -30.918]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Building_01_Shops_03_0.geometry} material={materials.Shops_03} position={[2.456, 11.905, -30.918]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Building_01_Shops_04_0.geometry} material={materials.Shops_04} position={[2.456, 11.905, -30.918]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Building_01_Shops_05_0.geometry} material={materials.Shops_05} position={[2.456, 11.905, -30.918]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Building_brick_modern_04_0.geometry} material={materials.brick_modern_04} position={[-33.413, 9.966, -31.501]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Building_building_06_0.geometry} material={materials.building_06} position={[-33.413, 9.966, -31.501]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Building_Shops_06_0.geometry} material={materials.Shops_06} position={[-33.413, 9.966, -31.501]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Building_Shops_09_0.geometry} material={materials.Shops_09} position={[-33.413, 9.966, -31.501]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Building_Shops_08_0.geometry} material={materials.Shops_08} position={[-33.413, 9.966, -31.501]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Building_02_brick_modern_02_0.geometry} material={materials.brick_modern_02} position={[42.732, 13.639, -31.966]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Building_02_Shops_11_0.geometry} material={materials.Shops_11} position={[42.732, 13.639, -31.966]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Building_02_building_08_0.geometry} material={materials.building_08} position={[42.732, 13.639, -31.966]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Building_02_Shops_10_0.geometry} material={materials.Shops_10} position={[42.732, 13.639, -31.966]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Building_02_Shops_12_0.geometry} material={materials.Shops_12} position={[42.732, 13.639, -31.966]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Building_02_Shops_14_0.geometry} material={materials.Shops_14} position={[42.732, 13.639, -31.966]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Building_02_Shops_13_0.geometry} material={materials.Shops_13} position={[42.732, 13.639, -31.966]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Building_04_Shops_16_0.geometry} material={materials.Shops_16} position={[-3.356, 9.414, 14.103]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Building_04_building_01_0.geometry} material={materials.building_01} position={[-3.356, 9.414, 14.103]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Building_04_Shops_15_0.geometry} material={materials.Shops_15} position={[-3.356, 9.414, 14.103]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Building_04_Shops_17_0.geometry} material={materials.Shops_17} position={[-3.356, 9.414, 14.103]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Building_09_building_10_0.geometry} material={materials.building_10} position={[46.521, 6.023, 55.072]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Building_09_brick_modern_0.geometry} material={materials.brick_modern} position={[46.521, 6.023, 55.072]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Building_09_Shops_18_0.geometry} material={materials.Shops_18} position={[46.521, 6.023, 55.072]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Building_09_Shops_07_0.geometry} material={materials.Shops_07} position={[46.521, 6.023, 55.072]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Building_05_brick_modern_01_0.geometry} material={materials.brick_modern_01} position={[34.318, 9.517, 13.666]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Building_05_building_03_0.geometry} material={materials.building_03} position={[34.318, 9.517, 13.666]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Building_05_Shops_19_0.geometry} material={materials.Shops_19} position={[34.318, 9.517, 13.666]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Building_05_Shops_21_0.geometry} material={materials.Shops_21} position={[34.318, 9.517, 13.666]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Building_05_Shops_20_0.geometry} material={materials.Shops_20} position={[34.318, 9.517, 13.666]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Building_05_Shops_22_0.geometry} material={materials.Shops_22} position={[34.318, 9.517, 13.666]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Building_07_brick_modern_05_0.geometry} material={materials.brick_modern_05} position={[0.775, 8.666, 54.249]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Building_07_building_0.geometry} material={materials.building} position={[0.775, 8.666, 54.249]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Building_07_Shops_23_0.geometry} material={materials.Shops_23} position={[0.775, 8.666, 54.249]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Building_07_Shops_24_0.geometry} material={materials.Shops_24} position={[0.775, 8.666, 54.249]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Building_07_Shops_25_0.geometry} material={materials.Shops_25} position={[0.775, 8.666, 54.249]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Building_08_BrickSmallPainted_0.geometry} material={materials.BrickSmallPainted} position={[25.932, 5.979, 54.853]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Building_08_Shops_26_0.geometry} material={materials.Shops_26} position={[25.932, 5.979, 54.853]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Building_08_Shops_27_0.geometry} material={materials.Shops_27} position={[25.932, 5.979, 54.853]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Building_08_building_11_0.geometry} material={materials.building_11} position={[25.932, 5.979, 54.853]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Building_06_BrickSmallBrown_0.geometry} material={materials.BrickSmallBrown} position={[-31.262, 7.39, 53.525]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Building_06_Shops_28_0.geometry} material={materials.Shops_28} position={[-31.262, 7.39, 53.525]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Building_06_building_07_0.geometry} material={materials.building_07} position={[-31.262, 7.39, 53.525]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Building_06_Shops_29_0.geometry} material={materials.Shops_29} position={[-31.262, 7.39, 53.525]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Building_06_Shops_31_0.geometry} material={materials.Shops_31} position={[-31.262, 7.39, 53.525]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Building_06_Shops_30_0.geometry} material={materials.Shops_30} position={[-31.262, 7.39, 53.525]} rotation={[-Math.PI / 2, 0, 0]} />
    </group>
  )
}

useGLTF.preload('./buildings-transformed.glb')
