/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 --resolution 1204 --types --output ./src/models/ConstructionModel.tsx --transform ./src-models/construction/construction.gltf 
Files: ./src-models/construction/construction.gltf [48.61KB] > D:\Work\train-sim\src\models\construction-transformed.glb [280.38KB] (-477%)
Author: 99.Miles (https://sketchfab.com/99.Miles)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/low-poly-construction-assets-5c134526af464b5389f6c8a29fddeaff
Title: Low Poly Construction Assets
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Construction007_Construction_Assets_0: THREE.Mesh
    Portable_Cabin001_Portable_Cabin_0: THREE.Mesh
  }
  materials: {
    Construction_Assets: THREE.MeshStandardMaterial
    Portable_Cabin: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('./construction-transformed.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Construction007_Construction_Assets_0.geometry} material={materials.Construction_Assets} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Portable_Cabin001_Portable_Cabin_0.geometry} material={materials.Portable_Cabin} rotation={[-Math.PI / 2, 0, 0]} />
    </group>
  )
}

useGLTF.preload('./construction-transformed.glb')
