/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 --resolution 1204 --types --output ./src/models/FuturisticBuildingModel.tsx --transform ./src-models/futuristic-building/futuristic-building.gltf 
Files: ./src-models/futuristic-building/futuristic-building.gltf [187.36KB] > D:\Work\train-sim\src\models\futuristic-building-transformed.glb [1.84MB] (-879%)
Author: 3DHaupt (https://sketchfab.com/dennish2010)
License: CC-BY-NC-4.0 (http://creativecommons.org/licenses/by-nc/4.0/)
Source: https://sketchfab.com/3d-models/futuristic-building-e73f9bb9981d469c8a8ccdc1f168faad
Title: Futuristic Building
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Plane022_0: THREE.Mesh
    Plane013_0: THREE.Mesh
    Plane013_1: THREE.Mesh
    Plane016_0: THREE.Mesh
    Plane_0: THREE.Mesh
    Plane_1: THREE.Mesh
    Plane_4: THREE.Mesh
    Circle003_0: THREE.Mesh
    Plane020_0: THREE.Mesh
    Cube002_0: THREE.Mesh
  }
  materials: {
    ['s.001']: THREE.MeshStandardMaterial
    ['Material.004_B_1']: THREE.MeshStandardMaterial
    ['Material.004']: THREE.MeshStandardMaterial
    material_11: THREE.MeshStandardMaterial
    ['Material.001']: THREE.MeshStandardMaterial
    ['Material.002']: THREE.MeshStandardMaterial
    ['Material.009']: THREE.MeshStandardMaterial
    ['Material.013']: THREE.MeshStandardMaterial
    ['Material.005']: THREE.MeshStandardMaterial
    material: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/futuristic-building-transformed.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Plane022_0.geometry} material={materials['s.001']} position={[2.86, 17.228, -4.484]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Plane013_0.geometry} material={materials['Material.004_B_1']} position={[2.909, 1.1, 0.9]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Plane013_1.geometry} material={materials['Material.004']} position={[2.909, 1.1, 0.9]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Plane016_0.geometry} material={materials.material_11} position={[14.949, 2.286, -9.08]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Plane_0.geometry} material={materials['Material.001']} position={[2.914, 5.536, -4.281]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Plane_1.geometry} material={materials['Material.002']} position={[2.914, 5.536, -4.281]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Plane_4.geometry} material={materials['Material.009']} position={[2.914, 5.536, -4.281]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Circle003_0.geometry} material={materials['Material.013']} position={[-8.305, 11.875, 0.974]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Plane020_0.geometry} material={materials['Material.005']} position={[2.559, -0.666, -3.969]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Cube002_0.geometry} material={materials.material} position={[6.062, 4.211, 0.261]} rotation={[-Math.PI / 2, 0, 0]} />
    </group>
  )
}

useGLTF.preload('/futuristic-building-transformed.glb')
