/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 --keepmeshes --resolution 1024 --keepnames --types --output ./src/models/HomeSignalModel.tsx --transform ./src-models/home-signal/home-signal.gltf 
Files: ./src-models/home-signal/home-signal.gltf [74.43KB] > D:\Work\train-sim\src\models\home-signal-transformed.glb [75.01KB] (-1%)
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    GreenLight: THREE.Mesh
    YellowLight: THREE.Mesh
    RedLight: THREE.Mesh
    FS_1001: THREE.Mesh
    FS_2001: THREE.Mesh
    FS_3001: THREE.Mesh
    Lights_1001: THREE.Mesh
    Octagon_with_7001: THREE.Mesh
    pole001: THREE.Mesh
    SLLL001: THREE.Mesh
    SLLM: THREE.Mesh
    SLLT: THREE.Mesh
    Stairs001: THREE.Mesh
    stand001: THREE.Mesh
    WhiteLight01: THREE.Mesh
    WhiteLight02: THREE.Mesh
    WhiteLight03: THREE.Mesh
    WhiteLight07: THREE.Mesh
    WhiteLight08: THREE.Mesh
    WhiteLight09: THREE.Mesh
    WhiteLight13: THREE.Mesh
    WhiteLight12: THREE.Mesh
    WhiteLight11: THREE.Mesh
    WhiteLight05: THREE.Mesh
    WhiteLight10: THREE.Mesh
    WhiteLight04: THREE.Mesh
    WhiteLight06: THREE.Mesh
    Light_1001: THREE.Mesh
    board003: THREE.Mesh
    cube001: THREE.Mesh
    hs_17001: THREE.Mesh
    pipe_1001: THREE.Mesh
    pipe_2001: THREE.Mesh
    pipe_3001: THREE.Mesh
    hs_16001: THREE.Mesh
    board002: THREE.Mesh
    BEG_Light_1006: THREE.Mesh
    BEG_Light_2006: THREE.Mesh
    BEG_Light_3007: THREE.Mesh
    hs_18001: THREE.Mesh
    SS_1002: THREE.Mesh
    SS_2002: THREE.Mesh
    SS_3002: THREE.Mesh
    BEG_Light_10: THREE.Mesh
    BEG_Light_4: THREE.Mesh
    BEG_Light_5: THREE.Mesh
    BEG_Light_9: THREE.Mesh
    nut_1001: THREE.Mesh
    nut_2001: THREE.Mesh
    nut_3001: THREE.Mesh
    nut_4001: THREE.Mesh
    SS_1003: THREE.Mesh
    SS_2003: THREE.Mesh
    SS_3003: THREE.Mesh
    st_1001: THREE.Mesh
    st_2001: THREE.Mesh
    st_3001: THREE.Mesh
    BEG_Light_1004: THREE.Mesh
    BEG_Light_2004: THREE.Mesh
    BEG_Light_3004: THREE.Mesh
    BEG_Light_1005: THREE.Mesh
    BEG_Light_2005: THREE.Mesh
    BEG_Light_3005: THREE.Mesh
    BEG_Light_1003: THREE.Mesh
    BEG_Light_2007: THREE.Mesh
    BEG_Light_3003: THREE.Mesh
  }
  materials: {
    PaletteMaterial001: THREE.MeshStandardMaterial
    PaletteMaterial002: THREE.MeshStandardMaterial
    PaletteMaterial003: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('./home-signal-transformed.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh name="GreenLight" geometry={nodes.GreenLight.geometry} material={materials.PaletteMaterial001} position={[0.408, -0.826, 0.021]} />
      <mesh name="YellowLight" geometry={nodes.YellowLight.geometry} material={materials.PaletteMaterial001} position={[0.408, -1.069, 0.021]} />
      <mesh name="RedLight" geometry={nodes.RedLight.geometry} material={materials.PaletteMaterial001} position={[0.408, -1.309, 0.021]} />
      <mesh name="FS_1001" geometry={nodes.FS_1001.geometry} material={materials.PaletteMaterial002} />
      <mesh name="FS_2001" geometry={nodes.FS_2001.geometry} material={materials.PaletteMaterial002} />
      <mesh name="FS_3001" geometry={nodes.FS_3001.geometry} material={materials.PaletteMaterial002} />
      <mesh name="Lights_1001" geometry={nodes.Lights_1001.geometry} material={materials.PaletteMaterial002} />
      <mesh name="Octagon_with_7001" geometry={nodes.Octagon_with_7001.geometry} material={materials.PaletteMaterial002} />
      <mesh name="pole001" geometry={nodes.pole001.geometry} material={materials.PaletteMaterial001} />
      <mesh name="SLLL001" geometry={nodes.SLLL001.geometry} material={materials.PaletteMaterial002} />
      <mesh name="SLLM" geometry={nodes.SLLM.geometry} material={materials.PaletteMaterial002} />
      <mesh name="SLLT" geometry={nodes.SLLT.geometry} material={materials.PaletteMaterial002} />
      <mesh name="Stairs001" geometry={nodes.Stairs001.geometry} material={materials.PaletteMaterial002} />
      <mesh name="stand001" geometry={nodes.stand001.geometry} material={materials.PaletteMaterial003} />
      <mesh name="WhiteLight01" geometry={nodes.WhiteLight01.geometry} material={materials.PaletteMaterial001} position={[0, 0.719, 0.741]} />
      <mesh name="WhiteLight02" geometry={nodes.WhiteLight02.geometry} material={materials.PaletteMaterial001} position={[0, 0.551, 0.573]} />
      <mesh name="WhiteLight03" geometry={nodes.WhiteLight03.geometry} material={materials.PaletteMaterial001} position={[0, 0.383, 0.401]} />
      <mesh name="WhiteLight07" geometry={nodes.WhiteLight07.geometry} material={materials.PaletteMaterial001} position={[0, 0, 0.56]} />
      <mesh name="WhiteLight08" geometry={nodes.WhiteLight08.geometry} material={materials.PaletteMaterial001} position={[0, -0.003, 0.797]} />
      <mesh name="WhiteLight09" geometry={nodes.WhiteLight09.geometry} material={materials.PaletteMaterial001} position={[0, 0, 1.039]} />
      <mesh name="WhiteLight13" geometry={nodes.WhiteLight13.geometry} material={materials.PaletteMaterial001} position={[0, -0.719, 0.741]} />
      <mesh name="WhiteLight12" geometry={nodes.WhiteLight12.geometry} material={materials.PaletteMaterial001} position={[0, -0.554, 0.573]} />
      <mesh name="WhiteLight11" geometry={nodes.WhiteLight11.geometry} material={materials.PaletteMaterial001} position={[0, -0.383, 0.398]} />
      <mesh name="WhiteLight05" geometry={nodes.WhiteLight05.geometry} material={materials.PaletteMaterial001} />
      <mesh name="WhiteLight10" geometry={nodes.WhiteLight10.geometry} material={materials.PaletteMaterial001} position={[0, -0.18, 0.177]} />
      <mesh name="WhiteLight04" geometry={nodes.WhiteLight04.geometry} material={materials.PaletteMaterial001} position={[0, 0.177, 0.143]} />
      <mesh name="WhiteLight06" geometry={nodes.WhiteLight06.geometry} material={materials.PaletteMaterial001} position={[0, 0, 0.24]} />
      <mesh name="Light_1001" geometry={nodes.Light_1001.geometry} material={materials.PaletteMaterial002} />
      <mesh name="board003" geometry={nodes.board003.geometry} material={materials.PaletteMaterial002} />
      <mesh name="cube001" geometry={nodes.cube001.geometry} material={materials.PaletteMaterial002} />
      <mesh name="hs_17001" geometry={nodes.hs_17001.geometry} material={materials.PaletteMaterial002} />
      <mesh name="pipe_1001" geometry={nodes.pipe_1001.geometry} material={materials.PaletteMaterial002} />
      <mesh name="pipe_2001" geometry={nodes.pipe_2001.geometry} material={materials.PaletteMaterial002} />
      <mesh name="pipe_3001" geometry={nodes.pipe_3001.geometry} material={materials.PaletteMaterial002} />
      <mesh name="hs_16001" geometry={nodes.hs_16001.geometry} material={materials.PaletteMaterial002} />
      <mesh name="board002" geometry={nodes.board002.geometry} material={materials.PaletteMaterial002} />
      <mesh name="BEG_Light_1006" geometry={nodes.BEG_Light_1006.geometry} material={materials.PaletteMaterial002} />
      <mesh name="BEG_Light_2006" geometry={nodes.BEG_Light_2006.geometry} material={materials.PaletteMaterial002} />
      <mesh name="BEG_Light_3007" geometry={nodes.BEG_Light_3007.geometry} material={materials.PaletteMaterial002} />
      <mesh name="hs_18001" geometry={nodes.hs_18001.geometry} material={materials.PaletteMaterial002} />
      <mesh name="SS_1002" geometry={nodes.SS_1002.geometry} material={materials.PaletteMaterial002} />
      <mesh name="SS_2002" geometry={nodes.SS_2002.geometry} material={materials.PaletteMaterial002} />
      <mesh name="SS_3002" geometry={nodes.SS_3002.geometry} material={materials.PaletteMaterial002} />
      <mesh name="BEG_Light_10" geometry={nodes.BEG_Light_10.geometry} material={materials.PaletteMaterial002} />
      <mesh name="BEG_Light_4" geometry={nodes.BEG_Light_4.geometry} material={materials.PaletteMaterial002} />
      <mesh name="BEG_Light_5" geometry={nodes.BEG_Light_5.geometry} material={materials.PaletteMaterial002} />
      <mesh name="BEG_Light_9" geometry={nodes.BEG_Light_9.geometry} material={materials.PaletteMaterial002} />
      <mesh name="nut_1001" geometry={nodes.nut_1001.geometry} material={materials.PaletteMaterial002} />
      <mesh name="nut_2001" geometry={nodes.nut_2001.geometry} material={materials.PaletteMaterial002} />
      <mesh name="nut_3001" geometry={nodes.nut_3001.geometry} material={materials.PaletteMaterial002} />
      <mesh name="nut_4001" geometry={nodes.nut_4001.geometry} material={materials.PaletteMaterial002} />
      <mesh name="SS_1003" geometry={nodes.SS_1003.geometry} material={materials.PaletteMaterial002} />
      <mesh name="SS_2003" geometry={nodes.SS_2003.geometry} material={materials.PaletteMaterial002} />
      <mesh name="SS_3003" geometry={nodes.SS_3003.geometry} material={materials.PaletteMaterial002} />
      <mesh name="st_1001" geometry={nodes.st_1001.geometry} material={materials.PaletteMaterial002} />
      <mesh name="st_2001" geometry={nodes.st_2001.geometry} material={materials.PaletteMaterial002} />
      <mesh name="st_3001" geometry={nodes.st_3001.geometry} material={materials.PaletteMaterial002} />
      <mesh name="BEG_Light_1004" geometry={nodes.BEG_Light_1004.geometry} material={materials.PaletteMaterial002} />
      <mesh name="BEG_Light_2004" geometry={nodes.BEG_Light_2004.geometry} material={materials.PaletteMaterial002} />
      <mesh name="BEG_Light_3004" geometry={nodes.BEG_Light_3004.geometry} material={materials.PaletteMaterial002} />
      <mesh name="BEG_Light_1005" geometry={nodes.BEG_Light_1005.geometry} material={materials.PaletteMaterial002} />
      <mesh name="BEG_Light_2005" geometry={nodes.BEG_Light_2005.geometry} material={materials.PaletteMaterial002} />
      <mesh name="BEG_Light_3005" geometry={nodes.BEG_Light_3005.geometry} material={materials.PaletteMaterial002} />
      <mesh name="BEG_Light_1003" geometry={nodes.BEG_Light_1003.geometry} material={materials.PaletteMaterial002} />
      <mesh name="BEG_Light_2007" geometry={nodes.BEG_Light_2007.geometry} material={materials.PaletteMaterial002} />
      <mesh name="BEG_Light_3003" geometry={nodes.BEG_Light_3003.geometry} material={materials.PaletteMaterial002} />
    </group>
  )
}

useGLTF.preload('./home-signal-transformed.glb')
