/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 --resolution 1204 --types --output ./src/models/IndianShopModel.tsx --transform ./src-models/indian-shop/indian-shop.gltf 
Files: ./src-models/indian-shop/indian-shop.gltf [6.02KB] > D:\Work\train-sim\src\models\indian-shop-transformed.glb [75.03KB] (-1146%)
Author: anandmohan662 (https://sketchfab.com/anandmohan662)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/indian-shop-dad04bbb505443129a86cebd89d77610
Title: Indian Shop
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Object_4: THREE.Mesh
    Object_5: THREE.Mesh
  }
  materials: {
    ['Untitled-design-62']: THREE.MeshStandardMaterial
    Material: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('./indian-shop-transformed.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Object_4.geometry} material={materials['Untitled-design-62']} position={[0, 2.924, -1.027]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={6.444} />
      <mesh geometry={nodes.Object_5.geometry} material={materials.Material} position={[0, 2.924, -1.027]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={6.444} />
    </group>
  )
}

useGLTF.preload('./indian-shop-transformed.glb')
