/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 --keepmeshes --resolution 1024 --keepnames --types --output ./src/models/MainStarterSignalModel.tsx --transform ./src-models/main-starter-signal/main-starter-signal.gltf 
Files: ./src-models/main-starter-signal/main-starter-signal.gltf [34.99KB] > D:\Work\train-sim\src\models\main-starter-signal-transformed.glb [37.76KB] (-8%)
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    YellowLight: THREE.Mesh
    RedLight: THREE.Mesh
    GreenLight: THREE.Mesh
    BEG_Light_2002: THREE.Mesh
    board005: THREE.Mesh
    cube003: THREE.Mesh
    FS_2005: THREE.Mesh
    FS_3003: THREE.Mesh
    hs_16003: THREE.Mesh
    hs_17003: THREE.Mesh
    hs_18003: THREE.Mesh
    Lights_1003: THREE.Mesh
    nut_1003: THREE.Mesh
    nut_2003: THREE.Mesh
    nut_3003: THREE.Mesh
    nut_4003: THREE.Mesh
    pipe_1002: THREE.Mesh
    pipe_2002: THREE.Mesh
    pipe_3002: THREE.Mesh
    Mesh004: THREE.Mesh
    Mesh004_1: THREE.Mesh
    SS_1005: THREE.Mesh
    SS_2005: THREE.Mesh
    SS_3005: THREE.Mesh
    st_1003: THREE.Mesh
    Stairs003: THREE.Mesh
    stand003: THREE.Mesh
  }
  materials: {
    PaletteMaterial001: THREE.MeshStandardMaterial
    PaletteMaterial002: THREE.MeshStandardMaterial
    PaletteMaterial003: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('./main-starter-signal-transformed.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh name="YellowLight" geometry={nodes.YellowLight.geometry} material={materials.PaletteMaterial001} position={[0.142, 5.126, -0.007]} rotation={[0, 0, -Math.PI / 2]} scale={[0.071, 0.04, 0.071]} />
      <mesh name="RedLight" geometry={nodes.RedLight.geometry} material={materials.PaletteMaterial001} position={[0.145, 4.772, 0.004]} rotation={[0, 0, -Math.PI / 2]} scale={[0.071, 0.04, 0.071]} />
      <mesh name="GreenLight" geometry={nodes.GreenLight.geometry} material={materials.PaletteMaterial001} position={[0.142, 5.51, 0.004]} rotation={[0, 0, -Math.PI / 2]} scale={[0.071, 0.04, 0.071]} />
      <mesh name="BEG_Light_2002" geometry={nodes.BEG_Light_2002.geometry} material={materials.PaletteMaterial002} position={[0.215, 5.144, -0.008]} />
      <mesh name="board005" geometry={nodes.board005.geometry} material={materials.PaletteMaterial002} position={[0.359, 2.311, -0.011]} />
      <mesh name="cube003" geometry={nodes.cube003.geometry} material={materials.PaletteMaterial002} position={[0.448, 2.651, -0.01]} />
      <mesh name="FS_2005" geometry={nodes.FS_2005.geometry} material={materials.PaletteMaterial002} position={[0, 2.225, -0.01]} />
      <mesh name="FS_3003" geometry={nodes.FS_3003.geometry} material={materials.PaletteMaterial002} position={[-0.01, 3.393, 0.01]} />
      <mesh name="hs_16003" geometry={nodes.hs_16003.geometry} material={materials.PaletteMaterial002} position={[0.559, 2.35, -0.01]} />
      <mesh name="hs_17003" geometry={nodes.hs_17003.geometry} material={materials.PaletteMaterial002} position={[0.601, 3.038, -0.01]} />
      <mesh name="hs_18003" geometry={nodes.hs_18003.geometry} material={materials.PaletteMaterial002} position={[0.204, 4.008, 0.008]} />
      <mesh name="Lights_1003" geometry={nodes.Lights_1003.geometry} material={materials.PaletteMaterial002} position={[0.063, 4.606, 0.04]} />
      <mesh name="nut_1003" geometry={nodes.nut_1003.geometry} material={materials.PaletteMaterial002} position={[0.12, 0.694, -0.111]} />
      <mesh name="nut_2003" geometry={nodes.nut_2003.geometry} material={materials.PaletteMaterial002} position={[0.12, 0.694, 0.115]} />
      <mesh name="nut_3003" geometry={nodes.nut_3003.geometry} material={materials.PaletteMaterial002} position={[-0.107, 0.694, 0.115]} />
      <mesh name="nut_4003" geometry={nodes.nut_4003.geometry} material={materials.PaletteMaterial001} position={[-0.107, 0.694, -0.111]} />
      <mesh name="pipe_1002" geometry={nodes.pipe_1002.geometry} material={materials.PaletteMaterial002} position={[0.628, 2.871, -0.011]} />
      <mesh name="pipe_2002" geometry={nodes.pipe_2002.geometry} material={materials.PaletteMaterial002} position={[0.628, 2.739, -0.076]} />
      <mesh name="pipe_3002" geometry={nodes.pipe_3002.geometry} material={materials.PaletteMaterial002} position={[0.628, 2.739, 0.054]} />
      <group name="pole003" position={[0.007, 2.41, 0.001]}>
        <mesh name="Mesh004" geometry={nodes.Mesh004.geometry} material={materials.PaletteMaterial001} />
        <mesh name="Mesh004_1" geometry={nodes.Mesh004_1.geometry} material={materials.PaletteMaterial002} />
      </group>
      <mesh name="SS_1005" geometry={nodes.SS_1005.geometry} material={materials.PaletteMaterial002} position={[0.054, 4.222, -0.133]} />
      <mesh name="SS_2005" geometry={nodes.SS_2005.geometry} material={materials.PaletteMaterial002} position={[0.054, 4.222, 0.149]} />
      <mesh name="SS_3005" geometry={nodes.SS_3005.geometry} material={materials.PaletteMaterial002} position={[-0.109, 4.222, 0.002]} />
      <mesh name="st_1003" geometry={nodes.st_1003.geometry} material={materials.PaletteMaterial002} position={[0.05, 4.134, 0.002]} />
      <mesh name="Stairs003" geometry={nodes.Stairs003.geometry} material={materials.PaletteMaterial002} position={[-0.787, 3.128, 0.009]} />
      <mesh name="stand003" geometry={nodes.stand003.geometry} material={materials.PaletteMaterial003} position={[0, 0.326, 0.008]} />
    </group>
  )
}

useGLTF.preload('./main-starter-signal-transformed.glb')
