/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 --keepmeshes --resolution 1024 --keepnames --types --output ./newStation1.tsx --transform ./newRS.gltf 
Files: ./newRS.gltf [291.48KB] > /home/cronabit/Desktop/NewRS/new/newRS-transformed.glb [476.82KB] (-64%)
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    polySurface61: THREE.Mesh
    polySurface21: THREE.Mesh
    polySurface128: THREE.Mesh
    Shop_8: THREE.Mesh
    polySurface124: THREE.Mesh
    pillers_L1: THREE.Mesh
    polySurface101: THREE.Mesh
    polySurface132: THREE.Mesh
    polySurface102: THREE.Mesh
    polySurface23: THREE.Mesh
    polySurface114: THREE.Mesh
    polySurface24: THREE.Mesh
    polySurface91: THREE.Mesh
    polySurface111: THREE.Mesh
    polySurface117: THREE.Mesh
    polySurface92: THREE.Mesh
    Piller_Left_M1: THREE.Mesh
    polySurface90: THREE.Mesh
    polySurface104: THREE.Mesh
    polySurface94: THREE.Mesh
    polySurface96: THREE.Mesh
    polySurface110: THREE.Mesh
    polySurface66: THREE.Mesh
    polySurface67: THREE.Mesh
    polySurface97: THREE.Mesh
    polySurface93: THREE.Mesh
    polySurface18: THREE.Mesh
    polySurface115: THREE.Mesh
    polySurface106: THREE.Mesh
    Railings_L1: THREE.Mesh
    polySurface116: THREE.Mesh
    polySurface63: THREE.Mesh
    polySurface68: THREE.Mesh
    polySurface5: THREE.Mesh
    Support_M: THREE.Mesh
    polySurface20: THREE.Mesh
    polySurface26: THREE.Mesh
    polySurface64: THREE.Mesh
    Support_L1: THREE.Mesh
    polySurface112: THREE.Mesh
    polySurface27: THREE.Mesh
    polySurface10: THREE.Mesh
    Stairs_M: THREE.Mesh
    Shop_21: THREE.Mesh
    polySurface17: THREE.Mesh
    polySurface25: THREE.Mesh
    polySurface6: THREE.Mesh
    polySurface15: THREE.Mesh
    polySurface4: THREE.Mesh
    Stairs_L1: THREE.Mesh
    polySurface29: THREE.Mesh
    polySurface58: THREE.Mesh
    Stair_roof_L1: THREE.Mesh
    polySurface77: THREE.Mesh
    polySurface16: THREE.Mesh
    Shop_15: THREE.Mesh
    polySurface19: THREE.Mesh
    polySurface14: THREE.Mesh
    polySurface8: THREE.Mesh
    polySurface9: THREE.Mesh
    polySurface28: THREE.Mesh
    polySurface22: THREE.Mesh
    polySurface13: THREE.Mesh
    Roof_M: THREE.Mesh
    Fob_Mid_Railings_M2: THREE.Mesh
    polySurface486: THREE.Mesh
    polySurface508: THREE.Mesh
    polySurface509: THREE.Mesh
    polySurface513: THREE.Mesh
    polySurface518: THREE.Mesh
    polySurface523: THREE.Mesh
    polySurface525: THREE.Mesh
    polySurface560: THREE.Mesh
    polySurface562: THREE.Mesh
    polySurface569: THREE.Mesh
    polySurface401: THREE.Mesh
    polySurface402: THREE.Mesh
    polySurface404: THREE.Mesh
    polySurface405: THREE.Mesh
    polySurface406: THREE.Mesh
    polySurface407: THREE.Mesh
    polySurface408: THREE.Mesh
    polySurface410: THREE.Mesh
    polySurface411: THREE.Mesh
    polySurface412: THREE.Mesh
    polySurface413: THREE.Mesh
    polySurface417: THREE.Mesh
    polySurface418: THREE.Mesh
    polySurface419: THREE.Mesh
    polySurface423: THREE.Mesh
    polySurface424: THREE.Mesh
    polySurface425: THREE.Mesh
    polySurface426: THREE.Mesh
    polySurface427: THREE.Mesh
    polySurface428: THREE.Mesh
    polySurface429: THREE.Mesh
    polySurface431: THREE.Mesh
    polySurface433: THREE.Mesh
    polySurface434: THREE.Mesh
    polySurface435: THREE.Mesh
    polySurface438: THREE.Mesh
    polySurface439: THREE.Mesh
    polySurface440: THREE.Mesh
    polySurface444: THREE.Mesh
    polySurface445: THREE.Mesh
    polySurface446: THREE.Mesh
    polySurface447: THREE.Mesh
    polySurface449: THREE.Mesh
    polySurface450: THREE.Mesh
    polySurface451: THREE.Mesh
    polySurface452: THREE.Mesh
    polySurface453: THREE.Mesh
    polySurface454: THREE.Mesh
    polySurface456: THREE.Mesh
    polySurface459: THREE.Mesh
    polySurface465: THREE.Mesh
    polySurface467: THREE.Mesh
    polySurface468: THREE.Mesh
    polySurface470: THREE.Mesh
    polySurface472: THREE.Mesh
    polySurface473: THREE.Mesh
    polySurface475: THREE.Mesh
    polySurface476: THREE.Mesh
    polySurface478: THREE.Mesh
    polySurface479: THREE.Mesh
    polySurface480: THREE.Mesh
    polySurface484: THREE.Mesh
    polySurface312: THREE.Mesh
    polySurface313: THREE.Mesh
    polySurface314: THREE.Mesh
    polySurface318: THREE.Mesh
    polySurface320: THREE.Mesh
    polySurface321: THREE.Mesh
    polySurface323: THREE.Mesh
    polySurface325: THREE.Mesh
    polySurface327: THREE.Mesh
    polySurface329: THREE.Mesh
    polySurface330: THREE.Mesh
    polySurface331: THREE.Mesh
    polySurface332: THREE.Mesh
    polySurface333: THREE.Mesh
    polySurface334: THREE.Mesh
    polySurface335: THREE.Mesh
    polySurface337: THREE.Mesh
    polySurface339: THREE.Mesh
    polySurface342: THREE.Mesh
    polySurface345: THREE.Mesh
    polySurface347: THREE.Mesh
    polySurface348: THREE.Mesh
    polySurface350: THREE.Mesh
    polySurface353: THREE.Mesh
    polySurface355: THREE.Mesh
    polySurface358: THREE.Mesh
    polySurface359: THREE.Mesh
    polySurface360: THREE.Mesh
    polySurface362: THREE.Mesh
    polySurface363: THREE.Mesh
    polySurface365: THREE.Mesh
    polySurface367: THREE.Mesh
    polySurface369: THREE.Mesh
    polySurface370: THREE.Mesh
    polySurface371: THREE.Mesh
    polySurface372: THREE.Mesh
    polySurface373: THREE.Mesh
    polySurface374: THREE.Mesh
    polySurface377: THREE.Mesh
    polySurface378: THREE.Mesh
    polySurface379: THREE.Mesh
    polySurface380: THREE.Mesh
    polySurface381: THREE.Mesh
    polySurface382: THREE.Mesh
    polySurface383: THREE.Mesh
    polySurface386: THREE.Mesh
    polySurface387: THREE.Mesh
    polySurface388: THREE.Mesh
    polySurface390: THREE.Mesh
    polySurface391: THREE.Mesh
    polySurface392: THREE.Mesh
    polySurface394: THREE.Mesh
    polySurface396: THREE.Mesh
    polySurface397: THREE.Mesh
    polySurface398: THREE.Mesh
    polySurface399: THREE.Mesh
    Mesh316: THREE.Mesh
    Mesh316_1: THREE.Mesh
    Mesh322: THREE.Mesh
    Mesh322_1: THREE.Mesh
    Mesh322_2: THREE.Mesh
    Cube001_1: THREE.Mesh
    Cube001_2: THREE.Mesh
    Cube002: THREE.Mesh
    Cube006: THREE.Mesh
    Cube006_1: THREE.Mesh
    Cube006_2: THREE.Mesh
    Cube006_3: THREE.Mesh
    Cube007: THREE.Mesh
    Cube007_1: THREE.Mesh
    Cube007_2: THREE.Mesh
    Cube007_3: THREE.Mesh
    // Cube007: THREE.Mesh
    // Cube007_1: THREE.Mesh
    // Cube007_2: THREE.Mesh
    // Cube007_3: THREE.Mesh
    polySurface494001: THREE.Mesh
    polySurface539001: THREE.Mesh
    Mesh355: THREE.Mesh
    Mesh355_1: THREE.Mesh
    Mesh355_2: THREE.Mesh
    polySurface539002: THREE.Mesh
    Mesh411: THREE.Mesh
    Mesh411_1: THREE.Mesh
    Mesh411_2: THREE.Mesh
    polySurface493004: THREE.Mesh
    polySurface539004: THREE.Mesh
    polySurface563004: THREE.Mesh
    polySurface564004: THREE.Mesh
    Mesh467: THREE.Mesh
    Mesh467_1: THREE.Mesh
    Mesh467_2: THREE.Mesh
  }
  materials: {
    PaletteMaterial001: THREE.MeshStandardMaterial
    ['Material.007']: THREE.MeshStandardMaterial
    ['Material.011']: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('./newRS-transformed.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh name="polySurface61" geometry={nodes.polySurface61.geometry} material={materials.PaletteMaterial001} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh name="polySurface21" geometry={nodes.polySurface21.geometry} material={materials.PaletteMaterial001} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh name="polySurface128" geometry={nodes.polySurface128.geometry} material={materials.PaletteMaterial001} position={[0, 0, 0.006]} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh name="Shop_8" geometry={nodes.Shop_8.geometry} material={materials.PaletteMaterial001} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh name="polySurface124" geometry={nodes.polySurface124.geometry} material={materials.PaletteMaterial001} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh name="pillers_L1" geometry={nodes.pillers_L1.geometry} material={materials.PaletteMaterial001} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh name="polySurface101" geometry={nodes.polySurface101.geometry} material={materials.PaletteMaterial001} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh name="polySurface132" geometry={nodes.polySurface132.geometry} material={materials.PaletteMaterial001} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh name="polySurface102" geometry={nodes.polySurface102.geometry} material={materials.PaletteMaterial001} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh name="polySurface23" geometry={nodes.polySurface23.geometry} material={materials.PaletteMaterial001} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh name="polySurface114" geometry={nodes.polySurface114.geometry} material={materials.PaletteMaterial001} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh name="polySurface24" geometry={nodes.polySurface24.geometry} material={materials.PaletteMaterial001} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh name="polySurface91" geometry={nodes.polySurface91.geometry} material={materials.PaletteMaterial001} position={[0, 0, 0.004]} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh name="polySurface111" geometry={nodes.polySurface111.geometry} material={materials.PaletteMaterial001} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh name="polySurface117" geometry={nodes.polySurface117.geometry} material={materials.PaletteMaterial001} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh name="polySurface92" geometry={nodes.polySurface92.geometry} material={materials.PaletteMaterial001} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh name="Piller_Left_M1" geometry={nodes.Piller_Left_M1.geometry} material={materials.PaletteMaterial001} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh name="polySurface90" geometry={nodes.polySurface90.geometry} material={materials.PaletteMaterial001} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh name="polySurface104" geometry={nodes.polySurface104.geometry} material={materials.PaletteMaterial001} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh name="polySurface94" geometry={nodes.polySurface94.geometry} material={materials.PaletteMaterial001} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh name="polySurface96" geometry={nodes.polySurface96.geometry} material={materials.PaletteMaterial001} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh name="polySurface110" geometry={nodes.polySurface110.geometry} material={materials.PaletteMaterial001} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh name="polySurface66" geometry={nodes.polySurface66.geometry} material={materials.PaletteMaterial001} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh name="polySurface67" geometry={nodes.polySurface67.geometry} material={materials.PaletteMaterial001} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh name="polySurface97" geometry={nodes.polySurface97.geometry} material={materials.PaletteMaterial001} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh name="polySurface93" geometry={nodes.polySurface93.geometry} material={materials.PaletteMaterial001} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh name="polySurface18" geometry={nodes.polySurface18.geometry} material={materials.PaletteMaterial001} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh name="polySurface115" geometry={nodes.polySurface115.geometry} material={materials.PaletteMaterial001} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh name="polySurface106" geometry={nodes.polySurface106.geometry} material={materials.PaletteMaterial001} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh name="Railings_L1" geometry={nodes.Railings_L1.geometry} material={materials.PaletteMaterial001} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh name="polySurface116" geometry={nodes.polySurface116.geometry} material={materials.PaletteMaterial001} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh name="polySurface63" geometry={nodes.polySurface63.geometry} material={materials.PaletteMaterial001} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh name="polySurface68" geometry={nodes.polySurface68.geometry} material={materials.PaletteMaterial001} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh name="polySurface5" geometry={nodes.polySurface5.geometry} material={materials.PaletteMaterial001} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh name="Support_M" geometry={nodes.Support_M.geometry} material={materials.PaletteMaterial001} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh name="polySurface20" geometry={nodes.polySurface20.geometry} material={materials.PaletteMaterial001} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh name="polySurface26" geometry={nodes.polySurface26.geometry} material={materials.PaletteMaterial001} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh name="polySurface64" geometry={nodes.polySurface64.geometry} material={materials.PaletteMaterial001} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh name="Support_L1" geometry={nodes.Support_L1.geometry} material={materials.PaletteMaterial001} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh name="polySurface112" geometry={nodes.polySurface112.geometry} material={materials.PaletteMaterial001} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh name="polySurface27" geometry={nodes.polySurface27.geometry} material={materials.PaletteMaterial001} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh name="polySurface10" geometry={nodes.polySurface10.geometry} material={materials.PaletteMaterial001} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh name="Stairs_M" geometry={nodes.Stairs_M.geometry} material={materials.PaletteMaterial001} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh name="Shop_21" geometry={nodes.Shop_21.geometry} material={materials.PaletteMaterial001} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh name="polySurface17" geometry={nodes.polySurface17.geometry} material={materials.PaletteMaterial001} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh name="polySurface25" geometry={nodes.polySurface25.geometry} material={materials.PaletteMaterial001} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh name="polySurface6" geometry={nodes.polySurface6.geometry} material={materials.PaletteMaterial001} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh name="polySurface15" geometry={nodes.polySurface15.geometry} material={materials.PaletteMaterial001} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh name="polySurface4" geometry={nodes.polySurface4.geometry} material={materials.PaletteMaterial001} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh name="Stairs_L1" geometry={nodes.Stairs_L1.geometry} material={materials.PaletteMaterial001} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh name="polySurface29" geometry={nodes.polySurface29.geometry} material={materials.PaletteMaterial001} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh name="polySurface58" geometry={nodes.polySurface58.geometry} material={materials.PaletteMaterial001} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh name="Stair_roof_L1" geometry={nodes.Stair_roof_L1.geometry} material={materials['Material.007']} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh name="polySurface77" geometry={nodes.polySurface77.geometry} material={materials.PaletteMaterial001} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh name="polySurface16" geometry={nodes.polySurface16.geometry} material={materials.PaletteMaterial001} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh name="Shop_15" geometry={nodes.Shop_15.geometry} material={materials.PaletteMaterial001} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh name="polySurface19" geometry={nodes.polySurface19.geometry} material={materials.PaletteMaterial001} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh name="polySurface14" geometry={nodes.polySurface14.geometry} material={materials.PaletteMaterial001} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh name="polySurface8" geometry={nodes.polySurface8.geometry} material={materials.PaletteMaterial001} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh name="polySurface9" geometry={nodes.polySurface9.geometry} material={materials.PaletteMaterial001} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh name="polySurface28" geometry={nodes.polySurface28.geometry} material={materials.PaletteMaterial001} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh name="polySurface22" geometry={nodes.polySurface22.geometry} material={materials.PaletteMaterial001} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh name="polySurface13" geometry={nodes.polySurface13.geometry} material={materials.PaletteMaterial001} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh name="Roof_M" geometry={nodes.Roof_M.geometry} material={materials['Material.007']} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh name="Fob_Mid_Railings_M2" geometry={nodes.Fob_Mid_Railings_M2.geometry} material={materials.PaletteMaterial001} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh name="polySurface486" geometry={nodes.polySurface486.geometry} material={materials.PaletteMaterial001} position={[0.137, 0, 0]} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh name="polySurface508" geometry={nodes.polySurface508.geometry} material={materials.PaletteMaterial001} position={[0.137, 0, 0]} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh name="polySurface509" geometry={nodes.polySurface509.geometry} material={materials.PaletteMaterial001} position={[0.137, 0, 0]} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh name="polySurface513" geometry={nodes.polySurface513.geometry} material={materials.PaletteMaterial001} position={[0.137, 0, 0]} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh name="polySurface518" geometry={nodes.polySurface518.geometry} material={materials.PaletteMaterial001} position={[0.137, 0, 0]} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh name="polySurface523" geometry={nodes.polySurface523.geometry} material={materials.PaletteMaterial001} position={[0.137, 0, 0]} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh name="polySurface525" geometry={nodes.polySurface525.geometry} material={materials.PaletteMaterial001} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh name="polySurface560" geometry={nodes.polySurface560.geometry} material={materials.PaletteMaterial001} position={[0.137, 0, 0]} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh name="polySurface562" geometry={nodes.polySurface562.geometry} material={materials.PaletteMaterial001} position={[0.137, 0, 0]} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh name="polySurface569" geometry={nodes.polySurface569.geometry} material={materials.PaletteMaterial001} position={[0.137, 0, 0]} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh name="polySurface401" geometry={nodes.polySurface401.geometry} material={materials.PaletteMaterial001} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh name="polySurface402" geometry={nodes.polySurface402.geometry} material={materials.PaletteMaterial001} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh name="polySurface404" geometry={nodes.polySurface404.geometry} material={materials.PaletteMaterial001} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh name="polySurface405" geometry={nodes.polySurface405.geometry} material={materials.PaletteMaterial001} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh name="polySurface406" geometry={nodes.polySurface406.geometry} material={materials['Material.007']} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh name="polySurface407" geometry={nodes.polySurface407.geometry} material={materials.PaletteMaterial001} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh name="polySurface408" geometry={nodes.polySurface408.geometry} material={materials.PaletteMaterial001} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh name="polySurface410" geometry={nodes.polySurface410.geometry} material={materials.PaletteMaterial001} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh name="polySurface411" geometry={nodes.polySurface411.geometry} material={materials.PaletteMaterial001} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh name="polySurface412" geometry={nodes.polySurface412.geometry} material={materials.PaletteMaterial001} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh name="polySurface413" geometry={nodes.polySurface413.geometry} material={materials.PaletteMaterial001} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh name="polySurface417" geometry={nodes.polySurface417.geometry} material={materials.PaletteMaterial001} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh name="polySurface418" geometry={nodes.polySurface418.geometry} material={materials.PaletteMaterial001} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh name="polySurface419" geometry={nodes.polySurface419.geometry} material={materials.PaletteMaterial001} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh name="polySurface423" geometry={nodes.polySurface423.geometry} material={materials.PaletteMaterial001} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh name="polySurface424" geometry={nodes.polySurface424.geometry} material={materials.PaletteMaterial001} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh name="polySurface425" geometry={nodes.polySurface425.geometry} material={materials.PaletteMaterial001} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh name="polySurface426" geometry={nodes.polySurface426.geometry} material={materials.PaletteMaterial001} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh name="polySurface427" geometry={nodes.polySurface427.geometry} material={materials.PaletteMaterial001} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh name="polySurface428" geometry={nodes.polySurface428.geometry} material={materials.PaletteMaterial001} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh name="polySurface429" geometry={nodes.polySurface429.geometry} material={materials.PaletteMaterial001} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh name="polySurface431" geometry={nodes.polySurface431.geometry} material={materials.PaletteMaterial001} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh name="polySurface433" geometry={nodes.polySurface433.geometry} material={materials.PaletteMaterial001} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh name="polySurface434" geometry={nodes.polySurface434.geometry} material={materials.PaletteMaterial001} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh name="polySurface435" geometry={nodes.polySurface435.geometry} material={materials.PaletteMaterial001} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh name="polySurface438" geometry={nodes.polySurface438.geometry} material={materials.PaletteMaterial001} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh name="polySurface439" geometry={nodes.polySurface439.geometry} material={materials.PaletteMaterial001} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh name="polySurface440" geometry={nodes.polySurface440.geometry} material={materials.PaletteMaterial001} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh name="polySurface444" geometry={nodes.polySurface444.geometry} material={materials.PaletteMaterial001} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh name="polySurface445" geometry={nodes.polySurface445.geometry} material={materials.PaletteMaterial001} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh name="polySurface446" geometry={nodes.polySurface446.geometry} material={materials.PaletteMaterial001} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh name="polySurface447" geometry={nodes.polySurface447.geometry} material={materials.PaletteMaterial001} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh name="polySurface449" geometry={nodes.polySurface449.geometry} material={materials.PaletteMaterial001} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh name="polySurface450" geometry={nodes.polySurface450.geometry} material={materials.PaletteMaterial001} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh name="polySurface451" geometry={nodes.polySurface451.geometry} material={materials.PaletteMaterial001} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh name="polySurface452" geometry={nodes.polySurface452.geometry} material={materials.PaletteMaterial001} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh name="polySurface453" geometry={nodes.polySurface453.geometry} material={materials.PaletteMaterial001} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh name="polySurface454" geometry={nodes.polySurface454.geometry} material={materials['Material.007']} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh name="polySurface456" geometry={nodes.polySurface456.geometry} material={materials.PaletteMaterial001} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh name="polySurface459" geometry={nodes.polySurface459.geometry} material={materials.PaletteMaterial001} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh name="polySurface465" geometry={nodes.polySurface465.geometry} material={materials.PaletteMaterial001} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh name="polySurface467" geometry={nodes.polySurface467.geometry} material={materials.PaletteMaterial001} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh name="polySurface468" geometry={nodes.polySurface468.geometry} material={materials.PaletteMaterial001} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh name="polySurface470" geometry={nodes.polySurface470.geometry} material={materials.PaletteMaterial001} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh name="polySurface472" geometry={nodes.polySurface472.geometry} material={materials.PaletteMaterial001} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh name="polySurface473" geometry={nodes.polySurface473.geometry} material={materials.PaletteMaterial001} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh name="polySurface475" geometry={nodes.polySurface475.geometry} material={materials.PaletteMaterial001} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh name="polySurface476" geometry={nodes.polySurface476.geometry} material={materials.PaletteMaterial001} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh name="polySurface478" geometry={nodes.polySurface478.geometry} material={materials.PaletteMaterial001} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh name="polySurface479" geometry={nodes.polySurface479.geometry} material={materials.PaletteMaterial001} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh name="polySurface480" geometry={nodes.polySurface480.geometry} material={materials.PaletteMaterial001} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh name="polySurface484" geometry={nodes.polySurface484.geometry} material={materials.PaletteMaterial001} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh name="polySurface312" geometry={nodes.polySurface312.geometry} material={materials.PaletteMaterial001} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh name="polySurface313" geometry={nodes.polySurface313.geometry} material={materials.PaletteMaterial001} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh name="polySurface314" geometry={nodes.polySurface314.geometry} material={materials.PaletteMaterial001} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh name="polySurface318" geometry={nodes.polySurface318.geometry} material={materials.PaletteMaterial001} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh name="polySurface320" geometry={nodes.polySurface320.geometry} material={materials.PaletteMaterial001} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh name="polySurface321" geometry={nodes.polySurface321.geometry} material={materials.PaletteMaterial001} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh name="polySurface323" geometry={nodes.polySurface323.geometry} material={materials['Material.007']} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh name="polySurface325" geometry={nodes.polySurface325.geometry} material={materials.PaletteMaterial001} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh name="polySurface327" geometry={nodes.polySurface327.geometry} material={materials.PaletteMaterial001} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh name="polySurface329" geometry={nodes.polySurface329.geometry} material={materials.PaletteMaterial001} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh name="polySurface330" geometry={nodes.polySurface330.geometry} material={materials.PaletteMaterial001} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh name="polySurface331" geometry={nodes.polySurface331.geometry} material={materials.PaletteMaterial001} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh name="polySurface332" geometry={nodes.polySurface332.geometry} material={materials.PaletteMaterial001} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh name="polySurface333" geometry={nodes.polySurface333.geometry} material={materials.PaletteMaterial001} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh name="polySurface334" geometry={nodes.polySurface334.geometry} material={materials.PaletteMaterial001} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh name="polySurface335" geometry={nodes.polySurface335.geometry} material={materials.PaletteMaterial001} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh name="polySurface337" geometry={nodes.polySurface337.geometry} material={materials.PaletteMaterial001} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh name="polySurface339" geometry={nodes.polySurface339.geometry} material={materials.PaletteMaterial001} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh name="polySurface342" geometry={nodes.polySurface342.geometry} material={materials.PaletteMaterial001} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh name="polySurface345" geometry={nodes.polySurface345.geometry} material={materials.PaletteMaterial001} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh name="polySurface347" geometry={nodes.polySurface347.geometry} material={materials.PaletteMaterial001} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh name="polySurface348" geometry={nodes.polySurface348.geometry} material={materials.PaletteMaterial001} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh name="polySurface350" geometry={nodes.polySurface350.geometry} material={materials.PaletteMaterial001} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh name="polySurface353" geometry={nodes.polySurface353.geometry} material={materials.PaletteMaterial001} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh name="polySurface355" geometry={nodes.polySurface355.geometry} material={materials.PaletteMaterial001} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh name="polySurface358" geometry={nodes.polySurface358.geometry} material={materials.PaletteMaterial001} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh name="polySurface359" geometry={nodes.polySurface359.geometry} material={materials.PaletteMaterial001} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh name="polySurface360" geometry={nodes.polySurface360.geometry} material={materials.PaletteMaterial001} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh name="polySurface362" geometry={nodes.polySurface362.geometry} material={materials.PaletteMaterial001} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh name="polySurface363" geometry={nodes.polySurface363.geometry} material={materials.PaletteMaterial001} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh name="polySurface365" geometry={nodes.polySurface365.geometry} material={materials.PaletteMaterial001} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh name="polySurface367" geometry={nodes.polySurface367.geometry} material={materials.PaletteMaterial001} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh name="polySurface369" geometry={nodes.polySurface369.geometry} material={materials.PaletteMaterial001} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh name="polySurface370" geometry={nodes.polySurface370.geometry} material={materials.PaletteMaterial001} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh name="polySurface371" geometry={nodes.polySurface371.geometry} material={materials.PaletteMaterial001} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh name="polySurface372" geometry={nodes.polySurface372.geometry} material={materials.PaletteMaterial001} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh name="polySurface373" geometry={nodes.polySurface373.geometry} material={materials.PaletteMaterial001} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh name="polySurface374" geometry={nodes.polySurface374.geometry} material={materials.PaletteMaterial001} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh name="polySurface377" geometry={nodes.polySurface377.geometry} material={materials.PaletteMaterial001} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh name="polySurface378" geometry={nodes.polySurface378.geometry} material={materials.PaletteMaterial001} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh name="polySurface379" geometry={nodes.polySurface379.geometry} material={materials.PaletteMaterial001} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh name="polySurface380" geometry={nodes.polySurface380.geometry} material={materials.PaletteMaterial001} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh name="polySurface381" geometry={nodes.polySurface381.geometry} material={materials.PaletteMaterial001} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh name="polySurface382" geometry={nodes.polySurface382.geometry} material={materials.PaletteMaterial001} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh name="polySurface383" geometry={nodes.polySurface383.geometry} material={materials.PaletteMaterial001} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh name="polySurface386" geometry={nodes.polySurface386.geometry} material={materials.PaletteMaterial001} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh name="polySurface387" geometry={nodes.polySurface387.geometry} material={materials.PaletteMaterial001} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh name="polySurface388" geometry={nodes.polySurface388.geometry} material={materials.PaletteMaterial001} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh name="polySurface390" geometry={nodes.polySurface390.geometry} material={materials.PaletteMaterial001} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh name="polySurface391" geometry={nodes.polySurface391.geometry} material={materials.PaletteMaterial001} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh name="polySurface392" geometry={nodes.polySurface392.geometry} material={materials.PaletteMaterial001} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh name="polySurface394" geometry={nodes.polySurface394.geometry} material={materials.PaletteMaterial001} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh name="polySurface396" geometry={nodes.polySurface396.geometry} material={materials.PaletteMaterial001} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh name="polySurface397" geometry={nodes.polySurface397.geometry} material={materials.PaletteMaterial001} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh name="polySurface398" geometry={nodes.polySurface398.geometry} material={materials.PaletteMaterial001} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh name="polySurface399" geometry={nodes.polySurface399.geometry} material={materials.PaletteMaterial001} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <group name="pCube4" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
        <mesh name="Mesh316" geometry={nodes.Mesh316.geometry} material={materials.PaletteMaterial001} />
        <mesh name="Mesh316_1" geometry={nodes.Mesh316_1.geometry} material={materials['Material.007']} />
      </group>
      <group name="polySurface577" position={[0.137, 0, 0]} rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
        <mesh name="Mesh322" geometry={nodes.Mesh322.geometry} material={materials.PaletteMaterial001} />
        <mesh name="Mesh322_1" geometry={nodes.Mesh322_1.geometry} material={materials.PaletteMaterial001} />
        <mesh name="Mesh322_2" geometry={nodes.Mesh322_2.geometry} material={materials.PaletteMaterial001} />
      </group>
      <group name="Cube001" position={[0.591, 0.018, 0.223]} scale={[0.052, 0.031, 0.052]}>
        <mesh name="Cube001_1" geometry={nodes.Cube001_1.geometry} material={materials.PaletteMaterial001} />
        <mesh name="Cube001_2" geometry={nodes.Cube001_2.geometry} material={materials.PaletteMaterial001} />
      </group>
      <mesh name="Cube002" geometry={nodes.Cube002.geometry} material={materials.PaletteMaterial001} position={[0.497, -0.002, 0.352]} rotation={[-Math.PI, 0, -Math.PI]} scale={[-0.181, -0.002, -0.181]} />
      <group name="Cube005" position={[1.174, 0.011, -0.026]} scale={[0, 0.006, 0.013]}>
        <mesh name="Cube006" geometry={nodes.Cube006.geometry} material={materials.PaletteMaterial001} />
        <mesh name="Cube006_1" geometry={nodes.Cube006_1.geometry} material={materials['Material.011']} />
        <mesh name="Cube006_2" geometry={nodes.Cube006_2.geometry} material={materials.PaletteMaterial001} />
        <mesh name="Cube006_3" geometry={nodes.Cube006_3.geometry} material={materials.PaletteMaterial001} />
      </group>
      <group name="Cube003" position={[1.183, 0.011, 0.149]} scale={[0, 0.006, 0.013]}>
        <mesh name="Cube007" geometry={nodes.Cube007.geometry} material={materials.PaletteMaterial001} />
        <mesh name="Cube007_1" geometry={nodes.Cube007_1.geometry} material={materials['Material.011']} />
        <mesh name="Cube007_2" geometry={nodes.Cube007_2.geometry} material={materials.PaletteMaterial001} />
        <mesh name="Cube007_3" geometry={nodes.Cube007_3.geometry} material={materials.PaletteMaterial001} />
      </group>
      <group name="Cube004" position={[1.138, 0.011, -0.207]} scale={[0, 0.006, 0.013]}>
        <mesh name="Cube007" geometry={nodes.Cube007.geometry} material={materials.PaletteMaterial001} />
        <mesh name="Cube007_1" geometry={nodes.Cube007_1.geometry} material={materials['Material.011']} />
        <mesh name="Cube007_2" geometry={nodes.Cube007_2.geometry} material={materials.PaletteMaterial001} />
        <mesh name="Cube007_3" geometry={nodes.Cube007_3.geometry} material={materials.PaletteMaterial001} />
      </group>
      <mesh name="polySurface494001" geometry={nodes.polySurface494001.geometry} material={materials.PaletteMaterial001} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh name="polySurface539001" geometry={nodes.polySurface539001.geometry} material={materials['Material.007']} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <group name="polySurface578001" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
        <mesh name="Mesh355" geometry={nodes.Mesh355.geometry} material={materials.PaletteMaterial001} />
        <mesh name="Mesh355_1" geometry={nodes.Mesh355_1.geometry} material={materials.PaletteMaterial001} />
        <mesh name="Mesh355_2" geometry={nodes.Mesh355_2.geometry} material={materials.PaletteMaterial001} />
      </group>
      <mesh name="polySurface539002" geometry={nodes.polySurface539002.geometry} material={materials['Material.007']} position={[0, 0, 0.178]} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <group name="polySurface578003" position={[0, 0, 0.355]} rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
        <mesh name="Mesh411" geometry={nodes.Mesh411.geometry} material={materials.PaletteMaterial001} />
        <mesh name="Mesh411_1" geometry={nodes.Mesh411_1.geometry} material={materials.PaletteMaterial001} />
        <mesh name="Mesh411_2" geometry={nodes.Mesh411_2.geometry} material={materials.PaletteMaterial001} />
      </group>
      <mesh name="polySurface493004" geometry={nodes.polySurface493004.geometry} material={materials.PaletteMaterial001} position={[0.138, 0, 0.506]} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh name="polySurface539004" geometry={nodes.polySurface539004.geometry} material={materials['Material.007']} position={[0.138, 0, 0.506]} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh name="polySurface563004" geometry={nodes.polySurface563004.geometry} material={materials.PaletteMaterial001} position={[0.138, 0, 0.506]} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh name="polySurface564004" geometry={nodes.polySurface564004.geometry} material={materials.PaletteMaterial001} position={[0.138, 0, 0.506]} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <group name="polySurface578002" position={[-0.008, 0, 0.18]} rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
        <mesh name="Mesh467" geometry={nodes.Mesh467.geometry} material={materials.PaletteMaterial001} />
        <mesh name="Mesh467_1" geometry={nodes.Mesh467_1.geometry} material={materials.PaletteMaterial001} />
        <mesh name="Mesh467_2" geometry={nodes.Mesh467_2.geometry} material={materials.PaletteMaterial001} />
      </group>
    </group>
  )
}

useGLTF.preload('./newRS-transformed.glb')
