/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 --keepmeshes --resolution 1024 --keepnames --types --output ./OldRailwayStation.tsx --transform ./oldRailwayStation.gltf 
Files: ./oldRailwayStation.gltf [9.68KB] > /home/cronabit/Desktop/RailwayStation/oldRailwayStation-transformed.glb [1.39MB] (-14214%)
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    polySurface3: THREE.Mesh
    polySurface2: THREE.Mesh
    pCube21: THREE.Mesh
    polySurface7: THREE.Mesh
    polySurface4: THREE.Mesh
    group2_pCube28: THREE.Mesh
  }
  materials: {
    ['Soil Forest']: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('./oldRailwayStation-transformed.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh name="polySurface3" geometry={nodes.polySurface3.geometry} material={materials['Soil Forest']} rotation={[Math.PI / 2, 0, 0]} scale={0.091} />
      <mesh name="polySurface2" geometry={nodes.polySurface2.geometry} material={materials['Soil Forest']} rotation={[Math.PI / 2, 0, 0]} scale={0.091} />
      <mesh name="pCube21" geometry={nodes.pCube21.geometry} material={materials['Soil Forest']} rotation={[Math.PI / 2, 0, 0]} scale={0.091} />
      <mesh name="polySurface7" geometry={nodes.polySurface7.geometry} material={materials['Soil Forest']} rotation={[Math.PI / 2, 0, 0]} scale={0.091} />
      <mesh name="polySurface4" geometry={nodes.polySurface4.geometry} material={materials['Soil Forest']} rotation={[Math.PI / 2, 0, 0]} scale={0.091} />
      <mesh name="group2_pCube28" geometry={nodes.group2_pCube28.geometry} material={materials['Soil Forest']} rotation={[Math.PI / 2, 0, 0]} scale={0.091} />
    </group>
  )
}

useGLTF.preload('./oldRailwayStation-transformed.glb')
