/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 --keepmeshes --resolution 1024 --keepnames --types --output ./PackedBridge.tsx --transform ./packedBridge.gltf 
Files: ./packedBridge.gltf [3.43KB] > /home/cronabit/Desktop/PackedBridge/packedBridge-transformed.glb [3.97KB] (-16%)
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Bridge: THREE.Mesh
    Bridge_Support_1: THREE.Mesh
  }
  materials: {
    lambert2: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('./packedBridge-transformed.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh name="Bridge" geometry={nodes.Bridge.geometry} material={materials.lambert2} position={[141.774, 0, 0]} rotation={[Math.PI / 2, 0, 0]} scale={25.787} />
      <mesh name="Bridge_Support_1" geometry={nodes.Bridge_Support_1.geometry} material={materials.lambert2} position={[-116.097, 0, 0]} rotation={[Math.PI / 2, 0, 0]} scale={25.787} />
    </group>
  )
}

useGLTF.preload('./packedBridge-transformed.glb')
