/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 --resolution 1204 --types --output ./src/models/PepsiFridgeModel.tsx --transform ./src-models/pepsi-fridge/pepsi-fridge.gltf 
Files: ./src-models/pepsi-fridge/pepsi-fridge.gltf [24.47KB] > D:\Work\train-sim\src\models\pepsi-fridge-transformed.glb [353.18KB] (-1343%)
Author: AJ_AY (https://sketchfab.com/AJAY.K)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/pepsi-fridge-indian-fridge-model-free-by-ajay-f4e2137d8296440f9703b430c6ab4124
Title: Pepsi fridge indian Fridge Model Free By Ajay
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    door_Material008_0: THREE.Mesh
    door_Material007_0: THREE.Mesh
    body_Material003_0: THREE.Mesh
    body_Material004_0: THREE.Mesh
    body_Material005_0: THREE.Mesh
    body_Material009_0: THREE.Mesh
    body_Material002_0: THREE.Mesh
  }
  materials: {
    ['Material.008']: THREE.MeshStandardMaterial
    ['Material.007']: THREE.MeshStandardMaterial
    ['Material.003']: THREE.MeshStandardMaterial
    ['Material.004']: THREE.MeshStandardMaterial
    ['Material.005']: THREE.MeshStandardMaterial
    ['Material.009']: THREE.MeshStandardMaterial
    ['Material.002']: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/pepsi-fridge-transformed.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.door_Material008_0.geometry} material={materials['Material.008']} position={[-3.495, 2.641, -0.002]} rotation={[-Math.PI / 2, 0, 0]} scale={0.819} />
      <mesh geometry={nodes.door_Material007_0.geometry} material={materials['Material.007']} position={[-3.495, 2.641, -0.002]} rotation={[-Math.PI / 2, 0, 0]} scale={0.819} />
      <mesh geometry={nodes.body_Material003_0.geometry} material={materials['Material.003']} position={[-3.34, 4.108, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={[0.729, 0.729, 1.415]} />
      <mesh geometry={nodes.body_Material004_0.geometry} material={materials['Material.004']} position={[-3.34, 4.108, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={[0.729, 0.729, 1.415]} />
      <mesh geometry={nodes.body_Material005_0.geometry} material={materials['Material.005']} position={[-3.34, 4.108, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={[0.729, 0.729, 1.415]} />
      <mesh geometry={nodes.body_Material009_0.geometry} material={materials['Material.009']} position={[-3.34, 4.108, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={[0.729, 0.729, 1.415]} />
      <mesh geometry={nodes.body_Material002_0.geometry} material={materials['Material.002']} position={[-3.34, 4.108, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={[0.729, 0.729, 1.415]} />
    </group>
  )
}

useGLTF.preload('/pepsi-fridge-transformed.glb')
