/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 --keepmeshes --resolution 1024 --keepnames --types --output ./RailwayCrossing.tsx --transform ./RailwayCrossing.gltf 
Files: ./RailwayCrossing.gltf [56.65KB] > /home/cronabit/Desktop/RailwayCrossing/RailwayCrossing-transformed.glb [58.18KB] (-3%)
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Ring_12: THREE.Mesh
    STOP_1: THREE.Mesh
    STOP_2: THREE.Mesh
    Ring_13: THREE.Mesh
    Bolt_2: THREE.Mesh
    Bolt_8: THREE.Mesh
    Bolt_13: THREE.Mesh
    Bolt_33: THREE.Mesh
    Bolt_16: THREE.Mesh
    Bolt_17: THREE.Mesh
    Bolt_20: THREE.Mesh
    Bolt_15: THREE.Mesh
    Bolt_3: THREE.Mesh
    Bolt_4: THREE.Mesh
    Bolt_21: THREE.Mesh
    Bolt_10: THREE.Mesh
    Bolt_29: THREE.Mesh
    Bolt_5: THREE.Mesh
    Bolt_19: THREE.Mesh
    Side_Support1: THREE.Mesh
    Bolt_32: THREE.Mesh
    Bolt_26: THREE.Mesh
    Bolt_14: THREE.Mesh
    Bolt_11: THREE.Mesh
    Bolt_9: THREE.Mesh
    Bolt_27: THREE.Mesh
    Bolt_18: THREE.Mesh
    Bolt_6: THREE.Mesh
    Bolt_23: THREE.Mesh
    Bolt_31: THREE.Mesh
    Bolt_7: THREE.Mesh
    Side1: THREE.Mesh
    Bolt_30: THREE.Mesh
    main1: THREE.Mesh
    Bolt_24: THREE.Mesh
    Bolt_25: THREE.Mesh
    Bolt_1: THREE.Mesh
    Bolt_28: THREE.Mesh
    Bolt_34: THREE.Mesh
    Bolt_12: THREE.Mesh
    main_pole: THREE.Mesh
    Bolt_22: THREE.Mesh
    Side: THREE.Mesh
    Cube: THREE.Mesh
  }
  materials: {
    ['Material.004']: THREE.MeshStandardMaterial
    ['Material.002']: THREE.MeshStandardMaterial
    lambert1: THREE.MeshStandardMaterial
    ['Material.001']: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('./RailwayCrossing-transformed.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh name="Ring_12" geometry={nodes.Ring_12.geometry} material={materials['Material.004']} position={[0.002, 0, 0]} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh name="STOP_1" geometry={nodes.STOP_1.geometry} material={materials['Material.002']} position={[0.002, 0, 0]} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh name="STOP_2" geometry={nodes.STOP_2.geometry} material={materials['Material.002']} position={[0.002, 0, 0]} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh name="Ring_13" geometry={nodes.Ring_13.geometry} material={materials['Material.004']} position={[0.002, 0, 0]} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh name="Bolt_2" geometry={nodes.Bolt_2.geometry} material={materials['Material.004']} position={[0.002, 0, 0]} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh name="Bolt_8" geometry={nodes.Bolt_8.geometry} material={materials.lambert1} position={[0.002, 0, 0]} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh name="Bolt_13" geometry={nodes.Bolt_13.geometry} material={materials.lambert1} position={[0.002, 0, 0]} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh name="Bolt_33" geometry={nodes.Bolt_33.geometry} material={materials.lambert1} position={[0.002, 0, 0]} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh name="Bolt_16" geometry={nodes.Bolt_16.geometry} material={materials['Material.004']} position={[0.002, 0, 0]} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh name="Bolt_17" geometry={nodes.Bolt_17.geometry} material={materials.lambert1} position={[0.002, 0, 0]} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh name="Bolt_20" geometry={nodes.Bolt_20.geometry} material={materials['Material.004']} position={[0.002, 0, 0]} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh name="Bolt_15" geometry={nodes.Bolt_15.geometry} material={materials.lambert1} position={[0.002, 0, 0]} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh name="Bolt_3" geometry={nodes.Bolt_3.geometry} material={materials['Material.004']} position={[0.002, 0, 0]} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh name="Bolt_4" geometry={nodes.Bolt_4.geometry} material={materials['Material.004']} position={[0.002, 0, 0]} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh name="Bolt_21" geometry={nodes.Bolt_21.geometry} material={materials['Material.004']} position={[0.002, 0, 0]} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh name="Bolt_10" geometry={nodes.Bolt_10.geometry} material={materials['Material.004']} position={[0.002, 0, 0]} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh name="Bolt_29" geometry={nodes.Bolt_29.geometry} material={materials['Material.004']} position={[0.002, 0, 0]} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh name="Bolt_5" geometry={nodes.Bolt_5.geometry} material={materials['Material.004']} position={[0.002, 0, 0]} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh name="Bolt_19" geometry={nodes.Bolt_19.geometry} material={materials['Material.004']} position={[0.002, 0, 0]} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh name="Side_Support1" geometry={nodes.Side_Support1.geometry} material={materials['Material.004']} position={[0.002, 0, 0]} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh name="Bolt_32" geometry={nodes.Bolt_32.geometry} material={materials.lambert1} position={[0.002, 0, 0]} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh name="Bolt_26" geometry={nodes.Bolt_26.geometry} material={materials['Material.004']} position={[0.002, 0, 0]} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh name="Bolt_14" geometry={nodes.Bolt_14.geometry} material={materials.lambert1} position={[0.002, 0, 0]} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh name="Bolt_11" geometry={nodes.Bolt_11.geometry} material={materials['Material.004']} position={[0.002, 0, 0]} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh name="Bolt_9" geometry={nodes.Bolt_9.geometry} material={materials.lambert1} position={[0.002, 0, 0]} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh name="Bolt_27" geometry={nodes.Bolt_27.geometry} material={materials['Material.004']} position={[0.002, 0, 0]} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh name="Bolt_18" geometry={nodes.Bolt_18.geometry} material={materials['Material.004']} position={[0.002, 0, 0]} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh name="Bolt_6" geometry={nodes.Bolt_6.geometry} material={materials['Material.004']} position={[0.002, 0, 0]} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh name="Bolt_23" geometry={nodes.Bolt_23.geometry} material={materials['Material.004']} position={[0.002, 0, 0]} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh name="Bolt_31" geometry={nodes.Bolt_31.geometry} material={materials.lambert1} position={[0.002, 0, 0]} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh name="Bolt_7" geometry={nodes.Bolt_7.geometry} material={materials['Material.004']} position={[0.002, 0, 0]} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh name="Side1" geometry={nodes.Side1.geometry} material={materials['Material.004']} position={[0.002, 0, 0]} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh name="Bolt_30" geometry={nodes.Bolt_30.geometry} material={materials['Material.004']} position={[0.002, 0, 0]} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh name="main1" geometry={nodes.main1.geometry} material={materials['Material.004']} position={[0.002, 0, 0]} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh name="Bolt_24" geometry={nodes.Bolt_24.geometry} material={materials.lambert1} position={[0.002, 0, 0]} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh name="Bolt_25" geometry={nodes.Bolt_25.geometry} material={materials['Material.004']} position={[0.002, 0, 0]} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh name="Bolt_1" geometry={nodes.Bolt_1.geometry} material={materials['Material.004']} position={[0.002, 0, 0]} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh name="Bolt_28" geometry={nodes.Bolt_28.geometry} material={materials['Material.004']} position={[0.002, 0, 0]} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh name="Bolt_34" geometry={nodes.Bolt_34.geometry} material={materials.lambert1} position={[0.002, 0, 0]} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh name="Bolt_12" geometry={nodes.Bolt_12.geometry} material={materials.lambert1} position={[0.002, 0, 0]} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh name="main_pole" geometry={nodes.main_pole.geometry} material={materials['Material.001']} position={[0.002, 0, 0]} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh name="Bolt_22" geometry={nodes.Bolt_22.geometry} material={materials['Material.004']} position={[0.002, 0, 0]} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh name="Side" geometry={nodes.Side.geometry} material={materials['Material.004']} position={[0.002, 0, 0]} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh name="Cube" geometry={nodes.Cube.geometry} material={materials['Material.004']} position={[-0.088, 0.007, 0]} scale={[0.001, 0.007, 0.001]} />
    </group>
  )
}

useGLTF.preload('./RailwayCrossing-transformed.glb')
