/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 --resolution 1204 --types --output ./src/models/SmallHouseModel.tsx --transform ./src-models/small-house/small-house.gltf 
Files: ./src-models/small-house/small-house.gltf [21.96KB] > D:\Work\train-sim\src\models\small-house-transformed.glb [1.93MB] (-8670%)
Author: Dynamike17 (https://sketchfab.com/Dynamike17)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/small-house-578d3864a3a84cc5a23d5066dcc4e4c8
Title: Small house
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Object_4: THREE.Mesh
    Object_5: THREE.Mesh
    Object_6: THREE.Mesh
    Object_7: THREE.Mesh
    Object_8: THREE.Mesh
    Object_9: THREE.Mesh
    Object_10: THREE.Mesh
    Object_11: THREE.Mesh
  }
  materials: {
    blue_wall: THREE.MeshStandardMaterial
    door: THREE.MeshStandardMaterial
    shutter: THREE.MeshStandardMaterial
    metal_door: THREE.MeshStandardMaterial
    window_frame: THREE.MeshStandardMaterial
    ['Material.001']: THREE.MeshStandardMaterial
    cement: THREE.MeshStandardMaterial
    ['Material.003']: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('./small-house-transformed.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Object_4.geometry} material={materials.blue_wall} />
      <mesh geometry={nodes.Object_5.geometry} material={materials.door} />
      <mesh geometry={nodes.Object_6.geometry} material={materials.shutter} />
      <mesh geometry={nodes.Object_7.geometry} material={materials.metal_door} />
      <mesh geometry={nodes.Object_8.geometry} material={materials.window_frame} />
      <mesh geometry={nodes.Object_9.geometry} material={materials['Material.001']} />
      <mesh geometry={nodes.Object_10.geometry} material={materials.cement} />
      <mesh geometry={nodes.Object_11.geometry} material={materials['Material.003']} />
    </group>
  )
}

useGLTF.preload('./small-house-transformed.glb')
