/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 --resolution 1204 --types --output ./src/models/TrainCoachModel.tsx --transform ./src-models/train-coach/train-coach.gltf 
Files: ./src-models/train-coach/train-coach.gltf [18.61KB] > D:\Work\train-sim\src\models\train-coach-transformed.glb [57.95KB] (-211%)
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Object_4: THREE.Mesh
    Object_5: THREE.Mesh
  }
  materials: {
    PaletteMaterial001: THREE.MeshStandardMaterial
    PaletteMaterial002: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('./train-coach-transformed.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Object_4.geometry} material={materials.PaletteMaterial001} position={[-0.004, 0.815, 0.006]} rotation={[0, -Math.PI / 2, 0]} scale={6.082} />
      <mesh geometry={nodes.Object_5.geometry} material={materials.PaletteMaterial002} position={[-0.004, 0.815, 0.006]} rotation={[0, -Math.PI / 2, 0]} scale={6.082} />
    </group>
  )
}

useGLTF.preload('./train-coach-transformed.glb')
