/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 --resolution 1204 --types --output ./src/models/TrainEngineModel.tsx --transform ./src-models/train-engine/train-engine.gltf 
Files: ./src-models/train-engine/train-engine.gltf [71.66KB] > D:\Work\train-sim\src\models\train-engine-transformed.glb [1.11MB] (-1452%)
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    object_0: THREE.Mesh
    object_2: THREE.Mesh
    object_4: THREE.Mesh
    object_8: THREE.Mesh
    object_9: THREE.Mesh
    object_11: THREE.Mesh
    object_13: THREE.Mesh
    object_14: THREE.Mesh
    object_17: THREE.Mesh
    object_20: THREE.Mesh
    object_21: THREE.Mesh
    object_23: THREE.Mesh
    object_24: THREE.Mesh
    object_25: THREE.Mesh
    object_26: THREE.Mesh
    object_27: THREE.Mesh
    object_28: THREE.Mesh
    object_32: THREE.Mesh
    object_33: THREE.Mesh
    object_35: THREE.Mesh
    object_36: THREE.Mesh
    object_37: THREE.Mesh
    object_38: THREE.Mesh
    object_39: THREE.Mesh
    object_40: THREE.Mesh
    object_42: THREE.Mesh
    object_43: THREE.Mesh
    object_44: THREE.Mesh
  }
  materials: {
    PaletteMaterial001: THREE.MeshStandardMaterial
    object_2: THREE.MeshStandardMaterial
    object_3: THREE.MeshStandardMaterial
    object_4: THREE.MeshStandardMaterial
    object_5: THREE.MeshStandardMaterial
    object_8: THREE.MeshStandardMaterial
    object_9: THREE.MeshStandardMaterial
    object_11: THREE.MeshStandardMaterial
    object_13: THREE.MeshStandardMaterial
    object_14: THREE.MeshStandardMaterial
    object_16: THREE.MeshStandardMaterial
    PaletteMaterial002: THREE.MeshStandardMaterial
    object_20: THREE.MeshStandardMaterial
    object_21: THREE.MeshStandardMaterial
    object_22: THREE.MeshStandardMaterial
    object_23: THREE.MeshStandardMaterial
    object_24: THREE.MeshStandardMaterial
    object_25: THREE.MeshStandardMaterial
    object_26: THREE.MeshStandardMaterial
    object_27: THREE.MeshStandardMaterial
    object_28: THREE.MeshStandardMaterial
    object_32: THREE.MeshStandardMaterial
    object_33: THREE.MeshStandardMaterial
    object_35: THREE.MeshStandardMaterial
    object_36: THREE.MeshStandardMaterial
    object_37: THREE.MeshStandardMaterial
    object_38: THREE.MeshStandardMaterial
    object_39: THREE.MeshStandardMaterial
    object_40: THREE.MeshStandardMaterial
    object_41: THREE.MeshStandardMaterial
    ['object_42.001']: THREE.MeshStandardMaterial
    object_43: THREE.MeshStandardMaterial
    object_42: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('./train-Engine.glb') as GLTFResult
  
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.object_0.geometry} material={materials.PaletteMaterial001} scale={0.01} />
      <mesh geometry={nodes.object_2.geometry} material={materials.object_2} scale={0.01} />
      <mesh geometry={nodes.object_4.geometry} material={materials.object_4} scale={0.01} />
      <mesh geometry={nodes.object_8.geometry} material={materials.object_8} scale={0.01} />
      <mesh geometry={nodes.object_9.geometry} material={materials.object_9} scale={0.01} />
      <mesh geometry={nodes.object_11.geometry} material={materials.object_11} scale={0.01} />
      <mesh geometry={nodes.object_13.geometry} material={materials.object_13} scale={0.01} />
      <mesh geometry={nodes.object_14.geometry} material={materials.object_14} scale={0.01} />
      <mesh geometry={nodes.object_17.geometry} material={materials.PaletteMaterial002} scale={0.01} />
      <mesh geometry={nodes.object_20.geometry} material={materials.object_20} scale={0.01} />
      <mesh geometry={nodes.object_21.geometry} material={materials.object_21} scale={0.01} />
      <mesh geometry={nodes.object_23.geometry} material={materials.object_23} scale={0.01} />
      <mesh geometry={nodes.object_24.geometry} material={materials.object_24} scale={0.01} />
      <mesh geometry={nodes.object_25.geometry} material={materials.object_25} scale={0.01} />
      <mesh geometry={nodes.object_26.geometry} material={materials.object_26} scale={0.01} />
      <mesh geometry={nodes.object_27.geometry} material={materials.object_27} scale={0.01} />
      <mesh geometry={nodes.object_28.geometry} material={materials.object_28} scale={0.01} />
      <mesh geometry={nodes.object_32.geometry} material={materials.object_32} scale={0.01} />
      <mesh geometry={nodes.object_33.geometry} material={materials.object_33} scale={0.01} />
      <mesh geometry={nodes.object_35.geometry} material={materials.object_35} scale={0.01} />
      <mesh geometry={nodes.object_36.geometry} material={materials.object_36} scale={0.01} />
      <mesh geometry={nodes.object_37.geometry} material={materials.object_37} scale={0.01} />
      <mesh geometry={nodes.object_38.geometry} material={materials.object_38} scale={0.01} />
      <mesh geometry={nodes.object_39.geometry} material={materials.object_39} scale={0.01} />
      <mesh geometry={nodes.object_40.geometry} material={materials.object_40} scale={0.01} />
      <mesh geometry={nodes.object_42.geometry} material={materials['object_42.001']} scale={0.01} />
      <mesh geometry={nodes.object_43.geometry} material={materials.object_43} scale={0.01} />
      <mesh geometry={nodes.object_44.geometry} material={materials.object_42} scale={0.01} />
    </group>
  )
}

useGLTF.preload('./train-Engine.glb')
