/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 --instanceall --resolution 1024 --types --output ./src/models/TreesBushesModel.tsx --transform ./src-models/trees-bushes/trees-bushes.gltf 
Files: ./src-models/trees-bushes/trees-bushes.gltf [19.61KB] > D:\Work\train-sim\src\models\trees-bushes-transformed.glb [1.27MB] (-6366%)
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF, Merged } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    BushBig2_bush2_0: THREE.Mesh
    BushFlowerSmall_bushflower_0: THREE.Mesh
    BushMed_bushType1_0: THREE.Mesh
    pine1_pine2_0: THREE.Mesh
    Pine2_pine3_0: THREE.Mesh
    Pine2_Trunk_0: THREE.Mesh
    tree2_tree2_0: THREE.Mesh
    TreeSmall_tree3_0: THREE.Mesh
  }
  materials: {
    bush2: THREE.MeshStandardMaterial
    bushflower: THREE.MeshStandardMaterial
    bushType1: THREE.MeshStandardMaterial
    pine2: THREE.MeshStandardMaterial
    pine3: THREE.MeshStandardMaterial
    Trunk: THREE.MeshStandardMaterial
    tree2: THREE.MeshStandardMaterial
    tree3: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

type ContextType = Record<string, React.ForwardRefExoticComponent<JSX.IntrinsicElements['mesh']>>

const context = React.createContext({} as ContextType)

export function Instances({ children, ...props }: JSX.IntrinsicElements['group']) {
  const { nodes } = useGLTF('./trees-bushes-transformed.glb') as GLTFResult
  const instances = React.useMemo(
    () => ({
      BushBigbush: nodes.BushBig2_bush2_0,
      BushFlowerSmallbushflower: nodes.BushFlowerSmall_bushflower_0,
      BushMedbushType: nodes.BushMed_bushType1_0,
      Pinepine: nodes.pine1_pine2_0,
      Pinepine1: nodes.Pine2_pine3_0,
      PineTrunk: nodes.Pine2_Trunk_0,
      Treetree: nodes.tree2_tree2_0,
      TreeSmalltree: nodes.TreeSmall_tree3_0,
    }),
    [nodes],
  )
  return (
    <Merged meshes={instances} {...props}>
      {(instances: ContextType) => <context.Provider value={instances} children={children} />}
    </Merged>
  )
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const instances = React.useContext(context)
  return (
    <group {...props} dispose={null}>
      <instances.BushBigbush position={[6.627, 1.449, -17.377]} rotation={[-3.131, 0.135, 2.8]} scale={[3.587, 2.845, 4.141]} />
      <instances.BushFlowerSmallbushflower position={[12.482, 0.818, -0.558]} rotation={[-Math.PI / 2, 1.283, Math.PI / 2]} scale={[2.995, 3.692, 3.003]} />
      <instances.BushMedbushType position={[-1.123, 1.33, -7.542]} rotation={[0.047, 0.108, -0.409]} scale={[3.587, 2.845, 4.141]} />
      <instances.Pinepine position={[-15.714, 17.381, -26.766]} scale={43.479} />
      <instances.Pinepine1 position={[10.195, 21.203, -45.551]} scale={43.479} />
      <instances.PineTrunk position={[10.195, 21.203, -45.551]} scale={43.479} />
      <instances.Treetree position={[19.766, 10.128, -20.16]} scale={19.334} />
      <instances.TreeSmalltree position={[22.992, 6.341, 0.802]} scale={12.165} />
    </group>
  )
}

useGLTF.preload('./trees-bushes-transformed.glb')
