/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 --keepmeshes --resolution 1024 --keepnames --types --output ./underBridge.tsx --transform ./underBridge.gltf 
Files: ./underBridge.gltf [14.94KB] > /home/cronabit/Desktop/underBridge_dev/underBridge-transformed.glb [9.22KB] (38%)
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Bridge: THREE.Mesh
    Bridge_Support_1: THREE.Mesh
    Bridge_Support_2: THREE.Mesh
    Bridge_Support_07: THREE.Mesh
    Bridge_Support_08: THREE.Mesh
    Bridge_Support_09: THREE.Mesh
    Bridge_Support_3: THREE.Mesh
    Bridge_Support_4: THREE.Mesh
    Bridge_Support_5: THREE.Mesh
    Bridge_Support_10: THREE.Mesh
    Bridge_Support_6: THREE.Mesh
    Bridge_Support_11: THREE.Mesh
  }
  materials: {
    lambert2: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('./underBridge-transformed.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh name="Bridge" geometry={nodes.Bridge.geometry} material={materials.lambert2} position={[16.295, 0, 0]} rotation={[Math.PI / 2, 0, 0]} scale={97.783} />
      <mesh name="Bridge_Support_1" geometry={nodes.Bridge_Support_1.geometry} material={materials.lambert2} position={[-961.53, 0, 0]} rotation={[Math.PI / 2, 0, 0]} scale={97.783} />
      <mesh name="Bridge_Support_2" geometry={nodes.Bridge_Support_2.geometry} material={materials.lambert2} position={[-961.53, 0, 0]} rotation={[Math.PI / 2, 0, 0]} scale={97.783} />
      <mesh name="Bridge_Support_07" geometry={nodes.Bridge_Support_07.geometry} material={materials.lambert2} position={[-179.27, 0, 0]} rotation={[Math.PI / 2, 0, 0]} scale={97.783} />
      <mesh name="Bridge_Support_08" geometry={nodes.Bridge_Support_08.geometry} material={materials.lambert2} position={[211.86, 0, 0]} rotation={[Math.PI / 2, 0, 0]} scale={97.783} />
      <mesh name="Bridge_Support_09" geometry={nodes.Bridge_Support_09.geometry} material={materials.lambert2} position={[602.991, 0, 0]} rotation={[Math.PI / 2, 0, 0]} scale={97.783} />
      <mesh name="Bridge_Support_3" geometry={nodes.Bridge_Support_3.geometry} material={materials.lambert2} position={[-961.53, 0, 0]} rotation={[Math.PI / 2, 0, 0]} scale={97.783} />
      <mesh name="Bridge_Support_4" geometry={nodes.Bridge_Support_4.geometry} material={materials.lambert2} position={[-961.53, 0, 0]} rotation={[Math.PI / 2, 0, 0]} scale={97.783} />
      <mesh name="Bridge_Support_5" geometry={nodes.Bridge_Support_5.geometry} material={materials.lambert2} position={[-961.53, 0, 0]} rotation={[Math.PI / 2, 0, 0]} scale={97.783} />
      <mesh name="Bridge_Support_10" geometry={nodes.Bridge_Support_10.geometry} material={materials.lambert2} position={[2167.512, 0, 0]} rotation={[Math.PI / 2, 0, 0]} scale={97.783} />
      <mesh name="Bridge_Support_6" geometry={nodes.Bridge_Support_6.geometry} material={materials.lambert2} position={[-961.53, 0, 0]} rotation={[Math.PI / 2, 0, 0]} scale={97.783} />
      <mesh name="Bridge_Support_11" geometry={nodes.Bridge_Support_11.geometry} material={materials.lambert2} position={[2949.772, 0, 0]} rotation={[Math.PI / 2, 0, 0]} scale={97.783} />
    </group>
  )
}

useGLTF.preload('./underBridge-transformed.glb')
